#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 20-Jul-2016 12:46
#endif

#ifndef VARS_H
#define VARS_H

#define BLEGS 5

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub10(4), Sub1(4), Sub63(3,2)
        ComplexType Sub62(3,2), Sub18(4,4)
        ComplexType Sub19(4,4), Sub3(3,4,2)
        ComplexType Sub5(3,4,2), Sub4(3,4,2)
        ComplexType Sub9(3,4,2), Sub16(3,4,2)
        ComplexType Sub15(3,4,2), Sub11(3,4,2)
        ComplexType Sub12(3,4,2), Sub2(3,4,2)
        ComplexType Sub7(3,4,2)
        common /varXs/ Sub10, Sub1, Sub63, Sub62, Sub18, Sub19, Sub3
        common /varXs/ Sub5, Sub4, Sub9, Sub16, Sub15, Sub11, Sub12
        common /varXs/ Sub2, Sub7

        ComplexType Sub60(3,3,4,4)
        ComplexType Sub61(3,3,4,4)
        RealType S, T, T14, U, T24, S34
        common /varXa/ Sub60, Sub61, S, T, T14, U, T24, S34

        HelType F21, F34, F40, F24, F25, F42, F3, F1, F32, F36, F7
        HelType F15, F19, F2, F9, F22, F16, F8, F33, F28, F30, F13
        HelType F5, F35, F27, F26, F45, F47, F55, F6, F20, F12, F31
        HelType F51, F4, F23, F14, F29, F43, F38, F39, F18, F44, F41
        HelType F37, F11, F49, F46, F48, F50, F52, F53, F17, F54
        HelType F56, F10, Pair1, Pair4, Pair3, Pair2, Abb1, Abb2
        HelType Sub40, Sub37, Sub20(HelDim(4),4)
        HelType Sub34(HelDim(4),4), Sub21(HelDim(4),4)
        HelType Sub35(HelDim(4),4), Sub29(HelDim(4),4)
        HelType Sub44(HelDim(4),4)
        HelType Sub25(HelDim(3),4,4)
        HelType Sub28(HelDim(3),4,4)
        HelType Sub50(HelDim(3),4,2)
        HelType Sub6(HelDim(3),4,2)
        HelType Sub46(HelDim(3),4,2)
        HelType Sub49(HelDim(3),4,2)
        HelType Sub57(HelDim(3),4,2)
        HelType Sub54(HelDim(3),4,2)
        HelType Sub39(HelDim(3),4,4)
        HelType Sub43(HelDim(3),4,4)
        HelType Sub13(HelDim(3),4,2)
        HelType Sub56(HelDim(3),4,2)
        HelType Sub58(HelDim(3),4,2)
        HelType Sub59(HelDim(3),4,2)
        HelType Sub33(HelDim(3),4,2)
        HelType Sub31(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub32(HelDim(3),4,2)
        HelType Sub55(HelDim(3),3,4,4,2)
        HelType Sub64(HelDim(3),3,4,4,2)
        HelType Sub65(HelDim(3),3,4,4,2)
        HelType Sub66(HelDim(3),3,4,4,2)
        HelType Sub51(HelDim(3),3,4,4,2)
        HelType Sub17(HelDim(3),3,4,4,2)
        HelType Sub22(HelDim(4)), Sub23(HelDim(3),4)
        HelType Sub30(HelDim(3),4,4)
        HelType Sub45(HelDim(3),3,4,4)
        HelType Sub48(HelDim(4)), Sub47(HelDim(4))
        HelType Sub52(HelDim(4)), Sub53(HelDim(4))
        HelType Sub26(HelDim(3),4), Sub24(HelDim(3),4)
        HelType Sub27(HelDim(3),4)
        HelType Sub42(HelDim(3),4,4)
        HelType Sub36(HelDim(3),4,4)
        HelType Sub41(HelDim(3),4,4)
        HelType Sub38(HelDim(3),4,4)
        common /varXh/ F21, F34, F40, F24, F25, F42, F3, F1, F32, F36
        common /varXh/ F7, F15, F19, F2, F9, F22, F16, F8, F33, F28
        common /varXh/ F30, F13, F5, F35, F27, F26, F45, F47, F55
        common /varXh/ F6, F20, F12, F31, F51, F4, F23, F14, F29
        common /varXh/ F43, F38, F39, F18, F44, F41, F37, F11, F49
        common /varXh/ F46, F48, F50, F52, F53, F17, F54, F56, F10
        common /varXh/ Pair1, Pair4, Pair3, Pair2, Abb1, Abb2, Sub40
        common /varXh/ Sub37, Sub20, Sub34, Sub21, Sub35, Sub29
        common /varXh/ Sub44, Sub25, Sub28, Sub50, Sub6, Sub46
        common /varXh/ Sub49, Sub57, Sub54, Sub39, Sub43, Sub13
        common /varXh/ Sub56, Sub58, Sub59, Sub33, Sub31, Sub8
        common /varXh/ Sub32, Sub55, Sub64, Sub65, Sub66, Sub51
        common /varXh/ Sub17, Sub22, Sub23, Sub30, Sub45, Sub48
        common /varXh/ Sub47, Sub52, Sub53, Sub26, Sub24, Sub27
        common /varXh/ Sub42, Sub36, Sub41, Sub38

        integer seq(2), Hel(5)
        common /helind/ seq, Hel

        integer Sfe6
        common /indices/ Sfe6

        HelType Ctree(HelDim(1))
        ComplexType MatSUN(1,1)
        common /ququbar_nInJg_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
