#!/bin/bash

if [[ "$1" == "" ]]; then
  suspect2
  cp suspect2_lha.out ./SD_leshouches.in
  sdecay
  cp sdecay_slha.out input_mSUGRA1410.4999.slha
elif [[ "$1" == "clean" ]]; then
  find . ! \( -name 'suspect2_lha.in' -o -name 'sdecay.in' -o -name 'make' -o -name 'README' \) -type f -exec rm -f {} +
fi