#!/bin/bash

x=./iflist
sed -i -e "s/001/dxdx_nInJdxdx/g" $x
sed -i -e "s/002/dxd_nInJddx/g" $x
sed -i -e "s/003/dxd_nInJuux/g" $x
sed -i -e "s/004/dxd_nInJccx/g" $x
sed -i -e "s/005/dxd_nInJssx/g" $x
sed -i -e "s/006/dxd_nInJbbx/g" $x
sed -i -e "s/007/dxd_nInJgg/g" $x
sed -i -e "s/008/dxux_nInJdxux/g" $x
sed -i -e "s/009/dxu_nInJdxu/g" $x
sed -i -e "s/010/dxcx_nInJdxcx/g" $x
sed -i -e "s/011/dxc_nInJdxc/g" $x
sed -i -e "s/012/dxsx_nInJdxsx/g" $x
sed -i -e "s/013/dxs_nInJdxs/g" $x
sed -i -e "s/014/dxbx_nInJdxbx/g" $x
sed -i -e "s/015/dxb_nInJdxb/g" $x
sed -i -e "s/016/dxg_nInJdxg/g" $x
sed -i -e "s/017/ddx_nInJddx/g" $x
sed -i -e "s/018/ddx_nInJuux/g" $x
sed -i -e "s/019/ddx_nInJccx/g" $x
sed -i -e "s/020/ddx_nInJssx/g" $x
sed -i -e "s/021/ddx_nInJbbx/g" $x
sed -i -e "s/022/ddx_nInJgg/g" $x
sed -i -e "s/023/dd_nInJdd/g" $x
sed -i -e "s/024/dux_nInJdux/g" $x
sed -i -e "s/025/du_nInJdu/g" $x
sed -i -e "s/026/dcx_nInJdcx/g" $x
sed -i -e "s/027/dc_nInJdc/g" $x
sed -i -e "s/028/dsx_nInJdsx/g" $x
sed -i -e "s/029/ds_nInJds/g" $x
sed -i -e "s/030/dbx_nInJdbx/g" $x
sed -i -e "s/031/db_nInJdb/g" $x
sed -i -e "s/032/dg_nInJdg/g" $x
sed -i -e "s/033/uxdx_nInJdxux/g" $x
sed -i -e "s/034/uxd_nInJdux/g" $x
sed -i -e "s/035/uxux_nInJuxux/g" $x
sed -i -e "s/036/uxu_nInJddx/g" $x
sed -i -e "s/037/uxu_nInJuux/g" $x
sed -i -e "s/038/uxu_nInJccx/g" $x
sed -i -e "s/039/uxu_nInJssx/g" $x
sed -i -e "s/040/uxu_nInJbbx/g" $x
sed -i -e "s/041/uxu_nInJgg/g" $x
sed -i -e "s/042/uxcx_nInJuxcx/g" $x
sed -i -e "s/043/uxc_nInJuxc/g" $x
sed -i -e "s/044/uxsx_nInJuxsx/g" $x
sed -i -e "s/045/uxs_nInJuxs/g" $x
sed -i -e "s/046/uxbx_nInJuxbx/g" $x
sed -i -e "s/047/uxb_nInJuxb/g" $x
sed -i -e "s/048/uxg_nInJuxg/g" $x
sed -i -e "s/049/udx_nInJdxu/g" $x
sed -i -e "s/050/ud_nInJdu/g" $x
sed -i -e "s/051/uux_nInJddx/g" $x
sed -i -e "s/052/uux_nInJuux/g" $x
sed -i -e "s/053/uux_nInJccx/g" $x
sed -i -e "s/054/uux_nInJssx/g" $x
sed -i -e "s/055/uux_nInJbbx/g" $x
sed -i -e "s/056/uux_nInJgg/g" $x
sed -i -e "s/057/uu_nInJuu/g" $x
sed -i -e "s/058/ucx_nInJucx/g" $x
sed -i -e "s/059/uc_nInJuc/g" $x
sed -i -e "s/060/usx_nInJusx/g" $x
sed -i -e "s/061/us_nInJus/g" $x
sed -i -e "s/062/ubx_nInJubx/g" $x
sed -i -e "s/063/ub_nInJub/g" $x
sed -i -e "s/064/ug_nInJug/g" $x
sed -i -e "s/065/cxdx_nInJdxcx/g" $x
sed -i -e "s/066/cxd_nInJdcx/g" $x
sed -i -e "s/067/cxux_nInJuxcx/g" $x
sed -i -e "s/068/cxu_nInJucx/g" $x
sed -i -e "s/069/cxcx_nInJcxcx/g" $x
sed -i -e "s/070/cxc_nInJddx/g" $x
sed -i -e "s/071/cxc_nInJuux/g" $x
sed -i -e "s/072/cxc_nInJccx/g" $x
sed -i -e "s/073/cxc_nInJssx/g" $x
sed -i -e "s/074/cxc_nInJbbx/g" $x
sed -i -e "s/075/cxc_nInJgg/g" $x
sed -i -e "s/076/cxsx_nInJcxsx/g" $x
sed -i -e "s/077/cxs_nInJcxs/g" $x
sed -i -e "s/078/cxbx_nInJcxbx/g" $x
sed -i -e "s/079/cxb_nInJcxb/g" $x
sed -i -e "s/080/cxg_nInJcxg/g" $x
sed -i -e "s/081/cdx_nInJdxc/g" $x
sed -i -e "s/082/cd_nInJdc/g" $x
sed -i -e "s/083/cux_nInJuxc/g" $x
sed -i -e "s/084/cu_nInJuc/g" $x
sed -i -e "s/085/ccx_nInJddx/g" $x
sed -i -e "s/086/ccx_nInJuux/g" $x
sed -i -e "s/087/ccx_nInJccx/g" $x
sed -i -e "s/088/ccx_nInJssx/g" $x
sed -i -e "s/089/ccx_nInJbbx/g" $x
sed -i -e "s/090/ccx_nInJgg/g" $x
sed -i -e "s/091/cc_nInJcc/g" $x
sed -i -e "s/092/csx_nInJcsx/g" $x
sed -i -e "s/093/cs_nInJcs/g" $x
sed -i -e "s/094/cbx_nInJcbx/g" $x
sed -i -e "s/095/cb_nInJcb/g" $x
sed -i -e "s/096/cg_nInJcg/g" $x
sed -i -e "s/097/sxdx_nInJdxsx/g" $x
sed -i -e "s/098/sxd_nInJdsx/g" $x
sed -i -e "s/099/sxux_nInJuxsx/g" $x
sed -i -e "s/100/sxu_nInJusx/g" $x
sed -i -e "s/101/sxcx_nInJcxsx/g" $x
sed -i -e "s/102/sxc_nInJcsx/g" $x
sed -i -e "s/103/sxsx_nInJsxsx/g" $x
sed -i -e "s/104/sxs_nInJddx/g" $x
sed -i -e "s/105/sxs_nInJuux/g" $x
sed -i -e "s/106/sxs_nInJccx/g" $x
sed -i -e "s/107/sxs_nInJssx/g" $x
sed -i -e "s/108/sxs_nInJbbx/g" $x
sed -i -e "s/109/sxs_nInJgg/g" $x
sed -i -e "s/110/sxbx_nInJsxbx/g" $x
sed -i -e "s/111/sxb_nInJsxb/g" $x
sed -i -e "s/112/sxg_nInJsxg/g" $x
sed -i -e "s/113/sdx_nInJdxs/g" $x
sed -i -e "s/114/sd_nInJds/g" $x
sed -i -e "s/115/sux_nInJuxs/g" $x
sed -i -e "s/116/su_nInJus/g" $x
sed -i -e "s/117/scx_nInJcxs/g" $x
sed -i -e "s/118/sc_nInJcs/g" $x
sed -i -e "s/119/ssx_nInJddx/g" $x
sed -i -e "s/120/ssx_nInJuux/g" $x
sed -i -e "s/121/ssx_nInJccx/g" $x
sed -i -e "s/122/ssx_nInJssx/g" $x
sed -i -e "s/123/ssx_nInJbbx/g" $x
sed -i -e "s/124/ssx_nInJgg/g" $x
sed -i -e "s/125/ss_nInJss/g" $x
sed -i -e "s/126/sbx_nInJsbx/g" $x
sed -i -e "s/127/sb_nInJsb/g" $x
sed -i -e "s/128/sg_nInJsg/g" $x
sed -i -e "s/129/bxdx_nInJdxbx/g" $x
sed -i -e "s/130/bxd_nInJdbx/g" $x
sed -i -e "s/131/bxux_nInJuxbx/g" $x
sed -i -e "s/132/bxu_nInJubx/g" $x
sed -i -e "s/133/bxcx_nInJcxbx/g" $x
sed -i -e "s/134/bxc_nInJcbx/g" $x
sed -i -e "s/135/bxsx_nInJsxbx/g" $x
sed -i -e "s/136/bxs_nInJsbx/g" $x
sed -i -e "s/137/bxbx_nInJbxbx/g" $x
sed -i -e "s/138/bxb_nInJddx/g" $x
sed -i -e "s/139/bxb_nInJuux/g" $x
sed -i -e "s/140/bxb_nInJccx/g" $x
sed -i -e "s/141/bxb_nInJssx/g" $x
sed -i -e "s/142/bxb_nInJbbx/g" $x
sed -i -e "s/143/bxb_nInJgg/g" $x
sed -i -e "s/144/bxg_nInJbxg/g" $x
sed -i -e "s/145/bdx_nInJdxb/g" $x
sed -i -e "s/146/bd_nInJdb/g" $x
sed -i -e "s/147/bux_nInJuxb/g" $x
sed -i -e "s/148/bu_nInJub/g" $x
sed -i -e "s/149/bcx_nInJcxb/g" $x
sed -i -e "s/150/bc_nInJcb/g" $x
sed -i -e "s/151/bsx_nInJsxb/g" $x
sed -i -e "s/152/bs_nInJsb/g" $x
sed -i -e "s/153/bbx_nInJddx/g" $x
sed -i -e "s/154/bbx_nInJuux/g" $x
sed -i -e "s/155/bbx_nInJccx/g" $x
sed -i -e "s/156/bbx_nInJssx/g" $x
sed -i -e "s/157/bbx_nInJbbx/g" $x
sed -i -e "s/158/bbx_nInJgg/g" $x
sed -i -e "s/159/bb_nInJbb/g" $x
sed -i -e "s/160/bg_nInJbg/g" $x
sed -i -e "s/161/gdx_nInJdxg/g" $x
sed -i -e "s/162/gd_nInJdg/g" $x
sed -i -e "s/163/gux_nInJuxg/g" $x
sed -i -e "s/164/gu_nInJug/g" $x
sed -i -e "s/165/gcx_nInJcxg/g" $x
sed -i -e "s/166/gc_nInJcg/g" $x
sed -i -e "s/167/gsx_nInJsxg/g" $x
sed -i -e "s/168/gs_nInJsg/g" $x
sed -i -e "s/169/gbx_nInJbxg/g" $x
sed -i -e "s/170/gb_nInJbg/g" $x
sed -i -e "s/171/gg_nInJddx/g" $x
sed -i -e "s/172/gg_nInJuux/g" $x
sed -i -e "s/173/gg_nInJccx/g" $x
sed -i -e "s/174/gg_nInJssx/g" $x
sed -i -e "s/175/gg_nInJbbx/g" $x