c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  1,  4/          !  MCL     WCL     
      data tprid(  -1,   1) / 1000004/
      data(iforest(i, -2,   1),i=1,2) / -1,  3/          !  ZERO    ZERO    
      data tprid(  -2,   1) /      -3/
      data(iforest(i, -3,   1),i=1,2) / -2,  5/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  5,  3/          !  MCL     WCL     
      data sprop(  -1,   2) / 1000004/
      data(iforest(i, -2,   2),i=1,2) /  1,  4/          !  MCL     WCL     
      data tprid(  -2,   2) / 1000004/
      data(iforest(i, -3,   2),i=1,2) / -2, -1/          !  
c   Graph      3
      data mapconfig(   3) /   3/
      data(iforest(i, -1,   3),i=1,2) /  5,  3/          !  MCL     WCL     
      data sprop(  -1,   3) / 1000004/
      data(iforest(i, -2,   3),i=1,2) /  4, -1/          !  ZERO    ZERO    
      data sprop(  -2,   3) /       3/
c   Graph      4
      data mapconfig(   4) /   4/
      data(iforest(i, -1,   4),i=1,2) /  4,  3/          !  ZERO    AWIDTH  
      data sprop(  -1,   4) /      22/
      data(iforest(i, -2,   4),i=1,2) /  1, -1/          !  ZERO    ZERO    
      data tprid(  -2,   4) /      -3/
      data(iforest(i, -3,   4),i=1,2) / -2,  5/          !  
c   Graph      5
      data mapconfig(   5) /   5/
      data(iforest(i, -1,   5),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data sprop(  -1,   5) /      23/
      data(iforest(i, -2,   5),i=1,2) /  1, -1/          !  ZERO    ZERO    
      data tprid(  -2,   5) /      -3/
      data(iforest(i, -3,   5),i=1,2) / -2,  5/          !  
c   Graph      6
      data mapconfig(   6) /   6/
      data(iforest(i, -1,   6),i=1,2) /  4,  3/          !  ZERO    AWIDTH  
      data sprop(  -1,   6) /      22/
      data(iforest(i, -2,   6),i=1,2) /  5, -1/          !  ZERO    ZERO    
      data sprop(  -2,   6) /       3/
c   Graph      7
      data mapconfig(   7) /   7/
      data(iforest(i, -1,   7),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data sprop(  -1,   7) /      23/
      data(iforest(i, -2,   7),i=1,2) /  5, -1/          !  ZERO    ZERO    
      data sprop(  -2,   7) /       3/
      data mapconfig(   0) /   7/
