#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 29-May-2017 11:57
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub2(2,3,2), Sub3(2,3,2)
        ComplexType Sub53(2,3,2), Sub58(2,3,2)
        ComplexType Sub121(2,2), Sub123(2,2)
        ComplexType Sub126(3,3), Sub154(2,2)
        ComplexType Sub155(2,2), Sub169(2,2)
        ComplexType Sub170(2,2), Sub179(2,2)
        ComplexType Sub180(2,2), Sub181(2,2)
        ComplexType Sub182(2,2), Sub300(3,3)
        ComplexType Sub608(3,2), Sub610(3,2)
        common /gqu_xIxJqug_varXs/ Sub2, Sub3, Sub53, Sub58, Sub121, Sub123
        common /gqu_xIxJqug_varXs/ Sub126, Sub154, Sub155, Sub169, Sub170
        common /gqu_xIxJqug_varXs/ Sub179, Sub180, Sub181, Sub182, Sub300
        common /gqu_xIxJqug_varXs/ Sub608, Sub610

        ComplexType Opt6(2,2), Sub34(2,2,3)
        ComplexType Sub61(2,2,3)
        ComplexType Sub128(2,2,3,3)
        ComplexType Sub140(2,2,3)
        ComplexType Sub147(2,2,3,3)
        ComplexType Sub165(2,2,3,3)
        ComplexType Sub322(2,2,3,3), Sub349(3,3)
        ComplexType Sub429(2,2,3,3)
        ComplexType Sub581(2,2,3,3)
        ComplexType Sub607(2,2,3,3)
        ComplexType Sub609(2,2,3,3)
        ComplexType Sub611(2,2,3,3)
        ComplexType Sub613(2,2,3,3), Sub614(2,3)
        ComplexType Sub621(2,3), Sub625(2,2,3,3)
        ComplexType Sub340(2,2,3,3)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /gqu_xIxJqug_varXa/ Opt6, Sub34, Sub61, Sub128, Sub140, Sub147
        common /gqu_xIxJqug_varXa/ Sub165, Sub322, Sub349, Sub429, Sub581
        common /gqu_xIxJqug_varXa/ Sub607, Sub609, Sub611, Sub613, Sub614
        common /gqu_xIxJqug_varXa/ Sub621, Sub625, Sub340, S, T, T14, T15, U
        common /gqu_xIxJqug_varXa/ T24, T25, S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, F107, F108, F109, F110, F111
        HelType F112, F113, F114, F115, F116, F117, F118, F119, F120
        HelType F121, F122, F123, F124, F125, F126, F127, F128, F129
        HelType F130, F131, F132, F133, F134, F135, F136, F137, F138
        HelType F139, F140, F141, F142, F143, F144, F145, F146, F147
        HelType F148, F149, F150, F151, F152, F153, F154, F155, F156
        HelType F157, F158, F159, F160, F161, F162, F163, F164, F165
        HelType F166, F167, F168, F169, F170, F171, F172, F173, F174
        HelType F175, F176, F177, F178, F179, F180, F181, F182, F183
        HelType F184, F185, F186, F187, F188, F189, F190, F191, F192
        HelType F193, F194, F195, F196, F197, F198, F199, F200, F201
        HelType F202, F203, F204, F205, F206, F207, F208, F209, F210
        HelType F211, F212, F213, F214, F215, F216, F217, F218, F219
        HelType F220, Opt1, Opt2, Opt3, Opt4, Opt5, Opt7, Opt8
        HelType Pair1, Pair2, Pair3, Pair4, Pair5, Pair6, Pair7
        HelType Pair8, Pair9, Pair10, Pair11, Sub1, Sub4, Sub7
        HelType Sub8(HelDim(2),3), Sub11(HelDim(2),3)
        HelType Sub12(HelDim(2),3), Sub14, Sub18(HelDim(2))
        HelType Sub20(HelDim(2)), Sub32
        HelType Sub38(HelDim(2),2,3)
        HelType Sub42(HelDim(2),2,3), Sub44
        HelType Sub54(HelDim(2),3,2)
        HelType Sub55(HelDim(2),3,2)
        HelType Sub56(HelDim(2),2,3,3,2), Sub57, Sub63
        HelType Sub65(HelDim(2),2,3), Sub67
        HelType Sub69(HelDim(2),2,3), Sub71
        HelType Sub80(HelDim(2),2,3,3,2)
        HelType Sub81(HelDim(2),2,3,3,2), Sub82, Sub83
        HelType Sub85, Sub86, Sub87(HelDim(2),3)
        HelType Sub88(HelDim(2),3), Sub89
        HelType Sub90(HelDim(2),3), Sub91(HelDim(2),3)
        HelType Sub92, Sub93(HelDim(2),3)
        HelType Sub95(HelDim(2),3), Sub96(HelDim(2),3)
        HelType Sub97(HelDim(2),3)
        HelType Sub98(HelDim(2),2,3,3,2), Sub100
        HelType Sub101(HelDim(2),3), Sub102(HelDim(2),3)
        HelType Sub104(HelDim(2),3), Sub106
        HelType Sub107(HelDim(2),3), Sub110
        HelType Sub115(HelDim(2),3), Sub120, Sub122
        HelType Sub124(HelDim(2),2)
        HelType Sub130(HelDim(2),2,3,3), Sub133, Sub134
        HelType Sub135(HelDim(2),2,3,3,2)
        HelType Sub136(HelDim(2),2,3,3,2)
        HelType Sub137(HelDim(2),2,3,3,2)
        HelType Sub138(HelDim(3),3)
        HelType Sub141(HelDim(2),2,3,3)
        HelType Sub148(HelDim(2),2,3,3), Sub153
        HelType Sub156(HelDim(2),2), Sub158
        HelType Sub161(HelDim(2),2,3,3)
        HelType Sub166(HelDim(2),2,3,3)
        HelType Sub171(HelDim(2),2)
        HelType Sub172(HelDim(2),2,3,3)
        HelType Sub176(HelDim(2),2,3,3)
        HelType Sub183(HelDim(2),2), Sub185, Sub186
        HelType Sub187(HelDim(2),2), Sub188, Sub189
        HelType Sub190(HelDim(2),2), Sub191, Sub193, Sub195
        HelType Sub197, Sub200, Sub202, Sub204, Sub206
        HelType Sub210(HelDim(2),2), Sub211(HelDim(2),2)
        HelType Sub212(HelDim(2),2), Sub215, Sub216, Sub217
        HelType Sub218, Sub219, Sub221, Sub228, Sub229, Sub230
        HelType Sub231, Sub232, Sub233, Sub234, Sub236, Sub237
        HelType Sub239, Sub241, Sub245, Sub246
        HelType Sub247(HelDim(2),2), Sub248, Sub249
        HelType Sub250(HelDim(2),2), Sub251
        HelType Sub252(HelDim(2),2), Sub253
        HelType Sub254(HelDim(2),2), Sub255
        HelType Sub256(HelDim(2),2), Sub257
        HelType Sub258(HelDim(2),2), Sub259, Sub260, Sub261
        HelType Sub262, Sub264, Sub266, Sub267, Sub268, Sub269
        HelType Sub271, Sub274, Sub275, Sub276, Sub277, Sub279
        HelType Sub281, Sub282, Sub283, Sub284, Sub286
        HelType Sub289(HelDim(2),2,3,3)
        HelType Sub291(HelDim(2),2)
        HelType Sub292(HelDim(2),2,3)
        HelType Sub297(HelDim(2),2), Sub298, Sub299
        HelType Sub301(HelDim(3),3)
        HelType Sub302(HelDim(2),2,3,3)
        HelType Sub303(HelDim(2),2,3,3)
        HelType Sub304(HelDim(2),2,3,3)
        HelType Sub307(HelDim(3),3), Sub315, Sub316, Sub317
        HelType Sub318, Sub320(HelDim(2),2)
        HelType Sub321(HelDim(2),2), Sub334(HelDim(2),2)
        HelType Sub335(HelDim(2),2), Sub336(HelDim(2),2)
        HelType Sub341(HelDim(2),2,3,3)
        HelType Sub351(HelDim(2),2,3,3)
        HelType Sub357(HelDim(2),2,3,3), Sub360, Sub361
        HelType Sub362(HelDim(3),3)
        HelType Sub363(HelDim(2),2,3,3)
        HelType Sub364(HelDim(2),2,3,3)
        HelType Sub365(HelDim(2),2,3,3)
        HelType Sub367(HelDim(2),2,3,3)
        HelType Sub370(HelDim(2),2), Sub372(HelDim(2),2)
        HelType Sub373(HelDim(2),2), Sub374, Sub377, Sub380
        HelType Sub381, Sub382(HelDim(2),2), Sub383, Sub384
        HelType Sub385(HelDim(2),2), Sub386
        HelType Sub387(HelDim(3)), Sub389, Sub390(HelDim(3))
        HelType Sub393, Sub394(HelDim(3)), Sub396
        HelType Sub397(HelDim(3)), Sub401(HelDim(2),2)
        HelType Sub413(HelDim(3),3), Sub418(HelDim(2),2)
        HelType Sub419(HelDim(2),2), Sub440(HelDim(2),2)
        HelType Sub445, Sub446, Sub447, Sub448, Sub450(HelDim(3))
        HelType Sub452(HelDim(3)), Sub455(HelDim(3))
        HelType Sub457(HelDim(3)), Sub460(HelDim(2),2,3)
        HelType Sub461(HelDim(2),2), Sub462(HelDim(2),2)
        HelType Sub465(HelDim(3),3), Sub468(HelDim(2),2)
        HelType Sub469(HelDim(2),2), Sub470
        HelType Sub471(HelDim(2),2), Sub472
        HelType Sub473(HelDim(2),2), Sub474
        HelType Sub475(HelDim(2),2), Sub476
        HelType Sub477(HelDim(2),2), Sub478, Sub479, Sub482
        HelType Sub483, Sub487, Sub488, Sub491, Sub492
        HelType Sub496(HelDim(2),2,3,3)
        HelType Sub501(HelDim(2),2,3)
        HelType Sub504(HelDim(2),2), Sub505(HelDim(2),2)
        HelType Sub506(HelDim(3),3), Sub507(HelDim(3),3)
        HelType Sub508(HelDim(2),2,3,3)
        HelType Sub509(HelDim(3),3), Sub510(HelDim(3),3)
        HelType Sub511(HelDim(2),2,3,3)
        HelType Sub512(HelDim(2),2,3,3)
        HelType Sub513(HelDim(2),2,3,3)
        HelType Sub514(HelDim(2),2)
        HelType Sub515(HelDim(2),2,3)
        HelType Sub516(HelDim(2),2), Sub517(HelDim(2),2)
        HelType Sub518(HelDim(2),2,3,3)
        HelType Sub519(HelDim(2),2,3,3), Sub520, Sub521
        HelType Sub522, Sub523, Sub524, Sub525, Sub526(HelDim(3))
        HelType Sub528(HelDim(2),2,3), Sub530, Sub531
        HelType Sub532, Sub533, Sub534(HelDim(3))
        HelType Sub536(HelDim(2),3)
        HelType Sub538(HelDim(2),2,3,3)
        HelType Sub541(HelDim(2),2,3,3)
        HelType Sub542(HelDim(2),2,3,3)
        HelType Sub543(HelDim(2),2,3,3), Sub544, Sub545
        HelType Sub546, Sub547, Sub548, Sub549, Sub550, Sub551
        HelType Sub557, Sub558, Sub565, Sub568, Sub572, Sub573
        HelType Sub574(HelDim(3),3)
        HelType Sub575(HelDim(2),2,3,3)
        HelType Sub576(HelDim(2),3,2)
        HelType Sub577(HelDim(2),3,2)
        HelType Sub578(HelDim(2),2,3,3,2), Sub579
        HelType Sub580, Sub583, Sub584, Sub586, Sub588, Sub589
        HelType Sub591(HelDim(2),2,3,3), Sub592, Sub594
        HelType Sub595, Sub603, Sub604, Sub632(HelDim(2),2)
        HelType Abb1, Abb2, Abb3, Abb4, Abb5, Abb6, Abb7, Abb8, Abb9
        HelType Abb10, Abb11, Abb12, Abb13, Abb14, Abb15, Abb16
        HelType Abb17, Abb18, Abb19, Abb20, Abb21
        HelType Sub5(HelDim(2),3), Sub6(HelDim(2),3)
        HelType Sub9(HelDim(2),3), Sub10(HelDim(2),3)
        HelType Sub13(HelDim(2),3), Sub15(HelDim(2),3)
        HelType Sub16(HelDim(2),3), Sub17(HelDim(2),3)
        HelType Sub19(HelDim(2),3), Sub21(HelDim(2),3)
        HelType Sub22(HelDim(2),2,3,3,2)
        HelType Sub23(HelDim(2),2,3,3,2), Sub24, Sub25
        HelType Sub26, Sub27, Sub28(HelDim(2))
        HelType Sub29(HelDim(2))
        HelType Sub30(HelDim(2),2,3,3,2)
        HelType Sub31(HelDim(2),2,3,3,2), Sub33
        HelType Sub35(HelDim(2),2,3), Sub36, Sub40, Sub41
        HelType Sub43(HelDim(2),2,3), Sub45
        HelType Sub46(HelDim(2),2,3)
        HelType Sub47(HelDim(2),2,3)
        HelType Sub48(HelDim(2),2,3)
        HelType Sub50(HelDim(2),2,3), Sub59, Sub60
        HelType Sub62(HelDim(2),2,3), Sub64
        HelType Sub66(HelDim(2),2,3), Sub72
        HelType Sub73(HelDim(2),2,3)
        HelType Sub74(HelDim(2),2,3)
        HelType Sub75(HelDim(2),2,3)
        HelType Sub76(HelDim(2),2,3)
        HelType Sub84(HelDim(2),3), Sub94(HelDim(2),3)
        HelType Sub99(HelDim(2),2,3,3,2)
        HelType Sub103(HelDim(2),3), Sub105(HelDim(2),3)
        HelType Sub108(HelDim(2),3), Sub109(HelDim(2),3)
        HelType Sub111(HelDim(2),3), Sub112(HelDim(2),3)
        HelType Sub113(HelDim(2),3), Sub114(HelDim(2),3)
        HelType Sub116(HelDim(2),3)
        HelType Sub117(HelDim(2),2,3,3,2)
        HelType Sub118(HelDim(2),2,3,3,2)
        HelType Sub119(HelDim(2),2,3,3,2), Sub125
        HelType Sub127(HelDim(3),3)
        HelType Sub129(HelDim(2),2,3,3)
        HelType Sub131(HelDim(2),2,3,3)
        HelType Sub132(HelDim(2),2,3,3)
        HelType Sub139(HelDim(3),3)
        HelType Sub142(HelDim(2),2,3,3)
        HelType Sub143(HelDim(2),2,3,3)
        HelType Sub144(HelDim(2),2,3,3)
        HelType Sub145(HelDim(2),2,3,3)
        HelType Sub146(HelDim(3),3)
        HelType Sub149(HelDim(2),2,3,3)
        HelType Sub150(HelDim(2),2,3,3)
        HelType Sub151(HelDim(2),2,3,3)
        HelType Sub152(HelDim(2),2,3,3), Sub157
        HelType Sub159(HelDim(3),3)
        HelType Sub160(HelDim(2),2,3,3)
        HelType Sub162(HelDim(2),2,3,3)
        HelType Sub163(HelDim(2),2,3,3)
        HelType Sub164(HelDim(3),3)
        HelType Sub167(HelDim(2),2,3,3)
        HelType Sub168(HelDim(2),2,3,3)
        HelType Sub173(HelDim(2),2,3,3)
        HelType Sub174(HelDim(2),2,3,3)
        HelType Sub175(HelDim(3),3)
        HelType Sub177(HelDim(2),2,3,3)
        HelType Sub178(HelDim(2),2,3,3)
        HelType Sub184(HelDim(2),2,3,3)
        HelType Sub192(HelDim(3))
        HelType Sub194(HelDim(2),2,3,3)
        HelType Sub196(HelDim(3))
        HelType Sub198(HelDim(2),2,3,3)
        HelType Sub199(HelDim(2),2,3,3)
        HelType Sub201(HelDim(3))
        HelType Sub203(HelDim(2),2,3,3)
        HelType Sub205(HelDim(3))
        HelType Sub207(HelDim(2),2,3,3)
        HelType Sub208(HelDim(2),2,3,3)
        HelType Sub209(HelDim(2),2,3,3)
        HelType Sub213(HelDim(2),2,3,3)
        HelType Sub214(HelDim(2),2,3,3), Sub220, Sub222
        HelType Sub223, Sub224, Sub225(HelDim(2),2,3,3)
        HelType Sub226, Sub227(HelDim(2),2,3,3), Sub235
        HelType Sub238, Sub240, Sub242
        HelType Sub243(HelDim(2),2,3,3)
        HelType Sub244(HelDim(2),2,3,3)
        HelType Sub263(HelDim(3))
        HelType Sub265(HelDim(2),2,3,3)
        HelType Sub270(HelDim(3))
        HelType Sub272(HelDim(2),2,3,3)
        HelType Sub273(HelDim(2),2,3,3)
        HelType Sub278(HelDim(3))
        HelType Sub280(HelDim(2),2,3,3)
        HelType Sub285(HelDim(3))
        HelType Sub287(HelDim(2),2,3,3)
        HelType Sub288(HelDim(2),2,3,3)
        HelType Sub290(HelDim(2),2,3,3)
        HelType Sub293(HelDim(2),2,3,3)
        HelType Sub294(HelDim(2),2,3,3)
        HelType Sub295(HelDim(2),2,3,3)
        HelType Sub296(HelDim(2),2,3,3)
        HelType Sub306(HelDim(3),3), Sub308(HelDim(3),3)
        HelType Sub309(HelDim(2),2,3,3)
        HelType Sub310(HelDim(2),2,3,3)
        HelType Sub311(HelDim(3),3), Sub312(HelDim(3),3)
        HelType Sub313(HelDim(2),2,3,3)
        HelType Sub314(HelDim(2),2,3,3)
        HelType Sub319(HelDim(2),2,3,3)
        HelType Sub323(HelDim(2),2,3,3)
        HelType Sub324(HelDim(2),2,3,3)
        HelType Sub325(HelDim(2),2,3,3)
        HelType Sub326(HelDim(2),2,3,3)
        HelType Sub327(HelDim(2),2,3,3)
        HelType Sub328(HelDim(2),2,3,3)
        HelType Sub329(HelDim(2),2,3,3)
        HelType Sub330(HelDim(2),2,3,3)
        HelType Sub331(HelDim(2),2,3,3)
        HelType Sub332(HelDim(2),2,3,3)
        HelType Sub333(HelDim(2),2,3,3)
        HelType Sub337(HelDim(2),2,3,3)
        HelType Sub338(HelDim(2),2,3,3), Sub339
        HelType Sub342(HelDim(2),2,3,3), Sub343
        HelType Sub344(HelDim(2),2,3,3)
        HelType Sub345(HelDim(2),2,3,3)
        HelType Sub346(HelDim(2),2,3,3), Sub347, Sub348
        HelType Sub350(HelDim(3),3)
        HelType Sub352(HelDim(2),2,3,3)
        HelType Sub353(HelDim(2),2,3,3), Sub354, Sub355
        HelType Sub356(HelDim(3),3)
        HelType Sub358(HelDim(2),2,3,3)
        HelType Sub359(HelDim(2),2,3,3), Sub366
        HelType Sub368(HelDim(2),2,3,3)
        HelType Sub369(HelDim(2),2,3,3)
        HelType Sub371(HelDim(2),2,3,3)
        HelType Sub376(HelDim(2),2), Sub379(HelDim(2),2)
        HelType Sub388(HelDim(3)), Sub391(HelDim(3))
        HelType Sub392(HelDim(2),2,3), Sub395(HelDim(3))
        HelType Sub398(HelDim(3)), Sub399(HelDim(2),2,3)
        HelType Sub400(HelDim(2),2,3,3)
        HelType Sub402(HelDim(2),2), Sub403(HelDim(2),2)
        HelType Sub404(HelDim(2),2,3,3)
        HelType Sub405(HelDim(2),2,3,3), Sub406, Sub407
        HelType Sub408, Sub409, Sub410(HelDim(2),3,2)
        HelType Sub411(HelDim(2),3,2)
        HelType Sub412(HelDim(2),2,3,3,2)
        HelType Sub415(HelDim(3),3), Sub416(HelDim(3),3)
        HelType Sub417(HelDim(2),2,3,3), Sub420
        HelType Sub421(HelDim(2),2), Sub422
        HelType Sub423(HelDim(2),2), Sub424
        HelType Sub425(HelDim(2),2), Sub426
        HelType Sub427(HelDim(2),2), Sub428(HelDim(3))
        HelType Sub430(HelDim(2),2,3,3)
        HelType Sub431(HelDim(3))
        HelType Sub432(HelDim(2),2,3,3)
        HelType Sub433(HelDim(2),2,3,3)
        HelType Sub434(HelDim(3))
        HelType Sub435(HelDim(2),2,3,3)
        HelType Sub436(HelDim(3))
        HelType Sub437(HelDim(2),2,3,3)
        HelType Sub438(HelDim(2),2,3,3)
        HelType Sub439(HelDim(2),2,3,3)
        HelType Sub441(HelDim(2),2,3,3)
        HelType Sub442(HelDim(2),2,3,3)
        HelType Sub443(HelDim(2),2,3,3)
        HelType Sub444(HelDim(2),2,3,3)
        HelType Sub449(HelDim(2),2,3,3)
        HelType Sub451(HelDim(3)), Sub453(HelDim(3))
        HelType Sub454(HelDim(2),2,3), Sub456(HelDim(3))
        HelType Sub458(HelDim(3)), Sub459(HelDim(2),2,3)
        HelType Sub463(HelDim(2),2,3)
        HelType Sub464(HelDim(2),2,3,3)
        HelType Sub466(HelDim(3),3), Sub467(HelDim(3),3)
        HelType Sub480(HelDim(3)), Sub481(HelDim(3),3)
        HelType Sub484(HelDim(3)), Sub485(HelDim(3),3)
        HelType Sub486(HelDim(2),2,3,3)
        HelType Sub489(HelDim(3)), Sub490(HelDim(3),3)
        HelType Sub493(HelDim(3)), Sub494(HelDim(3),3)
        HelType Sub495(HelDim(2),2,3,3)
        HelType Sub497(HelDim(2),2,3,3)
        HelType Sub498(HelDim(2),2,3,3)
        HelType Sub499(HelDim(2),2,3,3)
        HelType Sub500(HelDim(2),2,3,3)
        HelType Sub502(HelDim(2),2,3,3)
        HelType Sub503(HelDim(2),2,3,3)
        HelType Sub527(HelDim(3))
        HelType Sub529(HelDim(2),2,3,3)
        HelType Sub535(HelDim(3))
        HelType Sub537(HelDim(2),2,3,3)
        HelType Sub539(HelDim(2),2,3,3)
        HelType Sub540(HelDim(2),2,3,3)
        HelType Sub552(HelDim(3),3)
        HelType Sub553(HelDim(2),2,3,3), Sub554, Sub555
        HelType Sub556, Sub559(HelDim(2),2,3,3)
        HelType Sub560(HelDim(2),2,3,3), Sub561, Sub562
        HelType Sub563, Sub564, Sub566, Sub567
        HelType Sub569(HelDim(2),2,3,3,2)
        HelType Sub570(HelDim(2),2,3,3,2)
        HelType Sub571(HelDim(2),2,3,3,2)
        HelType Sub582(HelDim(2),2,3,3), Sub585
        HelType Sub587(HelDim(2),2,3,3), Sub590
        HelType Sub593(HelDim(2),2,3,3)
        HelType Sub596(HelDim(2),2,3,3)
        HelType Sub597(HelDim(2),2,3,3)
        HelType Sub598(HelDim(2),2,3,3)
        HelType Sub599(HelDim(2),2,3,3)
        HelType Sub600(HelDim(2),2,3,3)
        HelType Sub601(HelDim(2),2,3,3,2)
        HelType Sub602(HelDim(2),2,3,3,2)
        HelType Sub605(HelDim(2),2,3,3)
        HelType Sub606(HelDim(2),2,3,3)
        HelType Sub612(HelDim(2),2,3,3,2)
        HelType Sub616(HelDim(2),2,3,3,2)
        HelType Sub618(HelDim(2),2,3,3,2)
        HelType Sub619(HelDim(2),2,3,3,2)
        HelType Sub622(HelDim(2),2,3,3)
        HelType Sub623(HelDim(2),2,3,3,2)
        HelType Sub624(HelDim(2),2,3,3,2)
        HelType Sub628(HelDim(2),2,3,3,2)
        HelType Sub630(HelDim(2),2,3,3)
        HelType Sub631(HelDim(2),2,3,3)
        HelType Sub633(HelDim(2),2,3,3)
        HelType Sub634(HelDim(2),2,3,3)
        HelType Sub635(HelDim(2),2,3,3)
        HelType Sub636(HelDim(2),2,3,3)
        HelType Sub637(HelDim(2),2,3,3)
        HelType Sub638(HelDim(2),2,3,3)
        HelType Sub639(HelDim(2),2,3,3)
        HelType Sub640(HelDim(2),2,3,3)
        HelType Sub641(HelDim(2),2,3,3)
        HelType Sub642(HelDim(2),2,3,3)
        HelType Sub643(HelDim(2),2,3,3)
        HelType Sub644(HelDim(2),2,3,3)
        HelType Sub645(HelDim(2),2,3,3)
        HelType Sub646(HelDim(2),2,3,3)
        HelType Sub647(HelDim(2),2,3,3)
        HelType Sub648(HelDim(2),2,3,3)
        HelType Sub649(HelDim(2),2,3,3)
        HelType Sub650(HelDim(2),2,3,3)
        HelType Sub651(HelDim(2),2,3,3)
        HelType Sub652(HelDim(2),2,3,3)
        HelType Sub653(HelDim(2),2,3,3)
        HelType Sub654(HelDim(2),2,3,3)
        HelType Sub655(HelDim(2),2,3,3)
        HelType Sub656(HelDim(2),2,3,3)
        HelType Sub657(HelDim(2),2,3,3)
        HelType Sub658(HelDim(2),2,3,3)
        HelType Sub659(HelDim(2),2,3,3)
        HelType Sub660(HelDim(2),2,3,3)
        HelType Sub661(HelDim(2),2,3,3)
        HelType Sub662(HelDim(2),2,3,3)
        HelType Sub663(HelDim(2),2,3,3)
        HelType Sub664(HelDim(2),2,3,3), Sub37
        HelType Sub39(HelDim(2),2,3)
        HelType Sub49(HelDim(2),2,3)
        HelType Sub51(HelDim(2),2,3,3,2)
        HelType Sub52(HelDim(2),2,3,3,2), Sub68
        HelType Sub70(HelDim(2),2,3)
        HelType Sub77(HelDim(2),2,3)
        HelType Sub78(HelDim(2),2,3,3,2)
        HelType Sub79(HelDim(2),2,3,3,2)
        HelType Sub615(HelDim(2),2,3,3,2)
        HelType Sub617(HelDim(2),2,3,3,2)
        HelType Sub620(HelDim(2),2,3,3,2)
        HelType Sub626(HelDim(2),2,3,3,2)
        HelType Sub627(HelDim(2),2,3,3,2)
        HelType Sub629(HelDim(2),2,3,3,2)
        common /gqu_xIxJqug_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /gqu_xIxJqug_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /gqu_xIxJqug_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /gqu_xIxJqug_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /gqu_xIxJqug_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /gqu_xIxJqug_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /gqu_xIxJqug_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /gqu_xIxJqug_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /gqu_xIxJqug_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /gqu_xIxJqug_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /gqu_xIxJqug_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /gqu_xIxJqug_varXh/ F102, F103, F104, F105, F106, F107, F108
        common /gqu_xIxJqug_varXh/ F109, F110, F111, F112, F113, F114, F115
        common /gqu_xIxJqug_varXh/ F116, F117, F118, F119, F120, F121, F122
        common /gqu_xIxJqug_varXh/ F123, F124, F125, F126, F127, F128, F129
        common /gqu_xIxJqug_varXh/ F130, F131, F132, F133, F134, F135, F136
        common /gqu_xIxJqug_varXh/ F137, F138, F139, F140, F141, F142, F143
        common /gqu_xIxJqug_varXh/ F144, F145, F146, F147, F148, F149, F150
        common /gqu_xIxJqug_varXh/ F151, F152, F153, F154, F155, F156, F157
        common /gqu_xIxJqug_varXh/ F158, F159, F160, F161, F162, F163, F164
        common /gqu_xIxJqug_varXh/ F165, F166, F167, F168, F169, F170, F171
        common /gqu_xIxJqug_varXh/ F172, F173, F174, F175, F176, F177, F178
        common /gqu_xIxJqug_varXh/ F179, F180, F181, F182, F183, F184, F185
        common /gqu_xIxJqug_varXh/ F186, F187, F188, F189, F190, F191, F192
        common /gqu_xIxJqug_varXh/ F193, F194, F195, F196, F197, F198, F199
        common /gqu_xIxJqug_varXh/ F200, F201, F202, F203, F204, F205, F206
        common /gqu_xIxJqug_varXh/ F207, F208, F209, F210, F211, F212, F213
        common /gqu_xIxJqug_varXh/ F214, F215, F216, F217, F218, F219, F220
        common /gqu_xIxJqug_varXh/ Opt1, Opt2, Opt3, Opt4, Opt5, Opt7, Opt8
        common /gqu_xIxJqug_varXh/ Pair1, Pair2, Pair3, Pair4, Pair5, Pair6
        common /gqu_xIxJqug_varXh/ Pair7, Pair8, Pair9, Pair10, Pair11, Sub1
        common /gqu_xIxJqug_varXh/ Sub4, Sub7, Sub8, Sub11, Sub12, Sub14, Sub18
        common /gqu_xIxJqug_varXh/ Sub20, Sub32, Sub38, Sub42, Sub44, Sub54
        common /gqu_xIxJqug_varXh/ Sub55, Sub56, Sub57, Sub63, Sub65, Sub67
        common /gqu_xIxJqug_varXh/ Sub69, Sub71, Sub80, Sub81, Sub82, Sub83
        common /gqu_xIxJqug_varXh/ Sub85, Sub86, Sub87, Sub88, Sub89, Sub90
        common /gqu_xIxJqug_varXh/ Sub91, Sub92, Sub93, Sub95, Sub96, Sub97
        common /gqu_xIxJqug_varXh/ Sub98, Sub100, Sub101, Sub102, Sub104, Sub106
        common /gqu_xIxJqug_varXh/ Sub107, Sub110, Sub115, Sub120, Sub122
        common /gqu_xIxJqug_varXh/ Sub124, Sub130, Sub133, Sub134, Sub135
        common /gqu_xIxJqug_varXh/ Sub136, Sub137, Sub138, Sub141, Sub148
        common /gqu_xIxJqug_varXh/ Sub153, Sub156, Sub158, Sub161, Sub166
        common /gqu_xIxJqug_varXh/ Sub171, Sub172, Sub176, Sub183, Sub185
        common /gqu_xIxJqug_varXh/ Sub186, Sub187, Sub188, Sub189, Sub190
        common /gqu_xIxJqug_varXh/ Sub191, Sub193, Sub195, Sub197, Sub200
        common /gqu_xIxJqug_varXh/ Sub202, Sub204, Sub206, Sub210, Sub211
        common /gqu_xIxJqug_varXh/ Sub212, Sub215, Sub216, Sub217, Sub218
        common /gqu_xIxJqug_varXh/ Sub219, Sub221, Sub228, Sub229, Sub230
        common /gqu_xIxJqug_varXh/ Sub231, Sub232, Sub233, Sub234, Sub236
        common /gqu_xIxJqug_varXh/ Sub237, Sub239, Sub241, Sub245, Sub246
        common /gqu_xIxJqug_varXh/ Sub247, Sub248, Sub249, Sub250, Sub251
        common /gqu_xIxJqug_varXh/ Sub252, Sub253, Sub254, Sub255, Sub256
        common /gqu_xIxJqug_varXh/ Sub257, Sub258, Sub259, Sub260, Sub261
        common /gqu_xIxJqug_varXh/ Sub262, Sub264, Sub266, Sub267, Sub268
        common /gqu_xIxJqug_varXh/ Sub269, Sub271, Sub274, Sub275, Sub276
        common /gqu_xIxJqug_varXh/ Sub277, Sub279, Sub281, Sub282, Sub283
        common /gqu_xIxJqug_varXh/ Sub284, Sub286, Sub289, Sub291, Sub292
        common /gqu_xIxJqug_varXh/ Sub297, Sub298, Sub299, Sub301, Sub302
        common /gqu_xIxJqug_varXh/ Sub303, Sub304, Sub307, Sub315, Sub316
        common /gqu_xIxJqug_varXh/ Sub317, Sub318, Sub320, Sub321, Sub334
        common /gqu_xIxJqug_varXh/ Sub335, Sub336, Sub341, Sub351, Sub357
        common /gqu_xIxJqug_varXh/ Sub360, Sub361, Sub362, Sub363, Sub364
        common /gqu_xIxJqug_varXh/ Sub365, Sub367, Sub370, Sub372, Sub373
        common /gqu_xIxJqug_varXh/ Sub374, Sub377, Sub380, Sub381, Sub382
        common /gqu_xIxJqug_varXh/ Sub383, Sub384, Sub385, Sub386, Sub387
        common /gqu_xIxJqug_varXh/ Sub389, Sub390, Sub393, Sub394, Sub396
        common /gqu_xIxJqug_varXh/ Sub397, Sub401, Sub413, Sub418, Sub419
        common /gqu_xIxJqug_varXh/ Sub440, Sub445, Sub446, Sub447, Sub448
        common /gqu_xIxJqug_varXh/ Sub450, Sub452, Sub455, Sub457, Sub460
        common /gqu_xIxJqug_varXh/ Sub461, Sub462, Sub465, Sub468, Sub469
        common /gqu_xIxJqug_varXh/ Sub470, Sub471, Sub472, Sub473, Sub474
        common /gqu_xIxJqug_varXh/ Sub475, Sub476, Sub477, Sub478, Sub479
        common /gqu_xIxJqug_varXh/ Sub482, Sub483, Sub487, Sub488, Sub491
        common /gqu_xIxJqug_varXh/ Sub492, Sub496, Sub501, Sub504, Sub505
        common /gqu_xIxJqug_varXh/ Sub506, Sub507, Sub508, Sub509, Sub510
        common /gqu_xIxJqug_varXh/ Sub511, Sub512, Sub513, Sub514, Sub515
        common /gqu_xIxJqug_varXh/ Sub516, Sub517, Sub518, Sub519, Sub520
        common /gqu_xIxJqug_varXh/ Sub521, Sub522, Sub523, Sub524, Sub525
        common /gqu_xIxJqug_varXh/ Sub526, Sub528, Sub530, Sub531, Sub532
        common /gqu_xIxJqug_varXh/ Sub533, Sub534, Sub536, Sub538, Sub541
        common /gqu_xIxJqug_varXh/ Sub542, Sub543, Sub544, Sub545, Sub546
        common /gqu_xIxJqug_varXh/ Sub547, Sub548, Sub549, Sub550, Sub551
        common /gqu_xIxJqug_varXh/ Sub557, Sub558, Sub565, Sub568, Sub572
        common /gqu_xIxJqug_varXh/ Sub573, Sub574, Sub575, Sub576, Sub577
        common /gqu_xIxJqug_varXh/ Sub578, Sub579, Sub580, Sub583, Sub584
        common /gqu_xIxJqug_varXh/ Sub586, Sub588, Sub589, Sub591, Sub592
        common /gqu_xIxJqug_varXh/ Sub594, Sub595, Sub603, Sub604, Sub632, Abb1
        common /gqu_xIxJqug_varXh/ Abb2, Abb3, Abb4, Abb5, Abb6, Abb7, Abb8
        common /gqu_xIxJqug_varXh/ Abb9, Abb10, Abb11, Abb12, Abb13, Abb14
        common /gqu_xIxJqug_varXh/ Abb15, Abb16, Abb17, Abb18, Abb19, Abb20
        common /gqu_xIxJqug_varXh/ Abb21, Sub5, Sub6, Sub9, Sub10, Sub13, Sub15
        common /gqu_xIxJqug_varXh/ Sub16, Sub17, Sub19, Sub21, Sub22, Sub23
        common /gqu_xIxJqug_varXh/ Sub24, Sub25, Sub26, Sub27, Sub28, Sub29
        common /gqu_xIxJqug_varXh/ Sub30, Sub31, Sub33, Sub35, Sub36, Sub40
        common /gqu_xIxJqug_varXh/ Sub41, Sub43, Sub45, Sub46, Sub47, Sub48
        common /gqu_xIxJqug_varXh/ Sub50, Sub59, Sub60, Sub62, Sub64, Sub66
        common /gqu_xIxJqug_varXh/ Sub72, Sub73, Sub74, Sub75, Sub76, Sub84
        common /gqu_xIxJqug_varXh/ Sub94, Sub99, Sub103, Sub105, Sub108, Sub109
        common /gqu_xIxJqug_varXh/ Sub111, Sub112, Sub113, Sub114, Sub116
        common /gqu_xIxJqug_varXh/ Sub117, Sub118, Sub119, Sub125, Sub127
        common /gqu_xIxJqug_varXh/ Sub129, Sub131, Sub132, Sub139, Sub142
        common /gqu_xIxJqug_varXh/ Sub143, Sub144, Sub145, Sub146, Sub149
        common /gqu_xIxJqug_varXh/ Sub150, Sub151, Sub152, Sub157, Sub159
        common /gqu_xIxJqug_varXh/ Sub160, Sub162, Sub163, Sub164, Sub167
        common /gqu_xIxJqug_varXh/ Sub168, Sub173, Sub174, Sub175, Sub177
        common /gqu_xIxJqug_varXh/ Sub178, Sub184, Sub192, Sub194, Sub196
        common /gqu_xIxJqug_varXh/ Sub198, Sub199, Sub201, Sub203, Sub205
        common /gqu_xIxJqug_varXh/ Sub207, Sub208, Sub209, Sub213, Sub214
        common /gqu_xIxJqug_varXh/ Sub220, Sub222, Sub223, Sub224, Sub225
        common /gqu_xIxJqug_varXh/ Sub226, Sub227, Sub235, Sub238, Sub240
        common /gqu_xIxJqug_varXh/ Sub242, Sub243, Sub244, Sub263, Sub265
        common /gqu_xIxJqug_varXh/ Sub270, Sub272, Sub273, Sub278, Sub280
        common /gqu_xIxJqug_varXh/ Sub285, Sub287, Sub288, Sub290, Sub293
        common /gqu_xIxJqug_varXh/ Sub294, Sub295, Sub296, Sub306, Sub308
        common /gqu_xIxJqug_varXh/ Sub309, Sub310, Sub311, Sub312, Sub313
        common /gqu_xIxJqug_varXh/ Sub314, Sub319, Sub323, Sub324, Sub325
        common /gqu_xIxJqug_varXh/ Sub326, Sub327, Sub328, Sub329, Sub330
        common /gqu_xIxJqug_varXh/ Sub331, Sub332, Sub333, Sub337, Sub338
        common /gqu_xIxJqug_varXh/ Sub339, Sub342, Sub343, Sub344, Sub345
        common /gqu_xIxJqug_varXh/ Sub346, Sub347, Sub348, Sub350, Sub352
        common /gqu_xIxJqug_varXh/ Sub353, Sub354, Sub355, Sub356, Sub358
        common /gqu_xIxJqug_varXh/ Sub359, Sub366, Sub368, Sub369, Sub371
        common /gqu_xIxJqug_varXh/ Sub376, Sub379, Sub388, Sub391, Sub392
        common /gqu_xIxJqug_varXh/ Sub395, Sub398, Sub399, Sub400, Sub402
        common /gqu_xIxJqug_varXh/ Sub403, Sub404, Sub405, Sub406, Sub407
        common /gqu_xIxJqug_varXh/ Sub408, Sub409, Sub410, Sub411, Sub412
        common /gqu_xIxJqug_varXh/ Sub415, Sub416, Sub417, Sub420, Sub421
        common /gqu_xIxJqug_varXh/ Sub422, Sub423, Sub424, Sub425, Sub426
        common /gqu_xIxJqug_varXh/ Sub427, Sub428, Sub430, Sub431, Sub432
        common /gqu_xIxJqug_varXh/ Sub433, Sub434, Sub435, Sub436, Sub437
        common /gqu_xIxJqug_varXh/ Sub438, Sub439, Sub441, Sub442, Sub443
        common /gqu_xIxJqug_varXh/ Sub444, Sub449, Sub451, Sub453, Sub454
        common /gqu_xIxJqug_varXh/ Sub456, Sub458, Sub459, Sub463, Sub464
        common /gqu_xIxJqug_varXh/ Sub466, Sub467, Sub480, Sub481, Sub484
        common /gqu_xIxJqug_varXh/ Sub485, Sub486, Sub489, Sub490, Sub493
        common /gqu_xIxJqug_varXh/ Sub494, Sub495, Sub497, Sub498, Sub499
        common /gqu_xIxJqug_varXh/ Sub500, Sub502, Sub503, Sub527, Sub529
        common /gqu_xIxJqug_varXh/ Sub535, Sub537, Sub539, Sub540, Sub552
        common /gqu_xIxJqug_varXh/ Sub553, Sub554, Sub555, Sub556, Sub559
        common /gqu_xIxJqug_varXh/ Sub560, Sub561, Sub562, Sub563, Sub564
        common /gqu_xIxJqug_varXh/ Sub566, Sub567, Sub569, Sub570, Sub571
        common /gqu_xIxJqug_varXh/ Sub582, Sub585, Sub587, Sub590, Sub593
        common /gqu_xIxJqug_varXh/ Sub596, Sub597, Sub598, Sub599, Sub600
        common /gqu_xIxJqug_varXh/ Sub601, Sub602, Sub605, Sub606, Sub612
        common /gqu_xIxJqug_varXh/ Sub616, Sub618, Sub619, Sub622, Sub623
        common /gqu_xIxJqug_varXh/ Sub624, Sub628, Sub630, Sub631, Sub633
        common /gqu_xIxJqug_varXh/ Sub634, Sub635, Sub636, Sub637, Sub638
        common /gqu_xIxJqug_varXh/ Sub639, Sub640, Sub641, Sub642, Sub643
        common /gqu_xIxJqug_varXh/ Sub644, Sub645, Sub646, Sub647, Sub648
        common /gqu_xIxJqug_varXh/ Sub649, Sub650, Sub651, Sub652, Sub653
        common /gqu_xIxJqug_varXh/ Sub654, Sub655, Sub656, Sub657, Sub658
        common /gqu_xIxJqug_varXh/ Sub659, Sub660, Sub661, Sub662, Sub663
        common /gqu_xIxJqug_varXh/ Sub664, Sub37, Sub39, Sub49, Sub51, Sub52
        common /gqu_xIxJqug_varXh/ Sub68, Sub70, Sub77, Sub78, Sub79, Sub615
        common /gqu_xIxJqug_varXh/ Sub617, Sub620, Sub626, Sub627, Sub629

        integer Sfe7
        common /gqu_xIxJqug_indices/ Sfe7

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /gqu_xIxJqug_formfactors/ Ctree, MatSUN

#endif

