#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 23-May-2017 14:34
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub1(2,3,2), Sub2(2,3,2)
        ComplexType Sub6(2,3,2), Sub7(2,3,2)
        ComplexType Sub21(2,2), Sub22(2,2)
        ComplexType Sub31(2,2), Sub33(2,2)
        ComplexType Sub35(2,2), Sub36(2,2)
        ComplexType Sub41(2,2), Sub42(2,2)
        ComplexType Sub53(2,3,2), Sub58(2,3,2)
        ComplexType Sub59(2,3,2), Sub64(2,3,2)
        ComplexType Sub70(2,3,2), Sub76(2,2)
        ComplexType Sub77(2,2), Sub108(2,3,2)
        ComplexType Sub120(2,3,2), Sub122(2,3,2)
        ComplexType Sub127(2,3,2), Sub138(3,2)
        ComplexType Sub140(3,2), Sub142(3,2), Sub143(3,2)
        ComplexType Sub146(3,2), Sub147(3,2), Sub149(3,2)
        ComplexType Sub150(3,2), Sub172(3,2), Sub173(3,2)
        ComplexType Sub177(3,2), Sub178(3,2), Sub179(3,2)
        common /qdqdbar_xIxJququbar_varXs/ Sub1, Sub2, Sub6, Sub7, Sub21, Sub22, Sub31
        common /qdqdbar_xIxJququbar_varXs/ Sub33, Sub35, Sub36, Sub41, Sub42, Sub53
        common /qdqdbar_xIxJququbar_varXs/ Sub58, Sub59, Sub64, Sub70, Sub76, Sub77
        common /qdqdbar_xIxJququbar_varXs/ Sub108, Sub120, Sub122, Sub127, Sub138
        common /qdqdbar_xIxJququbar_varXs/ Sub140, Sub142, Sub143, Sub146, Sub147
        common /qdqdbar_xIxJququbar_varXs/ Sub149, Sub150, Sub172, Sub173, Sub177
        common /qdqdbar_xIxJququbar_varXs/ Sub178, Sub179

        ComplexType Opt1(2,3,3,3), Opt2(3)
        ComplexType Sub139(2,2,3,3,3,3)
        ComplexType Sub145(2,3,3)
        ComplexType Sub152(2,2,3,3,3,3)
        ComplexType Sub153(2,2,3,3,3,3)
        ComplexType Sub155(2,2,3), Sub157(3,3,3)
        ComplexType Sub158(2,2,3,3,3,3)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qdqdbar_xIxJququbar_varXa/ Opt1, Opt2, Sub139, Sub145, Sub152, Sub153
        common /qdqdbar_xIxJququbar_varXa/ Sub155, Sub157, Sub158, S, T, T14, T15, U
        common /qdqdbar_xIxJququbar_varXa/ T24, T25, S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, Sub3(HelDim(2),3,2)
        HelType Sub4(HelDim(2),3,2)
        HelType Sub5(HelDim(2),2,3,3,2)
        HelType Sub8(HelDim(3),3,2,2)
        HelType Sub9(HelDim(3),3,2,2), Sub12, Sub13, Sub14
        HelType Sub15, Sub16, Sub17, Sub18, Sub19, Sub20
        HelType Sub23(HelDim(2),2), Sub24, Sub25, Sub26, Sub27
        HelType Sub28, Sub29, Sub32, Sub34(HelDim(2),2)
        HelType Sub37(HelDim(2),2), Sub39
        HelType Sub40(HelDim(2),2), Sub43, Sub44
        HelType Sub45(HelDim(2),2), Sub46, Sub47
        HelType Sub48(HelDim(2),2), Sub49(HelDim(2),2)
        HelType Sub50(HelDim(2),2), Sub51(HelDim(2),2)
        HelType Sub52, Sub54, Sub55(HelDim(2),2,3,3,2)
        HelType Sub56, Sub57, Sub60(HelDim(2))
        HelType Sub61(HelDim(2))
        HelType Sub62(HelDim(2),2,3,3,2)
        HelType Sub63(HelDim(2),2,3,3,2)
        HelType Sub65(HelDim(2),3,2)
        HelType Sub66(HelDim(2),3,2)
        HelType Sub67(HelDim(2),2,3,3,2), Sub68, Sub69
        HelType Sub71(HelDim(2)), Sub72(HelDim(2))
        HelType Sub73(HelDim(2),3,3,2)
        HelType Sub74(HelDim(2),3,3,2)
        HelType Sub75(HelDim(2),2,3,3,2)
        HelType Sub78(HelDim(2),2), Sub79, Sub80
        HelType Sub81(HelDim(2),2), Sub82, Sub83, Sub84, Sub85
        HelType Sub86(HelDim(2),2)
        HelType Sub87(HelDim(2),2,3)
        HelType Sub88(HelDim(2),2,3)
        HelType Sub89(HelDim(2),2), Sub90(HelDim(2),2)
        HelType Sub91(HelDim(2),2)
        HelType Sub92(HelDim(2),2,3)
        HelType Sub93(HelDim(2),2,3)
        HelType Sub94(HelDim(2),2), Sub95(HelDim(2),2)
        HelType Sub96, Sub97, Sub98, Sub99
        HelType Sub100(HelDim(2),2), Sub101, Sub102, Sub103
        HelType Sub104(HelDim(2),2), Sub105
        HelType Sub106(HelDim(2),2), Sub107, Sub109
        HelType Sub110(HelDim(2),3,3,2)
        HelType Sub111(HelDim(2),3,3,2)
        HelType Sub112(HelDim(2),2,3,3,2), Sub113
        HelType Sub114(HelDim(2),2), Sub115, Sub116, Sub117
        HelType Sub118, Sub119(HelDim(2),2)
        HelType Sub121(HelDim(3),3,2,2)
        HelType Sub123(HelDim(3),3,2,2)
        HelType Sub128(HelDim(3),3,2,2)
        HelType Sub129(HelDim(3),3,2,2)
        HelType Sub130(HelDim(2),3,2)
        HelType Sub131(HelDim(2),3,2)
        HelType Sub133(HelDim(3),3,2,2)
        HelType Sub135(HelDim(3),3,2,2)
        HelType Sub136(HelDim(2),3,3,3,2,2)
        HelType Sub154(HelDim(2),2)
        HelType Sub156(HelDim(2),2,3,3,3,3)
        HelType Sub159(HelDim(2),2,3,3,3,3)
        HelType Sub160(HelDim(2),2,3,3,3,3)
        HelType Sub161(HelDim(2),2), Sub162(HelDim(2),2)
        HelType Sub163(HelDim(2),2,3,3,3,3)
        HelType Sub164(HelDim(2),2,3,3,3,3)
        HelType Sub165(HelDim(2),2,3,3,3,3)
        HelType Sub166(HelDim(2),2,3,3,3,3)
        HelType Sub167(HelDim(2),2,3,3,3,3)
        HelType Sub168(HelDim(2),2,3,3,3,3)
        HelType Sub169(HelDim(2),2,3,3,3,3)
        HelType Sub170(HelDim(2),2,3,3,3,3)
        HelType Sub174(HelDim(2),2,3,3,2)
        HelType Sub134(HelDim(3),3,2,2)
        common /qdqdbar_xIxJququbar_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /qdqdbar_xIxJququbar_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /qdqdbar_xIxJququbar_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /qdqdbar_xIxJququbar_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /qdqdbar_xIxJququbar_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /qdqdbar_xIxJququbar_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /qdqdbar_xIxJququbar_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /qdqdbar_xIxJququbar_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /qdqdbar_xIxJququbar_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /qdqdbar_xIxJququbar_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /qdqdbar_xIxJququbar_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /qdqdbar_xIxJququbar_varXh/ F102, F103, F104, F105, F106, Sub3, Sub4
        common /qdqdbar_xIxJququbar_varXh/ Sub5, Sub8, Sub9, Sub12, Sub13, Sub14, Sub15
        common /qdqdbar_xIxJququbar_varXh/ Sub16, Sub17, Sub18, Sub19, Sub20, Sub23
        common /qdqdbar_xIxJququbar_varXh/ Sub24, Sub25, Sub26, Sub27, Sub28, Sub29
        common /qdqdbar_xIxJququbar_varXh/ Sub32, Sub34, Sub37, Sub39, Sub40, Sub43
        common /qdqdbar_xIxJququbar_varXh/ Sub44, Sub45, Sub46, Sub47, Sub48, Sub49
        common /qdqdbar_xIxJququbar_varXh/ Sub50, Sub51, Sub52, Sub54, Sub55, Sub56
        common /qdqdbar_xIxJququbar_varXh/ Sub57, Sub60, Sub61, Sub62, Sub63, Sub65
        common /qdqdbar_xIxJququbar_varXh/ Sub66, Sub67, Sub68, Sub69, Sub71, Sub72
        common /qdqdbar_xIxJququbar_varXh/ Sub73, Sub74, Sub75, Sub78, Sub79, Sub80
        common /qdqdbar_xIxJququbar_varXh/ Sub81, Sub82, Sub83, Sub84, Sub85, Sub86
        common /qdqdbar_xIxJququbar_varXh/ Sub87, Sub88, Sub89, Sub90, Sub91, Sub92
        common /qdqdbar_xIxJququbar_varXh/ Sub93, Sub94, Sub95, Sub96, Sub97, Sub98
        common /qdqdbar_xIxJququbar_varXh/ Sub99, Sub100, Sub101, Sub102, Sub103, Sub104
        common /qdqdbar_xIxJququbar_varXh/ Sub105, Sub106, Sub107, Sub109, Sub110
        common /qdqdbar_xIxJququbar_varXh/ Sub111, Sub112, Sub113, Sub114, Sub115
        common /qdqdbar_xIxJququbar_varXh/ Sub116, Sub117, Sub118, Sub119, Sub121
        common /qdqdbar_xIxJququbar_varXh/ Sub123, Sub128, Sub129, Sub130, Sub131
        common /qdqdbar_xIxJququbar_varXh/ Sub133, Sub135, Sub136, Sub154, Sub156
        common /qdqdbar_xIxJququbar_varXh/ Sub159, Sub160, Sub161, Sub162, Sub163
        common /qdqdbar_xIxJququbar_varXh/ Sub164, Sub165, Sub166, Sub167, Sub168
        common /qdqdbar_xIxJququbar_varXh/ Sub169, Sub170, Sub174, Sub134

        integer Sfe7, Sfe8
        common /qdqdbar_xIxJququbar_indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqdbar_xIxJququbar_formfactors/ Ctree, MatSUN

#endif

