#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 29-May-2017 12:00
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub1(2,3,2), Sub11(2,3,2)
        ComplexType Sub17(2,3,2), Sub149(3,2)
        ComplexType Sub150(3,2), Sub153(3,2)
        common /quqdbar_xIxJquqdbar_465_Sq1_varXs/ Sub1, Sub11, Sub17, Sub149, Sub150, Sub153

        ComplexType Sub148(2,3,3)
        ComplexType Sub152(2,2,3,3,3,3)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /quqdbar_xIxJquqdbar_465_Sq1_varXa/ Sub148, Sub152, S, T, T14, T15, U, T24, T25
        common /quqdbar_xIxJquqdbar_465_Sq1_varXa/ S34, S35, S45

        HelType F2, F7, F12, F18, F19, F20, F21, F22, F23, F24, F25
        HelType F26, F27, F28, F29, F30, F31, F32
        HelType Sub16(HelDim(3),3,2,2)
        HelType Sub18(HelDim(2),3,3,2)
        HelType Sub20(HelDim(2),3,3,2)
        HelType Sub21(HelDim(3),3,2,2)
        HelType Sub22(HelDim(2),3,3,3,2,2)
        HelType Sub24(HelDim(3),3,2,2)
        HelType Sub25(HelDim(3),3,2,2)
        HelType Sub26(HelDim(2),3,3,2)
        HelType Sub27(HelDim(2),3,3,2)
        HelType Sub19(HelDim(3),3,2,2)
        common /quqdbar_xIxJquqdbar_465_Sq1_varXh/ F2, F7, F12, F18, F19, F20, F21, F22, F23, F24
        common /quqdbar_xIxJquqdbar_465_Sq1_varXh/ F25, F26, F27, F28, F29, F30, F31, F32, Sub16
        common /quqdbar_xIxJquqdbar_465_Sq1_varXh/ Sub18, Sub20, Sub21, Sub22, Sub24, Sub25
        common /quqdbar_xIxJquqdbar_465_Sq1_varXh/ Sub26, Sub27, Sub19

        integer Sfe8
        common /quqdbar_xIxJquqdbar_465_Sq1_indices/ Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /quqdbar_xIxJquqdbar_465_Sq1_formfactors/ Ctree, MatSUN

#endif

