#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 15-Jul-2016 11:59
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub274, Sub276, Sub19, Sub20, Sub22, Sub27, Sub21
	ComplexType Sub28
	common /varXs/ Sub274, Sub276, Sub19, Sub20, Sub22, Sub27
	common /varXs/ Sub21, Sub28

	ComplexType Sub277, Sub278
	RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
	common /varXa/ Sub277, Sub278, S, T, T14, T15, U, T24, T25
	common /varXa/ S34, S35, S45

	HelType F10, F1, F13, F11, F12, F14, F16, F9, F15, F7, Sub29
	HelType Sub30
	common /varXh/ F10, F1, F13, F11, F12, F14, F16, F9, F15, F7
	common /varXh/ Sub29, Sub30

	integer seq(2), Hel(6)
	common /helind/ seq, Hel

	HelType Ctree(HelDim(2))
	ComplexType MatSUN(2,2)
	common /du_n1n2du_L36R45_formfactors/ Ctree, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
