#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 23-Oct-2017 10:40
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub1(3,4,2), Sub2(3,4,2)
        ComplexType Sub3(3,4,2), Sub5(2,3,2)
        ComplexType Sub11(2,3,2), Sub12(4)
        ComplexType Sub13(3,4,2), Sub14(3,4,2)
        ComplexType Sub21(2,4), Sub24(2,4)
        ComplexType Sub40(3,3), Sub71(3,3)
        ComplexType Sub80(2,3,2), Sub90(2,3,2)
        ComplexType Sub409(4), Sub410(2,4), Sub414(4)
        ComplexType Sub415(2,4), Sub497(3,3)
        ComplexType Sub580(3,2), Sub586(3,2), Sub587(3,2)
        ComplexType Sub595(3,2)
        common /gqu_nIxJqdg_varXs/ Sub1, Sub2, Sub3, Sub5, Sub11, Sub12, Sub13
        common /gqu_nIxJqdg_varXs/ Sub14, Sub21, Sub24, Sub40, Sub71, Sub80
        common /gqu_nIxJqdg_varXs/ Sub90, Sub409, Sub410, Sub414, Sub415, Sub497
        common /gqu_nIxJqdg_varXs/ Sub580, Sub586, Sub587, Sub595

        ComplexType Opt1(2,3), Sub41(2,3,3,4)
        ComplexType Sub61(2,3,4), Sub72(2,3,4)
        ComplexType Sub86(2,3,4)
        ComplexType Sub111(2,3,3,4)
        ComplexType Sub138(2,3,3,4)
        ComplexType Sub152(2,3,3,4)
        ComplexType Sub215(2,3,4), Sub248(2,3,4)
        ComplexType Sub253(2,3,3,4)
        ComplexType Sub351(2,3,4), Sub407(3,3)
        ComplexType Sub488(2,3,3,4), Sub581(2,3)
        ComplexType Sub582(2,3,3,4)
        ComplexType Sub583(2,3,3,4)
        ComplexType Sub584(2,3,3,4), Sub588(3,4)
        ComplexType Sub591(2,3,3,4), Sub604(2,3)
        ComplexType Sub607(2,3,3,4), Sub610(3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /gqu_nIxJqdg_varXa/ Opt1, Sub41, Sub61, Sub72, Sub86, Sub111
        common /gqu_nIxJqdg_varXa/ Sub138, Sub152, Sub215, Sub248, Sub253
        common /gqu_nIxJqdg_varXa/ Sub351, Sub407, Sub488, Sub581, Sub582
        common /gqu_nIxJqdg_varXa/ Sub583, Sub584, Sub588, Sub591, Sub604
        common /gqu_nIxJqdg_varXa/ Sub607, Sub610, S, T, T14, T15, U, T24, T25
        common /gqu_nIxJqdg_varXa/ S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, F107, F108, F109, F110, F111
        HelType F112, F113, F114, F115, F116, F117, F118, F119, F120
        HelType F121, F122, F123, F124, F125, F126, F127, F128, F129
        HelType F130, F131, F132, F133, F134, F135, F136, F137, F138
        HelType F139, F140, F141, F142, F143, F144, F145, F146, F147
        HelType F148, F149, F150, F151, F152, F153, F154, F155, F156
        HelType F157, F158, F159, F160, F161, F162, F163, F164, F165
        HelType F166, F167, F168, F169, F170, F171, F172, F173, F174
        HelType F175, F176, F177, F178, F179, F180, F181, F182, F183
        HelType F184, F185, F186, F187, F188, F189, F190, F191, F192
        HelType F193, F194, F195, F196, F197, F198, F199, F200, F201
        HelType F202, F203, F204, F205, F206, F207, F208, F209, F210
        HelType F211, Pair1, Pair2, Pair3, Pair4, Pair5, Pair6
        HelType Pair7, Pair8, Pair9, Pair10, Pair11
        HelType Sub4(HelDim(3),4,2), Sub6, Sub7
        HelType Sub8(HelDim(3),4,2)
        HelType Sub9(HelDim(2),3,3,4,2), Sub10
        HelType Sub15(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub17(HelDim(3),4,2)
        HelType Sub18(HelDim(2),3,2), Sub19, Sub20, Sub22
        HelType Sub23, Sub25(HelDim(2),4), Sub26, Sub27, Sub28
        HelType Sub29(HelDim(2),4), Sub30, Sub31, Sub32
        HelType Sub33(HelDim(2),4), Sub34, Sub35, Sub36, Sub37
        HelType Sub39, Sub42(HelDim(2),3,3,4), Sub44
        HelType Sub45, Sub46, Sub47, Sub49
        HelType Sub50(HelDim(2),3,3,4), Sub54, Sub55
        HelType Sub56, Sub57, Sub58(HelDim(2),4), Sub59
        HelType Sub62(HelDim(2),3,3,4), Sub64
        HelType Sub66(HelDim(2),3,3,4)
        HelType Sub74(HelDim(2),4), Sub75(HelDim(2),4)
        HelType Sub76(HelDim(2),4)
        HelType Sub87(HelDim(2),3,3,4), Sub89
        HelType Sub91(HelDim(3),4,2), Sub92
        HelType Sub93(HelDim(2),3), Sub94(HelDim(2),3)
        HelType Sub95, Sub96, Sub97(HelDim(2),3)
        HelType Sub98(HelDim(2),3), Sub99(HelDim(2),3)
        HelType Sub100(HelDim(2),3,3,2)
        HelType Sub101(HelDim(3),4,2), Sub102, Sub103
        HelType Sub104(HelDim(3),4,2)
        HelType Sub105(HelDim(3),4,2), Sub106, Sub107
        HelType Sub108(HelDim(3),4,2), Sub110, Sub116, Sub119
        HelType Sub128(HelDim(2),4), Sub136
        HelType Sub139(HelDim(2),3,3,4), Sub141
        HelType Sub143(HelDim(2),3,3,4), Sub147, Sub148
        HelType Sub149(HelDim(2),4), Sub151
        HelType Sub153(HelDim(2),3,3,4), Sub156
        HelType Sub157(HelDim(2),3,3,4), Sub161, Sub162
        HelType Sub163(HelDim(2),4), Sub164(HelDim(3))
        HelType Sub165(HelDim(3)), Sub167(HelDim(3))
        HelType Sub168(HelDim(3)), Sub171(HelDim(2),3,4)
        HelType Sub175, Sub178, Sub179, Sub180(HelDim(2),4)
        HelType Sub181(HelDim(3)), Sub182(HelDim(3))
        HelType Sub184(HelDim(3)), Sub185(HelDim(3))
        HelType Sub190(HelDim(2),4), Sub191, Sub192, Sub193
        HelType Sub194(HelDim(2),4), Sub195, Sub196, Sub197
        HelType Sub198(HelDim(2),4), Sub199, Sub200
        HelType Sub203(HelDim(3),3), Sub205, Sub206
        HelType Sub209(HelDim(3),3), Sub213, Sub217
        HelType Sub218(HelDim(2),3), Sub219(HelDim(2),3)
        HelType Sub221, Sub222, Sub228, Sub229
        HelType Sub230(HelDim(2),4), Sub231
        HelType Sub232(HelDim(3),3), Sub233(HelDim(3),3)
        HelType Sub234, Sub235(HelDim(3),3)
        HelType Sub236(HelDim(3),3)
        HelType Sub237(HelDim(2),3,3,4)
        HelType Sub238(HelDim(2),3,3,4)
        HelType Sub246(HelDim(2),3,2)
        HelType Sub249(HelDim(2),3,3,4)
        HelType Sub254(HelDim(2),3,3,4), Sub256, Sub264
        HelType Sub265, Sub266(HelDim(3),4,2)
        HelType Sub267(HelDim(3),4), Sub268(HelDim(3),4)
        HelType Sub270(HelDim(3),4), Sub271(HelDim(3),4)
        HelType Sub274, Sub275(HelDim(3),4)
        HelType Sub277(HelDim(3),4)
        HelType Sub286(HelDim(3),4,2)
        HelType Sub287(HelDim(2),3,2), Sub288
        HelType Sub289(HelDim(3),4,2)
        HelType Sub290(HelDim(2),3)
        HelType Sub292(HelDim(2),3,3,4,2), Sub293
        HelType Sub294(HelDim(2),3), Sub295(HelDim(2),3)
        HelType Sub296(HelDim(2),3)
        HelType Sub297(HelDim(2),3,3,4,2)
        HelType Sub298(HelDim(2),3,3,4,2)
        HelType Sub299(HelDim(2),3)
        HelType Sub300(HelDim(2),3,3,4,2)
        HelType Sub301(HelDim(2),3,3,4,2), Sub302
        HelType Sub303, Sub304(HelDim(3),4,2)
        HelType Sub305(HelDim(3),4), Sub307(HelDim(3),4)
        HelType Sub310(HelDim(3),4), Sub311(HelDim(3),4)
        HelType Sub313(HelDim(3),4)
        HelType Sub319(HelDim(3),4,2), Sub329, Sub330
        HelType Sub331(HelDim(3),4,2)
        HelType Sub344(HelDim(3),4,2), Sub349, Sub353
        HelType Sub364(HelDim(3),4,2), Sub365, Sub366
        HelType Sub367(HelDim(3),4,2), Sub368, Sub369
        HelType Sub370(HelDim(3),4,2), Sub371, Sub372
        HelType Sub373(HelDim(3),4,2)
        HelType Sub375(HelDim(2),3,3,4), Sub376
        HelType Sub379(HelDim(2),3,3,4), Sub380
        HelType Sub391(HelDim(3),4,2)
        HelType Sub392(HelDim(2),3,3,4,2)
        HelType Sub393(HelDim(3),4,2), Sub394, Sub395
        HelType Sub396(HelDim(3),4,2)
        HelType Sub405(HelDim(2),3,3,2)
        HelType Sub412(HelDim(3),3), Sub416(HelDim(3),3)
        HelType Sub418(HelDim(2),4), Sub419(HelDim(3),3)
        HelType Sub423(HelDim(3),3)
        HelType Sub425(HelDim(3),4,2)
        HelType Sub426(HelDim(3),4,2), Sub427, Sub428
        HelType Sub429(HelDim(3),4,2), Sub430
        HelType Sub431(HelDim(3),4), Sub432(HelDim(3),4)
        HelType Sub433, Sub434(HelDim(3),4)
        HelType Sub435(HelDim(3),4)
        HelType Sub436(HelDim(3),4,2)
        HelType Sub437(HelDim(3),4), Sub438(HelDim(3),4)
        HelType Sub439(HelDim(3),4,2)
        HelType Sub440(HelDim(3),4,2)
        HelType Sub441(HelDim(3),4,2)
        HelType Sub442(HelDim(2),3,3,4,2)
        HelType Sub443(HelDim(3),4,2), Sub444, Sub445
        HelType Sub446(HelDim(3),4,2)
        HelType Sub449(HelDim(2),3,3,4)
        HelType Sub457(HelDim(2),3)
        HelType Sub460(HelDim(2),3,3,4,2)
        HelType Sub461(HelDim(3),3), Sub462(HelDim(3),3)
        HelType Sub464(HelDim(3),3), Sub466(HelDim(3))
        HelType Sub468, Sub470(HelDim(3),4,2)
        HelType Sub472(HelDim(3),4,2), Sub473
        HelType Sub476(HelDim(2),3), Sub477(HelDim(2),3)
        HelType Sub479(HelDim(2),3), Sub480(HelDim(2),3)
        HelType Sub489(HelDim(2),3,3,4)
        HelType Sub492(HelDim(2),3,3,4)
        HelType Sub494(HelDim(3)), Sub496
        HelType Sub498(HelDim(3),3), Sub499
        HelType Sub500(HelDim(3),3), Sub501(HelDim(3))
        HelType Sub502(HelDim(3),3), Sub503, Sub506
        HelType Sub509(HelDim(2),4), Sub510(HelDim(3))
        HelType Sub513, Sub514, Sub516
        HelType Sub517(HelDim(2),3,3,4), Sub520
        HelType Sub521(HelDim(2),3,3,4)
        HelType Sub523(HelDim(3)), Sub529(HelDim(3)), Sub532
        HelType Sub535, Sub537(HelDim(3))
        HelType Sub539(HelDim(3),3), Sub541(HelDim(3),3)
        HelType Sub543(HelDim(3)), Sub548(HelDim(3),3)
        HelType Sub555(HelDim(3),3), Sub561(HelDim(3),3)
        HelType Sub567(HelDim(3)), Sub569, Sub571
        HelType Sub573(HelDim(3),3), Sub576(HelDim(3),3)
        HelType Sub577(HelDim(3),3), Sub578(HelDim(3))
        HelType Sub579(HelDim(3),3), Abb1, Abb2, Abb3, Abb4
        HelType Abb5, Abb6, Abb7, Abb8, Abb9, Abb10, Abb11, Abb12
        HelType Abb13, Abb14, Abb15, Abb16, Abb17, Abb18, Abb19
        HelType Abb20, Abb21, Abb22, Abb23, Abb24, Abb25, Abb26
        HelType Abb27, Abb28, Abb29, Abb30, Abb31, Abb32, Abb33
        HelType Abb34, Abb35, Abb36, Abb37, Abb38, Abb39, Abb40
        HelType Abb41, Abb42, Abb43, Abb44, Abb45, Abb46, Sub38
        HelType Sub43(HelDim(2),3,3,4), Sub48
        HelType Sub51(HelDim(2),3,3,4)
        HelType Sub52(HelDim(2),3,3,4)
        HelType Sub53(HelDim(2),3,3,4), Sub60
        HelType Sub63(HelDim(2),3,3,4), Sub65
        HelType Sub67(HelDim(2),3,3,4)
        HelType Sub68(HelDim(2),3,3,4)
        HelType Sub69(HelDim(2),3,3,4), Sub70
        HelType Sub73(HelDim(2),3,3,4), Sub77, Sub78
        HelType Sub79(HelDim(3),4,2), Sub81, Sub82
        HelType Sub83(HelDim(3),4,2)
        HelType Sub84(HelDim(2),3,3,4,2), Sub85
        HelType Sub88(HelDim(2),3,3,4), Sub109
        HelType Sub112(HelDim(2),3,3,4)
        HelType Sub113(HelDim(2),3,3,4)
        HelType Sub114(HelDim(2),3,3,4,2), Sub115
        HelType Sub117(HelDim(2),3,3,4), Sub118
        HelType Sub120(HelDim(2),3,3,4)
        HelType Sub121(HelDim(2),3,3,4,2)
        HelType Sub122(HelDim(2),3,3,4,2)
        HelType Sub123(HelDim(2),3,3,4,2)
        HelType Sub124(HelDim(2),3,3,4,2), Sub125
        HelType Sub126, Sub127(HelDim(2),3,2), Sub129, Sub130
        HelType Sub131, Sub132(HelDim(2),4), Sub133, Sub134
        HelType Sub135(HelDim(2),4), Sub137
        HelType Sub140(HelDim(2),3,3,4), Sub142
        HelType Sub144(HelDim(2),3,3,4)
        HelType Sub145(HelDim(2),3,3,4)
        HelType Sub146(HelDim(2),3,3,4), Sub150
        HelType Sub154(HelDim(2),3,3,4), Sub155
        HelType Sub158(HelDim(2),3,3,4)
        HelType Sub159(HelDim(2),3,3,4)
        HelType Sub160(HelDim(2),3,3,4)
        HelType Sub166(HelDim(3)), Sub169(HelDim(3))
        HelType Sub170(HelDim(2),3,4)
        HelType Sub172(HelDim(2),3,3,4), Sub173
        HelType Sub174(HelDim(2),3,3,4)
        HelType Sub177(HelDim(2),4), Sub183(HelDim(3))
        HelType Sub186(HelDim(3)), Sub187(HelDim(2),3,4)
        HelType Sub188(HelDim(2),3,4)
        HelType Sub189(HelDim(2),3,3,4), Sub201, Sub202
        HelType Sub204(HelDim(3),3), Sub207, Sub208
        HelType Sub210(HelDim(3),3)
        HelType Sub211(HelDim(2),3,3,4)
        HelType Sub212(HelDim(2),3,3,4), Sub214
        HelType Sub216(HelDim(2),3,3,4)
        HelType Sub220(HelDim(2),3), Sub223(HelDim(2),3)
        HelType Sub224(HelDim(2),3), Sub225(HelDim(2),3)
        HelType Sub226(HelDim(2),3)
        HelType Sub227(HelDim(2),3,3,2), Sub239, Sub240
        HelType Sub241, Sub242, Sub243, Sub244(HelDim(2))
        HelType Sub245(HelDim(2),3,3,2), Sub247
        HelType Sub250(HelDim(2),3,3,4), Sub251, Sub252
        HelType Sub255(HelDim(2),3,3,4), Sub257
        HelType Sub258(HelDim(2),3,3,4)
        HelType Sub259(HelDim(2),3,3,4)
        HelType Sub260(HelDim(2),3,3,4)
        HelType Sub261(HelDim(2),3,3,4,2), Sub262
        HelType Sub263(HelDim(2),3,3,4)
        HelType Sub269(HelDim(3),4), Sub272(HelDim(3),4)
        HelType Sub273(HelDim(3),4,2)
        HelType Sub276(HelDim(3),4), Sub278(HelDim(3),4)
        HelType Sub279(HelDim(3),4,2)
        HelType Sub280(HelDim(3),4,2)
        HelType Sub281(HelDim(3),4,2)
        HelType Sub282(HelDim(2),3,3,4,2), Sub283
        HelType Sub284, Sub285, Sub306(HelDim(3),4)
        HelType Sub308(HelDim(3),4)
        HelType Sub309(HelDim(3),4,2)
        HelType Sub312(HelDim(3),4), Sub314(HelDim(3),4)
        HelType Sub315(HelDim(3),4,2)
        HelType Sub316(HelDim(3),4,2)
        HelType Sub317(HelDim(3),4,2)
        HelType Sub318(HelDim(2),3,3,4,2), Sub320
        HelType Sub321, Sub322(HelDim(3),4,2), Sub323, Sub324
        HelType Sub325(HelDim(3),4,2)
        HelType Sub326(HelDim(3),4,2)
        HelType Sub327(HelDim(3),4,2)
        HelType Sub328(HelDim(2),3,3,4,2), Sub332
        HelType Sub333, Sub334, Sub335(HelDim(3),4,2), Sub336
        HelType Sub337, Sub338, Sub339, Sub340(HelDim(3),4,2)
        HelType Sub341(HelDim(3),4,2)
        HelType Sub342(HelDim(3),4,2)
        HelType Sub343(HelDim(2),3,3,4,2)
        HelType Sub345(HelDim(3),4,2), Sub346, Sub347
        HelType Sub348(HelDim(3),4,2), Sub350
        HelType Sub352(HelDim(2),3,4)
        HelType Sub354(HelDim(2),3,4)
        HelType Sub355(HelDim(2),3,3,4,2), Sub356
        HelType Sub357(HelDim(2),3,4), Sub358
        HelType Sub359(HelDim(2),3,4)
        HelType Sub360(HelDim(2),3,3,4,2)
        HelType Sub361(HelDim(2),3,3,4,2)
        HelType Sub362(HelDim(2),3,3,4,2)
        HelType Sub363(HelDim(2),3,3,4,2), Sub383
        HelType Sub384(HelDim(2),3,3,4), Sub385
        HelType Sub386(HelDim(2),3,3,4)
        HelType Sub387(HelDim(2),3,3,4,2)
        HelType Sub389(HelDim(2),3,3,4,2), Sub397
        HelType Sub398, Sub399, Sub400, Sub401
        HelType Sub402(HelDim(3),4,2)
        HelType Sub403(HelDim(2),3,4,2)
        HelType Sub404(HelDim(2),3,3,4,2), Sub406
        HelType Sub408(HelDim(3),3), Sub411
        HelType Sub413(HelDim(3),3), Sub417(HelDim(3),3)
        HelType Sub420(HelDim(3),3), Sub422(HelDim(3),3)
        HelType Sub424(HelDim(3),3), Sub447
        HelType Sub448(HelDim(2),3,3,4)
        HelType Sub450(HelDim(2),3,3,4)
        HelType Sub451(HelDim(2),3,3,4,2), Sub452
        HelType Sub453(HelDim(2),3,3,4)
        HelType Sub455(HelDim(2),3,3,4,2)
        HelType Sub456(HelDim(2),3,3,4,2)
        HelType Sub458(HelDim(2),3,3,4,2)
        HelType Sub459(HelDim(2),3,3,4,2)
        HelType Sub463(HelDim(3),3), Sub465(HelDim(3),3)
        HelType Sub467(HelDim(3),3), Sub474(HelDim(2),3)
        HelType Sub475(HelDim(2),3), Sub478(HelDim(2),3)
        HelType Sub481(HelDim(2),3)
        HelType Sub482(HelDim(2),3,3,4,2)
        HelType Sub483(HelDim(2),3,3,4,2)
        HelType Sub484(HelDim(2),3)
        HelType Sub485(HelDim(2),3,3,4,2)
        HelType Sub486(HelDim(2),3,3,4,2), Sub504
        HelType Sub505(HelDim(2),3,3,4), Sub507
        HelType Sub508(HelDim(2),3,3,4)
        HelType Sub511(HelDim(2),3,3,4)
        HelType Sub512(HelDim(2),3,3,4), Sub531
        HelType Sub533(HelDim(2),3,3,4), Sub534
        HelType Sub536(HelDim(2),3,3,4)
        HelType Sub538(HelDim(2),3,3,4)
        HelType Sub540(HelDim(3),3), Sub542(HelDim(3),3)
        HelType Sub544(HelDim(3),3)
        HelType Sub545(HelDim(2),3,3,4)
        HelType Sub546(HelDim(3),3), Sub547(HelDim(3),3)
        HelType Sub549(HelDim(3),3)
        HelType Sub550(HelDim(2),3,3,4), Sub551
        HelType Sub552(HelDim(2),3,3,4), Sub553
        HelType Sub554(HelDim(2),3,3,4)
        HelType Sub556(HelDim(2),3,3,4), Sub557
        HelType Sub558(HelDim(2),3,3,4), Sub559
        HelType Sub560(HelDim(2),3,3,4)
        HelType Sub562(HelDim(2),3,3,4), Sub563
        HelType Sub564(HelDim(2),3,3,4), Sub565
        HelType Sub566(HelDim(2),3,3,4)
        HelType Sub568(HelDim(2),3,3,4)
        HelType Sub570(HelDim(3),3), Sub572(HelDim(3),3)
        HelType Sub574(HelDim(3),3)
        HelType Sub575(HelDim(2),3,3,4)
        HelType Sub585(HelDim(2),3,3,4,2)
        HelType Sub589(HelDim(2),3,3,4)
        HelType Sub590(HelDim(2),3,3,4,2)
        HelType Sub592(HelDim(2),3,3,4,2)
        HelType Sub593(HelDim(2),3,3,4,2)
        HelType Sub596(HelDim(2),3,3,4)
        HelType Sub597(HelDim(2),3,3,4,2)
        HelType Sub598(HelDim(2),3,3,4,2)
        HelType Sub599(HelDim(2),3,3,4,2)
        HelType Sub600(HelDim(2),3,3,4,2)
        HelType Sub601(HelDim(2),3,3,4,2)
        HelType Sub603(HelDim(2),3,3,4,2)
        HelType Sub605(HelDim(2),3,3,4,2)
        HelType Sub606(HelDim(2),3,3,4,2)
        HelType Sub608(HelDim(2),3,3,4,2)
        HelType Sub609(HelDim(2),3,3,4,2)
        HelType Sub611(HelDim(2),3,3,4,2)
        HelType Sub612(HelDim(2),3,3,4,2)
        HelType Sub613(HelDim(2),3,3,4,2)
        HelType Sub614(HelDim(2),3,3,4,2)
        HelType Sub615(HelDim(2),3,3,4,2)
        HelType Sub616(HelDim(2),3,3,4,2)
        HelType Sub617(HelDim(2),3,3,4,2)
        HelType Sub618(HelDim(2),3,3,4)
        HelType Sub619(HelDim(2),3,3,4)
        HelType Sub620(HelDim(2),3,3,4)
        HelType Sub621(HelDim(2),3,3,4)
        HelType Sub624(HelDim(2),3,3,4)
        HelType Sub625(HelDim(2),3,3,4)
        HelType Sub626(HelDim(2),3,3,4)
        HelType Sub629(HelDim(2),3,3,4)
        HelType Sub630(HelDim(2),3,3,4)
        HelType Sub631(HelDim(2),3,3,4)
        HelType Sub636(HelDim(2),3,3,4)
        HelType Sub637(HelDim(2),3,3,4)
        HelType Sub639(HelDim(2),3,3,4)
        HelType Sub640(HelDim(2),3,3,4)
        HelType Sub641(HelDim(2),3,3,4)
        HelType Sub643(HelDim(2),3,3,4)
        HelType Sub644(HelDim(2),3,3,4), Sub374
        HelType Sub377(HelDim(2),3,3,4), Sub378
        HelType Sub381(HelDim(2),3,3,4)
        HelType Sub382(HelDim(2),3,3,4,2)
        HelType Sub388(HelDim(2),3,3,4,2)
        HelType Sub390(HelDim(2),3,3,4,2), Sub487
        HelType Sub490(HelDim(2),3,3,4), Sub491
        HelType Sub493(HelDim(2),3,3,4)
        HelType Sub495(HelDim(2),3,3,4), Sub515
        HelType Sub518(HelDim(2),3,3,4), Sub519
        HelType Sub522(HelDim(2),3,3,4)
        HelType Sub524(HelDim(2),3,3,4), Sub525
        HelType Sub526(HelDim(2),3,3,4), Sub527
        HelType Sub528(HelDim(2),3,3,4)
        HelType Sub530(HelDim(2),3,3,4)
        HelType Sub594(HelDim(2),3,3,4,2)
        HelType Sub602(HelDim(2),3,3,4,2)
        HelType Sub622(HelDim(2),3,3,4)
        HelType Sub623(HelDim(2),3,3,4)
        HelType Sub627(HelDim(2),3,3,4)
        HelType Sub628(HelDim(2),3,3,4)
        HelType Sub632(HelDim(2),3,3,4)
        HelType Sub633(HelDim(2),3,3,4)
        HelType Sub634(HelDim(2),3,3,4)
        HelType Sub635(HelDim(2),3,3,4)
        HelType Sub638(HelDim(2),3,3,4)
        HelType Sub642(HelDim(2),3,3,4)
        HelType Sub645(HelDim(2),3,3,4)
        common /gqu_nIxJqdg_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /gqu_nIxJqdg_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /gqu_nIxJqdg_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /gqu_nIxJqdg_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /gqu_nIxJqdg_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /gqu_nIxJqdg_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /gqu_nIxJqdg_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /gqu_nIxJqdg_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /gqu_nIxJqdg_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /gqu_nIxJqdg_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /gqu_nIxJqdg_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /gqu_nIxJqdg_varXh/ F102, F103, F104, F105, F106, F107, F108
        common /gqu_nIxJqdg_varXh/ F109, F110, F111, F112, F113, F114, F115
        common /gqu_nIxJqdg_varXh/ F116, F117, F118, F119, F120, F121, F122
        common /gqu_nIxJqdg_varXh/ F123, F124, F125, F126, F127, F128, F129
        common /gqu_nIxJqdg_varXh/ F130, F131, F132, F133, F134, F135, F136
        common /gqu_nIxJqdg_varXh/ F137, F138, F139, F140, F141, F142, F143
        common /gqu_nIxJqdg_varXh/ F144, F145, F146, F147, F148, F149, F150
        common /gqu_nIxJqdg_varXh/ F151, F152, F153, F154, F155, F156, F157
        common /gqu_nIxJqdg_varXh/ F158, F159, F160, F161, F162, F163, F164
        common /gqu_nIxJqdg_varXh/ F165, F166, F167, F168, F169, F170, F171
        common /gqu_nIxJqdg_varXh/ F172, F173, F174, F175, F176, F177, F178
        common /gqu_nIxJqdg_varXh/ F179, F180, F181, F182, F183, F184, F185
        common /gqu_nIxJqdg_varXh/ F186, F187, F188, F189, F190, F191, F192
        common /gqu_nIxJqdg_varXh/ F193, F194, F195, F196, F197, F198, F199
        common /gqu_nIxJqdg_varXh/ F200, F201, F202, F203, F204, F205, F206
        common /gqu_nIxJqdg_varXh/ F207, F208, F209, F210, F211, Pair1, Pair2
        common /gqu_nIxJqdg_varXh/ Pair3, Pair4, Pair5, Pair6, Pair7, Pair8
        common /gqu_nIxJqdg_varXh/ Pair9, Pair10, Pair11, Sub4, Sub6, Sub7, Sub8
        common /gqu_nIxJqdg_varXh/ Sub9, Sub10, Sub15, Sub16, Sub17, Sub18
        common /gqu_nIxJqdg_varXh/ Sub19, Sub20, Sub22, Sub23, Sub25, Sub26
        common /gqu_nIxJqdg_varXh/ Sub27, Sub28, Sub29, Sub30, Sub31, Sub32
        common /gqu_nIxJqdg_varXh/ Sub33, Sub34, Sub35, Sub36, Sub37, Sub39
        common /gqu_nIxJqdg_varXh/ Sub42, Sub44, Sub45, Sub46, Sub47, Sub49
        common /gqu_nIxJqdg_varXh/ Sub50, Sub54, Sub55, Sub56, Sub57, Sub58
        common /gqu_nIxJqdg_varXh/ Sub59, Sub62, Sub64, Sub66, Sub74, Sub75
        common /gqu_nIxJqdg_varXh/ Sub76, Sub87, Sub89, Sub91, Sub92, Sub93
        common /gqu_nIxJqdg_varXh/ Sub94, Sub95, Sub96, Sub97, Sub98, Sub99
        common /gqu_nIxJqdg_varXh/ Sub100, Sub101, Sub102, Sub103, Sub104
        common /gqu_nIxJqdg_varXh/ Sub105, Sub106, Sub107, Sub108, Sub110
        common /gqu_nIxJqdg_varXh/ Sub116, Sub119, Sub128, Sub136, Sub139
        common /gqu_nIxJqdg_varXh/ Sub141, Sub143, Sub147, Sub148, Sub149
        common /gqu_nIxJqdg_varXh/ Sub151, Sub153, Sub156, Sub157, Sub161
        common /gqu_nIxJqdg_varXh/ Sub162, Sub163, Sub164, Sub165, Sub167
        common /gqu_nIxJqdg_varXh/ Sub168, Sub171, Sub175, Sub178, Sub179
        common /gqu_nIxJqdg_varXh/ Sub180, Sub181, Sub182, Sub184, Sub185
        common /gqu_nIxJqdg_varXh/ Sub190, Sub191, Sub192, Sub193, Sub194
        common /gqu_nIxJqdg_varXh/ Sub195, Sub196, Sub197, Sub198, Sub199
        common /gqu_nIxJqdg_varXh/ Sub200, Sub203, Sub205, Sub206, Sub209
        common /gqu_nIxJqdg_varXh/ Sub213, Sub217, Sub218, Sub219, Sub221
        common /gqu_nIxJqdg_varXh/ Sub222, Sub228, Sub229, Sub230, Sub231
        common /gqu_nIxJqdg_varXh/ Sub232, Sub233, Sub234, Sub235, Sub236
        common /gqu_nIxJqdg_varXh/ Sub237, Sub238, Sub246, Sub249, Sub254
        common /gqu_nIxJqdg_varXh/ Sub256, Sub264, Sub265, Sub266, Sub267
        common /gqu_nIxJqdg_varXh/ Sub268, Sub270, Sub271, Sub274, Sub275
        common /gqu_nIxJqdg_varXh/ Sub277, Sub286, Sub287, Sub288, Sub289
        common /gqu_nIxJqdg_varXh/ Sub290, Sub292, Sub293, Sub294, Sub295
        common /gqu_nIxJqdg_varXh/ Sub296, Sub297, Sub298, Sub299, Sub300
        common /gqu_nIxJqdg_varXh/ Sub301, Sub302, Sub303, Sub304, Sub305
        common /gqu_nIxJqdg_varXh/ Sub307, Sub310, Sub311, Sub313, Sub319
        common /gqu_nIxJqdg_varXh/ Sub329, Sub330, Sub331, Sub344, Sub349
        common /gqu_nIxJqdg_varXh/ Sub353, Sub364, Sub365, Sub366, Sub367
        common /gqu_nIxJqdg_varXh/ Sub368, Sub369, Sub370, Sub371, Sub372
        common /gqu_nIxJqdg_varXh/ Sub373, Sub375, Sub376, Sub379, Sub380
        common /gqu_nIxJqdg_varXh/ Sub391, Sub392, Sub393, Sub394, Sub395
        common /gqu_nIxJqdg_varXh/ Sub396, Sub405, Sub412, Sub416, Sub418
        common /gqu_nIxJqdg_varXh/ Sub419, Sub423, Sub425, Sub426, Sub427
        common /gqu_nIxJqdg_varXh/ Sub428, Sub429, Sub430, Sub431, Sub432
        common /gqu_nIxJqdg_varXh/ Sub433, Sub434, Sub435, Sub436, Sub437
        common /gqu_nIxJqdg_varXh/ Sub438, Sub439, Sub440, Sub441, Sub442
        common /gqu_nIxJqdg_varXh/ Sub443, Sub444, Sub445, Sub446, Sub449
        common /gqu_nIxJqdg_varXh/ Sub457, Sub460, Sub461, Sub462, Sub464
        common /gqu_nIxJqdg_varXh/ Sub466, Sub468, Sub470, Sub472, Sub473
        common /gqu_nIxJqdg_varXh/ Sub476, Sub477, Sub479, Sub480, Sub489
        common /gqu_nIxJqdg_varXh/ Sub492, Sub494, Sub496, Sub498, Sub499
        common /gqu_nIxJqdg_varXh/ Sub500, Sub501, Sub502, Sub503, Sub506
        common /gqu_nIxJqdg_varXh/ Sub509, Sub510, Sub513, Sub514, Sub516
        common /gqu_nIxJqdg_varXh/ Sub517, Sub520, Sub521, Sub523, Sub529
        common /gqu_nIxJqdg_varXh/ Sub532, Sub535, Sub537, Sub539, Sub541
        common /gqu_nIxJqdg_varXh/ Sub543, Sub548, Sub555, Sub561, Sub567
        common /gqu_nIxJqdg_varXh/ Sub569, Sub571, Sub573, Sub576, Sub577
        common /gqu_nIxJqdg_varXh/ Sub578, Sub579, Abb1, Abb2, Abb3, Abb4, Abb5
        common /gqu_nIxJqdg_varXh/ Abb6, Abb7, Abb8, Abb9, Abb10, Abb11, Abb12
        common /gqu_nIxJqdg_varXh/ Abb13, Abb14, Abb15, Abb16, Abb17, Abb18
        common /gqu_nIxJqdg_varXh/ Abb19, Abb20, Abb21, Abb22, Abb23, Abb24
        common /gqu_nIxJqdg_varXh/ Abb25, Abb26, Abb27, Abb28, Abb29, Abb30
        common /gqu_nIxJqdg_varXh/ Abb31, Abb32, Abb33, Abb34, Abb35, Abb36
        common /gqu_nIxJqdg_varXh/ Abb37, Abb38, Abb39, Abb40, Abb41, Abb42
        common /gqu_nIxJqdg_varXh/ Abb43, Abb44, Abb45, Abb46, Sub38, Sub43
        common /gqu_nIxJqdg_varXh/ Sub48, Sub51, Sub52, Sub53, Sub60, Sub63
        common /gqu_nIxJqdg_varXh/ Sub65, Sub67, Sub68, Sub69, Sub70, Sub73
        common /gqu_nIxJqdg_varXh/ Sub77, Sub78, Sub79, Sub81, Sub82, Sub83
        common /gqu_nIxJqdg_varXh/ Sub84, Sub85, Sub88, Sub109, Sub112, Sub113
        common /gqu_nIxJqdg_varXh/ Sub114, Sub115, Sub117, Sub118, Sub120
        common /gqu_nIxJqdg_varXh/ Sub121, Sub122, Sub123, Sub124, Sub125
        common /gqu_nIxJqdg_varXh/ Sub126, Sub127, Sub129, Sub130, Sub131
        common /gqu_nIxJqdg_varXh/ Sub132, Sub133, Sub134, Sub135, Sub137
        common /gqu_nIxJqdg_varXh/ Sub140, Sub142, Sub144, Sub145, Sub146
        common /gqu_nIxJqdg_varXh/ Sub150, Sub154, Sub155, Sub158, Sub159
        common /gqu_nIxJqdg_varXh/ Sub160, Sub166, Sub169, Sub170, Sub172
        common /gqu_nIxJqdg_varXh/ Sub173, Sub174, Sub177, Sub183, Sub186
        common /gqu_nIxJqdg_varXh/ Sub187, Sub188, Sub189, Sub201, Sub202
        common /gqu_nIxJqdg_varXh/ Sub204, Sub207, Sub208, Sub210, Sub211
        common /gqu_nIxJqdg_varXh/ Sub212, Sub214, Sub216, Sub220, Sub223
        common /gqu_nIxJqdg_varXh/ Sub224, Sub225, Sub226, Sub227, Sub239
        common /gqu_nIxJqdg_varXh/ Sub240, Sub241, Sub242, Sub243, Sub244
        common /gqu_nIxJqdg_varXh/ Sub245, Sub247, Sub250, Sub251, Sub252
        common /gqu_nIxJqdg_varXh/ Sub255, Sub257, Sub258, Sub259, Sub260
        common /gqu_nIxJqdg_varXh/ Sub261, Sub262, Sub263, Sub269, Sub272
        common /gqu_nIxJqdg_varXh/ Sub273, Sub276, Sub278, Sub279, Sub280
        common /gqu_nIxJqdg_varXh/ Sub281, Sub282, Sub283, Sub284, Sub285
        common /gqu_nIxJqdg_varXh/ Sub306, Sub308, Sub309, Sub312, Sub314
        common /gqu_nIxJqdg_varXh/ Sub315, Sub316, Sub317, Sub318, Sub320
        common /gqu_nIxJqdg_varXh/ Sub321, Sub322, Sub323, Sub324, Sub325
        common /gqu_nIxJqdg_varXh/ Sub326, Sub327, Sub328, Sub332, Sub333
        common /gqu_nIxJqdg_varXh/ Sub334, Sub335, Sub336, Sub337, Sub338
        common /gqu_nIxJqdg_varXh/ Sub339, Sub340, Sub341, Sub342, Sub343
        common /gqu_nIxJqdg_varXh/ Sub345, Sub346, Sub347, Sub348, Sub350
        common /gqu_nIxJqdg_varXh/ Sub352, Sub354, Sub355, Sub356, Sub357
        common /gqu_nIxJqdg_varXh/ Sub358, Sub359, Sub360, Sub361, Sub362
        common /gqu_nIxJqdg_varXh/ Sub363, Sub383, Sub384, Sub385, Sub386
        common /gqu_nIxJqdg_varXh/ Sub387, Sub389, Sub397, Sub398, Sub399
        common /gqu_nIxJqdg_varXh/ Sub400, Sub401, Sub402, Sub403, Sub404
        common /gqu_nIxJqdg_varXh/ Sub406, Sub408, Sub411, Sub413, Sub417
        common /gqu_nIxJqdg_varXh/ Sub420, Sub422, Sub424, Sub447, Sub448
        common /gqu_nIxJqdg_varXh/ Sub450, Sub451, Sub452, Sub453, Sub455
        common /gqu_nIxJqdg_varXh/ Sub456, Sub458, Sub459, Sub463, Sub465
        common /gqu_nIxJqdg_varXh/ Sub467, Sub474, Sub475, Sub478, Sub481
        common /gqu_nIxJqdg_varXh/ Sub482, Sub483, Sub484, Sub485, Sub486
        common /gqu_nIxJqdg_varXh/ Sub504, Sub505, Sub507, Sub508, Sub511
        common /gqu_nIxJqdg_varXh/ Sub512, Sub531, Sub533, Sub534, Sub536
        common /gqu_nIxJqdg_varXh/ Sub538, Sub540, Sub542, Sub544, Sub545
        common /gqu_nIxJqdg_varXh/ Sub546, Sub547, Sub549, Sub550, Sub551
        common /gqu_nIxJqdg_varXh/ Sub552, Sub553, Sub554, Sub556, Sub557
        common /gqu_nIxJqdg_varXh/ Sub558, Sub559, Sub560, Sub562, Sub563
        common /gqu_nIxJqdg_varXh/ Sub564, Sub565, Sub566, Sub568, Sub570
        common /gqu_nIxJqdg_varXh/ Sub572, Sub574, Sub575, Sub585, Sub589
        common /gqu_nIxJqdg_varXh/ Sub590, Sub592, Sub593, Sub596, Sub597
        common /gqu_nIxJqdg_varXh/ Sub598, Sub599, Sub600, Sub601, Sub603
        common /gqu_nIxJqdg_varXh/ Sub605, Sub606, Sub608, Sub609, Sub611
        common /gqu_nIxJqdg_varXh/ Sub612, Sub613, Sub614, Sub615, Sub616
        common /gqu_nIxJqdg_varXh/ Sub617, Sub618, Sub619, Sub620, Sub621
        common /gqu_nIxJqdg_varXh/ Sub624, Sub625, Sub626, Sub629, Sub630
        common /gqu_nIxJqdg_varXh/ Sub631, Sub636, Sub637, Sub639, Sub640
        common /gqu_nIxJqdg_varXh/ Sub641, Sub643, Sub644, Sub374, Sub377
        common /gqu_nIxJqdg_varXh/ Sub378, Sub381, Sub382, Sub388, Sub390
        common /gqu_nIxJqdg_varXh/ Sub487, Sub490, Sub491, Sub493, Sub495
        common /gqu_nIxJqdg_varXh/ Sub515, Sub518, Sub519, Sub522, Sub524
        common /gqu_nIxJqdg_varXh/ Sub525, Sub526, Sub527, Sub528, Sub530
        common /gqu_nIxJqdg_varXh/ Sub594, Sub602, Sub622, Sub623, Sub627
        common /gqu_nIxJqdg_varXh/ Sub628, Sub632, Sub633, Sub634, Sub635
        common /gqu_nIxJqdg_varXh/ Sub638, Sub642, Sub645

        integer Sfe7
        common /gqu_nIxJqdg_indices/ Sfe7

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /gqu_nIxJqdg_formfactors/ Ctree, MatSUN

#endif

