#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 12-Nov-2016 17:51
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub2(4), Sub9(4), Sub461(3,3)
        ComplexType Sub361(3,3), Sub76(3,3)
        ComplexType Sub504(3,3), Sub618(3,4)
        ComplexType Sub658(3,4), Sub785(3,2)
        ComplexType Sub750(3,4), Sub771(3,4)
        ComplexType Sub783(3,2), Sub38(4,4)
        ComplexType Sub40(4,4), Sub11(3,4,2)
        ComplexType Sub13(3,4,2), Sub12(3,4,2)
        ComplexType Sub1(3,4,2), Sub7(3,4,2)
        ComplexType Sub6(3,4,2), Sub3(3,4,2)
        ComplexType Sub4(3,4,2), Sub10(3,4,2)
        ComplexType Sub15(3,4,2), Sub332(3,3,4)
        ComplexType Sub333(3,3,4,4), Sub774(3,4)
        common /varXs/ Sub2, Sub9, Sub461, Sub361, Sub76, Sub504
        common /varXs/ Sub618, Sub658, Sub785, Sub750, Sub771
        common /varXs/ Sub783, Sub38, Sub40, Sub11, Sub13, Sub12
        common /varXs/ Sub1, Sub7, Sub6, Sub3, Sub4, Sub10, Sub15
        common /varXs/ Sub332, Sub333, Sub774

        ComplexType Opt2, Sub425(3,3,4)
        ComplexType Sub232(3,3,4), Sub804(3,4)
        ComplexType Sub809(3,4), Sub782(3,4)
        ComplexType Sub792(3,4), Sub81(3,3,4,4)
        ComplexType Sub162(3,4,4)
        ComplexType Sub83(3,3,4,4)
        ComplexType Sub276(3,3,4,4)
        ComplexType Sub299(3,3,4,4)
        ComplexType Sub542(3,4,4), Sub557(3,4,4)
        ComplexType Sub810(3,3,4,4)
        ComplexType Sub784(3,3,4,4)
        ComplexType Sub789(3,3,4,4)
        ComplexType Sub231(3,3,4,4)
        ComplexType Sub334(3,3,4,4)
        ComplexType Sub540(3,3,4,4)
        ComplexType Sub561(3,3,4,4)
        ComplexType Sub787(3,3,4,4)
        ComplexType Sub728(3,3,4,4)
        ComplexType Sub794(3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt2, Sub425, Sub232, Sub804, Sub809, Sub782
        common /varXa/ Sub792, Sub81, Sub162, Sub83, Sub276, Sub299
        common /varXa/ Sub542, Sub557, Sub810, Sub784, Sub789
        common /varXa/ Sub231, Sub334, Sub540, Sub561, Sub787
        common /varXa/ Sub728, Sub794, S, T, T14, T15, U, T24, T25
        common /varXa/ S34, S35, S45

        HelType F39, F27, F11, F14, F25, F45, F109, F33, F50, F93
        HelType F54, F34, F154, F46, F41, F155, F1, F161, F170, F162
        HelType F163, F3, F166, F172, F167, F168, F15, F29, F67
        HelType F143, F31, F69, F144, F57, F183, F94, F145, F194
        HelType F146, F66, F18, F36, F48, F97, F37, F53, F99, F62
        HelType F190, F92, F150, F191, F151, F72, F32, F56, F207
        HelType F30, F16, F2, F86, F49, F236, F242, F237, F133, F231
        HelType F135, F60, F44, F82, F208, F43, F17, F7, F79, F75
        HelType F232, F229, F234, F90, F235, F91, F84, F156, F12
        HelType F211, F213, F176, F177, F178, F179, F180, F157, F13
        HelType F201, F202, F184, F185, F186, F187, F188, F102, F28
        HelType F26, F115, F195, F117, F196, F119, F118, F120, F121
        HelType F122, F123, F173, F124, F103, F40, F38, F96, F197
        HelType F98, F198, F131, F100, F132, F101, F134, F136, F192
        HelType F137, F59, F35, F212, F55, F158, F199, F204, F223
        HelType F64, F224, F65, F189, F52, F19, F5, F20, F8, F61, F6
        HelType F63, F21, F230, F239, F238, F139, F47, F42, F214
        HelType F74, F105, F200, F206, F227, F80, F228, F81, F193
        HelType F70, F22, F9, F23, F4, F76, F10, F78, F24, F233
        HelType F240, F241, F106, F169, F159, F160, F171, F164, F165
        HelType F140, F68, F141, F71, F142, F147, F88, F148, F51
        HelType F149, F85, F87, F219, F209, F215, F128, F216, F130
        HelType F58, F152, F153, F125, F126, F77, F73, F220, F210
        HelType F217, F112, F218, F89, F83, F110, F111, F107, F108
        HelType F174, F175, F181, F182, F114, F113, F116, F127, F95
        HelType F129, F203, F221, F222, F138, F205, F225, F226, F104
        HelType Pair5, Pair1, Pair2, Pair11, Pair8, Pair10, Pair9
        HelType Pair6, Pair7, Pair3, Pair4, Abb25, Abb1, Abb30
        HelType Abb11, Abb21, Abb6, Abb14, Abb7, Abb16, Abb5, Abb24
        HelType Abb19, Abb15, Abb10, Abb8, Abb9, Abb17, Abb2, Abb34
        HelType Abb31, Abb27, Abb20, Abb23, Abb28, Abb13, Abb26
        HelType Abb4, Abb18, Abb32, Abb29, Abb33, Abb12, Abb3, Abb22
        HelType Opt1, Opt3(HelDim(3),3), Sub515, Sub502
        HelType Sub144, Sub181, Sub148, Sub156, Sub224, Sub493
        HelType Sub154, Sub180, Sub522, Sub54, Sub555, Sub271
        HelType Sub559, Sub278, Sub273, Sub280, Sub216, Sub220
        HelType Sub748, Sub752, Sub727, Sub776, Sub133, Sub46
        HelType Sub372, Sub366, Sub184, Sub158, Sub161, Sub472
        HelType Sub496, Sub212, Sub129, Sub170, Sub127, Sub178
        HelType Sub56, Sub65, Sub204, Sub474, Sub525, Sub187, Sub225
        HelType Sub168, Sub176, Sub251, Sub89, Sub209, Sub206
        HelType Sub288, Sub296, Sub303, Sub538, Sub294, Sub547
        HelType Sub307, Sub211, Sub203, Sub481, Sub731, Sub588
        HelType Sub596, Sub655, Sub539, Sub660, Sub545, Sub620
        HelType Sub560, Sub637, Sub639, Sub615, Sub556, Sub768
        HelType Sub715, Sub718, Sub157, Sub383, Sub400, Sub240
        HelType Sub374, Sub505, Sub389, Sub248, Sub402, Sub517
        HelType Sub183, Sub164, Sub160, Sub137, Sub331, Sub186
        HelType Sub131, Sub341, Sub182, Sub487, Sub586, Sub602
        HelType Sub226, Sub408(HelDim(3)), Sub399(HelDim(3))
        HelType Sub371(HelDim(3)), Sub410(HelDim(3))
        HelType Sub365(HelDim(3)), Sub376(HelDim(3))
        HelType Sub405(HelDim(3)), Sub79(HelDim(3))
        HelType Sub428(HelDim(3)), Sub466(HelDim(3))
        HelType Sub106(HelDim(3)), Sub117(HelDim(3))
        HelType Sub78(HelDim(3)), Sub94(HelDim(3))
        HelType Sub196(HelDim(3)), Sub622(HelDim(3))
        HelType Sub617(HelDim(3)), Sub354(HelDim(3))
        HelType Sub355(HelDim(3)), Sub662(HelDim(3))
        HelType Sub197(HelDim(3)), Sub657(HelDim(3))
        HelType Sub431(HelDim(3)), Sub451(HelDim(3))
        HelType Sub238(HelDim(3)), Sub246(HelDim(3))
        HelType Sub369(HelDim(3)), Sub463(HelDim(3))
        HelType Sub778(HelDim(3)), Sub770(HelDim(3))
        HelType Sub455(HelDim(3)), Sub434(HelDim(3))
        HelType Sub424(HelDim(3)), Sub769(HelDim(3))
        HelType Sub777(HelDim(3)), Sub749(HelDim(3))
        HelType Sub758(HelDim(3)), Sub729(HelDim(3))
        HelType Sub738(HelDim(4)), Sub740(HelDim(4))
        HelType Sub413(HelDim(4)), Sub584(HelDim(4))
        HelType Sub628(HelDim(4)), Sub630(HelDim(4))
        HelType Sub454(HelDim(3),3), Sub423(HelDim(3),3)
        HelType Sub453(HelDim(3),3), Sub611(HelDim(3),4)
        HelType Sub613(HelDim(3),4), Sub651(HelDim(3),4)
        HelType Sub653(HelDim(3),4), Sub443(HelDim(3),4)
        HelType Sub693(HelDim(3),4), Sub691(HelDim(3),4)
        HelType Sub696(HelDim(3),4), Sub695(HelDim(3),4)
        HelType Sub744(HelDim(3),4), Sub746(HelDim(3),4)
        HelType Sub675(HelDim(3),4), Sub671(HelDim(3),4)
        HelType Sub676(HelDim(3),4), Sub672(HelDim(3),4)
        HelType Sub764(HelDim(3),4), Sub766(HelDim(3),4)
        HelType Sub192(HelDim(4),4), Sub261(HelDim(4),4)
        HelType Sub351(HelDim(4),4), Sub570(HelDim(4),4)
        HelType Sub473(HelDim(4),4), Sub313(HelDim(4),4)
        HelType Sub128(HelDim(4),4), Sub314(HelDim(4),4)
        HelType Sub571(HelDim(4),4), Sub130(HelDim(4),4)
        HelType Sub202(HelDim(4),4), Sub41(HelDim(4),4)
        HelType Sub44(HelDim(4),4), Sub475(HelDim(4),4)
        HelType Sub200(HelDim(4),4), Sub531(HelDim(4),4)
        HelType Sub605(HelDim(4),4)
        HelType Sub441(HelDim(3),3,4)
        HelType Sub445(HelDim(3),3,4)
        HelType Sub456(HelDim(3),3,4)
        HelType Sub438(HelDim(3),3,4)
        HelType Sub448(HelDim(3),3,4)
        HelType Sub194(HelDim(3),4,4)
        HelType Sub350(HelDim(3),4,4)
        HelType Sub135(HelDim(3),4,4)
        HelType Sub140(HelDim(3),4,4)
        HelType Sub147(HelDim(3),4,4)
        HelType Sub153(HelDim(3),4,4)
        HelType Sub317(HelDim(3),4,4)
        HelType Sub321(HelDim(3),4,4)
        HelType Sub325(HelDim(3),4,4)
        HelType Sub328(HelDim(3),4,4)
        HelType Sub48(HelDim(3),4,4)
        HelType Sub53(HelDim(3),4,4)
        HelType Sub581(HelDim(3),4,4)
        HelType Sub595(HelDim(3),4,4)
        HelType Sub14(HelDim(3),4,2)
        HelType Sub553(HelDim(3),4,2)
        HelType Sub686(HelDim(3),4,2)
        HelType Sub17(HelDim(3),4,2)
        HelType Sub265(HelDim(3),4,2)
        HelType Sub554(HelDim(3),4,2)
        HelType Sub198(HelDim(3),4,2)
        HelType Sub199(HelDim(3),4,2)
        HelType Sub21(HelDim(3),4,2)
        HelType Sub24(HelDim(3),4,2)
        HelType Sub813(HelDim(3),4,2)
        HelType Sub270(HelDim(3),4,2)
        HelType Sub568(HelDim(3),4,2)
        HelType Sub614(HelDim(3),4,2)
        HelType Sub624(HelDim(3),4,2)
        HelType Sub625(HelDim(3),4,2)
        HelType Sub689(HelDim(3),4,2)
        HelType Sub741(HelDim(3),4,2)
        HelType Sub742(HelDim(3),4,2)
        HelType Sub35(HelDim(3),4,2)
        HelType Sub357(HelDim(3),4,2)
        HelType Sub551(HelDim(3),4,2)
        HelType Sub632(HelDim(3),4,2)
        HelType Sub665(HelDim(3),4,2)
        HelType Sub536(HelDim(3),4,2)
        HelType Sub33(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub626(HelDim(3),4,2)
        HelType Sub286(HelDim(3),4,2)
        HelType Sub537(HelDim(3),4,2)
        HelType Sub31(HelDim(3),4,2)
        HelType Sub356(HelDim(3),4,2)
        HelType Sub631(HelDim(3),4,2)
        HelType Sub654(HelDim(3),4,2)
        HelType Sub664(HelDim(3),4,2)
        HelType Sub669(HelDim(3),4,2)
        HelType Sub263(HelDim(3),4,4)
        HelType Sub208(HelDim(3),4,4)
        HelType Sub214(HelDim(3),4,4)
        HelType Sub219(HelDim(3),4,4)
        HelType Sub223(HelDim(3),4,4)
        HelType Sub479(HelDim(3),4,4)
        HelType Sub484(HelDim(3),4,4)
        HelType Sub490(HelDim(3),4,4)
        HelType Sub513(HelDim(3),4,4)
        HelType Sub574(HelDim(3),4,4)
        HelType Sub577(HelDim(3),4,4)
        HelType Sub61(HelDim(3),4,4)
        HelType Sub67(HelDim(3),4,4)
        HelType Sub125(HelDim(3),4,4)
        HelType Sub26(HelDim(3),4,2)
        HelType Sub5(HelDim(3),4,2)
        HelType Sub633(HelDim(3),4,2)
        HelType Sub643(HelDim(3),4,2)
        HelType Sub700(HelDim(3),4,2)
        HelType Sub701(HelDim(3),4,2)
        HelType Sub32(HelDim(3),4,2)
        HelType Sub636(HelDim(3),4,2)
        HelType Sub641(HelDim(3),4,2)
        HelType Sub648(HelDim(3),4,2)
        HelType Sub747(HelDim(3),4,2)
        HelType Sub755(HelDim(3),4,2)
        HelType Sub760(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub681(HelDim(3),4,2)
        HelType Sub711(HelDim(3),4,2)
        HelType Sub723(HelDim(3),4,2)
        HelType Sub726(HelDim(3),4,2)
        HelType Sub23(HelDim(3),4,2)
        HelType Sub25(HelDim(3),4,2)
        HelType Sub684(HelDim(3),4,2)
        HelType Sub685(HelDim(3),4,2)
        HelType Sub714(HelDim(3),4,2)
        HelType Sub721(HelDim(3),4,2)
        HelType Sub767(HelDim(3),4,2)
        HelType Sub817(HelDim(3),3,4,4)
        HelType Sub805(HelDim(3),3,4,4)
        HelType Sub821(HelDim(3),3,4,4)
        HelType Sub233(HelDim(3),3,4,4)
        HelType Sub256(HelDim(3),3,4,4)
        HelType Sub387(HelDim(3),3,4,4)
        HelType Sub417(HelDim(3),3,4,4)
        HelType Sub393(HelDim(3),3,4,4)
        HelType Sub122(HelDim(3),3,4,4)
        HelType Sub173(HelDim(3),3,4,4)
        HelType Sub191(HelDim(3),3,4,4)
        HelType Sub243(HelDim(3),3,4,4)
        HelType Sub260(HelDim(3),3,4,4)
        HelType Sub340(HelDim(3),3,4,4)
        HelType Sub349(HelDim(3),3,4,4)
        HelType Sub378(HelDim(3),3,4,4)
        HelType Sub388(HelDim(3),3,4,4)
        HelType Sub398(HelDim(3),3,4,4)
        HelType Sub123(HelDim(3),3,4,4)
        HelType Sub414(HelDim(3),3,4,4)
        HelType Sub416(HelDim(3),3,4,4)
        HelType Sub418(HelDim(3),3,4,4)
        HelType Sub419(HelDim(3),3,4,4)
        HelType Sub427(HelDim(3),3,4,4)
        HelType Sub436(HelDim(3),3,4,4)
        HelType Sub442(HelDim(3),3,4,4)
        HelType Sub469(HelDim(3),3,4,4)
        HelType Sub449(HelDim(3),3,4,4)
        HelType Sub465(HelDim(3),3,4,4)
        HelType Sub468(HelDim(3),3,4,4)
        HelType Sub470(HelDim(3),3,4,4)
        HelType Sub471(HelDim(3),3,4,4)
        HelType Sub822(HelDim(3),3,4,4)
        HelType Sub509(HelDim(3),3,4,4)
        HelType Sub533(HelDim(3),3,4,4)
        HelType Sub530(HelDim(3),3,4,4)
        HelType Sub534(HelDim(3),3,4,4)
        HelType Sub591(HelDim(3),3,4,4)
        HelType Sub607(HelDim(3),3,4,4)
        HelType Sub604(HelDim(3),3,4,4)
        HelType Sub608(HelDim(3),3,4,4)
        HelType Sub825(HelDim(3),3,4,4)
        HelType Sub163(HelDim(3),3,4,4)
        HelType Sub188(HelDim(3),3,4,4)
        HelType Sub824(HelDim(3),3,4,4)
        HelType Sub826(HelDim(3),3,4,4)
        HelType Sub97(HelDim(3),3,4,4)
        HelType Sub694(HelDim(3),3,4,2)
        HelType Sub697(HelDim(3),3,4,2)
        HelType Sub673(HelDim(3),4,4,2)
        HelType Sub677(HelDim(3),4,4,2)
        HelType Sub799(HelDim(3),3,4,4,2)
        HelType Sub284(HelDim(3),3,4,4,2)
        HelType Sub34(HelDim(3),3,4,4,2)
        HelType Sub808(HelDim(3),3,4,4,2)
        HelType Sub36(HelDim(3),3,4,4,2)
        HelType Sub290(HelDim(3),3,4,4,2)
        HelType Sub302(HelDim(3),3,4,4,2)
        HelType Sub310(HelDim(3),3,4,4,2)
        HelType Sub544(HelDim(3),3,4,4,2)
        HelType Sub549(HelDim(3),3,4,4,2)
        HelType Sub552(HelDim(3),3,4,4,2)
        HelType Sub563(HelDim(3),3,4,4,2)
        HelType Sub566(HelDim(3),3,4,4,2)
        HelType Sub567(HelDim(3),3,4,4,2)
        HelType Sub569(HelDim(3),3,4,4,2)
        HelType Sub788(HelDim(3),3,4,4,2)
        HelType Sub786(HelDim(3),3,4,4,2)
        HelType Sub790(HelDim(3),3,4,4,2)
        HelType Sub679(HelDim(3),3,4,4,2)
        HelType Sub698(HelDim(3),3,4,4,2)
        HelType Sub793(HelDim(3),3,4,4,2)
        HelType Sub28(HelDim(3),3,4,4,2)
        HelType Sub735(HelDim(3),3,4,4,2)
        HelType Sub311(HelDim(3),3,4,4,2)
        HelType Sub293(HelDim(3),3,4,4,2)
        HelType Sub550(HelDim(3),3,4,4,2)
        HelType Sub645(HelDim(3),3,4,4,2)
        HelType Sub666(HelDim(3),3,4,4,2)
        HelType Sub678(HelDim(3),3,4,4,2)
        HelType Sub703(HelDim(3),3,4,4,2)
        HelType Sub708(HelDim(3),3,4,4,2)
        HelType Sub709(HelDim(3),3,4,4,2)
        HelType Sub795(HelDim(3),3,4,4,2)
        HelType Sub733(HelDim(3),3,4,4,2)
        HelType Sub814(HelDim(3),3,4,4,2)
        HelType Sub761(HelDim(3),3,4,4,2)
        HelType Sub775(HelDim(3),3,4,4,2)
        HelType Sub780(HelDim(3),3,4,4,2)
        HelType Sub781(HelDim(3),3,4,4,2)
        HelType Sub801(HelDim(3),3,4,4,2)
        HelType Sub816(HelDim(3),3,4,4,2)
        HelType Sub791(HelDim(3),3,4,4,2)
        HelType Sub796(HelDim(3),3,4,4,2)
        HelType Sub798(HelDim(3),3,4,4,2)
        HelType Sub800(HelDim(3),3,4,4,2)
        HelType Sub736(HelDim(3),3,4,4,2)
        HelType Sub649(HelDim(3),3,4,4,2)
        HelType Sub710(HelDim(3),3,4,4,2)
        HelType Sub762(HelDim(3),3,4,4,2)
        HelType Sub802(HelDim(3),3,4,4,2)
        HelType Sub806(HelDim(3),3,4,4,2)
        HelType Sub807(HelDim(3),3,4,4,2)
        HelType Sub811(HelDim(3),3,4,4,2)
        HelType Sub812(HelDim(3),3,4,4,2)
        HelType Sub815(HelDim(3),3,4,4,2)
        HelType Sub818(HelDim(3),3,4,4,2), Sub77, Sub75
        HelType Sub239, Sub95, Sub247, Sub107, Sub115, Sub116, Sub69
        HelType Sub358, Sub510, Sub501, Sub85, Sub237, Sub101, Sub99
        HelType Sub110, Sub71, Sub68, Sub88, Sub86, Sub360, Sub87
        HelType Sub486, Sub245, Sub514, Sub98, Sub521, Sub109
        HelType Sub100, Sub166, Sub174, Sub112, Sub407, Sub257
        HelType Sub420, Sub458, Sub155, Sub252, Sub266, Sub268
        HelType Sub476, Sub138, Sub488, Sub141, Sub59, Sub62, Sub498
        HelType Sub482, Sub82, Sub228, Sub528, Sub91, Sub43, Sub92
        HelType Sub37, Sub103, Sub104, Sub254, Sub201, Sub329
        HelType Sub599, Sub64, Sub345, Sub70, Sub55, Sub58, Sub291
        HelType Sub582, Sub516, Sub503, Sub217, Sub149, Sub330
        HelType Sub145, Sub342, Sub725, Sub724, Sub272, Sub279
        HelType Sub295, Sub308, Sub364, Sub404, Sub50, Sub421
        HelType Sub359, Sub411, Sub459, Sub230, Sub120, Sub189
        HelType Sub111, Sub167, Sub175, Sub234, Sub241, Sub249
        HelType Sub258, Sub336, Sub347, Sub495, Sub19(HelDim(3))
        HelType Sub29(HelDim(3)), Sub30(HelDim(3))
        HelType Sub452(HelDim(3)), Sub20(HelDim(3))
        HelType Sub460(HelDim(3)), Sub422(HelDim(3))
        HelType Sub583(HelDim(3)), Sub430(HelDim(3))
        HelType Sub450(HelDim(3)), Sub432(HelDim(3))
        HelType Sub401(HelDim(3)), Sub403(HelDim(3))
        HelType Sub367(HelDim(3)), Sub375(HelDim(3))
        HelType Sub373(HelDim(3)), Sub597(HelDim(3))
        HelType Sub616(HelDim(3)), Sub621(HelDim(3))
        HelType Sub656(HelDim(3)), Sub661(HelDim(3))
        HelType Sub390(HelDim(3)), Sub683(HelDim(3))
        HelType Sub682(HelDim(3)), Sub394(HelDim(3))
        HelType Sub379(HelDim(3)), Sub362(HelDim(3))
        HelType Sub497(HelDim(3)), Sub647(HelDim(3))
        HelType Sub646(HelDim(3)), Sub384(HelDim(3))
        HelType Sub572(HelDim(3)), Sub576(HelDim(3))
        HelType Sub391(HelDim(4)), Sub385(HelDim(4))
        HelType Sub171(HelDim(4)), Sub322(HelDim(4))
        HelType Sub319(HelDim(4)), Sub395(HelDim(4))
        HelType Sub380(HelDim(4)), Sub409(HelDim(3),3)
        HelType Sub363(HelDim(3),3), Sub433(HelDim(3),3)
        HelType Sub462(HelDim(3),3), Sub592(HelDim(3),4)
        HelType Sub580(HelDim(3),4), Sub315(HelDim(3),4)
        HelType Sub327(HelDim(3),4), Sub579(HelDim(3),4)
        HelType Sub594(HelDim(3),4)
        HelType Sub464(HelDim(3),3,4)
        HelType Sub368(HelDim(3),3,4)
        HelType Sub412(HelDim(3),3,4)
        HelType Sub426(HelDim(3),3,4)
        HelType Sub440(HelDim(3),3,4)
        HelType Sub447(HelDim(3),3,4)
        HelType Sub193(HelDim(3),4,4)
        HelType Sub124(HelDim(3),4,4)
        HelType Sub262(HelDim(3),4,4)
        HelType Sub532(HelDim(3),4,4)
        HelType Sub606(HelDim(3),4,4)
        HelType Sub642(HelDim(3),4,2)
        HelType Sub722(HelDim(3),4,2)
        HelType Sub352(HelDim(3),3,4,4)
        HelType Sub382(HelDim(3),3,4,4)
        HelType Sub397(HelDim(3),3,4,4)
        HelType Sub535(HelDim(3),3,4,4)
        HelType Sub609(HelDim(3),3,4,4)
        HelType Sub823(HelDim(3),3,4,4)
        HelType Sub797(HelDim(3),3,4,4,2)
        HelType Sub285(HelDim(3),3,4,4,2)
        HelType Sub312(HelDim(3),3,4,4,2)
        HelType Sub680(HelDim(3),3,4,4,2)
        HelType Sub699(HelDim(3),3,4,4,2)
        HelType Sub734(HelDim(3),3,4,4,2)
        HelType Sub819(HelDim(3),3,4,4,2), Sub690
        HelType Sub692, Sub670, Sub674, Sub492, Sub491, Sub229
        HelType Sub51, Sub73, Sub119, Sub523, Sub494, Sub255, Sub159
        HelType Sub177, Sub274, Sub281, Sub297, Sub304, Sub524
        HelType Sub600(HelDim(3)), Sub589(HelDim(3))
        HelType Sub282(HelDim(3)), Sub275(HelDim(3))
        HelType Sub305(HelDim(3)), Sub298(HelDim(3))
        HelType Sub93(HelDim(3)), Sub80(HelDim(3))
        HelType Sub719(HelDim(3)), Sub716(HelDim(3))
        HelType Sub573(HelDim(3)), Sub478(HelDim(3))
        HelType Sub575(HelDim(3)), Sub480(HelDim(3))
        HelType Sub507(HelDim(3)), Sub506(HelDim(3))
        HelType Sub519(HelDim(3)), Sub518(HelDim(3))
        HelType Sub477(HelDim(3)), Sub483(HelDim(3))
        HelType Sub499(HelDim(3)), Sub704(HelDim(3))
        HelType Sub706(HelDim(3)), Sub739(HelDim(4))
        HelType Sub737(HelDim(4)), Sub629(HelDim(4))
        HelType Sub151(HelDim(4)), Sub142(HelDim(4))
        HelType Sub22(HelDim(4)), Sub627(HelDim(4))
        HelType Sub593(HelDim(4)), Sub578(HelDim(4))
        HelType Sub320(HelDim(3),4), Sub323(HelDim(3),4)
        HelType Sub619(HelDim(3),4), Sub623(HelDim(3),4)
        HelType Sub324(HelDim(3),4), Sub318(HelDim(3),4)
        HelType Sub143(HelDim(3),4), Sub152(HelDim(3),4)
        HelType Sub659(HelDim(3),4), Sub663(HelDim(3),4)
        HelType Sub439(HelDim(3),4), Sub446(HelDim(3),4)
        HelType Sub435(HelDim(3),3,4)
        HelType Sub444(HelDim(3),3,4)
        HelType Sub457(HelDim(3),3,4)
        HelType Sub437(HelDim(3),3,4)
        HelType Sub195(HelDim(3),3,4,4)
        HelType Sub264(HelDim(3),3,4,4)
        HelType Sub337(HelDim(3),3,4,4)
        HelType Sub348(HelDim(3),3,4,4)
        HelType Sub353(HelDim(3),3,4,4)
        HelType Sub381(HelDim(3),3,4,4)
        HelType Sub386(HelDim(3),3,4,4)
        HelType Sub392(HelDim(3),3,4,4)
        HelType Sub396(HelDim(3),3,4,4)
        HelType Sub429(HelDim(3),3,4,4)
        HelType Sub467(HelDim(3),3,4,4)
        HelType Sub126(HelDim(3),3,4,4), Sub244, Sub236
        HelType Sub253, Sub185, Sub113, Sub136(HelDim(3))
        HelType Sub134(HelDim(3)), Sub105(HelDim(3))
        HelType Sub118(HelDim(3)), Sub132(HelDim(3))
        HelType Sub139(HelDim(3)), Sub688(HelDim(4))
        HelType Sub687(HelDim(4)), Sub668(HelDim(4))
        HelType Sub667(HelDim(4)), Sub612(HelDim(3),4)
        HelType Sub610(HelDim(3),4), Sub326(HelDim(3),4)
        HelType Sub652(HelDim(3),4), Sub650(HelDim(3),4)
        HelType Sub745(HelDim(3),4), Sub743(HelDim(3),4)
        HelType Sub640(HelDim(3),4), Sub638(HelDim(3),4)
        HelType Sub751(HelDim(3),4), Sub754(HelDim(3),4)
        HelType Sub757(HelDim(3),4), Sub759(HelDim(3),4)
        HelType Sub765(HelDim(3),4), Sub763(HelDim(3),4)
        HelType Sub717(HelDim(3),4), Sub720(HelDim(3),4)
        HelType Sub772(HelDim(3),4), Sub779(HelDim(3),4)
        HelType Sub338(HelDim(3),3,4,4)
        HelType Sub343(HelDim(3),3,4,4)
        HelType Sub339(HelDim(3),3,4,4)
        HelType Sub344(HelDim(3),3,4,4)
        HelType Sub587(HelDim(3),3,4,4)
        HelType Sub603(HelDim(3),3,4,4)
        HelType Sub820(HelDim(3),3,4,4,2), Sub227
        HelType Sub169, Sub102, Sub90, Sub47(HelDim(3))
        HelType Sub114(HelDim(3)), Sub52(HelDim(3))
        HelType Sub527(HelDim(3)), Sub269(HelDim(3),4)
        HelType Sub267(HelDim(3),4), Sub316(HelDim(3),4)
        HelType Sub292(HelDim(3),4)
        HelType Sub590(HelDim(3),3,4)
        HelType Sub598(HelDim(3),3,4)
        HelType Sub489(HelDim(3),4,4)
        HelType Sub485(HelDim(3),4,4)
        HelType Sub370(HelDim(3),3,4,4)
        HelType Sub415(HelDim(3),3,4,4)
        HelType Sub585(HelDim(3),3,4,4)
        HelType Sub377(HelDim(3),3,4,4)
        HelType Sub406(HelDim(3),3,4,4)
        HelType Sub803(HelDim(3),3,4,4,2), Sub72
        HelType Sub45(HelDim(3)), Sub49(HelDim(3))
        HelType Sub74(HelDim(3)), Sub150(HelDim(3),4)
        HelType Sub146(HelDim(3),4), Sub289(HelDim(3),4)
        HelType Sub635(HelDim(3),4), Sub634(HelDim(3),4)
        HelType Sub713(HelDim(3),4), Sub712(HelDim(3),4)
        HelType Sub218(HelDim(3),4,4)
        HelType Sub512(HelDim(3),4,4)
        HelType Sub541(HelDim(3),3,4,4)
        HelType Sub548(HelDim(3),3,4,4)
        HelType Sub564(HelDim(3),3,4,4)
        HelType Sub562(HelDim(3),3,4,4)
        HelType Sub601(HelDim(3),3,4,4)
        HelType Sub705(HelDim(3),3,4,4)
        HelType Sub707(HelDim(3),3,4,4)
        HelType Sub335(HelDim(3),3,4,4)
        HelType Sub346(HelDim(3),3,4,4)
        HelType Sub287(HelDim(3),4)
        HelType Sub207(HelDim(3),4,4)
        HelType Sub210(HelDim(3),4,4)
        HelType Sub60(HelDim(3),4,4)
        HelType Sub511(HelDim(3),4,4)
        HelType Sub205(HelDim(3),4,4)
        HelType Sub215(HelDim(3),4,4)
        HelType Sub277(HelDim(3),3,4,4)
        HelType Sub283(HelDim(3),3,4,4)
        HelType Sub300(HelDim(3),3,4,4)
        HelType Sub309(HelDim(3),3,4,4)
        HelType Sub558(HelDim(3),3,4,4)
        HelType Sub565(HelDim(3),3,4,4)
        HelType Sub732(HelDim(3),3,4,4)
        HelType Sub730(HelDim(3),3,4,4)
        HelType Sub213(HelDim(3),4,4)
        HelType Sub57(HelDim(3),4,4)
        HelType Sub66(HelDim(3),4,4)
        HelType Sub543(HelDim(3),3,4,4)
        HelType Sub546(HelDim(3),3,4,4)
        HelType Sub63(HelDim(3),4,4)
        HelType Sub222(HelDim(3),4,4)
        HelType Sub301(HelDim(3),3,4,4)
        HelType Sub306(HelDim(3),3,4,4)
        HelType Sub508(HelDim(3),3,4,4)
        HelType Sub520(HelDim(3),3,4,4)
        HelType Sub172(HelDim(3),3,4,4)
        HelType Sub529(HelDim(3),3,4,4)
        HelType Sub500(HelDim(3),3,4,4)
        HelType Sub221(HelDim(3),4,4)
        HelType Sub179(HelDim(3),3,4,4)
        HelType Sub190(HelDim(3),3,4,4)
        HelType Sub165(HelDim(3),3,4,4)
        HelType Sub235(HelDim(3),3,4,4)
        HelType Sub242(HelDim(3),3,4,4)
        HelType Sub96(HelDim(3),3,4,4)
        HelType Sub250(HelDim(3),3,4,4)
        HelType Sub259(HelDim(3),3,4,4)
        HelType Sub108(HelDim(3),3,4,4)
        HelType Sub121(HelDim(3),3,4,4)
        HelType Sub84(HelDim(3),3,4,4)
        common /varXh/ F39, F27, F11, F14, F25, F45, F109, F33, F50
        common /varXh/ F93, F54, F34, F154, F46, F41, F155, F1, F161
        common /varXh/ F170, F162, F163, F3, F166, F172, F167, F168
        common /varXh/ F15, F29, F67, F143, F31, F69, F144, F57
        common /varXh/ F183, F94, F145, F194, F146, F66, F18, F36
        common /varXh/ F48, F97, F37, F53, F99, F62, F190, F92, F150
        common /varXh/ F191, F151, F72, F32, F56, F207, F30, F16, F2
        common /varXh/ F86, F49, F236, F242, F237, F133, F231, F135
        common /varXh/ F60, F44, F82, F208, F43, F17, F7, F79, F75
        common /varXh/ F232, F229, F234, F90, F235, F91, F84, F156
        common /varXh/ F12, F211, F213, F176, F177, F178, F179, F180
        common /varXh/ F157, F13, F201, F202, F184, F185, F186, F187
        common /varXh/ F188, F102, F28, F26, F115, F195, F117, F196
        common /varXh/ F119, F118, F120, F121, F122, F123, F173
        common /varXh/ F124, F103, F40, F38, F96, F197, F98, F198
        common /varXh/ F131, F100, F132, F101, F134, F136, F192
        common /varXh/ F137, F59, F35, F212, F55, F158, F199, F204
        common /varXh/ F223, F64, F224, F65, F189, F52, F19, F5, F20
        common /varXh/ F8, F61, F6, F63, F21, F230, F239, F238, F139
        common /varXh/ F47, F42, F214, F74, F105, F200, F206, F227
        common /varXh/ F80, F228, F81, F193, F70, F22, F9, F23, F4
        common /varXh/ F76, F10, F78, F24, F233, F240, F241, F106
        common /varXh/ F169, F159, F160, F171, F164, F165, F140, F68
        common /varXh/ F141, F71, F142, F147, F88, F148, F51, F149
        common /varXh/ F85, F87, F219, F209, F215, F128, F216, F130
        common /varXh/ F58, F152, F153, F125, F126, F77, F73, F220
        common /varXh/ F210, F217, F112, F218, F89, F83, F110, F111
        common /varXh/ F107, F108, F174, F175, F181, F182, F114
        common /varXh/ F113, F116, F127, F95, F129, F203, F221, F222
        common /varXh/ F138, F205, F225, F226, F104, Pair5, Pair1
        common /varXh/ Pair2, Pair11, Pair8, Pair10, Pair9, Pair6
        common /varXh/ Pair7, Pair3, Pair4, Abb25, Abb1, Abb30
        common /varXh/ Abb11, Abb21, Abb6, Abb14, Abb7, Abb16, Abb5
        common /varXh/ Abb24, Abb19, Abb15, Abb10, Abb8, Abb9, Abb17
        common /varXh/ Abb2, Abb34, Abb31, Abb27, Abb20, Abb23
        common /varXh/ Abb28, Abb13, Abb26, Abb4, Abb18, Abb32
        common /varXh/ Abb29, Abb33, Abb12, Abb3, Abb22, Opt1, Opt3
        common /varXh/ Sub515, Sub502, Sub144, Sub181, Sub148
        common /varXh/ Sub156, Sub224, Sub493, Sub154, Sub180
        common /varXh/ Sub522, Sub54, Sub555, Sub271, Sub559, Sub278
        common /varXh/ Sub273, Sub280, Sub216, Sub220, Sub748
        common /varXh/ Sub752, Sub727, Sub776, Sub133, Sub46, Sub372
        common /varXh/ Sub366, Sub184, Sub158, Sub161, Sub472
        common /varXh/ Sub496, Sub212, Sub129, Sub170, Sub127
        common /varXh/ Sub178, Sub56, Sub65, Sub204, Sub474, Sub525
        common /varXh/ Sub187, Sub225, Sub168, Sub176, Sub251, Sub89
        common /varXh/ Sub209, Sub206, Sub288, Sub296, Sub303
        common /varXh/ Sub538, Sub294, Sub547, Sub307, Sub211
        common /varXh/ Sub203, Sub481, Sub731, Sub588, Sub596
        common /varXh/ Sub655, Sub539, Sub660, Sub545, Sub620
        common /varXh/ Sub560, Sub637, Sub639, Sub615, Sub556
        common /varXh/ Sub768, Sub715, Sub718, Sub157, Sub383
        common /varXh/ Sub400, Sub240, Sub374, Sub505, Sub389
        common /varXh/ Sub248, Sub402, Sub517, Sub183, Sub164
        common /varXh/ Sub160, Sub137, Sub331, Sub186, Sub131
        common /varXh/ Sub341, Sub182, Sub487, Sub586, Sub602
        common /varXh/ Sub226, Sub408, Sub399, Sub371, Sub410
        common /varXh/ Sub365, Sub376, Sub405, Sub79, Sub428, Sub466
        common /varXh/ Sub106, Sub117, Sub78, Sub94, Sub196, Sub622
        common /varXh/ Sub617, Sub354, Sub355, Sub662, Sub197
        common /varXh/ Sub657, Sub431, Sub451, Sub238, Sub246
        common /varXh/ Sub369, Sub463, Sub778, Sub770, Sub455
        common /varXh/ Sub434, Sub424, Sub769, Sub777, Sub749
        common /varXh/ Sub758, Sub729, Sub738, Sub740, Sub413
        common /varXh/ Sub584, Sub628, Sub630, Sub454, Sub423
        common /varXh/ Sub453, Sub611, Sub613, Sub651, Sub653
        common /varXh/ Sub443, Sub693, Sub691, Sub696, Sub695
        common /varXh/ Sub744, Sub746, Sub675, Sub671, Sub676
        common /varXh/ Sub672, Sub764, Sub766, Sub192, Sub261
        common /varXh/ Sub351, Sub570, Sub473, Sub313, Sub128
        common /varXh/ Sub314, Sub571, Sub130, Sub202, Sub41, Sub44
        common /varXh/ Sub475, Sub200, Sub531, Sub605, Sub441
        common /varXh/ Sub445, Sub456, Sub438, Sub448, Sub194
        common /varXh/ Sub350, Sub135, Sub140, Sub147, Sub153
        common /varXh/ Sub317, Sub321, Sub325, Sub328, Sub48, Sub53
        common /varXh/ Sub581, Sub595, Sub14, Sub553, Sub686, Sub17
        common /varXh/ Sub265, Sub554, Sub198, Sub199, Sub21, Sub24
        common /varXh/ Sub813, Sub270, Sub568, Sub614, Sub624
        common /varXh/ Sub625, Sub689, Sub741, Sub742, Sub35, Sub357
        common /varXh/ Sub551, Sub632, Sub665, Sub536, Sub33, Sub8
        common /varXh/ Sub626, Sub286, Sub537, Sub31, Sub356, Sub631
        common /varXh/ Sub654, Sub664, Sub669, Sub263, Sub208
        common /varXh/ Sub214, Sub219, Sub223, Sub479, Sub484
        common /varXh/ Sub490, Sub513, Sub574, Sub577, Sub61, Sub67
        common /varXh/ Sub125, Sub26, Sub5, Sub633, Sub643, Sub700
        common /varXh/ Sub701, Sub32, Sub636, Sub641, Sub648, Sub747
        common /varXh/ Sub755, Sub760, Sub16, Sub18, Sub681, Sub711
        common /varXh/ Sub723, Sub726, Sub23, Sub25, Sub684, Sub685
        common /varXh/ Sub714, Sub721, Sub767, Sub817, Sub805
        common /varXh/ Sub821, Sub233, Sub256, Sub387, Sub417
        common /varXh/ Sub393, Sub122, Sub173, Sub191, Sub243
        common /varXh/ Sub260, Sub340, Sub349, Sub378, Sub388
        common /varXh/ Sub398, Sub123, Sub414, Sub416, Sub418
        common /varXh/ Sub419, Sub427, Sub436, Sub442, Sub469
        common /varXh/ Sub449, Sub465, Sub468, Sub470, Sub471
        common /varXh/ Sub822, Sub509, Sub533, Sub530, Sub534
        common /varXh/ Sub591, Sub607, Sub604, Sub608, Sub825
        common /varXh/ Sub163, Sub188, Sub824, Sub826, Sub97, Sub694
        common /varXh/ Sub697, Sub673, Sub677, Sub799, Sub284, Sub34
        common /varXh/ Sub808, Sub36, Sub290, Sub302, Sub310, Sub544
        common /varXh/ Sub549, Sub552, Sub563, Sub566, Sub567
        common /varXh/ Sub569, Sub788, Sub786, Sub790, Sub679
        common /varXh/ Sub698, Sub793, Sub28, Sub735, Sub311, Sub293
        common /varXh/ Sub550, Sub645, Sub666, Sub678, Sub703
        common /varXh/ Sub708, Sub709, Sub795, Sub733, Sub814
        common /varXh/ Sub761, Sub775, Sub780, Sub781, Sub801
        common /varXh/ Sub816, Sub791, Sub796, Sub798, Sub800
        common /varXh/ Sub736, Sub649, Sub710, Sub762, Sub802
        common /varXh/ Sub806, Sub807, Sub811, Sub812, Sub815
        common /varXh/ Sub818, Sub77, Sub75, Sub239, Sub95, Sub247
        common /varXh/ Sub107, Sub115, Sub116, Sub69, Sub358, Sub510
        common /varXh/ Sub501, Sub85, Sub237, Sub101, Sub99, Sub110
        common /varXh/ Sub71, Sub68, Sub88, Sub86, Sub360, Sub87
        common /varXh/ Sub486, Sub245, Sub514, Sub98, Sub521, Sub109
        common /varXh/ Sub100, Sub166, Sub174, Sub112, Sub407
        common /varXh/ Sub257, Sub420, Sub458, Sub155, Sub252
        common /varXh/ Sub266, Sub268, Sub476, Sub138, Sub488
        common /varXh/ Sub141, Sub59, Sub62, Sub498, Sub482, Sub82
        common /varXh/ Sub228, Sub528, Sub91, Sub43, Sub92, Sub37
        common /varXh/ Sub103, Sub104, Sub254, Sub201, Sub329
        common /varXh/ Sub599, Sub64, Sub345, Sub70, Sub55, Sub58
        common /varXh/ Sub291, Sub582, Sub516, Sub503, Sub217
        common /varXh/ Sub149, Sub330, Sub145, Sub342, Sub725
        common /varXh/ Sub724, Sub272, Sub279, Sub295, Sub308
        common /varXh/ Sub364, Sub404, Sub50, Sub421, Sub359, Sub411
        common /varXh/ Sub459, Sub230, Sub120, Sub189, Sub111
        common /varXh/ Sub167, Sub175, Sub234, Sub241, Sub249
        common /varXh/ Sub258, Sub336, Sub347, Sub495, Sub19, Sub29
        common /varXh/ Sub30, Sub452, Sub20, Sub460, Sub422, Sub583
        common /varXh/ Sub430, Sub450, Sub432, Sub401, Sub403
        common /varXh/ Sub367, Sub375, Sub373, Sub597, Sub616
        common /varXh/ Sub621, Sub656, Sub661, Sub390, Sub683
        common /varXh/ Sub682, Sub394, Sub379, Sub362, Sub497
        common /varXh/ Sub647, Sub646, Sub384, Sub572, Sub576
        common /varXh/ Sub391, Sub385, Sub171, Sub322, Sub319
        common /varXh/ Sub395, Sub380, Sub409, Sub363, Sub433
        common /varXh/ Sub462, Sub592, Sub580, Sub315, Sub327
        common /varXh/ Sub579, Sub594, Sub464, Sub368, Sub412
        common /varXh/ Sub426, Sub440, Sub447, Sub193, Sub124
        common /varXh/ Sub262, Sub532, Sub606, Sub642, Sub722
        common /varXh/ Sub352, Sub382, Sub397, Sub535, Sub609
        common /varXh/ Sub823, Sub797, Sub285, Sub312, Sub680
        common /varXh/ Sub699, Sub734, Sub819, Sub690, Sub692
        common /varXh/ Sub670, Sub674, Sub492, Sub491, Sub229, Sub51
        common /varXh/ Sub73, Sub119, Sub523, Sub494, Sub255, Sub159
        common /varXh/ Sub177, Sub274, Sub281, Sub297, Sub304
        common /varXh/ Sub524, Sub600, Sub589, Sub282, Sub275
        common /varXh/ Sub305, Sub298, Sub93, Sub80, Sub719, Sub716
        common /varXh/ Sub573, Sub478, Sub575, Sub480, Sub507
        common /varXh/ Sub506, Sub519, Sub518, Sub477, Sub483
        common /varXh/ Sub499, Sub704, Sub706, Sub739, Sub737
        common /varXh/ Sub629, Sub151, Sub142, Sub22, Sub627, Sub593
        common /varXh/ Sub578, Sub320, Sub323, Sub619, Sub623
        common /varXh/ Sub324, Sub318, Sub143, Sub152, Sub659
        common /varXh/ Sub663, Sub439, Sub446, Sub435, Sub444
        common /varXh/ Sub457, Sub437, Sub195, Sub264, Sub337
        common /varXh/ Sub348, Sub353, Sub381, Sub386, Sub392
        common /varXh/ Sub396, Sub429, Sub467, Sub126, Sub244
        common /varXh/ Sub236, Sub253, Sub185, Sub113, Sub136
        common /varXh/ Sub134, Sub105, Sub118, Sub132, Sub139
        common /varXh/ Sub688, Sub687, Sub668, Sub667, Sub612
        common /varXh/ Sub610, Sub326, Sub652, Sub650, Sub745
        common /varXh/ Sub743, Sub640, Sub638, Sub751, Sub754
        common /varXh/ Sub757, Sub759, Sub765, Sub763, Sub717
        common /varXh/ Sub720, Sub772, Sub779, Sub338, Sub343
        common /varXh/ Sub339, Sub344, Sub587, Sub603, Sub820
        common /varXh/ Sub227, Sub169, Sub102, Sub90, Sub47, Sub114
        common /varXh/ Sub52, Sub527, Sub269, Sub267, Sub316, Sub292
        common /varXh/ Sub590, Sub598, Sub489, Sub485, Sub370
        common /varXh/ Sub415, Sub585, Sub377, Sub406, Sub803, Sub72
        common /varXh/ Sub45, Sub49, Sub74, Sub150, Sub146, Sub289
        common /varXh/ Sub635, Sub634, Sub713, Sub712, Sub218
        common /varXh/ Sub512, Sub541, Sub548, Sub564, Sub562
        common /varXh/ Sub601, Sub705, Sub707, Sub335, Sub346
        common /varXh/ Sub287, Sub207, Sub210, Sub60, Sub511, Sub205
        common /varXh/ Sub215, Sub277, Sub283, Sub300, Sub309
        common /varXh/ Sub558, Sub565, Sub732, Sub730, Sub213, Sub57
        common /varXh/ Sub66, Sub543, Sub546, Sub63, Sub222, Sub301
        common /varXh/ Sub306, Sub508, Sub520, Sub172, Sub529
        common /varXh/ Sub500, Sub221, Sub179, Sub190, Sub165
        common /varXh/ Sub235, Sub242, Sub96, Sub250, Sub259, Sub108
        common /varXh/ Sub121, Sub84

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7
        common /indices/ Sfe7

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /gqu_nInJqug_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
