#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 10-Mar-2017 11:08
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub1(3,4,2), Sub2(4), Sub3(3,4,2)
        ComplexType Sub4(3,4,2), Sub6(3,4,2)
        ComplexType Sub7(3,4,2), Sub9(4)
        ComplexType Sub10(3,4,2), Sub11(3,4,2)
        ComplexType Sub12(3,4,2), Sub13(3,4,2)
        ComplexType Sub15(3,4,2), Sub25(4,4)
        ComplexType Sub28(4,4), Sub43(4), Sub44(4)
        ComplexType Sub45(4), Sub46(4), Sub47(4,4)
        ComplexType Sub48(4), Sub49(4), Sub50(4)
        ComplexType Sub51(4), Sub52(4,4), Sub241(4)
        ComplexType Sub242(4), Sub243(4,4), Sub244(4)
        ComplexType Sub245(4), Sub246(4,4), Sub248(4)
        ComplexType Sub249(4), Sub250(4,4), Sub251(4)
        ComplexType Sub252(4), Sub253(4,4), Sub259(4)
        ComplexType Sub260(4), Sub261(4,4), Sub262(4)
        ComplexType Sub263(4), Sub264(4,4)
        ComplexType Sub303(3,3,4,4), Sub583(3,2)
        ComplexType Sub585(3,2)
        common /gqubar_nInJqubarg_varXs/ Sub1, Sub2, Sub3, Sub4, Sub6, Sub7, Sub9
        common /gqubar_nInJqubarg_varXs/ Sub10, Sub11, Sub12, Sub13, Sub15, Sub25
        common /gqubar_nInJqubarg_varXs/ Sub28, Sub43, Sub44, Sub45, Sub46, Sub47
        common /gqubar_nInJqubarg_varXs/ Sub48, Sub49, Sub50, Sub51, Sub52, Sub241
        common /gqubar_nInJqubarg_varXs/ Sub242, Sub243, Sub244, Sub245, Sub246
        common /gqubar_nInJqubarg_varXs/ Sub248, Sub249, Sub250, Sub251, Sub252
        common /gqubar_nInJqubarg_varXs/ Sub253, Sub259, Sub260, Sub261, Sub262
        common /gqubar_nInJqubarg_varXs/ Sub263, Sub264, Sub303, Sub583, Sub585

        ComplexType Opt3, Opt4, Opt5, Sub31
        ComplexType Sub32(3,3,4,4)
        ComplexType Sub55(3,4,4)
        ComplexType Sub56(3,3,4,4)
        ComplexType Sub69(3,3,4,4)
        ComplexType Sub72(3,3,4,4)
        ComplexType Sub114(3,3,4,4)
        ComplexType Sub140(3,3,4,4)
        ComplexType Sub182(3,3,4,4)
        ComplexType Sub267(3,3,4,4)
        ComplexType Sub276(3,4,4)
        ComplexType Sub283(3,3,4,4)
        ComplexType Sub291(3,4,4)
        ComplexType Sub292(3,3,4,4)
        ComplexType Sub295(3,3,4,4)
        ComplexType Sub304(3,3,4,4)
        ComplexType Sub310(3,3,4,4)
        ComplexType Sub326(3,4,4)
        ComplexType Sub327(3,3,4,4)
        ComplexType Sub345(3,3,4,4)
        ComplexType Sub346(3,3,4,4)
        ComplexType Sub386(3,3,4,4)
        ComplexType Sub436(3,3,4,4)
        ComplexType Sub480(3,3,4,4)
        ComplexType Sub510(3,3,4,4)
        ComplexType Sub557(3,3,4,4)
        ComplexType Sub571(3,3,4,4), Sub584(3,4)
        ComplexType Sub586(3,3,4,4)
        ComplexType Sub590(3,3,4,4), Sub591(3,4)
        ComplexType Sub593(3,3,4,4)
        ComplexType Sub596(3,3,4,4), Sub606(3,4)
        ComplexType Sub608(3,4), Sub611(3,3,4,4)
        ComplexType Sub35(3,3,4,4)
        ComplexType Sub54(3,3,4,4)
        ComplexType Sub58(3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /gqubar_nInJqubarg_varXa/ Opt3, Opt4, Opt5, Sub31, Sub32, Sub55, Sub56
        common /gqubar_nInJqubarg_varXa/ Sub69, Sub72, Sub114, Sub140, Sub182, Sub267
        common /gqubar_nInJqubarg_varXa/ Sub276, Sub283, Sub291, Sub292, Sub295
        common /gqubar_nInJqubarg_varXa/ Sub304, Sub310, Sub326, Sub327, Sub345
        common /gqubar_nInJqubarg_varXa/ Sub346, Sub386, Sub436, Sub480, Sub510
        common /gqubar_nInJqubarg_varXa/ Sub557, Sub571, Sub584, Sub586, Sub590
        common /gqubar_nInJqubarg_varXa/ Sub591, Sub593, Sub596, Sub606, Sub608
        common /gqubar_nInJqubarg_varXa/ Sub611, Sub35, Sub54, Sub58, S, T, T14, T15
        common /gqubar_nInJqubarg_varXa/ U, T24, T25, S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, F107, F108, F109, F110, F111
        HelType F112, F113, F114, F115, F116, F117, F118, F119, F120
        HelType F121, F122, F123, F124, F125, F126, F127, F128, F129
        HelType F130, F131, F132, F133, F134, F135, F136, F137, F138
        HelType F139, F140, F141, F142, F143, F144, F145, F146, F147
        HelType F148, F149, F150, F151, F152, F153, F154, F155, F156
        HelType F157, F158, F159, F160, F161, F162, F163, F164, F165
        HelType F166, F167, F168, F169, F170, F171, F172, F173, F174
        HelType F175, F176, F177, F178, F179, F180, F181, F182, F183
        HelType F184, F185, F186, F187, F188, F189, F190, F191, F192
        HelType F193, F194, F195, F196, F197, F198, F199, F200, F201
        HelType F202, F203, F204, F205, F206, F207, F208, F209, F210
        HelType F211, F212, F213, F214, Opt1, Opt2, Pair1, Pair2
        HelType Pair3, Pair4, Pair5, Pair6, Pair7, Pair8, Pair9
        HelType Pair10, Pair11, Sub8(HelDim(3),4,2)
        HelType Sub14(HelDim(3),4,2)
        HelType Sub18(HelDim(3),3,4,4,2)
        HelType Sub19(HelDim(3),4,2)
        HelType Sub20(HelDim(3),4,2)
        HelType Sub21(HelDim(3),4,2)
        HelType Sub23(HelDim(3),3,4,4,2), Sub24, Sub26
        HelType Sub27, Sub29, Sub30
        HelType Sub33(HelDim(3),3,4,4), Sub34
        HelType Sub36(HelDim(3),3,4,4)
        HelType Sub37(HelDim(3),3,4,4), Sub38
        HelType Sub39(HelDim(3),3,4,4), Sub40
        HelType Sub41(HelDim(3),3,4,4)
        HelType Sub42(HelDim(3),3,4,4)
        HelType Sub53(HelDim(4),4), Sub57
        HelType Sub59(HelDim(3),3,4,4)
        HelType Sub60(HelDim(4),4), Sub61(HelDim(4),4)
        HelType Sub62(HelDim(3),3,4,4)
        HelType Sub63(HelDim(3),3,4,4)
        HelType Sub64(HelDim(3),3,4,4), Sub65, Sub66
        HelType Sub67, Sub68, Sub70(HelDim(3),3,4,4)
        HelType Sub73(HelDim(3),3,4,4)
        HelType Sub76(HelDim(3),3,4,4)
        HelType Sub78(HelDim(3),3,4,4)
        HelType Sub81(HelDim(3),3,4,4)
        HelType Sub82(HelDim(3),3,4,4)
        HelType Sub84(HelDim(4),4), Sub85(HelDim(4),4)
        HelType Sub86(HelDim(4),4), Sub87(HelDim(4),4)
        HelType Sub92(HelDim(4),4), Sub93(HelDim(4),4)
        HelType Sub94, Sub95, Sub96, Sub97(HelDim(4),4), Sub98
        HelType Sub99, Sub100, Sub101(HelDim(4),4), Sub102
        HelType Sub103, Sub104(HelDim(4),4), Sub105, Sub106
        HelType Sub107(HelDim(4),4), Sub108, Sub109, Sub110
        HelType Sub111, Sub112, Sub113, Sub116, Sub117, Sub118
        HelType Sub119, Sub120, Sub121, Sub124, Sub125, Sub126
        HelType Sub127, Sub128, Sub129, Sub131, Sub132, Sub133
        HelType Sub134, Sub135, Sub136, Sub139
        HelType Sub145(HelDim(4),4), Sub146(HelDim(4),4)
        HelType Sub147(HelDim(4),4), Sub151(HelDim(4),4)
        HelType Sub152, Sub153, Sub154, Sub155(HelDim(4),4)
        HelType Sub156, Sub157, Sub158, Sub159(HelDim(4),4)
        HelType Sub160, Sub161, Sub162(HelDim(4),4), Sub163
        HelType Sub164, Sub165(HelDim(4),4), Sub166, Sub167
        HelType Sub170, Sub171, Sub175, Sub176, Sub178, Sub179
        HelType Sub184, Sub191, Sub192, Sub193(HelDim(4),4)
        HelType Sub194, Sub195, Sub196(HelDim(4),4), Sub197
        HelType Sub198(HelDim(4),4), Sub199
        HelType Sub200(HelDim(4),4), Sub201
        HelType Sub202(HelDim(3),3,4,4), Sub204
        HelType Sub205(HelDim(3),3,4,4), Sub208
        HelType Sub209(HelDim(3),3,4,4), Sub211
        HelType Sub212(HelDim(3),3,4,4)
        HelType Sub217(HelDim(4),4)
        HelType Sub221(HelDim(3),4,2)
        HelType Sub222(HelDim(3),4,2)
        HelType Sub231(HelDim(3),4,2)
        HelType Sub232(HelDim(3),4,2)
        HelType Sub247(HelDim(4),4), Sub254(HelDim(4),4)
        HelType Sub255, Sub265(HelDim(4),4), Sub266, Sub270
        HelType Sub275, Sub284(HelDim(3),3,4,4)
        HelType Sub285(HelDim(3),3,4,4)
        HelType Sub286(HelDim(3),4,2)
        HelType Sub287(HelDim(3),4,2)
        HelType Sub289(HelDim(3),3,4,4,2), Sub290
        HelType Sub293(HelDim(3),3,4,4), Sub294
        HelType Sub296(HelDim(3),3,4,4)
        HelType Sub297(HelDim(3),3,4,4,2)
        HelType Sub298(HelDim(3),3,4,4)
        HelType Sub299(HelDim(3),3,4,4)
        HelType Sub300(HelDim(3),3,4,4,2)
        HelType Sub301(HelDim(3),3,4,4,2)
        HelType Sub302(HelDim(3),3,4,4,2), Sub312
        HelType Sub318, Sub321(HelDim(3),3,4,4,2)
        HelType Sub322, Sub323, Sub324(HelDim(3),4,2), Sub325
        HelType Sub328(HelDim(3),3,4,4)
        HelType Sub330(HelDim(3),3,4,4,2), Sub331
        HelType Sub332(HelDim(3),3,4,4)
        HelType Sub333(HelDim(3),3,4,4,2)
        HelType Sub334(HelDim(3),3,4,4,2)
        HelType Sub340(HelDim(3),4,2), Sub341, Sub342
        HelType Sub343(HelDim(3),4,2)
        HelType Sub381(HelDim(3),4,2), Sub395, Sub396, Sub397
        HelType Sub398(HelDim(4),4), Sub399, Sub400, Sub401
        HelType Sub402(HelDim(4),4), Sub403, Sub404
        HelType Sub405(HelDim(4),4), Sub406, Sub407
        HelType Sub408(HelDim(4),4), Sub409, Sub411, Sub414
        HelType Sub416, Sub421(HelDim(4),4)
        HelType Sub422(HelDim(4),4), Sub428, Sub432
        HelType Sub433(HelDim(3),4,2), Sub435, Sub438
        HelType Sub441(HelDim(3),4,2), Sub443, Sub444, Sub445
        HelType Sub446, Sub447(HelDim(4),4), Sub448, Sub449
        HelType Sub452, Sub453, Sub456, Sub457, Sub459, Sub460
        HelType Sub465(HelDim(4)), Sub466(HelDim(4))
        HelType Sub467(HelDim(4),4), Sub468(HelDim(4))
        HelType Sub469(HelDim(4)), Sub470(HelDim(4),4)
        HelType Sub471, Sub475(HelDim(3),4,2), Sub489
        HelType Sub491(HelDim(3),4,2), Sub493
        HelType Sub494(HelDim(3),4,2)
        HelType Sub495(HelDim(3),3,4,4,2), Sub496
        HelType Sub498, Sub503(HelDim(3),4,2)
        HelType Sub505(HelDim(3),3,4,4,2), Sub506
        HelType Sub507, Sub508(HelDim(3),4,2)
        HelType Sub517(HelDim(3),4,2)
        HelType Sub519(HelDim(3),3,4,4,2), Sub520
        HelType Sub522, Sub527, Sub529, Sub530(HelDim(3),4,2)
        HelType Sub531(HelDim(3),3,4,4,2), Sub532
        HelType Sub534, Sub538(HelDim(3),4,2)
        HelType Sub539(HelDim(3),3,4,4,2)
        HelType Sub540(HelDim(3),3,4,4,2)
        HelType Sub541(HelDim(3),4,2)
        HelType Sub542(HelDim(3),4,2)
        HelType Sub543(HelDim(3),4,2)
        HelType Sub544(HelDim(3),3,4,4,2)
        HelType Sub545(HelDim(3),3,4,4,2)
        HelType Sub550(HelDim(3),4,2)
        HelType Sub552(HelDim(3),3,4,4,2), Sub553
        HelType Sub554, Sub555(HelDim(3),4,2)
        HelType Sub565(HelDim(3),4,2), Sub566, Sub567
        HelType Sub568(HelDim(3),4,2)
        HelType Sub578(HelDim(3),3,4,4,2)
        HelType Sub594(HelDim(3),3,4,4,2)
        HelType Sub614(HelDim(3),3,4,4,2)
        HelType Sub615(HelDim(3),3,4,4,2)
        HelType Sub622(HelDim(4),4), Abb1, Abb2, Abb3, Abb4
        HelType Abb5, Abb6, Abb7, Abb8, Abb9, Abb10, Abb11, Abb12
        HelType Abb13, Abb14, Abb15, Abb16, Abb17, Abb18, Abb19
        HelType Abb20, Abb21, Abb22, Abb23, Abb24, Abb25, Abb26
        HelType Abb27, Abb28, Abb29, Abb30, Abb31
        HelType Opt6(HelDim(3),3,4,4)
        HelType Opt7(HelDim(3),3,4,4)
        HelType Opt8(HelDim(3),3,4,4)
        HelType Opt9(HelDim(3),3,4,4)
        HelType Sub5(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub71(HelDim(3),3,4,4)
        HelType Sub74(HelDim(3),3,4,4)
        HelType Sub75(HelDim(3),3,4,4)
        HelType Sub77(HelDim(3),3,4,4)
        HelType Sub79(HelDim(3),3,4,4)
        HelType Sub80(HelDim(3),3,4,4)
        HelType Sub83(HelDim(3),3,4,4)
        HelType Sub88(HelDim(3),3,4,4)
        HelType Sub89(HelDim(3),3,4,4)
        HelType Sub90(HelDim(3),3,4,4)
        HelType Sub91(HelDim(3),3,4,4)
        HelType Sub115(HelDim(3),3,4,4)
        HelType Sub122(HelDim(3),3,4,4)
        HelType Sub123(HelDim(3),3,4,4)
        HelType Sub130(HelDim(3),3,4,4)
        HelType Sub137(HelDim(3),3,4,4)
        HelType Sub138(HelDim(3),3,4,4)
        HelType Sub141(HelDim(3),3,4,4)
        HelType Sub142(HelDim(3),3,4,4)
        HelType Sub143(HelDim(3),3,4,4)
        HelType Sub144(HelDim(3),3,4,4)
        HelType Sub148(HelDim(3),3,4,4)
        HelType Sub149(HelDim(3),3,4,4)
        HelType Sub150(HelDim(3),3,4,4), Sub168
        HelType Sub169(HelDim(3),3,4,4), Sub172
        HelType Sub173(HelDim(3),3,4,4)
        HelType Sub174(HelDim(3),3,4,4)
        HelType Sub177(HelDim(3),3,4,4)
        HelType Sub180(HelDim(3),3,4,4)
        HelType Sub181(HelDim(3),3,4,4)
        HelType Sub183(HelDim(3),3,4,4)
        HelType Sub185(HelDim(3),3,4,4)
        HelType Sub186(HelDim(3),3,4,4)
        HelType Sub187(HelDim(3),3,4,4)
        HelType Sub188(HelDim(3),3,4,4)
        HelType Sub189(HelDim(3),3,4,4)
        HelType Sub190(HelDim(3),3,4,4)
        HelType Sub203(HelDim(3),3,4,4)
        HelType Sub206(HelDim(3),3,4,4)
        HelType Sub207(HelDim(3),3,4,4)
        HelType Sub210(HelDim(3),3,4,4)
        HelType Sub213(HelDim(3),3,4,4)
        HelType Sub214(HelDim(3),3,4,4)
        HelType Sub215(HelDim(3),3,4,4)
        HelType Sub216(HelDim(3),3,4,4)
        HelType Sub218(HelDim(3),3,4,4)
        HelType Sub219(HelDim(3),3,4,4)
        HelType Sub220(HelDim(3),3,4,4), Sub223, Sub224
        HelType Sub225(HelDim(3),4,2), Sub226, Sub227
        HelType Sub228(HelDim(3),4,2)
        HelType Sub229(HelDim(3),3,4,4,2)
        HelType Sub230(HelDim(3),3,4,4,2), Sub233
        HelType Sub234, Sub235(HelDim(3),4,2), Sub236, Sub237
        HelType Sub238(HelDim(3),4,2)
        HelType Sub239(HelDim(3),3,4,4,2)
        HelType Sub240(HelDim(3),3,4,4,2)
        HelType Sub257(HelDim(3),3,4,4)
        HelType Sub258(HelDim(3),3,4,4)
        HelType Sub268(HelDim(3),3,4,4)
        HelType Sub269(HelDim(3),3,4,4)
        HelType Sub271(HelDim(3),3,4,4)
        HelType Sub272(HelDim(3),3,4,4)
        HelType Sub273(HelDim(3),3,4,4)
        HelType Sub274(HelDim(3),3,4,4), Sub277
        HelType Sub278(HelDim(3),3,4,4), Sub279
        HelType Sub280(HelDim(3),3,4,4)
        HelType Sub281(HelDim(3),3,4,4)
        HelType Sub282(HelDim(3),3,4,4), Sub305
        HelType Sub306(HelDim(3),3,4,4)
        HelType Sub307(HelDim(3),3,4,4)
        HelType Sub308(HelDim(3),3,4,4)
        HelType Sub309(HelDim(3),3,4,4), Sub311
        HelType Sub313(HelDim(3),3,4,4)
        HelType Sub314(HelDim(3),3,4,4)
        HelType Sub315(HelDim(3),3,4,4)
        HelType Sub316(HelDim(3),3,4,4), Sub317
        HelType Sub319(HelDim(3),3,4,4)
        HelType Sub320(HelDim(3),3,4,4)
        HelType Sub335(HelDim(3),3,4,4)
        HelType Sub336(HelDim(3),3,4,4), Sub337
        HelType Sub338(HelDim(3),3,4,4)
        HelType Sub339(HelDim(3),3,4,4), Sub344, Sub347
        HelType Sub348(HelDim(3),3,4,4), Sub349
        HelType Sub350(HelDim(3),3,4,4)
        HelType Sub351(HelDim(3),3,4,4,2)
        HelType Sub352(HelDim(3),3,4,4,2), Sub353
        HelType Sub354, Sub355, Sub356, Sub357
        HelType Sub358(HelDim(3),3,4,4)
        HelType Sub359(HelDim(3),3,4,4), Sub360
        HelType Sub361(HelDim(3),3,4,4)
        HelType Sub362(HelDim(3),3,4,4)
        HelType Sub363(HelDim(3),3,4,4), Sub364
        HelType Sub365(HelDim(3),3,4,4)
        HelType Sub366(HelDim(3),3,4,4), Sub367
        HelType Sub368(HelDim(3),3,4,4)
        HelType Sub369(HelDim(3),3,4,4)
        HelType Sub370(HelDim(3),3,4,4)
        HelType Sub371(HelDim(3),3,4,4)
        HelType Sub372(HelDim(4)), Sub373(HelDim(4))
        HelType Sub374(HelDim(4),4), Sub375(HelDim(4))
        HelType Sub376(HelDim(4)), Sub377(HelDim(4),4)
        HelType Sub378(HelDim(3),3,4,4)
        HelType Sub379(HelDim(3),3,4,4)
        HelType Sub380(HelDim(3),3,4,4)
        HelType Sub382(HelDim(3),4,2)
        HelType Sub384(HelDim(3),3,4,4,2), Sub385
        HelType Sub387(HelDim(3),3,4,4), Sub388
        HelType Sub389(HelDim(3),3,4,4)
        HelType Sub390(HelDim(3),3,4,4,2)
        HelType Sub391(HelDim(3),3,4,4)
        HelType Sub392(HelDim(3),3,4,4,2)
        HelType Sub393(HelDim(3),3,4,4,2)
        HelType Sub394(HelDim(3),3,4,4,2)
        HelType Sub410(HelDim(3),3,4,4)
        HelType Sub412(HelDim(3),3,4,4)
        HelType Sub413(HelDim(3),3,4,4)
        HelType Sub415(HelDim(3),3,4,4)
        HelType Sub417(HelDim(3),3,4,4)
        HelType Sub418(HelDim(3),3,4,4)
        HelType Sub419(HelDim(3),3,4,4)
        HelType Sub420(HelDim(3),3,4,4)
        HelType Sub423(HelDim(3),3,4,4)
        HelType Sub424(HelDim(3),3,4,4)
        HelType Sub425(HelDim(3),3,4,4)
        HelType Sub426(HelDim(3),3,4,4)
        HelType Sub427(HelDim(3),3,4,4)
        HelType Sub430(HelDim(3),4,2)
        HelType Sub434(HelDim(3),3,4,4,2)
        HelType Sub437(HelDim(3),3,4,4)
        HelType Sub439(HelDim(3),3,4,4)
        HelType Sub440(HelDim(3),3,4,4,2)
        HelType Sub442(HelDim(3),3,4,4,2)
        HelType Sub450(HelDim(3),3,4,4)
        HelType Sub451(HelDim(3),3,4,4)
        HelType Sub454(HelDim(3),3,4,4)
        HelType Sub455(HelDim(3),3,4,4)
        HelType Sub458(HelDim(3),3,4,4)
        HelType Sub461(HelDim(3),3,4,4)
        HelType Sub462(HelDim(3),3,4,4)
        HelType Sub463(HelDim(3),3,4,4)
        HelType Sub464(HelDim(3),3,4,4)
        HelType Sub472(HelDim(3),3,4,4)
        HelType Sub473(HelDim(3),3,4,4)
        HelType Sub474(HelDim(3),3,4,4), Sub476, Sub477
        HelType Sub478(HelDim(3),4,2), Sub479
        HelType Sub481(HelDim(3),3,4,4)
        HelType Sub482(HelDim(3),3,4,4), Sub483
        HelType Sub484(HelDim(3),3,4,4)
        HelType Sub485(HelDim(3),3,4,4,2)
        HelType Sub486(HelDim(3),3,4,4,2)
        HelType Sub487(HelDim(3),4,2)
        HelType Sub488(HelDim(3),3,4,4,2)
        HelType Sub497(HelDim(3),3,4,4)
        HelType Sub499(HelDim(3),3,4,4)
        HelType Sub500(HelDim(3),3,4,4,2)
        HelType Sub501(HelDim(3),3,4,4,2)
        HelType Sub502(HelDim(3),3,4,4,2), Sub509
        HelType Sub511(HelDim(3),3,4,4), Sub512
        HelType Sub513(HelDim(3),3,4,4)
        HelType Sub514(HelDim(3),3,4,4,2)
        HelType Sub515(HelDim(3),3,4,4,2)
        HelType Sub516(HelDim(3),3,4,4,2)
        HelType Sub521(HelDim(3),3,4,4)
        HelType Sub523(HelDim(3),3,4,4)
        HelType Sub524(HelDim(3),3,4,4,2)
        HelType Sub525(HelDim(3),3,4,4,2)
        HelType Sub526(HelDim(3),3,4,4,2)
        HelType Sub533(HelDim(3),3,4,4)
        HelType Sub535(HelDim(3),3,4,4)
        HelType Sub536(HelDim(3),3,4,4,2)
        HelType Sub537(HelDim(3),3,4,4,2), Sub546
        HelType Sub547, Sub548(HelDim(3),4,2)
        HelType Sub549(HelDim(3),4,2), Sub556
        HelType Sub558(HelDim(3),3,4,4), Sub559, Sub560
        HelType Sub561(HelDim(3),3,4,4)
        HelType Sub562(HelDim(3),3,4,4,2)
        HelType Sub563(HelDim(3),3,4,4,2)
        HelType Sub564(HelDim(3),3,4,4,2), Sub569
        HelType Sub570, Sub572(HelDim(3),3,4,4), Sub573
        HelType Sub574(HelDim(3),3,4,4)
        HelType Sub575(HelDim(3),3,4,4,2)
        HelType Sub576(HelDim(3),3,4,4,2), Sub579
        HelType Sub580, Sub581(HelDim(3),4,2)
        HelType Sub582(HelDim(3),3,4,4,2)
        HelType Sub587(HelDim(3),3,4,4)
        HelType Sub588(HelDim(3),3,4,4,2)
        HelType Sub589(HelDim(3),3,4,4,2)
        HelType Sub592(HelDim(3),3,4,4,2)
        HelType Sub595(HelDim(3),3,4,4,2)
        HelType Sub597(HelDim(3),3,4,4,2)
        HelType Sub598(HelDim(3),3,4,4,2)
        HelType Sub599(HelDim(3),3,4,4,2)
        HelType Sub600(HelDim(3),3,4,4,2)
        HelType Sub601(HelDim(3),3,4,4,2)
        HelType Sub602(HelDim(3),3,4,4)
        HelType Sub603(HelDim(3),3,4,4,2)
        HelType Sub604(HelDim(3),3,4,4,2)
        HelType Sub605(HelDim(3),3,4,4,2)
        HelType Sub607(HelDim(3),3,4,4,2)
        HelType Sub609(HelDim(3),3,4,4,2)
        HelType Sub610(HelDim(3),3,4,4,2)
        HelType Sub612(HelDim(3),3,4,4,2)
        HelType Sub613(HelDim(3),3,4,4,2)
        HelType Sub616(HelDim(3),3,4,4,2)
        HelType Sub617(HelDim(3),3,4,4,2)
        HelType Sub618(HelDim(3),3,4,4,2)
        HelType Sub619(HelDim(3),3,4,4,2)
        HelType Sub620(HelDim(3),3,4,4,2)
        HelType Sub621(HelDim(3),3,4,4)
        HelType Sub623(HelDim(3),3,4,4)
        HelType Sub624(HelDim(3),3,4,4)
        HelType Sub625(HelDim(3),3,4,4)
        HelType Sub626(HelDim(3),3,4,4)
        HelType Sub627(HelDim(3),3,4,4)
        HelType Sub628(HelDim(3),3,4,4)
        HelType Sub629(HelDim(3),3,4,4)
        HelType Sub630(HelDim(3),3,4,4)
        HelType Sub631(HelDim(3),3,4,4)
        HelType Sub632(HelDim(3),3,4,4)
        HelType Sub633(HelDim(3),3,4,4)
        HelType Sub634(HelDim(3),3,4,4)
        HelType Sub635(HelDim(3),3,4,4)
        HelType Sub636(HelDim(3),3,4,4)
        HelType Sub637(HelDim(3),3,4,4)
        HelType Sub638(HelDim(3),3,4,4)
        HelType Sub639(HelDim(3),3,4,4)
        HelType Sub640(HelDim(3),3,4,4)
        HelType Sub641(HelDim(3),3,4,4)
        HelType Sub642(HelDim(3),3,4,4)
        HelType Sub643(HelDim(3),3,4,4)
        HelType Sub644(HelDim(3),3,4,4)
        HelType Sub645(HelDim(3),3,4,4)
        common /gqubar_nInJqubarg_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /gqubar_nInJqubarg_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /gqubar_nInJqubarg_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /gqubar_nInJqubarg_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /gqubar_nInJqubarg_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /gqubar_nInJqubarg_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /gqubar_nInJqubarg_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /gqubar_nInJqubarg_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /gqubar_nInJqubarg_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /gqubar_nInJqubarg_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /gqubar_nInJqubarg_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /gqubar_nInJqubarg_varXh/ F102, F103, F104, F105, F106, F107, F108
        common /gqubar_nInJqubarg_varXh/ F109, F110, F111, F112, F113, F114, F115
        common /gqubar_nInJqubarg_varXh/ F116, F117, F118, F119, F120, F121, F122
        common /gqubar_nInJqubarg_varXh/ F123, F124, F125, F126, F127, F128, F129
        common /gqubar_nInJqubarg_varXh/ F130, F131, F132, F133, F134, F135, F136
        common /gqubar_nInJqubarg_varXh/ F137, F138, F139, F140, F141, F142, F143
        common /gqubar_nInJqubarg_varXh/ F144, F145, F146, F147, F148, F149, F150
        common /gqubar_nInJqubarg_varXh/ F151, F152, F153, F154, F155, F156, F157
        common /gqubar_nInJqubarg_varXh/ F158, F159, F160, F161, F162, F163, F164
        common /gqubar_nInJqubarg_varXh/ F165, F166, F167, F168, F169, F170, F171
        common /gqubar_nInJqubarg_varXh/ F172, F173, F174, F175, F176, F177, F178
        common /gqubar_nInJqubarg_varXh/ F179, F180, F181, F182, F183, F184, F185
        common /gqubar_nInJqubarg_varXh/ F186, F187, F188, F189, F190, F191, F192
        common /gqubar_nInJqubarg_varXh/ F193, F194, F195, F196, F197, F198, F199
        common /gqubar_nInJqubarg_varXh/ F200, F201, F202, F203, F204, F205, F206
        common /gqubar_nInJqubarg_varXh/ F207, F208, F209, F210, F211, F212, F213
        common /gqubar_nInJqubarg_varXh/ F214, Opt1, Opt2, Pair1, Pair2, Pair3, Pair4
        common /gqubar_nInJqubarg_varXh/ Pair5, Pair6, Pair7, Pair8, Pair9, Pair10
        common /gqubar_nInJqubarg_varXh/ Pair11, Sub8, Sub14, Sub18, Sub19, Sub20
        common /gqubar_nInJqubarg_varXh/ Sub21, Sub23, Sub24, Sub26, Sub27, Sub29
        common /gqubar_nInJqubarg_varXh/ Sub30, Sub33, Sub34, Sub36, Sub37, Sub38
        common /gqubar_nInJqubarg_varXh/ Sub39, Sub40, Sub41, Sub42, Sub53, Sub57
        common /gqubar_nInJqubarg_varXh/ Sub59, Sub60, Sub61, Sub62, Sub63, Sub64
        common /gqubar_nInJqubarg_varXh/ Sub65, Sub66, Sub67, Sub68, Sub70, Sub73
        common /gqubar_nInJqubarg_varXh/ Sub76, Sub78, Sub81, Sub82, Sub84, Sub85
        common /gqubar_nInJqubarg_varXh/ Sub86, Sub87, Sub92, Sub93, Sub94, Sub95
        common /gqubar_nInJqubarg_varXh/ Sub96, Sub97, Sub98, Sub99, Sub100, Sub101
        common /gqubar_nInJqubarg_varXh/ Sub102, Sub103, Sub104, Sub105, Sub106
        common /gqubar_nInJqubarg_varXh/ Sub107, Sub108, Sub109, Sub110, Sub111
        common /gqubar_nInJqubarg_varXh/ Sub112, Sub113, Sub116, Sub117, Sub118
        common /gqubar_nInJqubarg_varXh/ Sub119, Sub120, Sub121, Sub124, Sub125
        common /gqubar_nInJqubarg_varXh/ Sub126, Sub127, Sub128, Sub129, Sub131
        common /gqubar_nInJqubarg_varXh/ Sub132, Sub133, Sub134, Sub135, Sub136
        common /gqubar_nInJqubarg_varXh/ Sub139, Sub145, Sub146, Sub147, Sub151
        common /gqubar_nInJqubarg_varXh/ Sub152, Sub153, Sub154, Sub155, Sub156
        common /gqubar_nInJqubarg_varXh/ Sub157, Sub158, Sub159, Sub160, Sub161
        common /gqubar_nInJqubarg_varXh/ Sub162, Sub163, Sub164, Sub165, Sub166
        common /gqubar_nInJqubarg_varXh/ Sub167, Sub170, Sub171, Sub175, Sub176
        common /gqubar_nInJqubarg_varXh/ Sub178, Sub179, Sub184, Sub191, Sub192
        common /gqubar_nInJqubarg_varXh/ Sub193, Sub194, Sub195, Sub196, Sub197
        common /gqubar_nInJqubarg_varXh/ Sub198, Sub199, Sub200, Sub201, Sub202
        common /gqubar_nInJqubarg_varXh/ Sub204, Sub205, Sub208, Sub209, Sub211
        common /gqubar_nInJqubarg_varXh/ Sub212, Sub217, Sub221, Sub222, Sub231
        common /gqubar_nInJqubarg_varXh/ Sub232, Sub247, Sub254, Sub255, Sub265
        common /gqubar_nInJqubarg_varXh/ Sub266, Sub270, Sub275, Sub284, Sub285
        common /gqubar_nInJqubarg_varXh/ Sub286, Sub287, Sub289, Sub290, Sub293
        common /gqubar_nInJqubarg_varXh/ Sub294, Sub296, Sub297, Sub298, Sub299
        common /gqubar_nInJqubarg_varXh/ Sub300, Sub301, Sub302, Sub312, Sub318
        common /gqubar_nInJqubarg_varXh/ Sub321, Sub322, Sub323, Sub324, Sub325
        common /gqubar_nInJqubarg_varXh/ Sub328, Sub330, Sub331, Sub332, Sub333
        common /gqubar_nInJqubarg_varXh/ Sub334, Sub340, Sub341, Sub342, Sub343
        common /gqubar_nInJqubarg_varXh/ Sub381, Sub395, Sub396, Sub397, Sub398
        common /gqubar_nInJqubarg_varXh/ Sub399, Sub400, Sub401, Sub402, Sub403
        common /gqubar_nInJqubarg_varXh/ Sub404, Sub405, Sub406, Sub407, Sub408
        common /gqubar_nInJqubarg_varXh/ Sub409, Sub411, Sub414, Sub416, Sub421
        common /gqubar_nInJqubarg_varXh/ Sub422, Sub428, Sub432, Sub433, Sub435
        common /gqubar_nInJqubarg_varXh/ Sub438, Sub441, Sub443, Sub444, Sub445
        common /gqubar_nInJqubarg_varXh/ Sub446, Sub447, Sub448, Sub449, Sub452
        common /gqubar_nInJqubarg_varXh/ Sub453, Sub456, Sub457, Sub459, Sub460
        common /gqubar_nInJqubarg_varXh/ Sub465, Sub466, Sub467, Sub468, Sub469
        common /gqubar_nInJqubarg_varXh/ Sub470, Sub471, Sub475, Sub489, Sub491
        common /gqubar_nInJqubarg_varXh/ Sub493, Sub494, Sub495, Sub496, Sub498
        common /gqubar_nInJqubarg_varXh/ Sub503, Sub505, Sub506, Sub507, Sub508
        common /gqubar_nInJqubarg_varXh/ Sub517, Sub519, Sub520, Sub522, Sub527
        common /gqubar_nInJqubarg_varXh/ Sub529, Sub530, Sub531, Sub532, Sub534
        common /gqubar_nInJqubarg_varXh/ Sub538, Sub539, Sub540, Sub541, Sub542
        common /gqubar_nInJqubarg_varXh/ Sub543, Sub544, Sub545, Sub550, Sub552
        common /gqubar_nInJqubarg_varXh/ Sub553, Sub554, Sub555, Sub565, Sub566
        common /gqubar_nInJqubarg_varXh/ Sub567, Sub568, Sub578, Sub594, Sub614
        common /gqubar_nInJqubarg_varXh/ Sub615, Sub622, Abb1, Abb2, Abb3, Abb4, Abb5
        common /gqubar_nInJqubarg_varXh/ Abb6, Abb7, Abb8, Abb9, Abb10, Abb11, Abb12
        common /gqubar_nInJqubarg_varXh/ Abb13, Abb14, Abb15, Abb16, Abb17, Abb18
        common /gqubar_nInJqubarg_varXh/ Abb19, Abb20, Abb21, Abb22, Abb23, Abb24
        common /gqubar_nInJqubarg_varXh/ Abb25, Abb26, Abb27, Abb28, Abb29, Abb30
        common /gqubar_nInJqubarg_varXh/ Abb31, Opt6, Opt7, Opt8, Opt9, Sub5, Sub16
        common /gqubar_nInJqubarg_varXh/ Sub71, Sub74, Sub75, Sub77, Sub79, Sub80
        common /gqubar_nInJqubarg_varXh/ Sub83, Sub88, Sub89, Sub90, Sub91, Sub115
        common /gqubar_nInJqubarg_varXh/ Sub122, Sub123, Sub130, Sub137, Sub138
        common /gqubar_nInJqubarg_varXh/ Sub141, Sub142, Sub143, Sub144, Sub148
        common /gqubar_nInJqubarg_varXh/ Sub149, Sub150, Sub168, Sub169, Sub172
        common /gqubar_nInJqubarg_varXh/ Sub173, Sub174, Sub177, Sub180, Sub181
        common /gqubar_nInJqubarg_varXh/ Sub183, Sub185, Sub186, Sub187, Sub188
        common /gqubar_nInJqubarg_varXh/ Sub189, Sub190, Sub203, Sub206, Sub207
        common /gqubar_nInJqubarg_varXh/ Sub210, Sub213, Sub214, Sub215, Sub216
        common /gqubar_nInJqubarg_varXh/ Sub218, Sub219, Sub220, Sub223, Sub224
        common /gqubar_nInJqubarg_varXh/ Sub225, Sub226, Sub227, Sub228, Sub229
        common /gqubar_nInJqubarg_varXh/ Sub230, Sub233, Sub234, Sub235, Sub236
        common /gqubar_nInJqubarg_varXh/ Sub237, Sub238, Sub239, Sub240, Sub257
        common /gqubar_nInJqubarg_varXh/ Sub258, Sub268, Sub269, Sub271, Sub272
        common /gqubar_nInJqubarg_varXh/ Sub273, Sub274, Sub277, Sub278, Sub279
        common /gqubar_nInJqubarg_varXh/ Sub280, Sub281, Sub282, Sub305, Sub306
        common /gqubar_nInJqubarg_varXh/ Sub307, Sub308, Sub309, Sub311, Sub313
        common /gqubar_nInJqubarg_varXh/ Sub314, Sub315, Sub316, Sub317, Sub319
        common /gqubar_nInJqubarg_varXh/ Sub320, Sub335, Sub336, Sub337, Sub338
        common /gqubar_nInJqubarg_varXh/ Sub339, Sub344, Sub347, Sub348, Sub349
        common /gqubar_nInJqubarg_varXh/ Sub350, Sub351, Sub352, Sub353, Sub354
        common /gqubar_nInJqubarg_varXh/ Sub355, Sub356, Sub357, Sub358, Sub359
        common /gqubar_nInJqubarg_varXh/ Sub360, Sub361, Sub362, Sub363, Sub364
        common /gqubar_nInJqubarg_varXh/ Sub365, Sub366, Sub367, Sub368, Sub369
        common /gqubar_nInJqubarg_varXh/ Sub370, Sub371, Sub372, Sub373, Sub374
        common /gqubar_nInJqubarg_varXh/ Sub375, Sub376, Sub377, Sub378, Sub379
        common /gqubar_nInJqubarg_varXh/ Sub380, Sub382, Sub384, Sub385, Sub387
        common /gqubar_nInJqubarg_varXh/ Sub388, Sub389, Sub390, Sub391, Sub392
        common /gqubar_nInJqubarg_varXh/ Sub393, Sub394, Sub410, Sub412, Sub413
        common /gqubar_nInJqubarg_varXh/ Sub415, Sub417, Sub418, Sub419, Sub420
        common /gqubar_nInJqubarg_varXh/ Sub423, Sub424, Sub425, Sub426, Sub427
        common /gqubar_nInJqubarg_varXh/ Sub430, Sub434, Sub437, Sub439, Sub440
        common /gqubar_nInJqubarg_varXh/ Sub442, Sub450, Sub451, Sub454, Sub455
        common /gqubar_nInJqubarg_varXh/ Sub458, Sub461, Sub462, Sub463, Sub464
        common /gqubar_nInJqubarg_varXh/ Sub472, Sub473, Sub474, Sub476, Sub477
        common /gqubar_nInJqubarg_varXh/ Sub478, Sub479, Sub481, Sub482, Sub483
        common /gqubar_nInJqubarg_varXh/ Sub484, Sub485, Sub486, Sub487, Sub488
        common /gqubar_nInJqubarg_varXh/ Sub497, Sub499, Sub500, Sub501, Sub502
        common /gqubar_nInJqubarg_varXh/ Sub509, Sub511, Sub512, Sub513, Sub514
        common /gqubar_nInJqubarg_varXh/ Sub515, Sub516, Sub521, Sub523, Sub524
        common /gqubar_nInJqubarg_varXh/ Sub525, Sub526, Sub533, Sub535, Sub536
        common /gqubar_nInJqubarg_varXh/ Sub537, Sub546, Sub547, Sub548, Sub549
        common /gqubar_nInJqubarg_varXh/ Sub556, Sub558, Sub559, Sub560, Sub561
        common /gqubar_nInJqubarg_varXh/ Sub562, Sub563, Sub564, Sub569, Sub570
        common /gqubar_nInJqubarg_varXh/ Sub572, Sub573, Sub574, Sub575, Sub576
        common /gqubar_nInJqubarg_varXh/ Sub579, Sub580, Sub581, Sub582, Sub587
        common /gqubar_nInJqubarg_varXh/ Sub588, Sub589, Sub592, Sub595, Sub597
        common /gqubar_nInJqubarg_varXh/ Sub598, Sub599, Sub600, Sub601, Sub602
        common /gqubar_nInJqubarg_varXh/ Sub603, Sub604, Sub605, Sub607, Sub609
        common /gqubar_nInJqubarg_varXh/ Sub610, Sub612, Sub613, Sub616, Sub617
        common /gqubar_nInJqubarg_varXh/ Sub618, Sub619, Sub620, Sub621, Sub623
        common /gqubar_nInJqubarg_varXh/ Sub624, Sub625, Sub626, Sub627, Sub628
        common /gqubar_nInJqubarg_varXh/ Sub629, Sub630, Sub631, Sub632, Sub633
        common /gqubar_nInJqubarg_varXh/ Sub634, Sub635, Sub636, Sub637, Sub638
        common /gqubar_nInJqubarg_varXh/ Sub639, Sub640, Sub641, Sub642, Sub643
        common /gqubar_nInJqubarg_varXh/ Sub644, Sub645

        integer Sfe7
        common /gqubar_nInJqubarg_indices/ Sfe7

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /gqubar_nInJqubarg_formfactors/ Ctree, MatSUN

#endif

