#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 19-Dec-2016 16:09
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub15(4), Sub16(3,4,2)
        ComplexType Sub17(3,4,2), Sub19(3,4,2)
        ComplexType Sub20(4), Sub21(3,4,2)
        ComplexType Sub26(3,4,2), Sub27(3,4,2)
        ComplexType Sub327(3,2), Sub328(3,2)
        ComplexType Sub330(3,2), Sub331(3,2)
        ComplexType Sub334(3,2), Sub336(3,2)
        ComplexType Sub338(3,2), Sub339(3,2)
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_varXs/ Sub15, Sub16, Sub17, Sub19, Sub20, Sub21
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_varXs/ Sub26, Sub27, Sub327, Sub328, Sub330, Sub331
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_varXs/ Sub334, Sub336, Sub338, Sub339

        ComplexType Opt1(3,3,3,3), Sub333(3,3,4)
        ComplexType Sub335(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_varXa/ Opt1, Sub333, Sub335, S, T, T14, T15, U, T24
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_varXa/ T25, S34, S35, S45

        HelType F3, F5, F7, F10, F11, F12, F13, F14, F15, F16
        HelType Sub18(HelDim(3),4,2)
        HelType Sub22(HelDim(3),4,2)
        HelType Sub23(HelDim(3),3,2,2)
        HelType Sub24(HelDim(3),3,2,2)
        HelType Sub25(HelDim(3),3)
        HelType Sub28(HelDim(3),4,2)
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_varXh/ F3, F5, F7, F10, F11, F12, F13, F14, F15, F16
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_varXh/ Sub18, Sub22, Sub23, Sub24, Sub25, Sub28

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdbarqd_nInJqdbarqd_3645_Sq1Sq2_formfactors/ Ctree, MatSUN

#endif

