#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 4-Aug-2016 14:48
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub6(4), Sub200(3,2), Sub198(3,2)
        ComplexType Sub1(3,4,2), Sub3(3,4,2)
        ComplexType Sub2(3,4,2), Sub5(3,4,2)
        ComplexType Sub7(3,4,2)
        common /varXs/ Sub6, Sub200, Sub198, Sub1, Sub3, Sub2, Sub5
        common /varXs/ Sub7

        ComplexType Opt1(3,4), Sub199(3,3,3,3,4,4), Sub201(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt1, Sub199, Sub201, S, T, T14, T15, U, T24
        common /varXa/ T25, S34, S35, S45

        HelType F4, F6, F1, F2, F3, F5, F9, F10, F7, F8
        HelType Sub4(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub10(HelDim(3),3,2,2)
        common /varXh/ F4, F6, F1, F2, F3, F5, F9, F10, F7, F8, Sub4
        common /varXh/ Sub8, Sub9, Sub10

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdbarqubar_nInJqubarqdbar_3546_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
