#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 17-Nov-2016 19:28
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub2(4), Sub20(4), Sub7(4)
        ComplexType Sub325(3,2), Sub331(3,2)
        ComplexType Sub29(3,4,2), Sub30(3,4,2)
        ComplexType Sub34(3,4,2), Sub35(3,4,2)
        ComplexType Sub3(3,4,2), Sub4(3,4,2)
        common /varXs/ Sub2, Sub20, Sub7, Sub325, Sub331, Sub29
        common /varXs/ Sub30, Sub34, Sub35, Sub3, Sub4

        ComplexType Sub347(3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Sub347, S, T, T14, T15, U, T24, T25, S34, S35
        common /varXa/ S45

        HelType F18, F29, F20, F27, F28, F26, F3, F5, F21, F19, F30
        HelType F31, F32, F33, F24, F25, F22, F23
        HelType Sub31(HelDim(3),4,2)
        HelType Sub36(HelDim(3),4,2)
        HelType Sub5(HelDim(3),4,2)
        HelType Sub39(HelDim(3),3,2,2)
        HelType Sub32(HelDim(3),3,2,2)
        HelType Sub348(HelDim(3),3,3,4,2,2)
        HelType Sub37(HelDim(3)), Sub38(HelDim(3))
        HelType Sub40(HelDim(3),3,2,2)
        HelType Sub33(HelDim(3),3,2,2)
        common /varXh/ F18, F29, F20, F27, F28, F26, F3, F5, F21, F19
        common /varXh/ F30, F31, F32, F33, F24, F25, F22, F23, Sub31
        common /varXh/ Sub36, Sub5, Sub39, Sub32, Sub348, Sub37
        common /varXh/ Sub38, Sub40, Sub33

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe8
        common /indices/ Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdbarqd_nInJqdqdbar_356_Sq1_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
