#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 22-Jul-2016 9:10
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub71(4), Sub2(4), Sub5(4), Sub76(4)
        ComplexType Sub94(3,3), Sub27(3,3)
        ComplexType Sub183(3,2), Sub182(3,2), Sub12(4,4)
        ComplexType Sub16(4,4), Sub1(3,4,2)
        ComplexType Sub3(3,4,2), Sub75(3,4,2)
        ComplexType Sub77(3,4,2), Sub72(3,4,2)
        ComplexType Sub73(3,4,2), Sub6(3,4,2)
        ComplexType Sub7(3,4,2), Sub44(3,3,4)
        ComplexType Sub45(3,3,4)
        common /varXs/ Sub71, Sub2, Sub5, Sub76, Sub94, Sub27, Sub183
        common /varXs/ Sub182, Sub12, Sub16, Sub1, Sub3, Sub75
        common /varXs/ Sub77, Sub72, Sub73, Sub6, Sub7, Sub44, Sub45

        ComplexType Opt1(3,4), Sub32(3,3,4,4)
        ComplexType Sub179(3,4,4)
        ComplexType Sub186(3,3,4,4)
        ComplexType Sub181(3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt1, Sub32, Sub179, Sub186, Sub181, S, T, T14
        common /varXa/ T15, U, T24, T25, S34, S35, S45

        HelType F3, F5, F59, F63, F1, F6, F7, F4, F17, F8, F65, F11
        HelType F2, F67, F103, F105, F107, F109, F111, F113, F116
        HelType F119, F93, F24, F27, F94, F25, F30, F12, F95, F15
        HelType F33, F9, F96, F10, F97, F29, F34, F98, F32, F35, F16
        HelType F99, F18, F38, F22, F128, F19, F47, F20, F64, F40
        HelType F21, F66, F85, F76, F42, F23, F68, F44, F79, F46
        HelType F14, F41, F26, F60, F43, F28, F61, F86, F81, F45
        HelType F31, F62, F37, F83, F39, F13, F114, F117, F120, F121
        HelType F122, F123, F124, F125, F126, F127, F104, F51, F106
        HelType F108, F52, F110, F54, F112, F115, F53, F118, F100
        HelType F55, F101, F56, F102, F87, F71, F72, F48, F88, F74
        HelType F77, F49, F89, F69, F70, F50, F90, F73, F75, F57
        HelType F91, F78, F80, F58, F92, F82, F84, F36, Pair1, Pair2
        HelType Pair3, Pair8, Pair5, Pair10, Pair6, Pair4, Pair7
        HelType Pair9, Pair11, Abb3, Abb6, Abb9, Abb7, Abb1, Abb4
        HelType Abb5, Abb2, Abb11, Abb8, Abb10, Sub18, Sub21, Sub9
        HelType Sub13, Sub144, Sub148, Sub159, Sub160, Sub169
        HelType Sub170, Sub101(HelDim(3)), Sub145(HelDim(3))
        HelType Sub134(HelDim(3)), Sub130(HelDim(3))
        HelType Sub149(HelDim(3)), Sub41(HelDim(4))
        HelType Sub53(HelDim(4)), Sub163(HelDim(3),4)
        HelType Sub173(HelDim(3),4), Sub81(HelDim(3),4)
        HelType Sub154(HelDim(3),4), Sub156(HelDim(3),4)
        HelType Sub29(HelDim(3),4), Sub62(HelDim(3),4)
        HelType Sub139(HelDim(3),4), Sub141(HelDim(3),4)
        HelType Sub43(HelDim(3),4), Sub55(HelDim(3),4)
        HelType Sub104(HelDim(3),3,4)
        HelType Sub113(HelDim(3),3,4)
        HelType Sub114(HelDim(3),3,4)
        HelType Sub105(HelDim(3),3,4)
        HelType Sub56(HelDim(3),3,4)
        HelType Sub46(HelDim(3),3,4)
        HelType Sub83(HelDim(3),3,4)
        HelType Sub86(HelDim(3),3,4)
        HelType Sub112(HelDim(3),3,4)
        HelType Sub103(HelDim(3),3,4)
        HelType Sub80(HelDim(3),3,4)
        HelType Sub88(HelDim(3),3,4)
        HelType Sub121(HelDim(3),3,4)
        HelType Sub95(HelDim(3),3,4)
        HelType Sub168(HelDim(3),4,2)
        HelType Sub4(HelDim(3),4,2)
        HelType Sub161(HelDim(3),4,2)
        HelType Sub167(HelDim(3),4,2)
        HelType Sub187(HelDim(3),4,2)
        HelType Sub178(HelDim(3),4,2)
        HelType Sub78(HelDim(3),4,2)
        HelType Sub171(HelDim(3),4,2)
        HelType Sub177(HelDim(3),4,2)
        HelType Sub158(HelDim(3),4,2)
        HelType Sub74(HelDim(3),4,2)
        HelType Sub152(HelDim(3),4,2)
        HelType Sub157(HelDim(3),4,2)
        HelType Sub143(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub137(HelDim(3),4,2)
        HelType Sub142(HelDim(3),4,2)
        HelType Sub126(HelDim(3),3,4,4)
        HelType Sub17(HelDim(3),3,4,4)
        HelType Sub24(HelDim(3),3,4,4)
        HelType Sub69(HelDim(3),3,4,4)
        HelType Sub123(HelDim(3),3,4,4)
        HelType Sub97(HelDim(3),3,4,4)
        HelType Sub33(HelDim(3),3,4,4)
        HelType Sub65(HelDim(3),3,4,4)
        HelType Sub34(HelDim(3),3,4,4)
        HelType Sub49(HelDim(3),3,4,4)
        HelType Sub68(HelDim(3),3,4,4)
        HelType Sub180(HelDim(3),3,4,4)
        HelType Sub84(HelDim(3),3,4,4)
        HelType Sub89(HelDim(3),3,4,4)
        HelType Sub127(HelDim(3),3,4,4)
        HelType Sub108(HelDim(3),3,4,4)
        HelType Sub189(HelDim(3),3,4,4,2)
        HelType Sub184(HelDim(3),3,4,4,2)
        HelType Sub185(HelDim(3),3,4,4,2)
        HelType Sub188(HelDim(3),3,4,4,2), Sub52, Sub25
        HelType Sub26, Sub59, Sub60, Sub50, Sub51, Sub39, Sub37
        HelType Sub38, Sub117, Sub90, Sub175, Sub172, Sub162, Sub165
        HelType Sub92, Sub119, Sub129, Sub133, Sub118, Sub91
        HelType Sub93(HelDim(3)), Sub102(HelDim(3))
        HelType Sub109(HelDim(3)), Sub111(HelDim(3))
        HelType Sub120(HelDim(3)), Sub100(HelDim(3))
        HelType Sub110(HelDim(3)), Sub40(HelDim(3))
        HelType Sub66(HelDim(3)), Sub35(HelDim(3))
        HelType Sub164(HelDim(3),4), Sub166(HelDim(3),4)
        HelType Sub174(HelDim(3),4), Sub176(HelDim(3),4)
        HelType Sub61(HelDim(3),4), Sub28(HelDim(3),4)
        HelType Sub54(HelDim(3),4), Sub42(HelDim(3),4)
        HelType Sub135(HelDim(3),4), Sub131(HelDim(3),4)
        HelType Sub106(HelDim(3),3,4)
        HelType Sub115(HelDim(3),3,4)
        HelType Sub15(HelDim(3),3,4)
        HelType Sub85(HelDim(3),3,4)
        HelType Sub20(HelDim(3),3,4)
        HelType Sub82(HelDim(3),3,4)
        HelType Sub11(HelDim(3),3,4)
        HelType Sub79(HelDim(3),3,4)
        HelType Sub122(HelDim(3),3,4)
        HelType Sub87(HelDim(3),3,4)
        HelType Sub23(HelDim(3),3,4)
        HelType Sub96(HelDim(3),3,4)
        HelType Sub124(HelDim(3),3,4,4)
        HelType Sub128(HelDim(3),3,4,4)
        HelType Sub31(HelDim(3),3,4,4)
        HelType Sub36(HelDim(3),3,4,4)
        HelType Sub47(HelDim(3),3,4,4)
        HelType Sub57(HelDim(3),3,4,4)
        HelType Sub64(HelDim(3),3,4,4)
        HelType Sub67(HelDim(3),3,4,4)
        HelType Sub70(HelDim(3),3,4,4)
        HelType Sub98(HelDim(3),3,4,4)
        HelType Sub14(HelDim(3),4), Sub146(HelDim(3),4)
        HelType Sub150(HelDim(3),4), Sub19(HelDim(3),4)
        HelType Sub147(HelDim(3),4), Sub151(HelDim(3),4)
        HelType Sub10(HelDim(3),4), Sub22(HelDim(3),4)
        HelType Sub63(HelDim(3),4), Sub30(HelDim(3),4)
        HelType Sub132(HelDim(3),4), Sub136(HelDim(3),4)
        HelType Sub107(HelDim(3),3,4)
        HelType Sub116(HelDim(3),3,4)
        HelType Sub125(HelDim(3),3,4,4)
        HelType Sub48(HelDim(3),3,4,4)
        HelType Sub58(HelDim(3),3,4,4)
        HelType Sub99(HelDim(3),3,4,4)
        HelType Sub153(HelDim(3),4), Sub155(HelDim(3),4)
        HelType Sub140(HelDim(3),4), Sub138(HelDim(3),4)
        common /varXh/ F3, F5, F59, F63, F1, F6, F7, F4, F17, F8, F65
        common /varXh/ F11, F2, F67, F103, F105, F107, F109, F111
        common /varXh/ F113, F116, F119, F93, F24, F27, F94, F25
        common /varXh/ F30, F12, F95, F15, F33, F9, F96, F10, F97
        common /varXh/ F29, F34, F98, F32, F35, F16, F99, F18, F38
        common /varXh/ F22, F128, F19, F47, F20, F64, F40, F21, F66
        common /varXh/ F85, F76, F42, F23, F68, F44, F79, F46, F14
        common /varXh/ F41, F26, F60, F43, F28, F61, F86, F81, F45
        common /varXh/ F31, F62, F37, F83, F39, F13, F114, F117
        common /varXh/ F120, F121, F122, F123, F124, F125, F126
        common /varXh/ F127, F104, F51, F106, F108, F52, F110, F54
        common /varXh/ F112, F115, F53, F118, F100, F55, F101, F56
        common /varXh/ F102, F87, F71, F72, F48, F88, F74, F77, F49
        common /varXh/ F89, F69, F70, F50, F90, F73, F75, F57, F91
        common /varXh/ F78, F80, F58, F92, F82, F84, F36, Pair1
        common /varXh/ Pair2, Pair3, Pair8, Pair5, Pair10, Pair6
        common /varXh/ Pair4, Pair7, Pair9, Pair11, Abb3, Abb6, Abb9
        common /varXh/ Abb7, Abb1, Abb4, Abb5, Abb2, Abb11, Abb8
        common /varXh/ Abb10, Sub18, Sub21, Sub9, Sub13, Sub144
        common /varXh/ Sub148, Sub159, Sub160, Sub169, Sub170
        common /varXh/ Sub101, Sub145, Sub134, Sub130, Sub149, Sub41
        common /varXh/ Sub53, Sub163, Sub173, Sub81, Sub154, Sub156
        common /varXh/ Sub29, Sub62, Sub139, Sub141, Sub43, Sub55
        common /varXh/ Sub104, Sub113, Sub114, Sub105, Sub56, Sub46
        common /varXh/ Sub83, Sub86, Sub112, Sub103, Sub80, Sub88
        common /varXh/ Sub121, Sub95, Sub168, Sub4, Sub161, Sub167
        common /varXh/ Sub187, Sub178, Sub78, Sub171, Sub177, Sub158
        common /varXh/ Sub74, Sub152, Sub157, Sub143, Sub8, Sub137
        common /varXh/ Sub142, Sub126, Sub17, Sub24, Sub69, Sub123
        common /varXh/ Sub97, Sub33, Sub65, Sub34, Sub49, Sub68
        common /varXh/ Sub180, Sub84, Sub89, Sub127, Sub108, Sub189
        common /varXh/ Sub184, Sub185, Sub188, Sub52, Sub25, Sub26
        common /varXh/ Sub59, Sub60, Sub50, Sub51, Sub39, Sub37
        common /varXh/ Sub38, Sub117, Sub90, Sub175, Sub172, Sub162
        common /varXh/ Sub165, Sub92, Sub119, Sub129, Sub133, Sub118
        common /varXh/ Sub91, Sub93, Sub102, Sub109, Sub111, Sub120
        common /varXh/ Sub100, Sub110, Sub40, Sub66, Sub35, Sub164
        common /varXh/ Sub166, Sub174, Sub176, Sub61, Sub28, Sub54
        common /varXh/ Sub42, Sub135, Sub131, Sub106, Sub115, Sub15
        common /varXh/ Sub85, Sub20, Sub82, Sub11, Sub79, Sub122
        common /varXh/ Sub87, Sub23, Sub96, Sub124, Sub128, Sub31
        common /varXh/ Sub36, Sub47, Sub57, Sub64, Sub67, Sub70
        common /varXh/ Sub98, Sub14, Sub146, Sub150, Sub19, Sub147
        common /varXh/ Sub151, Sub10, Sub22, Sub63, Sub30, Sub132
        common /varXh/ Sub136, Sub107, Sub116, Sub125, Sub48, Sub58
        common /varXh/ Sub99, Sub153, Sub155, Sub140, Sub138

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7
        common /indices/ Sfe7

        HelType Ctree(HelDim(3))
        ComplexType MatSUN(3,3)
        common /qdg_nInJgqd_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
