#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 12-May-2017 12:32
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub1(3,4,2), Sub2(4), Sub3(3,4,2)
        ComplexType Sub4(3,4,2), Sub6(3,4,2)
        ComplexType Sub7(3,4,2), Sub9(4)
        ComplexType Sub10(3,4,2), Sub11(3,4,2)
        ComplexType Sub12(3,4,2), Sub13(3,4,2)
        ComplexType Sub15(3,4,2), Sub17(3,4,2)
        ComplexType Sub18(4), Sub19(3,4,2), Sub23(4)
        ComplexType Sub24(3,4,2), Sub25(3,4,2)
        ComplexType Sub33(3,4,2), Sub34(4)
        ComplexType Sub35(3,4,2), Sub39(4)
        ComplexType Sub40(3,4,2), Sub41(3,4,2)
        ComplexType Sub61(3,4,2), Sub62(3,4,2)
        ComplexType Sub64(3,4,2), Sub65(3,4,2)
        ComplexType Sub67(3,4,2), Sub68(3,4,2)
        ComplexType Sub70(3,4,2), Sub71(3,4,2)
        ComplexType Sub74(4), Sub75(4), Sub76(4)
        ComplexType Sub77(4), Sub78(4,4), Sub79(4)
        ComplexType Sub80(4), Sub81(4), Sub82(4)
        ComplexType Sub83(4,4), Sub87(4), Sub88(4)
        ComplexType Sub89(4,4), Sub91(4), Sub92(4)
        ComplexType Sub93(4,4), Sub98(4), Sub99(4)
        ComplexType Sub100(4,4), Sub101(4), Sub102(4)
        ComplexType Sub103(4,4), Sub105(4,4)
        ComplexType Sub106(4,4), Sub126(4), Sub127(4)
        ComplexType Sub128(4,4), Sub129(4), Sub130(4)
        ComplexType Sub131(4,4), Sub173(3,2)
        ComplexType Sub175(3,2), Sub177(3,2), Sub178(3,2)
        ComplexType Sub184(3,2), Sub204(3,2), Sub205(3,2)
        common /qdqdbar_nInJququbar_varXs/ Sub1, Sub2, Sub3, Sub4, Sub6, Sub7, Sub9
        common /qdqdbar_nInJququbar_varXs/ Sub10, Sub11, Sub12, Sub13, Sub15, Sub17
        common /qdqdbar_nInJququbar_varXs/ Sub18, Sub19, Sub23, Sub24, Sub25, Sub33
        common /qdqdbar_nInJququbar_varXs/ Sub34, Sub35, Sub39, Sub40, Sub41, Sub61
        common /qdqdbar_nInJququbar_varXs/ Sub62, Sub64, Sub65, Sub67, Sub68, Sub70
        common /qdqdbar_nInJququbar_varXs/ Sub71, Sub74, Sub75, Sub76, Sub77, Sub78
        common /qdqdbar_nInJququbar_varXs/ Sub79, Sub80, Sub81, Sub82, Sub83, Sub87
        common /qdqdbar_nInJququbar_varXs/ Sub88, Sub89, Sub91, Sub92, Sub93, Sub98
        common /qdqdbar_nInJququbar_varXs/ Sub99, Sub100, Sub101, Sub102, Sub103, Sub105
        common /qdqdbar_nInJququbar_varXs/ Sub106, Sub126, Sub127, Sub128, Sub129
        common /qdqdbar_nInJququbar_varXs/ Sub130, Sub131, Sub173, Sub175, Sub177
        common /qdqdbar_nInJququbar_varXs/ Sub178, Sub184, Sub204, Sub205

        ComplexType Opt6(3,4), Opt7(3,3,3,4)
        ComplexType Opt8(3), Sub174(3,3,3,3,4,4), Sub180(3,3,3,3,4,4)
        ComplexType Sub183(3,3,4), Sub187(3,3,4)
        ComplexType Sub190(3,3,3,3,4,4)
        ComplexType Sub191(3,3,3)
        ComplexType Sub193(3,3,3,3,4,4)
        ComplexType Sub194(3,4,4)
        ComplexType Sub195(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qdqdbar_nInJququbar_varXa/ Opt6, Opt7, Opt8, Sub174, Sub180, Sub183
        common /qdqdbar_nInJququbar_varXa/ Sub187, Sub190, Sub191, Sub193, Sub194
        common /qdqdbar_nInJququbar_varXa/ Sub195, S, T, T14, T15, U, T24, T25, S34, S35
        common /qdqdbar_nInJququbar_varXa/ S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, F107, F108, F109, F110, F111
        HelType F112, F113, F114, F115, F116, F117, F118, F119, F120
        HelType F121, F122, F123, F124, F125, F126, F127, F128
        HelType Sub5(HelDim(3),4,2), Sub8(HelDim(3),4,2)
        HelType Sub14(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub20(HelDim(3),4,2)
        HelType Sub21(HelDim(3),3,2,2)
        HelType Sub22(HelDim(3),3,2,2)
        HelType Sub26(HelDim(3),4,2)
        HelType Sub27(HelDim(3),3,2,2)
        HelType Sub28(HelDim(3),3,2,2)
        HelType Sub29(HelDim(3),3,2,2)
        HelType Sub30(HelDim(3),3,2,2)
        HelType Sub31(HelDim(3),3,2,2)
        HelType Sub32(HelDim(3),3,2,2)
        HelType Sub36(HelDim(3),4,2)
        HelType Sub37(HelDim(3),3,2,2)
        HelType Sub38(HelDim(3),3,2,2)
        HelType Sub42(HelDim(3),4,2)
        HelType Sub43(HelDim(3),3,2,2)
        HelType Sub44(HelDim(3),3,2,2)
        HelType Sub45(HelDim(3),3,2,2)
        HelType Sub46(HelDim(3),3,2,2)
        HelType Sub47(HelDim(3),3,2,2)
        HelType Sub48(HelDim(3),3,2,2), Sub49, Sub50
        HelType Sub51(HelDim(3),4,2), Sub52, Sub53
        HelType Sub54(HelDim(3),4,2), Sub55, Sub56
        HelType Sub57(HelDim(3),4,2), Sub58, Sub59
        HelType Sub60(HelDim(3),4,2)
        HelType Sub63(HelDim(3),4,2)
        HelType Sub66(HelDim(3),4,2)
        HelType Sub69(HelDim(3),4,2)
        HelType Sub72(HelDim(3),4,2), Sub73
        HelType Sub84(HelDim(4),4), Sub85, Sub90
        HelType Sub94(HelDim(4),4), Sub96
        HelType Sub97(HelDim(4),4), Sub104(HelDim(4),4)
        HelType Sub107, Sub108, Sub109(HelDim(4),4), Sub110
        HelType Sub111, Sub112(HelDim(4),4)
        HelType Sub113(HelDim(4),4), Sub114(HelDim(4),4)
        HelType Sub115(HelDim(4),4), Sub116, Sub117, Sub118
        HelType Sub119, Sub120(HelDim(4),4), Sub121, Sub122
        HelType Sub123, Sub124, Sub125(HelDim(4),4)
        HelType Sub132(HelDim(4),4), Sub133(HelDim(4),4)
        HelType Sub134(HelDim(3),4,4), Sub135
        HelType Sub136(HelDim(4),4), Sub137
        HelType Sub138(HelDim(4),4), Sub139(HelDim(4),4)
        HelType Sub140(HelDim(4),4)
        HelType Sub141(HelDim(3),4,4)
        HelType Sub142(HelDim(4),4), Sub143(HelDim(4),4)
        HelType Sub144, Sub145, Sub146(HelDim(4),4), Sub147
        HelType Sub148, Sub149, Sub150(HelDim(4),4), Sub151
        HelType Sub152(HelDim(4),4)
        HelType Sub153(HelDim(3),4,2), Sub154, Sub155
        HelType Sub156(HelDim(3),4,2)
        HelType Sub157(HelDim(3),4,2)
        HelType Sub158(HelDim(3),4,2), Sub159, Sub160
        HelType Sub161(HelDim(3),4,2)
        HelType Sub162(HelDim(3),4,2)
        HelType Sub163(HelDim(3),4,2), Sub164, Sub165
        HelType Sub166(HelDim(3),4,2)
        HelType Sub167(HelDim(3),4,2), Sub168, Sub169
        HelType Sub170(HelDim(3),4,2)
        HelType Sub171(HelDim(3),4,2)
        HelType Sub172(HelDim(3),4,2)
        HelType Sub185(HelDim(3),3,3,4,2,2)
        HelType Sub186(HelDim(3),3,3,4,2,2)
        HelType Sub188(HelDim(3),3,3,4,2,2)
        HelType Sub189(HelDim(3),3,3,4,2,2)
        HelType Sub192(HelDim(3),3,3,3,4,4)
        HelType Sub196(HelDim(3),3,3,3,4,4)
        HelType Sub197(HelDim(3),3,3,3,4,4)
        HelType Sub198(HelDim(3),3,3,3,4,4)
        HelType Sub199(HelDim(4),4)
        HelType Sub200(HelDim(3),3,3,3,4,4)
        HelType Sub201(HelDim(3),3,3,3,4,4)
        HelType Sub202(HelDim(3),3,3,3,4,4)
        common /qdqdbar_nInJququbar_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /qdqdbar_nInJququbar_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /qdqdbar_nInJququbar_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /qdqdbar_nInJququbar_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /qdqdbar_nInJququbar_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /qdqdbar_nInJququbar_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /qdqdbar_nInJququbar_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /qdqdbar_nInJququbar_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /qdqdbar_nInJququbar_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /qdqdbar_nInJququbar_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /qdqdbar_nInJququbar_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /qdqdbar_nInJququbar_varXh/ F102, F103, F104, F105, F106, F107, F108
        common /qdqdbar_nInJququbar_varXh/ F109, F110, F111, F112, F113, F114, F115
        common /qdqdbar_nInJququbar_varXh/ F116, F117, F118, F119, F120, F121, F122
        common /qdqdbar_nInJququbar_varXh/ F123, F124, F125, F126, F127, F128, Sub5
        common /qdqdbar_nInJququbar_varXh/ Sub8, Sub14, Sub16, Sub20, Sub21, Sub22
        common /qdqdbar_nInJququbar_varXh/ Sub26, Sub27, Sub28, Sub29, Sub30, Sub31
        common /qdqdbar_nInJququbar_varXh/ Sub32, Sub36, Sub37, Sub38, Sub42, Sub43
        common /qdqdbar_nInJququbar_varXh/ Sub44, Sub45, Sub46, Sub47, Sub48, Sub49
        common /qdqdbar_nInJququbar_varXh/ Sub50, Sub51, Sub52, Sub53, Sub54, Sub55
        common /qdqdbar_nInJququbar_varXh/ Sub56, Sub57, Sub58, Sub59, Sub60, Sub63
        common /qdqdbar_nInJququbar_varXh/ Sub66, Sub69, Sub72, Sub73, Sub84, Sub85
        common /qdqdbar_nInJququbar_varXh/ Sub90, Sub94, Sub96, Sub97, Sub104, Sub107
        common /qdqdbar_nInJququbar_varXh/ Sub108, Sub109, Sub110, Sub111, Sub112
        common /qdqdbar_nInJququbar_varXh/ Sub113, Sub114, Sub115, Sub116, Sub117
        common /qdqdbar_nInJququbar_varXh/ Sub118, Sub119, Sub120, Sub121, Sub122
        common /qdqdbar_nInJququbar_varXh/ Sub123, Sub124, Sub125, Sub132, Sub133
        common /qdqdbar_nInJququbar_varXh/ Sub134, Sub135, Sub136, Sub137, Sub138
        common /qdqdbar_nInJququbar_varXh/ Sub139, Sub140, Sub141, Sub142, Sub143
        common /qdqdbar_nInJququbar_varXh/ Sub144, Sub145, Sub146, Sub147, Sub148
        common /qdqdbar_nInJququbar_varXh/ Sub149, Sub150, Sub151, Sub152, Sub153
        common /qdqdbar_nInJququbar_varXh/ Sub154, Sub155, Sub156, Sub157, Sub158
        common /qdqdbar_nInJququbar_varXh/ Sub159, Sub160, Sub161, Sub162, Sub163
        common /qdqdbar_nInJququbar_varXh/ Sub164, Sub165, Sub166, Sub167, Sub168
        common /qdqdbar_nInJququbar_varXh/ Sub169, Sub170, Sub171, Sub172, Sub185
        common /qdqdbar_nInJququbar_varXh/ Sub186, Sub188, Sub189, Sub192, Sub196
        common /qdqdbar_nInJququbar_varXh/ Sub197, Sub198, Sub199, Sub200, Sub201, Sub202

        integer Sfe7, Sfe8
        common /qdqdbar_nInJququbar_indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqdbar_nInJququbar_formfactors/ Ctree, MatSUN

#endif

