#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 23-Oct-2017 10:42
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub1(2,3,2), Sub2(4), Sub3(3,4,2)
        ComplexType Sub4(3,4,2), Sub7(2,3,2)
        ComplexType Sub11(3,4,2), Sub12(3,4,2)
        ComplexType Sub13(3,4,2), Sub15(2,3,2)
        ComplexType Sub17(3,4,2), Sub18(4)
        ComplexType Sub19(3,4,2), Sub24(3,4,2)
        ComplexType Sub25(3,4,2), Sub29(2,3,2)
        ComplexType Sub37(2,4), Sub40(2,4)
        ComplexType Sub47(2,3,2), Sub52(3,3)
        ComplexType Sub57(3,3), Sub80(2,3,2)
        ComplexType Sub88(2,3,2), Sub89(3,4,2)
        ComplexType Sub90(3,4,2), Sub97(2,3,2)
        ComplexType Sub100(3,4,2), Sub101(3,4,2)
        ComplexType Sub107(4), Sub108(2,4), Sub110(4)
        ComplexType Sub111(2,4), Sub132(3,2)
        ComplexType Sub134(3,2), Sub136(3,2), Sub137(3,2)
        ComplexType Sub140(3,2), Sub141(3,2), Sub143(3,2)
        ComplexType Sub144(3,2), Sub146(3,2), Sub148(3,2)
        ComplexType Sub150(3,2), Sub151(3,2), Sub154(3,2)
        ComplexType Sub183(3,2), Sub185(3,2), Sub192(3,2)
        common /qdqdbar_nIxJqdqubar_varXs/ Sub1, Sub2, Sub3, Sub4, Sub7, Sub11, Sub12
        common /qdqdbar_nIxJqdqubar_varXs/ Sub13, Sub15, Sub17, Sub18, Sub19, Sub24
        common /qdqdbar_nIxJqdqubar_varXs/ Sub25, Sub29, Sub37, Sub40, Sub47, Sub52
        common /qdqdbar_nIxJqdqubar_varXs/ Sub57, Sub80, Sub88, Sub89, Sub90, Sub97
        common /qdqdbar_nIxJqdqubar_varXs/ Sub100, Sub101, Sub107, Sub108, Sub110
        common /qdqdbar_nIxJqdqubar_varXs/ Sub111, Sub132, Sub134, Sub136, Sub137
        common /qdqdbar_nIxJqdqubar_varXs/ Sub140, Sub141, Sub143, Sub144, Sub146
        common /qdqdbar_nIxJqdqubar_varXs/ Sub148, Sub150, Sub151, Sub154, Sub183
        common /qdqdbar_nIxJqdqubar_varXs/ Sub185, Sub192

        ComplexType Opt5(3,3,3,3), Opt6(2,3)
        ComplexType Sub53(2,3,4), Sub58(2,3,4)
        ComplexType Sub133(2,3,3,3,3,4)
        ComplexType Sub139(3,3,4)
        ComplexType Sub147(2,3,3,3,3,4)
        ComplexType Sub153(3,3,4)
        ComplexType Sub157(2,3,3,3,3,4)
        ComplexType Sub158(3,3,3)
        ComplexType Sub160(2,3,3,3,3,4)
        ComplexType Sub64(3,3,3,3)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qdqdbar_nIxJqdqubar_varXa/ Opt5, Opt6, Sub53, Sub58, Sub133, Sub139
        common /qdqdbar_nIxJqdqubar_varXa/ Sub147, Sub153, Sub157, Sub158, Sub160, Sub64
        common /qdqdbar_nIxJqdqubar_varXa/ S, T, T14, T15, U, T24, T25, S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, F107, F108, F109, F110, F111
        HelType Sub5(HelDim(3),4,2), Sub6(HelDim(2),3,2)
        HelType Sub8(HelDim(3),3,2,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub10(HelDim(2),3,3,2)
        HelType Sub14(HelDim(3),4,2)
        HelType Sub16(HelDim(2),3,2)
        HelType Sub20(HelDim(3),4,2)
        HelType Sub21(HelDim(3),3,2,2)
        HelType Sub22(HelDim(2),3,2)
        HelType Sub23(HelDim(3),3,2,2)
        HelType Sub26(HelDim(3),4,2)
        HelType Sub27(HelDim(3),3,2,2)
        HelType Sub28(HelDim(3),3,2,2)
        HelType Sub30(HelDim(3),3,2,2)
        HelType Sub31(HelDim(3),3,2,2)
        HelType Sub32(HelDim(2),3,3,2)
        HelType Sub33(HelDim(3),3,2,2)
        HelType Sub34(HelDim(3),3,2,2), Sub35, Sub36, Sub38
        HelType Sub39, Sub41(HelDim(2),4), Sub42, Sub43
        HelType Sub44(HelDim(3),4,2), Sub45, Sub46
        HelType Sub48(HelDim(2),3,3,2), Sub49, Sub50
        HelType Sub51(HelDim(2),3,3,2)
        HelType Sub54(HelDim(2),4), Sub55(HelDim(2),4)
        HelType Sub56(HelDim(2),4), Sub59, Sub60
        HelType Sub61(HelDim(3),4,2), Sub62
        HelType Sub63(HelDim(2),4), Sub71, Sub72
        HelType Sub73(HelDim(2),3,3,2), Sub74, Sub75, Sub76
        HelType Sub77, Sub78(HelDim(2),4)
        HelType Sub79(HelDim(2),4), Sub81(HelDim(2),3,2)
        HelType Sub82(HelDim(3),4,2), Sub83, Sub84
        HelType Sub85(HelDim(3),4,2)
        HelType Sub86(HelDim(3),4,2), Sub87
        HelType Sub91(HelDim(3),4,2), Sub92
        HelType Sub93(HelDim(2)), Sub94(HelDim(2))
        HelType Sub95(HelDim(2),3,3,2)
        HelType Sub96(HelDim(3),3,2,2)
        HelType Sub98(HelDim(3),3,2,2)
        HelType Sub99(HelDim(2),3,2)
        HelType Sub102(HelDim(3),4,2)
        HelType Sub103(HelDim(3),3,2,2)
        HelType Sub104(HelDim(3),3,2,2)
        HelType Sub105(HelDim(3),3,2,2), Sub106, Sub109
        HelType Sub112(HelDim(3)), Sub113(HelDim(2),4)
        HelType Sub114, Sub115, Sub116(HelDim(3),3), Sub120
        HelType Sub121, Sub122(HelDim(3))
        HelType Sub123(HelDim(3),3), Sub124(HelDim(2),4)
        HelType Sub125(HelDim(3)), Sub128(HelDim(3)), Sub129
        HelType Sub130, Sub131(HelDim(3),4,2)
        HelType Sub155(HelDim(3),3,3,4,2,2)
        HelType Sub156(HelDim(3),3,3,4,2,2)
        HelType Sub159(HelDim(2),3,3,3,3,4)
        HelType Sub163(HelDim(2),3,3,3,3,4)
        HelType Sub167(HelDim(2),3,3,4)
        HelType Sub168(HelDim(2),3,3,3,3,4)
        HelType Sub169(HelDim(2),3,3,3,3,4)
        HelType Sub171(HelDim(2),3,3,4)
        HelType Sub180(HelDim(3),3,3,3,4,2)
        HelType Sub181(HelDim(2),3,3,4,2)
        HelType Sub184(HelDim(2),3,3,3,3,2)
        HelType Sub190(HelDim(3),3,3,3,4,2), Sub65
        HelType Sub66, Sub67, Sub68, Sub69(HelDim(2),4)
        HelType Sub70(HelDim(2),4), Sub117, Sub118
        HelType Sub119(HelDim(3),3), Sub126(HelDim(3),3)
        HelType Sub127(HelDim(2),3,3,4)
        HelType Sub161(HelDim(2),3,3,3,3,4)
        HelType Sub162(HelDim(2),3,3,3,3,4)
        HelType Sub164(HelDim(2),3,3,3,3,4)
        HelType Sub165(HelDim(2),3,3,3,3,4)
        HelType Sub166(HelDim(2),3,3,3,3,4)
        HelType Sub170(HelDim(2),3,3,3,3,4)
        HelType Sub172(HelDim(2),3,3,3,3,4)
        HelType Sub173(HelDim(2),3,3,3,3,4)
        HelType Sub174(HelDim(2),3,3,3,3,4)
        HelType Sub175(HelDim(2),3,3,3,3,4)
        HelType Sub176(HelDim(2),3,3,3,3,4)
        HelType Sub177(HelDim(2),3,3,3,3,4)
        HelType Sub178(HelDim(2),3,3,3,3,4)
        HelType Sub179(HelDim(2),3,3,3,3,4)
        common /qdqdbar_nIxJqdqubar_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /qdqdbar_nIxJqdqubar_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /qdqdbar_nIxJqdqubar_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /qdqdbar_nIxJqdqubar_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /qdqdbar_nIxJqdqubar_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /qdqdbar_nIxJqdqubar_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /qdqdbar_nIxJqdqubar_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /qdqdbar_nIxJqdqubar_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /qdqdbar_nIxJqdqubar_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /qdqdbar_nIxJqdqubar_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /qdqdbar_nIxJqdqubar_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /qdqdbar_nIxJqdqubar_varXh/ F102, F103, F104, F105, F106, F107, F108
        common /qdqdbar_nIxJqdqubar_varXh/ F109, F110, F111, Sub5, Sub6, Sub8, Sub9
        common /qdqdbar_nIxJqdqubar_varXh/ Sub10, Sub14, Sub16, Sub20, Sub21, Sub22
        common /qdqdbar_nIxJqdqubar_varXh/ Sub23, Sub26, Sub27, Sub28, Sub30, Sub31
        common /qdqdbar_nIxJqdqubar_varXh/ Sub32, Sub33, Sub34, Sub35, Sub36, Sub38
        common /qdqdbar_nIxJqdqubar_varXh/ Sub39, Sub41, Sub42, Sub43, Sub44, Sub45
        common /qdqdbar_nIxJqdqubar_varXh/ Sub46, Sub48, Sub49, Sub50, Sub51, Sub54
        common /qdqdbar_nIxJqdqubar_varXh/ Sub55, Sub56, Sub59, Sub60, Sub61, Sub62
        common /qdqdbar_nIxJqdqubar_varXh/ Sub63, Sub71, Sub72, Sub73, Sub74, Sub75
        common /qdqdbar_nIxJqdqubar_varXh/ Sub76, Sub77, Sub78, Sub79, Sub81, Sub82
        common /qdqdbar_nIxJqdqubar_varXh/ Sub83, Sub84, Sub85, Sub86, Sub87, Sub91
        common /qdqdbar_nIxJqdqubar_varXh/ Sub92, Sub93, Sub94, Sub95, Sub96, Sub98
        common /qdqdbar_nIxJqdqubar_varXh/ Sub99, Sub102, Sub103, Sub104, Sub105, Sub106
        common /qdqdbar_nIxJqdqubar_varXh/ Sub109, Sub112, Sub113, Sub114, Sub115
        common /qdqdbar_nIxJqdqubar_varXh/ Sub116, Sub120, Sub121, Sub122, Sub123
        common /qdqdbar_nIxJqdqubar_varXh/ Sub124, Sub125, Sub128, Sub129, Sub130
        common /qdqdbar_nIxJqdqubar_varXh/ Sub131, Sub155, Sub156, Sub159, Sub163
        common /qdqdbar_nIxJqdqubar_varXh/ Sub167, Sub168, Sub169, Sub171, Sub180
        common /qdqdbar_nIxJqdqubar_varXh/ Sub181, Sub184, Sub190, Sub65, Sub66, Sub67
        common /qdqdbar_nIxJqdqubar_varXh/ Sub68, Sub69, Sub70, Sub117, Sub118, Sub119
        common /qdqdbar_nIxJqdqubar_varXh/ Sub126, Sub127, Sub161, Sub162, Sub164
        common /qdqdbar_nIxJqdqubar_varXh/ Sub165, Sub166, Sub170, Sub172, Sub173
        common /qdqdbar_nIxJqdqubar_varXh/ Sub174, Sub175, Sub176, Sub177, Sub178, Sub179

        integer Sfe7, Sfe8
        common /qdqdbar_nIxJqdqubar_indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqdbar_nIxJqdqubar_formfactors/ Ctree, MatSUN

#endif

