#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 12-Nov-2016 10:49
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub41(4), Sub28(4), Sub12(4)
        ComplexType Sub36(4), Sub21(4), Sub6(4)
        ComplexType Sub193(3,2), Sub197(3,2), Sub201(3,2)
        ComplexType Sub205(3,2), Sub203(3,2), Sub206(3,2)
        ComplexType Sub195(3,2), Sub198(3,2), Sub216(3,2)
        ComplexType Sub220(3,2), Sub48(4,4)
        ComplexType Sub49(4,4), Sub29(3,4,2)
        ComplexType Sub30(3,4,2), Sub22(3,4,2)
        ComplexType Sub24(3,4,2), Sub42(3,4,2)
        ComplexType Sub43(3,4,2), Sub173(3,4,2)
        ComplexType Sub174(3,4,2), Sub37(3,4,2)
        ComplexType Sub38(3,4,2), Sub166(3,4,2)
        ComplexType Sub167(3,4,2), Sub1(3,4,2)
        ComplexType Sub3(3,4,2), Sub2(3,4,2)
        ComplexType Sub26(3,4,2), Sub33(3,4,2)
        ComplexType Sub32(3,4,2), Sub15(3,4,2)
        ComplexType Sub17(3,4,2), Sub16(3,4,2)
        ComplexType Sub11(3,4,2), Sub13(3,4,2)
        ComplexType Sub182(3,4,2), Sub183(3,4,2)
        ComplexType Sub45(3,4,2), Sub46(3,4,2)
        ComplexType Sub5(3,4,2), Sub7(3,4,2)
        common /varXs/ Sub41, Sub28, Sub12, Sub36, Sub21, Sub6
        common /varXs/ Sub193, Sub197, Sub201, Sub205, Sub203
        common /varXs/ Sub206, Sub195, Sub198, Sub216, Sub220, Sub48
        common /varXs/ Sub49, Sub29, Sub30, Sub22, Sub24, Sub42
        common /varXs/ Sub43, Sub173, Sub174, Sub37, Sub38, Sub166
        common /varXs/ Sub167, Sub1, Sub3, Sub2, Sub26, Sub33, Sub32
        common /varXs/ Sub15, Sub17, Sub16, Sub11, Sub13, Sub182
        common /varXs/ Sub183, Sub45, Sub46, Sub5, Sub7

        ComplexType Opt5(3,3,3,3), Opt6(3,4,4)
        ComplexType Sub213(3,3,3), Sub192(3,3,4)
        ComplexType Sub200(3,3,4), Sub210(3,4,4)
        ComplexType Sub194(3,3,3,3,4,4)
        ComplexType Sub202(3,3,3,3,4,4)
        ComplexType Sub208(3,3,3,3,4,4)
        ComplexType Sub212(3,3,3,3,4,4)
        ComplexType Sub209(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt5, Opt6, Sub213, Sub192, Sub200, Sub210
        common /varXa/ Sub194, Sub202, Sub208, Sub212, Sub209, S, T
        common /varXa/ T14, T15, U, T24, T25, S34, S35, S45

        HelType F32, F51, F85, F122, F30, F19, F39, F87, F123, F23
        HelType F26, F7, F24, F82, F46, F71, F21, F5, F34, F83, F57
        HelType F72, F60, F25, F18, F59, F20, F31, F130, F114, F2
        HelType F12, F133, F121, F3, F13, F90, F92, F52, F22, F61
        HelType F14, F4, F27, F29, F58, F15, F6, F77, F125, F45, F68
        HelType F126, F56, F134, F129, F102, F106, F117, F84, F48
        HelType F75, F49, F50, F66, F76, F53, F91, F120, F89, F41
        HelType F78, F36, F43, F67, F79, F40, F93, F105, F86, F42
        HelType F11, F73, F38, F37, F16, F74, F28, F10, F107, F88
        HelType F54, F8, F80, F33, F55, F17, F81, F35, F9, F110
        HelType F112, F137, F138, F140, F113, F141, F115, F116, F118
        HelType F142, F143, F144, F119, F145, F124, F95, F65, F97
        HelType F135, F69, F136, F63, F98, F139, F99, F44, F100, F62
        HelType F101, F128, F70, F131, F64, F103, F132, F104, F47
        HelType F108, F127, F109, F94, F111, F96
        HelType Opt4(HelDim(3),3,4), Sub98, Sub106, Sub66
        HelType Sub68, Sub71, Sub73, Sub93, Sub92, Sub95, Sub99
        HelType Sub102, Sub96, Sub40(HelDim(3),3)
        HelType Sub35(HelDim(3),3), Sub23(HelDim(3),3)
        HelType Sub27(HelDim(3),3), Sub50(HelDim(4),4)
        HelType Sub78(HelDim(4),4), Sub51(HelDim(4),4)
        HelType Sub64(HelDim(4),4), Sub65(HelDim(4),4)
        HelType Sub79(HelDim(4),4), Sub94(HelDim(4),4)
        HelType Sub97(HelDim(4),4), Sub62(HelDim(4),4)
        HelType Sub76(HelDim(4),4), Sub90(HelDim(4),4)
        HelType Sub109(HelDim(4),4)
        HelType Sub70(HelDim(3),4,4)
        HelType Sub75(HelDim(3),4,4)
        HelType Sub121(HelDim(3),4,2)
        HelType Sub31(HelDim(3),4,2)
        HelType Sub25(HelDim(3),4,2)
        HelType Sub111(HelDim(3),4,2)
        HelType Sub104(HelDim(3),4,4)
        HelType Sub108(HelDim(3),4,4)
        HelType Sub44(HelDim(3),4,2)
        HelType Sub146(HelDim(3),4,2)
        HelType Sub175(HelDim(3),4,2)
        HelType Sub39(HelDim(3),4,2)
        HelType Sub151(HelDim(3),4,2)
        HelType Sub168(HelDim(3),4,2)
        HelType Sub56(HelDim(3),4,4)
        HelType Sub61(HelDim(3),4,4)
        HelType Sub4(HelDim(3),4,2)
        HelType Sub139(HelDim(3),4,2)
        HelType Sub144(HelDim(3),4,2)
        HelType Sub34(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub85(HelDim(3),4,4)
        HelType Sub89(HelDim(3),4,4)
        HelType Sub14(HelDim(3),4,2)
        HelType Sub161(HelDim(3),4,2)
        HelType Sub164(HelDim(3),4,2)
        HelType Sub165(HelDim(3),4,2)
        HelType Sub184(HelDim(3),4,2)
        HelType Sub160(HelDim(3),4,2)
        HelType Sub156(HelDim(3),4,2)
        HelType Sub47(HelDim(3),4,2)
        HelType Sub159(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub19(HelDim(3),3,2,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub171(HelDim(3),3,2,2)
        HelType Sub178(HelDim(3),3,2,2)
        HelType Sub135(HelDim(3),4,4,2)
        HelType Sub180(HelDim(3),3,2,2)
        HelType Sub185(HelDim(3),3,2,2)
        HelType Sub190(HelDim(3),3,2,2)
        HelType Sub188(HelDim(3),3,2,2)
        HelType Sub150(HelDim(3),3,3,4,2)
        HelType Sub149(HelDim(3),3,3,4,2)
        HelType Sub155(HelDim(3),3,3,4,2)
        HelType Sub154(HelDim(3),3,3,4,2)
        HelType Sub124(HelDim(3),3,3,4,2)
        HelType Sub128(HelDim(3),3,3,4,2)
        HelType Sub138(HelDim(3),3,4,4,2)
        HelType Sub218(HelDim(3),3,4,4,2)
        HelType Sub141(HelDim(3),3,4,4,2)
        HelType Sub145(HelDim(3),3,4,4,2)
        HelType Sub132(HelDim(3),3,4,4,2)
        HelType Sub137(HelDim(3),3,4,4,2)
        HelType Sub215(HelDim(3),3,3,3,4,4)
        HelType Sub211(HelDim(3),3,3,3,4,4)
        HelType Sub214(HelDim(3),3,3,3,4,4), Sub52
        HelType Sub59, Sub57, Sub80, Sub86, Sub55(HelDim(3))
        HelType Sub58(HelDim(3)), Sub53(HelDim(3))
        HelType Sub60(HelDim(3)), Sub187(HelDim(3))
        HelType Sub177(HelDim(3)), Sub170(HelDim(3))
        HelType Sub176(HelDim(3)), Sub169(HelDim(3))
        HelType Sub163(HelDim(4)), Sub162(HelDim(4))
        HelType Sub142(HelDim(4)), Sub143(HelDim(4))
        HelType Sub157(HelDim(4)), Sub158(HelDim(4))
        HelType Sub136(HelDim(4)), Sub133(HelDim(4))
        HelType Sub100(HelDim(4),4)
        HelType Sub67(HelDim(3),4,4)
        HelType Sub74(HelDim(3),4,4)
        HelType Sub72(HelDim(3),4,4)
        HelType Sub77(HelDim(3),4,4)
        HelType Sub110(HelDim(3),4,4)
        HelType Sub82(HelDim(3),4,4)
        HelType Sub87(HelDim(3),4,4)
        HelType Sub20(HelDim(3),3,2,2)
        HelType Sub10(HelDim(3),3,2,2)
        HelType Sub63(HelDim(3),3,4,4)
        HelType Sub172(HelDim(3),3,2,2)
        HelType Sub179(HelDim(3),3,2,2)
        HelType Sub181(HelDim(3),3,2,2)
        HelType Sub186(HelDim(3),3,2,2)
        HelType Sub91(HelDim(3),3,4,4)
        HelType Sub191(HelDim(3),3,2,2)
        HelType Sub189(HelDim(3),3,2,2), Sub54, Sub83
        HelType Sub69(HelDim(3),4,4)
        HelType Sub101(HelDim(3),4,4)
        HelType Sub84(HelDim(3),4,4), Sub112(HelDim(3))
        HelType Sub125(HelDim(3)), Sub134(HelDim(4))
        HelType Sub81(HelDim(4),4)
        HelType Sub103(HelDim(3),4,4)
        HelType Sub126(HelDim(3),3,3,4)
        HelType Sub113(HelDim(3),3,3,4)
        HelType Sub116(HelDim(3),3,3,4)
        HelType Sub117(HelDim(3),3,3,4)
        HelType Sub148(HelDim(3),3,3)
        HelType Sub147(HelDim(3),3,3)
        HelType Sub152(HelDim(3),3,3)
        HelType Sub153(HelDim(3),3,3)
        HelType Sub105(HelDim(3),4,4)
        HelType Sub107(HelDim(3),4,4)
        HelType Sub114(HelDim(3),3,3,4)
        HelType Sub88(HelDim(3),4,4)
        HelType Sub127(HelDim(3),3,3,4)
        HelType Sub122(HelDim(3),3,3,4)
        HelType Sub123(HelDim(3),3,3,4)
        common /varXh/ F32, F51, F85, F122, F30, F19, F39, F87, F123
        common /varXh/ F23, F26, F7, F24, F82, F46, F71, F21, F5
        common /varXh/ F34, F83, F57, F72, F60, F25, F18, F59, F20
        common /varXh/ F31, F130, F114, F2, F12, F133, F121, F3, F13
        common /varXh/ F90, F92, F52, F22, F61, F14, F4, F27, F29
        common /varXh/ F58, F15, F6, F77, F125, F45, F68, F126, F56
        common /varXh/ F134, F129, F102, F106, F117, F84, F48, F75
        common /varXh/ F49, F50, F66, F76, F53, F91, F120, F89, F41
        common /varXh/ F78, F36, F43, F67, F79, F40, F93, F105, F86
        common /varXh/ F42, F11, F73, F38, F37, F16, F74, F28, F10
        common /varXh/ F107, F88, F54, F8, F80, F33, F55, F17, F81
        common /varXh/ F35, F9, F110, F112, F137, F138, F140, F113
        common /varXh/ F141, F115, F116, F118, F142, F143, F144
        common /varXh/ F119, F145, F124, F95, F65, F97, F135, F69
        common /varXh/ F136, F63, F98, F139, F99, F44, F100, F62
        common /varXh/ F101, F128, F70, F131, F64, F103, F132, F104
        common /varXh/ F47, F108, F127, F109, F94, F111, F96, Opt4
        common /varXh/ Sub98, Sub106, Sub66, Sub68, Sub71, Sub73
        common /varXh/ Sub93, Sub92, Sub95, Sub99, Sub102, Sub96
        common /varXh/ Sub40, Sub35, Sub23, Sub27, Sub50, Sub78
        common /varXh/ Sub51, Sub64, Sub65, Sub79, Sub94, Sub97
        common /varXh/ Sub62, Sub76, Sub90, Sub109, Sub70, Sub75
        common /varXh/ Sub121, Sub31, Sub25, Sub111, Sub104, Sub108
        common /varXh/ Sub44, Sub146, Sub175, Sub39, Sub151, Sub168
        common /varXh/ Sub56, Sub61, Sub4, Sub139, Sub144, Sub34
        common /varXh/ Sub18, Sub85, Sub89, Sub14, Sub161, Sub164
        common /varXh/ Sub165, Sub184, Sub160, Sub156, Sub47, Sub159
        common /varXh/ Sub8, Sub19, Sub9, Sub171, Sub178, Sub135
        common /varXh/ Sub180, Sub185, Sub190, Sub188, Sub150
        common /varXh/ Sub149, Sub155, Sub154, Sub124, Sub128
        common /varXh/ Sub138, Sub218, Sub141, Sub145, Sub132
        common /varXh/ Sub137, Sub215, Sub211, Sub214, Sub52, Sub59
        common /varXh/ Sub57, Sub80, Sub86, Sub55, Sub58, Sub53
        common /varXh/ Sub60, Sub187, Sub177, Sub170, Sub176, Sub169
        common /varXh/ Sub163, Sub162, Sub142, Sub143, Sub157
        common /varXh/ Sub158, Sub136, Sub133, Sub100, Sub67, Sub74
        common /varXh/ Sub72, Sub77, Sub110, Sub82, Sub87, Sub20
        common /varXh/ Sub10, Sub63, Sub172, Sub179, Sub181, Sub186
        common /varXh/ Sub91, Sub191, Sub189, Sub54, Sub83, Sub69
        common /varXh/ Sub101, Sub84, Sub112, Sub125, Sub134, Sub81
        common /varXh/ Sub103, Sub126, Sub113, Sub116, Sub117
        common /varXh/ Sub148, Sub147, Sub152, Sub153, Sub105
        common /varXh/ Sub107, Sub114, Sub88, Sub127, Sub122, Sub123

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7, Sfe8
        common /indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqdbar_nInJqubarqdbar_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
