#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 29-Jul-2016 8:53
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub20(4), Sub12(4), Sub30(4)
        ComplexType Sub33(4), Sub1(4), Sub25(4)
        ComplexType Sub208(3,2), Sub220(3,2), Sub211(3,2)
        ComplexType Sub226(3,2), Sub221(3,2), Sub37(4,4)
        ComplexType Sub38(4,4), Sub13(3,4,2)
        ComplexType Sub14(3,4,2), Sub2(3,4,2)
        ComplexType Sub8(3,4,2), Sub29(3,4,2)
        ComplexType Sub31(3,4,2), Sub174(3,4,2)
        ComplexType Sub175(3,4,2), Sub24(3,4,2)
        ComplexType Sub26(3,4,2), Sub168(3,4,2)
        ComplexType Sub169(3,4,2), Sub4(3,4,2)
        ComplexType Sub6(3,4,2), Sub5(3,4,2)
        ComplexType Sub10(3,4,2), Sub17(3,4,2)
        ComplexType Sub16(3,4,2), Sub21(3,4,2)
        ComplexType Sub22(3,4,2), Sub185(3,4,2)
        ComplexType Sub186(3,4,2), Sub34(3,4,2)
        ComplexType Sub35(3,4,2), Sub158(3,4,2)
        ComplexType Sub159(3,4,2)
        common /varXs/ Sub20, Sub12, Sub30, Sub33, Sub1, Sub25
        common /varXs/ Sub208, Sub220, Sub211, Sub226, Sub221, Sub37
        common /varXs/ Sub38, Sub13, Sub14, Sub2, Sub8, Sub29, Sub31
        common /varXs/ Sub174, Sub175, Sub24, Sub26, Sub168, Sub169
        common /varXs/ Sub4, Sub6, Sub5, Sub10, Sub17, Sub16, Sub21
        common /varXs/ Sub22, Sub185, Sub186, Sub34, Sub35, Sub158
        common /varXs/ Sub159

        ComplexType Opt1(3,3,3,3), Opt2(3,4,4)
        ComplexType Sub200(3,3,3), Sub212(3,3,4)
        ComplexType Sub209(3,3,4), Sub205(3,4,4)
        ComplexType Sub213(3,3,3,3,4,4)
        ComplexType Sub210(3,3,3,3,4,4)
        ComplexType Sub203(3,3,3,3,4,4)
        ComplexType Sub201(3,3,3,3,4,4)
        ComplexType Sub204(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt1, Opt2, Sub200, Sub212, Sub209, Sub205
        common /varXa/ Sub213, Sub210, Sub203, Sub201, Sub204, S, T
        common /varXa/ T14, T15, U, T24, T25, S34, S35, S45

        HelType F12, F39, F84, F136, F25, F3, F22, F75, F135, F6
        HelType F119, F120, F4, F10, F47, F21, F1, F46, F123, F90
        HelType F67, F109, F121, F89, F72, F110, F77, F81, F33, F7
        HelType F48, F13, F2, F15, F17, F45, F5, F11, F32, F57, F138
        HelType F38, F65, F137, F94, F96, F18, F86, F66, F9, F68
        HelType F36, F8, F83, F63, F14, F70, F37, F125, F78, F43
        HelType F59, F42, F34, F64, F60, F44, F73, F126, F82, F30
        HelType F61, F27, F24, F52, F53, F29, F80, F111, F128, F112
        HelType F113, F114, F130, F115, F132, F116, F117, F118, F134
        HelType F95, F50, F127, F97, F54, F49, F98, F99, F129, F35
        HelType F100, F51, F131, F101, F58, F62, F102, F103, F133
        HelType F31, F108, F93, F124, F105, F106, F122, F85, F55
        HelType F76, F56, F26, F92, F20, F104, F28, F79, F16, F87
        HelType F69, F88, F71, F40, F91, F19, F107, F41, F74, F23
        HelType Sub89, Sub100, Sub73, Sub58, Sub78, Sub76, Sub83
        HelType Sub93, Sub84, Sub91, Sub99, Sub87, Sub97, Sub86
        HelType Sub71, Sub59(HelDim(3)), Sub90(HelDim(3))
        HelType Sub64(HelDim(3)), Sub96(HelDim(3))
        HelType Sub19(HelDim(3),3), Sub28(HelDim(3),3)
        HelType Sub11(HelDim(3),3), Sub3(HelDim(3),3)
        HelType Sub55(HelDim(3),3), Sub39(HelDim(4),4)
        HelType Sub69(HelDim(4),4), Sub70(HelDim(4),4)
        HelType Sub53(HelDim(4),4), Sub54(HelDim(4),4)
        HelType Sub40(HelDim(4),4), Sub85(HelDim(4),4)
        HelType Sub88(HelDim(4),4), Sub51(HelDim(4),4)
        HelType Sub67(HelDim(4),4), Sub81(HelDim(4),4)
        HelType Sub103(HelDim(4),4)
        HelType Sub75(HelDim(3),4,4)
        HelType Sub80(HelDim(3),4,4)
        HelType Sub15(HelDim(3),4,2)
        HelType Sub130(HelDim(3),4,2)
        HelType Sub9(HelDim(3),4,2)
        HelType Sub105(HelDim(3),4,2)
        HelType Sub146(HelDim(3),4,2)
        HelType Sub32(HelDim(3),4,2)
        HelType Sub176(HelDim(3),4,2)
        HelType Sub27(HelDim(3),4,2)
        HelType Sub141(HelDim(3),4,2)
        HelType Sub170(HelDim(3),4,2)
        HelType Sub45(HelDim(3),4,4)
        HelType Sub50(HelDim(3),4,4)
        HelType Sub7(HelDim(3),4,2)
        HelType Sub123(HelDim(3),4,2)
        HelType Sub128(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub23(HelDim(3),4,2)
        HelType Sub151(HelDim(3),4,2)
        HelType Sub187(HelDim(3),4,2)
        HelType Sub167(HelDim(3),4,2)
        HelType Sub36(HelDim(3),4,2)
        HelType Sub163(HelDim(3),4,2)
        HelType Sub166(HelDim(3),4,2)
        HelType Sub160(HelDim(3),4,2)
        HelType Sub188(HelDim(3),3,2,2)
        HelType Sub161(HelDim(3),3,2,2)
        HelType Sub172(HelDim(3),3,2,2)
        HelType Sub179(HelDim(3),3,2,2)
        HelType Sub119(HelDim(3),4,4,2)
        HelType Sub183(HelDim(3),3,2,2)
        HelType Sub192(HelDim(3),3,2,2)
        HelType Sub95(HelDim(3),3,4,4)
        HelType Sub102(HelDim(3),3,4,4)
        HelType Sub157(HelDim(3),3,4,2)
        HelType Sub156(HelDim(3),3,4,2)
        HelType Sub194(HelDim(3),3,2,2)
        HelType Sub198(HelDim(3),3,2,2)
        HelType Sub150(HelDim(3),3,3,4,2)
        HelType Sub149(HelDim(3),3,3,4,2)
        HelType Sub145(HelDim(3),3,3,4,2)
        HelType Sub144(HelDim(3),3,3,4,2)
        HelType Sub136(HelDim(3),3,3,4,2)
        HelType Sub138(HelDim(3),3,3,4,2)
        HelType Sub122(HelDim(3),3,4,4,2)
        HelType Sub225(HelDim(3),3,4,4,2)
        HelType Sub116(HelDim(3),3,4,4,2)
        HelType Sub132(HelDim(3),3,4,4,2)
        HelType Sub121(HelDim(3),3,4,4,2)
        HelType Sub125(HelDim(3),3,4,4,2)
        HelType Sub129(HelDim(3),3,4,4,2)
        HelType Sub61(HelDim(3),3,3,4,4)
        HelType Sub66(HelDim(3),3,3,4,4)
        HelType Sub207(HelDim(3),3,3,3,4,4)
        HelType Sub202(HelDim(3),3,3,3,4,4)
        HelType Sub206(HelDim(3),3,3,3,4,4), Sub41
        HelType Sub43, Sub44(HelDim(3)), Sub42(HelDim(3))
        HelType Sub196(HelDim(3)), Sub197(HelDim(3))
        HelType Sub47(HelDim(3)), Sub49(HelDim(3))
        HelType Sub182(HelDim(3)), Sub191(HelDim(3))
        HelType Sub190(HelDim(3)), Sub181(HelDim(3))
        HelType Sub171(HelDim(3)), Sub177(HelDim(3))
        HelType Sub178(HelDim(3)), Sub126(HelDim(4))
        HelType Sub127(HelDim(4)), Sub117(HelDim(4))
        HelType Sub120(HelDim(4)), Sub74(HelDim(3),4,4)
        HelType Sub77(HelDim(3),4,4)
        HelType Sub72(HelDim(3),4,4)
        HelType Sub82(HelDim(3),4,4)
        HelType Sub57(HelDim(3),3,3)
        HelType Sub63(HelDim(3),3,3)
        HelType Sub162(HelDim(3),3,2,2)
        HelType Sub189(HelDim(3),3,2,2)
        HelType Sub52(HelDim(3),3,4,4)
        HelType Sub173(HelDim(3),3,2,2)
        HelType Sub180(HelDim(3),3,2,2)
        HelType Sub184(HelDim(3),3,2,2)
        HelType Sub193(HelDim(3),3,2,2)
        HelType Sub195(HelDim(3),3,2,2)
        HelType Sub199(HelDim(3),3,2,2)
        HelType Sub68(HelDim(3),3,3,4,4)
        HelType Sub104(HelDim(3),3,3,4,4), Sub48
        HelType Sub46, Sub164(HelDim(4)), Sub165(HelDim(4))
        HelType Sub154(HelDim(3),3), Sub62(HelDim(3),3)
        HelType Sub152(HelDim(3),3), Sub92(HelDim(3),3)
        HelType Sub98(HelDim(3),3)
        HelType Sub153(HelDim(3),3,4)
        HelType Sub155(HelDim(3),3,4), Sub133(HelDim(3))
        HelType Sub106(HelDim(3)), Sub118(HelDim(4))
        HelType Sub56(HelDim(3),3)
        HelType Sub142(HelDim(3),3,3)
        HelType Sub147(HelDim(3),3,3)
        HelType Sub60(HelDim(3),3,3)
        HelType Sub137(HelDim(3),3,3,4)
        HelType Sub134(HelDim(3),3,3,4)
        HelType Sub111(HelDim(3),3,3,4)
        HelType Sub107(HelDim(3),3,3,4)
        HelType Sub94(HelDim(3),3)
        HelType Sub143(HelDim(3),3,3)
        HelType Sub148(HelDim(3),3,3)
        HelType Sub79(HelDim(3),4,4)
        HelType Sub65(HelDim(3),3,3)
        HelType Sub101(HelDim(3),3)
        HelType Sub108(HelDim(3),3,3,4)
        HelType Sub110(HelDim(3),3,3,4)
        HelType Sub135(HelDim(3),3,3,4)
        common /varXh/ F12, F39, F84, F136, F25, F3, F22, F75, F135
        common /varXh/ F6, F119, F120, F4, F10, F47, F21, F1, F46
        common /varXh/ F123, F90, F67, F109, F121, F89, F72, F110
        common /varXh/ F77, F81, F33, F7, F48, F13, F2, F15, F17
        common /varXh/ F45, F5, F11, F32, F57, F138, F38, F65, F137
        common /varXh/ F94, F96, F18, F86, F66, F9, F68, F36, F8
        common /varXh/ F83, F63, F14, F70, F37, F125, F78, F43, F59
        common /varXh/ F42, F34, F64, F60, F44, F73, F126, F82, F30
        common /varXh/ F61, F27, F24, F52, F53, F29, F80, F111, F128
        common /varXh/ F112, F113, F114, F130, F115, F132, F116
        common /varXh/ F117, F118, F134, F95, F50, F127, F97, F54
        common /varXh/ F49, F98, F99, F129, F35, F100, F51, F131
        common /varXh/ F101, F58, F62, F102, F103, F133, F31, F108
        common /varXh/ F93, F124, F105, F106, F122, F85, F55, F76
        common /varXh/ F56, F26, F92, F20, F104, F28, F79, F16, F87
        common /varXh/ F69, F88, F71, F40, F91, F19, F107, F41, F74
        common /varXh/ F23, Sub89, Sub100, Sub73, Sub58, Sub78
        common /varXh/ Sub76, Sub83, Sub93, Sub84, Sub91, Sub99
        common /varXh/ Sub87, Sub97, Sub86, Sub71, Sub59, Sub90
        common /varXh/ Sub64, Sub96, Sub19, Sub28, Sub11, Sub3
        common /varXh/ Sub55, Sub39, Sub69, Sub70, Sub53, Sub54
        common /varXh/ Sub40, Sub85, Sub88, Sub51, Sub67, Sub81
        common /varXh/ Sub103, Sub75, Sub80, Sub15, Sub130, Sub9
        common /varXh/ Sub105, Sub146, Sub32, Sub176, Sub27, Sub141
        common /varXh/ Sub170, Sub45, Sub50, Sub7, Sub123, Sub128
        common /varXh/ Sub18, Sub23, Sub151, Sub187, Sub167, Sub36
        common /varXh/ Sub163, Sub166, Sub160, Sub188, Sub161
        common /varXh/ Sub172, Sub179, Sub119, Sub183, Sub192, Sub95
        common /varXh/ Sub102, Sub157, Sub156, Sub194, Sub198
        common /varXh/ Sub150, Sub149, Sub145, Sub144, Sub136
        common /varXh/ Sub138, Sub122, Sub225, Sub116, Sub132
        common /varXh/ Sub121, Sub125, Sub129, Sub61, Sub66, Sub207
        common /varXh/ Sub202, Sub206, Sub41, Sub43, Sub44, Sub42
        common /varXh/ Sub196, Sub197, Sub47, Sub49, Sub182, Sub191
        common /varXh/ Sub190, Sub181, Sub171, Sub177, Sub178
        common /varXh/ Sub126, Sub127, Sub117, Sub120, Sub74, Sub77
        common /varXh/ Sub72, Sub82, Sub57, Sub63, Sub162, Sub189
        common /varXh/ Sub52, Sub173, Sub180, Sub184, Sub193, Sub195
        common /varXh/ Sub199, Sub68, Sub104, Sub48, Sub46, Sub164
        common /varXh/ Sub165, Sub154, Sub62, Sub152, Sub92, Sub98
        common /varXh/ Sub153, Sub155, Sub133, Sub106, Sub118, Sub56
        common /varXh/ Sub142, Sub147, Sub60, Sub137, Sub134, Sub111
        common /varXh/ Sub107, Sub94, Sub143, Sub148, Sub79, Sub65
        common /varXh/ Sub101, Sub108, Sub110, Sub135

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7, Sfe8
        common /indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqd_nInJqubarqd_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
