#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 29-Jul-2016 8:46
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub3(4), Sub10(4), Sub359(3,2)
        ComplexType Sub353(3,2), Sub403(3,2), Sub351(3,2)
        ComplexType Sub395(3,2), Sub357(3,2), Sub50(4,4)
        ComplexType Sub52(4,4), Sub25(3,4,2)
        ComplexType Sub26(3,4,2), Sub34(3,4,2)
        ComplexType Sub36(3,4,2), Sub29(3,4,2)
        ComplexType Sub31(3,4,2), Sub30(3,4,2)
        ComplexType Sub317(3,4,2), Sub319(3,4,2)
        ComplexType Sub318(3,4,2), Sub19(3,4,2)
        ComplexType Sub22(3,4,2), Sub21(3,4,2)
        ComplexType Sub323(3,4,2), Sub325(3,4,2)
        ComplexType Sub324(3,4,2), Sub4(3,4,2)
        ComplexType Sub5(3,4,2), Sub274(3,4,2)
        ComplexType Sub275(3,4,2), Sub11(3,4,2)
        ComplexType Sub17(3,4,2), Sub294(3,4,2)
        ComplexType Sub295(3,4,2), Sub13(3,4,2)
        ComplexType Sub15(3,4,2), Sub14(3,4,2)
        ComplexType Sub331(3,4,2), Sub333(3,4,2)
        ComplexType Sub332(3,4,2), Sub1(3,4,2)
        ComplexType Sub8(3,4,2), Sub7(3,4,2)
        ComplexType Sub309(3,4,2), Sub311(3,4,2)
        ComplexType Sub310(3,4,2)
        common /varXs/ Sub3, Sub10, Sub359, Sub353, Sub403, Sub351
        common /varXs/ Sub395, Sub357, Sub50, Sub52, Sub25, Sub26
        common /varXs/ Sub34, Sub36, Sub29, Sub31, Sub30, Sub317
        common /varXs/ Sub319, Sub318, Sub19, Sub22, Sub21, Sub323
        common /varXs/ Sub325, Sub324, Sub4, Sub5, Sub274, Sub275
        common /varXs/ Sub11, Sub17, Sub294, Sub295, Sub13, Sub15
        common /varXs/ Sub14, Sub331, Sub333, Sub332, Sub1, Sub8
        common /varXs/ Sub7, Sub309, Sub311, Sub310

        ComplexType Opt1(3,3,3,3)
        ComplexType Opt2(3,3,4,4), Opt3(3)
        ComplexType Opt4(3,3,3,3)
        ComplexType Sub355(3,3,3), Sub398(3,3,4)
        ComplexType Sub394(3,3,4), Sub360(3,4,4)
        ComplexType Sub356(3,3,3,3,4,4)
        ComplexType Sub361(3,3,3,3,4,4)
        ComplexType Sub364(3,3,3,3,4,4)
        ComplexType Sub349(3,3,3,3,4,4)
        ComplexType Sub350(3,3,3,3,4,4)
        ComplexType Sub404(3,3,3,3,4,4)
        ComplexType Sub407(3,3,3,3,4,4)
        ComplexType Sub354(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt1, Opt2, Opt3, Opt4, Sub355, Sub398, Sub394
        common /varXa/ Sub360, Sub356, Sub361, Sub364, Sub349
        common /varXa/ Sub350, Sub404, Sub407, Sub354, S, T, T14
        common /varXa/ T15, U, T24, T25, S34, S35, S45

        HelType F3, F25, F11, F5, F43, F7, F26, F13, F9, F56, F27, F4
        HelType F45, F28, F8, F55, F35, F98, F29, F32, F95, F44, F66
        HelType F67, F140, F1, F68, F70, F142, F10, F151, F153, F152
        HelType F154, F33, F37, F82, F54, F24, F46, F40, F83, F30
        HelType F21, F78, F148, F12, F23, F6, F53, F79, F146, F14
        HelType F22, F2, F47, F59, F81, F155, F63, F80, F156, F103
        HelType F104, F16, F101, F38, F64, F69, F39, F100, F65, F71
        HelType F15, F20, F102, F41, F89, F86, F31, F97, F90, F60
        HelType F18, F57, F136, F117, F58, F118, F119, F137, F138
        HelType F145, F121, F61, F132, F122, F62, F123, F124, F133
        HelType F135, F147, F125, F73, F42, F127, F105, F75, F48
        HelType F106, F96, F139, F128, F129, F107, F91, F76, F50
        HelType F130, F108, F77, F52, F111, F99, F141, F131, F134
        HelType F112, F92, F17, F49, F143, F51, F87, F158, F93, F116
        HelType F88, F144, F94, F19, F34, F149, F36, F72, F157, F84
        HelType F115, F74, F150, F85, F113, F126, F114, F109, F120
        HelType F110, Sub64, Sub136, Sub49, Sub51, Sub119, Sub135
        HelType Sub86, Sub132, Sub118, Sub111, Sub164, Sub143
        HelType Sub124, Sub129, Sub121, Sub54, Sub108, Sub161
        HelType Sub122, Sub183, Sub128, Sub106, Sub159, Sub113
        HelType Sub166, Sub133(HelDim(3)), Sub125(HelDim(3))
        HelType Sub12(HelDim(3),3), Sub2(HelDim(3),3)
        HelType Sub20(HelDim(3),3), Sub28(HelDim(3),3)
        HelType Sub33(HelDim(3),3), Sub35(HelDim(3),3)
        HelType Sub24(HelDim(3),3), Sub38(HelDim(3),3)
        HelType Sub177(HelDim(3),3), Sub184(HelDim(3),3)
        HelType Sub203(HelDim(3),4), Sub202(HelDim(3),4)
        HelType Sub191(HelDim(3),4), Sub190(HelDim(3),4)
        HelType Sub116(HelDim(4),4), Sub139(HelDim(4),4)
        HelType Sub155(HelDim(4),4), Sub169(HelDim(4),4)
        HelType Sub187(HelDim(4),4), Sub104(HelDim(4),4)
        HelType Sub70(HelDim(4),4), Sub171(HelDim(4),4)
        HelType Sub157(HelDim(4),4), Sub84(HelDim(4),4)
        HelType Sub141(HelDim(4),4), Sub71(HelDim(4),4)
        HelType Sub85(HelDim(4),4), Sub142(HelDim(4),4)
        HelType Sub172(HelDim(4),4), Sub105(HelDim(4),4)
        HelType Sub158(HelDim(4),4), Sub120(HelDim(4),4)
        HelType Sub123(HelDim(4),4), Sub53(HelDim(4),4)
        HelType Sub56(HelDim(4),4), Sub68(HelDim(4),4)
        HelType Sub76(HelDim(4),4), Sub97(HelDim(4),4)
        HelType Sub110(HelDim(3),4,4)
        HelType Sub115(HelDim(3),4,4)
        HelType Sub163(HelDim(3),4,4)
        HelType Sub168(HelDim(3),4,4)
        HelType Sub27(HelDim(3),4,2)
        HelType Sub241(HelDim(3),4,2)
        HelType Sub213(HelDim(3),4,2)
        HelType Sub37(HelDim(3),4,2)
        HelType Sub260(HelDim(3),4,2)
        HelType Sub265(HelDim(3),4,2)
        HelType Sub206(HelDim(3),4,2)
        HelType Sub199(HelDim(3),4,2)
        HelType Sub32(HelDim(3),4,2)
        HelType Sub211(HelDim(3),4,2)
        HelType Sub320(HelDim(3),4,2)
        HelType Sub23(HelDim(3),4,2)
        HelType Sub225(HelDim(3),4,2)
        HelType Sub228(HelDim(3),4,2)
        HelType Sub229(HelDim(3),4,2)
        HelType Sub326(HelDim(3),4,2)
        HelType Sub6(HelDim(3),4,2)
        HelType Sub44(HelDim(3),4,2)
        HelType Sub230(HelDim(3),4,2)
        HelType Sub276(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub255(HelDim(3),4,2)
        HelType Sub39(HelDim(3),4,2)
        HelType Sub258(HelDim(3),4,2)
        HelType Sub259(HelDim(3),4,2)
        HelType Sub296(HelDim(3),4,2)
        HelType Sub148(HelDim(3),4,4)
        HelType Sub154(HelDim(3),4,4)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub99(HelDim(3),4,2)
        HelType Sub248(HelDim(3),4,2)
        HelType Sub253(HelDim(3),4,2)
        HelType Sub334(HelDim(3),4,2)
        HelType Sub198(HelDim(3),4,2)
        HelType Sub9(HelDim(3),4,2)
        HelType Sub194(HelDim(3),4,2)
        HelType Sub197(HelDim(3),4,2)
        HelType Sub312(HelDim(3),4,2)
        HelType Sub280(HelDim(3),3,2,2)
        HelType Sub303(HelDim(3),3,2,2)
        HelType Sub279(HelDim(3),3,2,2)
        HelType Sub337(HelDim(3),3,2,2)
        HelType Sub347(HelDim(3),3,2,2)
        HelType Sub341(HelDim(3),3,2,2)
        HelType Sub345(HelDim(3),3,2,2)
        HelType Sub292(HelDim(3),3,2,2)
        HelType Sub291(HelDim(3),3,2,2)
        HelType Sub307(HelDim(3),3,2,2)
        HelType Sub313(HelDim(3),3,2,2)
        HelType Sub335(HelDim(3),3,2,2)
        HelType Sub204(HelDim(3),3,4,2)
        HelType Sub285(HelDim(3),3,2,2)
        HelType Sub299(HelDim(3),3,2,2)
        HelType Sub286(HelDim(3),3,2,2)
        HelType Sub301(HelDim(3),3,2,2)
        HelType Sub315(HelDim(3),3,2,2)
        HelType Sub268(HelDim(3),4,4,2)
        HelType Sub271(HelDim(3),4,4,2)
        HelType Sub131(HelDim(3),3,4,4)
        HelType Sub138(HelDim(3),3,4,4)
        HelType Sub234(HelDim(3),3,4,2)
        HelType Sub238(HelDim(3),3,4,2)
        HelType Sub321(HelDim(3),3,2,2)
        HelType Sub329(HelDim(3),3,2,2)
        HelType Sub73(HelDim(3),3,3,4,4)
        HelType Sub75(HelDim(3),3,3,4,4)
        HelType Sub246(HelDim(3),3,3,4,2)
        HelType Sub48(HelDim(3),3,3,4,2)
        HelType Sub47(HelDim(3),3,3,4,2)
        HelType Sub375(HelDim(3),3,3,4,2)
        HelType Sub264(HelDim(3),3,3,4,2)
        HelType Sub263(HelDim(3),3,3,4,2)
        HelType Sub42(HelDim(3),3,3,4,2)
        HelType Sub43(HelDim(3),3,3,4,2)
        HelType Sub61(HelDim(3),3,3,4,4)
        HelType Sub67(HelDim(3),3,3,4,4)
        HelType Sub102(HelDim(3),3,3,4,2)
        HelType Sub103(HelDim(3),3,3,4,2)
        HelType Sub82(HelDim(3),3,3,4,2)
        HelType Sub215(HelDim(3),3,4,4,2)
        HelType Sub273(HelDim(3),3,4,4,2)
        HelType Sub208(HelDim(3),3,4,4,2)
        HelType Sub272(HelDim(3),3,4,4,2)
        HelType Sub212(HelDim(3),3,4,4,2)
        HelType Sub219(HelDim(3),3,3,4,2)
        HelType Sub222(HelDim(3),3,3,4,2)
        HelType Sub250(HelDim(3),3,4,4,2)
        HelType Sub254(HelDim(3),3,4,4,2)
        HelType Sub243(HelDim(3),3,4,4,2)
        HelType Sub179(HelDim(3),3,3,4,4)
        HelType Sub186(HelDim(3),3,3,4,4)
        HelType Sub91(HelDim(3),3,3,4,4)
        HelType Sub96(HelDim(3),3,3,4,4)
        HelType Sub201(HelDim(3),3,4,4,2)
        HelType Sub189(HelDim(3),3,4,4,2)
        HelType Sub79(HelDim(3),3,4,4,2)
        HelType Sub386(HelDim(3),3,3,3,4,4)
        HelType Sub387(HelDim(3),3,3,3,4,4)
        HelType Sub388(HelDim(3),3,3,3,4,4)
        HelType Sub391(HelDim(3),3,3,3,4,4)
        HelType Sub393(HelDim(3),3,3,3,4,4)
        HelType Sub392(HelDim(3),3,3,3,4,4)
        HelType Sub389(HelDim(3),3,3,3,4,4)
        HelType Sub390(HelDim(3),3,3,3,4,4)
        HelType Sub376(HelDim(3),3,3,3,4,2)
        HelType Sub383(HelDim(3),3,3,3,4,2)
        HelType Sub282(HelDim(3),3,4,4,2,2)
        HelType Sub193(HelDim(3),3,3,4,4,2)
        HelType Sub205(HelDim(3),3,3,4,4,2)
        HelType Sub352(HelDim(3),3,3,4,4,2)
        HelType Sub239(HelDim(3),3,3,4,4,2)
        HelType Sub240(HelDim(3),3,3,4,4,2)
        HelType Sub192(HelDim(3),3,3,4,4,2)
        HelType Sub288(HelDim(3),3,4,4,2,2)
        HelType Sub278(HelDim(3),3,4,4,2,2), Sub176
        HelType Sub92, Sub55, Sub152, Sub149, Sub290(HelDim(3))
        HelType Sub306(HelDim(3)), Sub305(HelDim(3))
        HelType Sub289(HelDim(3)), Sub339(HelDim(3))
        HelType Sub343(HelDim(3)), Sub340(HelDim(3))
        HelType Sub344(HelDim(3)), Sub284(HelDim(3))
        HelType Sub298(HelDim(3)), Sub283(HelDim(3))
        HelType Sub297(HelDim(3)), Sub328(HelDim(3))
        HelType Sub327(HelDim(3)), Sub209(HelDim(4))
        HelType Sub210(HelDim(4)), Sub252(HelDim(4))
        HelType Sub251(HelDim(4)), Sub226(HelDim(4))
        HelType Sub227(HelDim(4)), Sub195(HelDim(4))
        HelType Sub196(HelDim(4)), Sub65(HelDim(3),3)
        HelType Sub181(HelDim(3),3), Sub89(HelDim(3),3)
        HelType Sub94(HelDim(3),3), Sub126(HelDim(4),4)
        HelType Sub107(HelDim(3),4,4)
        HelType Sub114(HelDim(3),4,4)
        HelType Sub160(HelDim(3),4,4)
        HelType Sub167(HelDim(3),4,4)
        HelType Sub117(HelDim(3),4,4)
        HelType Sub170(HelDim(3),4,4)
        HelType Sub175(HelDim(3),3,3)
        HelType Sub182(HelDim(3),3,3)
        HelType Sub90(HelDim(3),3,3)
        HelType Sub95(HelDim(3),3,3)
        HelType Sub153(HelDim(3),4,4)
        HelType Sub147(HelDim(3),4,4)
        HelType Sub151(HelDim(3),4,4)
        HelType Sub304(HelDim(3),3,2,2)
        HelType Sub338(HelDim(3),3,2,2)
        HelType Sub348(HelDim(3),3,2,2)
        HelType Sub342(HelDim(3),3,2,2)
        HelType Sub346(HelDim(3),3,2,2)
        HelType Sub156(HelDim(3),3,4,4)
        HelType Sub308(HelDim(3),3,2,2)
        HelType Sub314(HelDim(3),3,2,2)
        HelType Sub336(HelDim(3),3,2,2)
        HelType Sub300(HelDim(3),3,2,2)
        HelType Sub302(HelDim(3),3,2,2)
        HelType Sub316(HelDim(3),3,2,2)
        HelType Sub322(HelDim(3),3,2,2)
        HelType Sub330(HelDim(3),3,2,2)
        HelType Sub77(HelDim(3),3,3,4,4)
        HelType Sub140(HelDim(3),3,3,4,4)
        HelType Sub188(HelDim(3),3,3,4,4)
        HelType Sub69(HelDim(3),3,3,3,4,4)
        HelType Sub98(HelDim(3),3,3,3,4,4), Sub145
        HelType Sub266(HelDim(4)), Sub256(HelDim(4))
        HelType Sub270(HelDim(4)), Sub257(HelDim(4))
        HelType Sub236(HelDim(3),3), Sub173(HelDim(3),3)
        HelType Sub231(HelDim(3),3), Sub180(HelDim(3),3)
        HelType Sub174(HelDim(3),3)
        HelType Sub58(HelDim(3),3,3)
        HelType Sub60(HelDim(3),3,3)
        HelType Sub63(HelDim(3),3,3)
        HelType Sub109(HelDim(3),4,4)
        HelType Sub162(HelDim(3),4,4)
        HelType Sub93(HelDim(3),3,3)
        HelType Sub233(HelDim(3),3,4)
        HelType Sub235(HelDim(3),3,4)
        HelType Sub217(HelDim(3),3,4)
        HelType Sub221(HelDim(3),3,4)
        HelType Sub232(HelDim(3),3,4)
        HelType Sub237(HelDim(3),3,4)
        HelType Sub127(HelDim(3),3,4,4)
        HelType Sub62(HelDim(3),3), Sub59(HelDim(3),3)
        HelType Sub57(HelDim(3),3), Sub88(HelDim(3),3)
        HelType Sub216(HelDim(3),3), Sub146(HelDim(4),4)
        HelType Sub150(HelDim(4),4)
        HelType Sub66(HelDim(3),3,3)
        HelType Sub112(HelDim(3),4,4)
        HelType Sub165(HelDim(3),4,4)
        HelType Sub178(HelDim(3),3,3)
        HelType Sub134(HelDim(3),3,4,4)
        HelType Sub261(HelDim(3),3,3)
        HelType Sub46(HelDim(3),3,3)
        HelType Sub244(HelDim(3),3,3)
        HelType Sub72(HelDim(3),3,3)
        HelType Sub41(HelDim(3),3,3)
        HelType Sub262(HelDim(3),3,3)
        HelType Sub45(HelDim(3),3,3)
        HelType Sub245(HelDim(3),3,3)
        HelType Sub74(HelDim(3),3,3)
        HelType Sub40(HelDim(3),3,3)
        HelType Sub81(HelDim(3),3,3)
        HelType Sub80(HelDim(3),3,3)
        HelType Sub100(HelDim(3),3,3)
        HelType Sub101(HelDim(3),3,3)
        HelType Sub87(HelDim(3),3,3)
        HelType Sub130(HelDim(3),3,4,4)
        HelType Sub137(HelDim(3),3,4,4)
        HelType Sub267(HelDim(4)), Sub269(HelDim(4))
        HelType Sub185(HelDim(3),3,3)
        HelType Sub220(HelDim(3),3,4)
        HelType Sub218(HelDim(3),3,4)
        HelType Sub144(HelDim(3),4,4)
        common /varXh/ F3, F25, F11, F5, F43, F7, F26, F13, F9, F56
        common /varXh/ F27, F4, F45, F28, F8, F55, F35, F98, F29
        common /varXh/ F32, F95, F44, F66, F67, F140, F1, F68, F70
        common /varXh/ F142, F10, F151, F153, F152, F154, F33, F37
        common /varXh/ F82, F54, F24, F46, F40, F83, F30, F21, F78
        common /varXh/ F148, F12, F23, F6, F53, F79, F146, F14, F22
        common /varXh/ F2, F47, F59, F81, F155, F63, F80, F156, F103
        common /varXh/ F104, F16, F101, F38, F64, F69, F39, F100
        common /varXh/ F65, F71, F15, F20, F102, F41, F89, F86, F31
        common /varXh/ F97, F90, F60, F18, F57, F136, F117, F58
        common /varXh/ F118, F119, F137, F138, F145, F121, F61, F132
        common /varXh/ F122, F62, F123, F124, F133, F135, F147, F125
        common /varXh/ F73, F42, F127, F105, F75, F48, F106, F96
        common /varXh/ F139, F128, F129, F107, F91, F76, F50, F130
        common /varXh/ F108, F77, F52, F111, F99, F141, F131, F134
        common /varXh/ F112, F92, F17, F49, F143, F51, F87, F158
        common /varXh/ F93, F116, F88, F144, F94, F19, F34, F149
        common /varXh/ F36, F72, F157, F84, F115, F74, F150, F85
        common /varXh/ F113, F126, F114, F109, F120, F110, Sub64
        common /varXh/ Sub136, Sub49, Sub51, Sub119, Sub135, Sub86
        common /varXh/ Sub132, Sub118, Sub111, Sub164, Sub143
        common /varXh/ Sub124, Sub129, Sub121, Sub54, Sub108, Sub161
        common /varXh/ Sub122, Sub183, Sub128, Sub106, Sub159
        common /varXh/ Sub113, Sub166, Sub133, Sub125, Sub12, Sub2
        common /varXh/ Sub20, Sub28, Sub33, Sub35, Sub24, Sub38
        common /varXh/ Sub177, Sub184, Sub203, Sub202, Sub191
        common /varXh/ Sub190, Sub116, Sub139, Sub155, Sub169
        common /varXh/ Sub187, Sub104, Sub70, Sub171, Sub157, Sub84
        common /varXh/ Sub141, Sub71, Sub85, Sub142, Sub172, Sub105
        common /varXh/ Sub158, Sub120, Sub123, Sub53, Sub56, Sub68
        common /varXh/ Sub76, Sub97, Sub110, Sub115, Sub163, Sub168
        common /varXh/ Sub27, Sub241, Sub213, Sub37, Sub260, Sub265
        common /varXh/ Sub206, Sub199, Sub32, Sub211, Sub320, Sub23
        common /varXh/ Sub225, Sub228, Sub229, Sub326, Sub6, Sub44
        common /varXh/ Sub230, Sub276, Sub18, Sub255, Sub39, Sub258
        common /varXh/ Sub259, Sub296, Sub148, Sub154, Sub16, Sub99
        common /varXh/ Sub248, Sub253, Sub334, Sub198, Sub9, Sub194
        common /varXh/ Sub197, Sub312, Sub280, Sub303, Sub279
        common /varXh/ Sub337, Sub347, Sub341, Sub345, Sub292
        common /varXh/ Sub291, Sub307, Sub313, Sub335, Sub204
        common /varXh/ Sub285, Sub299, Sub286, Sub301, Sub315
        common /varXh/ Sub268, Sub271, Sub131, Sub138, Sub234
        common /varXh/ Sub238, Sub321, Sub329, Sub73, Sub75, Sub246
        common /varXh/ Sub48, Sub47, Sub375, Sub264, Sub263, Sub42
        common /varXh/ Sub43, Sub61, Sub67, Sub102, Sub103, Sub82
        common /varXh/ Sub215, Sub273, Sub208, Sub272, Sub212
        common /varXh/ Sub219, Sub222, Sub250, Sub254, Sub243
        common /varXh/ Sub179, Sub186, Sub91, Sub96, Sub201, Sub189
        common /varXh/ Sub79, Sub386, Sub387, Sub388, Sub391, Sub393
        common /varXh/ Sub392, Sub389, Sub390, Sub376, Sub383
        common /varXh/ Sub282, Sub193, Sub205, Sub352, Sub239
        common /varXh/ Sub240, Sub192, Sub288, Sub278, Sub176, Sub92
        common /varXh/ Sub55, Sub152, Sub149, Sub290, Sub306, Sub305
        common /varXh/ Sub289, Sub339, Sub343, Sub340, Sub344
        common /varXh/ Sub284, Sub298, Sub283, Sub297, Sub328
        common /varXh/ Sub327, Sub209, Sub210, Sub252, Sub251
        common /varXh/ Sub226, Sub227, Sub195, Sub196, Sub65, Sub181
        common /varXh/ Sub89, Sub94, Sub126, Sub107, Sub114, Sub160
        common /varXh/ Sub167, Sub117, Sub170, Sub175, Sub182, Sub90
        common /varXh/ Sub95, Sub153, Sub147, Sub151, Sub304, Sub338
        common /varXh/ Sub348, Sub342, Sub346, Sub156, Sub308
        common /varXh/ Sub314, Sub336, Sub300, Sub302, Sub316
        common /varXh/ Sub322, Sub330, Sub77, Sub140, Sub188, Sub69
        common /varXh/ Sub98, Sub145, Sub266, Sub256, Sub270, Sub257
        common /varXh/ Sub236, Sub173, Sub231, Sub180, Sub174, Sub58
        common /varXh/ Sub60, Sub63, Sub109, Sub162, Sub93, Sub233
        common /varXh/ Sub235, Sub217, Sub221, Sub232, Sub237
        common /varXh/ Sub127, Sub62, Sub59, Sub57, Sub88, Sub216
        common /varXh/ Sub146, Sub150, Sub66, Sub112, Sub165, Sub178
        common /varXh/ Sub134, Sub261, Sub46, Sub244, Sub72, Sub41
        common /varXh/ Sub262, Sub45, Sub245, Sub74, Sub40, Sub81
        common /varXh/ Sub80, Sub100, Sub101, Sub87, Sub130, Sub137
        common /varXh/ Sub267, Sub269, Sub185, Sub220, Sub218, Sub144

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7, Sfe8
        common /indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqu_nInJququbar_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
