#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 3-Aug-2016 19:01
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub2(4), Sub12(3,4,2)
        ComplexType Sub13(3,4,2), Sub3(3,4,Sfe8)
        ComplexType Sub4(3,4,Sfe8), Sub1(3,4,2)
        ComplexType Sub7(3,4,2), Sub6(3,4,2)
        common /varXs/ Sub2, Sub12, Sub13, Sub3, Sub4, Sub1, Sub7
        common /varXs/ Sub6

        ComplexType Opt1(3,4), Sub346(3,3,3,3,4,N
 
          eu4), Sub347(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt1, Sub346, Sub347, S, T, T14, T15, U, T24
        common /varXa/ T25, S34, S35, S45

        HelType F3, F4, F1, F6, F2, F5, F7, F8, F9, F10
        HelType Sub11(HelDim(3),3)
        HelType Sub14(HelDim(3),4,2)
        HelType Sub5(HelDim(3),4,Sfe8)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub9(HelDim(3),3,2,Sfe8)
        HelType Sub10(HelDim(3),3,2,Sfe8)
        common /varXh/ F3, F4, F1, F6, F2, F5, F7, F8, F9, F10, Sub11
        common /varXh/ Sub14, Sub5, Sub8, Sub9, Sub10

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqu_nInJququbar_3546_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
