#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 10-Mar-2017 11:16
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub1(4), Sub16(4), Sub17(3,4,2)
        ComplexType Sub18(3,4,2), Sub29(3,4,2)
        ComplexType Sub30(3,4,2), Sub34(3,4,2)
        ComplexType Sub35(3,4,2), Sub36(3,4,2)
        ComplexType Sub343(3,2), Sub353(3,2)
        common /qubarqu_nInJqubarqu_365_Sq1_varXs/ Sub1, Sub16, Sub17, Sub18, Sub29, Sub30, Sub34
        common /qubarqu_nInJqubarqu_365_Sq1_varXs/ Sub35, Sub36, Sub343, Sub353

        ComplexType Sub349(3,3,3,3,4,4)
        ComplexType Sub359(3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qubarqu_nInJqubarqu_365_Sq1_varXa/ Sub349, Sub359, S, T, T14, T15, U, T24, T25
        common /qubarqu_nInJqubarqu_365_Sq1_varXa/ S34, S35, S45

        HelType F12, F15, F18, F19, F26, F27, F33, F34, F35, F36, F37
        HelType F38, F39, F40, F41, F42, F43, F44
        HelType Sub19(HelDim(3),4,2)
        HelType Sub40(HelDim(3),4,2)
        HelType Sub41(HelDim(3),3,2,2)
        HelType Sub42(HelDim(3),3,2,2)
        HelType Sub43(HelDim(3),4,2)
        HelType Sub44(HelDim(3),3,2,2)
        HelType Sub45(HelDim(3),3,2,2)
        HelType Sub361(HelDim(3),3,3,4,2,2)
        common /qubarqu_nInJqubarqu_365_Sq1_varXh/ F12, F15, F18, F19, F26, F27, F33, F34, F35
        common /qubarqu_nInJqubarqu_365_Sq1_varXh/ F36, F37, F38, F39, F40, F41, F42, F43, F44
        common /qubarqu_nInJqubarqu_365_Sq1_varXh/ Sub19, Sub40, Sub41, Sub42, Sub43, Sub44
        common /qubarqu_nInJqubarqu_365_Sq1_varXh/ Sub45, Sub361

        integer Sfe8
        common /qubarqu_nInJqubarqu_365_Sq1_indices/ Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqu_nInJqubarqu_365_Sq1_formfactors/ Ctree, MatSUN

#endif

