#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 11-Nov-2016 14:46
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub3(4), Sub19(4), Sub400(3,2)
        ComplexType Sub403(3,2), Sub384(3,2), Sub387(3,2)
        ComplexType Sub382(3,2), Sub386(3,2), Sub399(3,2)
        ComplexType Sub402(3,2), Sub390(3,2), Sub393(3,2)
        ComplexType Sub391(3,2), Sub394(3,2)
        ComplexType Sub113(4,4), Sub115(4,4)
        ComplexType Sub89(3,4,2), Sub90(3,4,2)
        ComplexType Sub54(3,4,2), Sub55(3,4,2)
        ComplexType Sub84(3,4,2), Sub86(3,4,2)
        ComplexType Sub33(3,4,2), Sub34(3,4,2)
        ComplexType Sub75(3,4,2), Sub77(3,4,2)
        ComplexType Sub76(3,4,2), Sub59(3,4,2)
        ComplexType Sub61(3,4,2), Sub60(3,4,2)
        ComplexType Sub79(3,4,2), Sub82(3,4,2)
        ComplexType Sub81(3,4,2), Sub38(3,4,2)
        ComplexType Sub40(3,4,2), Sub39(3,4,2)
        ComplexType Sub4(3,4,2), Sub5(3,4,2)
        ComplexType Sub356(3,4,2), Sub357(3,4,2)
        ComplexType Sub20(3,4,2), Sub26(3,4,2)
        ComplexType Sub28(3,4,2), Sub29(3,4,2)
        ComplexType Sub22(3,4,2), Sub24(3,4,2)
        ComplexType Sub23(3,4,2), Sub1(3,4,2)
        ComplexType Sub8(3,4,2), Sub7(3,4,2)
        ComplexType Sub10(3,4,2), Sub13(3,4,2)
        ComplexType Sub12(3,4,2)
        common /varXs/ Sub3, Sub19, Sub400, Sub403, Sub384, Sub387
        common /varXs/ Sub382, Sub386, Sub399, Sub402, Sub390
        common /varXs/ Sub393, Sub391, Sub394, Sub113, Sub115, Sub89
        common /varXs/ Sub90, Sub54, Sub55, Sub84, Sub86, Sub33
        common /varXs/ Sub34, Sub75, Sub77, Sub76, Sub59, Sub61
        common /varXs/ Sub60, Sub79, Sub82, Sub81, Sub38, Sub40
        common /varXs/ Sub39, Sub4, Sub5, Sub356, Sub357, Sub20
        common /varXs/ Sub26, Sub28, Sub29, Sub22, Sub24, Sub23
        common /varXs/ Sub1, Sub8, Sub7, Sub10, Sub13, Sub12

        ComplexType Opt12(3,3,3,3)
        ComplexType Opt13(3,3,4,4), Opt14(3)
        ComplexType Opt15(3,3,3,3)
        ComplexType Sub413(3,3,3), Sub409(3,3,4)
        ComplexType Sub406(3,3,4), Sub418(3,4,4)
        ComplexType Sub383(3,3,3,3,4,4)
        ComplexType Sub396(3,3,3,3,4,4)
        ComplexType Sub415(3,3,3,3,4,4)
        ComplexType Sub420(3,3,3,3,4,4)
        ComplexType Sub412(3,3,3,3,4,4)
        ComplexType Sub389(3,3,3,3,4,4)
        ComplexType Sub405(3,3,3,3,4,4)
        ComplexType Sub416(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt12, Opt13, Opt14, Opt15, Sub413, Sub409
        common /varXa/ Sub406, Sub418, Sub383, Sub396, Sub415
        common /varXa/ Sub420, Sub412, Sub389, Sub405, Sub416, S, T
        common /varXa/ T14, T15, U, T24, T25, S34, S35, S45

        HelType F4, F46, F18, F59, F29, F6, F47, F19, F61, F27, F64
        HelType F58, F79, F65, F60, F91, F69, F112, F73, F72, F113
        HelType F66, F87, F51, F144, F12, F89, F50, F145, F15, F152
        HelType F156, F153, F157, F67, F26, F110, F68, F2, F70, F28
        HelType F109, F74, F7, F104, F40, F34, F5, F14, F75, F107
        HelType F41, F35, F3, F13, F71, F86, F111, F158, F84, F108
        HelType F159, F21, F20, F63, F30, F8, F96, F52, F16, F119
        HelType F97, F31, F9, F62, F32, F10, F94, F53, F17, F117
        HelType F95, F33, F11, F100, F146, F128, F101, F129, F130
        HelType F154, F147, F148, F131, F102, F149, F132, F103, F133
        HelType F124, F155, F150, F151, F126, F105, F78, F135, F120
        HelType F106, F80, F121, F116, F141, F136, F137, F123, F115
        HelType F82, F81, F138, F125, F83, F85, F127, F118, F142
        HelType F139, F140, F122, F114, F36, F88, F42, F90, F92, F56
        HelType F54, F143, F93, F43, F37, F39, F76, F44, F77, F98
        HelType F57, F55, F134, F99, F45, F38, F24, F49, F25, F22
        HelType F48, F23, Sub165, Sub114, Sub174, Sub159, Sub112
        HelType Sub168, Sub176, Sub118, Sub117, Sub163, Sub148
        HelType Sub167, Sub153, Sub220, Sub222, Sub236, Sub234
        HelType Sub239, Sub241, Sub227, Sub225, Sub154, Sub173
        HelType Sub169, Sub177(HelDim(3))
        HelType Sub21(HelDim(3),3), Sub2(HelDim(3),3)
        HelType Sub130(HelDim(3),3), Sub127(HelDim(3),3)
        HelType Sub123(HelDim(3),3), Sub80(HelDim(3),3)
        HelType Sub74(HelDim(3),3), Sub85(HelDim(3),3)
        HelType Sub93(HelDim(3),3), Sub88(HelDim(3),3)
        HelType Sub92(HelDim(3),3), Sub204(HelDim(3),3)
        HelType Sub210(HelDim(3),3), Sub266(HelDim(3),4)
        HelType Sub265(HelDim(3),4), Sub271(HelDim(3),4)
        HelType Sub270(HelDim(3),4), Sub135(HelDim(4),4)
        HelType Sub246(HelDim(4),4), Sub202(HelDim(4),4)
        HelType Sub136(HelDim(4),4), Sub143(HelDim(4),4)
        HelType Sub144(HelDim(4),4), Sub247(HelDim(4),4)
        HelType Sub203(HelDim(4),4), Sub218(HelDim(4),4)
        HelType Sub232(HelDim(4),4), Sub233(HelDim(4),4)
        HelType Sub219(HelDim(4),4), Sub116(HelDim(4),4)
        HelType Sub119(HelDim(4),4), Sub161(HelDim(4),4)
        HelType Sub164(HelDim(4),4), Sub133(HelDim(4),4)
        HelType Sub141(HelDim(4),4), Sub157(HelDim(4),4)
        HelType Sub180(HelDim(4),4), Sub216(HelDim(4),4)
        HelType Sub230(HelDim(4),4), Sub244(HelDim(4),4)
        HelType Sub260(HelDim(4),4)
        HelType Sub224(HelDim(3),4,4)
        HelType Sub229(HelDim(3),4,4)
        HelType Sub238(HelDim(3),4,4)
        HelType Sub243(HelDim(3),4,4)
        HelType Sub91(HelDim(3),4,2)
        HelType Sub316(HelDim(3),4,2)
        HelType Sub296(HelDim(3),4,2)
        HelType Sub56(HelDim(3),4,2)
        HelType Sub87(HelDim(3),4,2)
        HelType Sub349(HelDim(3),4,2)
        HelType Sub48(HelDim(3),4,2)
        HelType Sub78(HelDim(3),4,2)
        HelType Sub279(HelDim(3),4,2)
        HelType Sub262(HelDim(3),4,2)
        HelType Sub284(HelDim(3),4,2)
        HelType Sub62(HelDim(3),4,2)
        HelType Sub278(HelDim(3),4,2)
        HelType Sub83(HelDim(3),4,2)
        HelType Sub274(HelDim(3),4,2)
        HelType Sub277(HelDim(3),4,2)
        HelType Sub45(HelDim(3),4,2)
        HelType Sub6(HelDim(3),4,2)
        HelType Sub94(HelDim(3),4,2)
        HelType Sub328(HelDim(3),4,2)
        HelType Sub358(HelDim(3),4,2)
        HelType Sub27(HelDim(3),4,2)
        HelType Sub103(HelDim(3),4,2)
        HelType Sub30(HelDim(3),4,2)
        HelType Sub254(HelDim(3),4,4)
        HelType Sub259(HelDim(3),4,4)
        HelType Sub25(HelDim(3),4,2)
        HelType Sub286(HelDim(3),4,2)
        HelType Sub182(HelDim(3),4,2)
        HelType Sub289(HelDim(3),4,2)
        HelType Sub290(HelDim(3),4,2)
        HelType Sub295(HelDim(3),4,2)
        HelType Sub9(HelDim(3),4,2)
        HelType Sub294(HelDim(3),4,2)
        HelType Sub293(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub31(HelDim(3),3,2,2)
        HelType Sub17(HelDim(3),3,2,2)
        HelType Sub15(HelDim(3),3,2,2)
        HelType Sub52(HelDim(3),3,2,2)
        HelType Sub72(HelDim(3),3,2,2)
        HelType Sub375(HelDim(3),3,2,2)
        HelType Sub380(HelDim(3),3,2,2)
        HelType Sub376(HelDim(3),3,2,2)
        HelType Sub46(HelDim(3),3,2,2)
        HelType Sub44(HelDim(3),3,2,2)
        HelType Sub67(HelDim(3),3,2,2)
        HelType Sub69(HelDim(3),3,2,2)
        HelType Sub50(HelDim(3),3,2,2)
        HelType Sub267(HelDim(3),3,4,2)
        HelType Sub36(HelDim(3),3,2,2)
        HelType Sub57(HelDim(3),3,2,2)
        HelType Sub342(HelDim(3),3,2,2)
        HelType Sub363(HelDim(3),3,2,2)
        HelType Sub364(HelDim(3),3,2,2)
        HelType Sub310(HelDim(3),4,4,2)
        HelType Sub313(HelDim(3),4,4,2)
        HelType Sub172(HelDim(3),3,4,4)
        HelType Sub179(HelDim(3),3,4,4)
        HelType Sub334(HelDim(3),3,4,2)
        HelType Sub337(HelDim(3),3,4,2)
        HelType Sub371(HelDim(3),3,2,2)
        HelType Sub368(HelDim(3),3,2,2)
        HelType Sub138(HelDim(3),3,3,4,4)
        HelType Sub140(HelDim(3),3,3,4,4)
        HelType Sub301(HelDim(3),3,3,4,2)
        HelType Sub303(HelDim(3),3,3,4,2)
        HelType Sub97(HelDim(3),3,3,4,2)
        HelType Sub100(HelDim(3),3,3,4,2)
        HelType Sub125(HelDim(3),3,3,4,4)
        HelType Sub132(HelDim(3),3,3,4,4)
        HelType Sub187(HelDim(3),3,3,4,2)
        HelType Sub190(HelDim(3),3,3,4,2)
        HelType Sub315(HelDim(3),3,4,4,2)
        HelType Sub318(HelDim(3),3,4,4,2)
        HelType Sub281(HelDim(3),3,4,4,2)
        HelType Sub307(HelDim(3),3,4,4,2)
        HelType Sub314(HelDim(3),3,4,4,2)
        HelType Sub285(HelDim(3),3,4,4,2)
        HelType Sub322(HelDim(3),3,3,4,2)
        HelType Sub325(HelDim(3),3,3,4,2)
        HelType Sub298(HelDim(3),3,4,4,2)
        HelType Sub150(HelDim(3),3,3,4,4)
        HelType Sub156(HelDim(3),3,3,4,4)
        HelType Sub209(HelDim(3),3,3,4,4)
        HelType Sub215(HelDim(3),3,3,4,4)
        HelType Sub264(HelDim(3),3,4,4,2)
        HelType Sub348(HelDim(3),3,4,4,2)
        HelType Sub344(HelDim(3),3,4,4,2)
        HelType Sub347(HelDim(3),3,4,4,2)
        HelType Sub269(HelDim(3),3,4,4,2)
        HelType Sub330(HelDim(3),3,4,4,2)
        HelType Sub184(HelDim(3),3,4,4,2)
        HelType Sub193(HelDim(3),3,4,4,2)
        HelType Sub414(HelDim(3),3,3,3,4,4)
        HelType Sub421(HelDim(3),3,3,3,4,4)
        HelType Sub424(HelDim(3),3,3,3,4,4)
        HelType Sub419(HelDim(3),3,3,3,4,4)
        HelType Sub417(HelDim(3),3,3,3,4,4)
        HelType Sub422(HelDim(3),3,3,3,4,4)
        HelType Sub106(HelDim(3),3,3,3,4,2)
        HelType Sub109(HelDim(3),3,3,3,4,2)
        HelType Sub352(HelDim(3),3,3,3,4,2)
        HelType Sub196(HelDim(3),3,3,3,4,2)
        HelType Sub199(HelDim(3),3,3,3,4,2)
        HelType Sub408(HelDim(3),3,3,4,2,2)
        HelType Sub370(HelDim(3),3,4,4,2,2)
        HelType Sub35(HelDim(3),3,4,4,2,2)
        HelType Sub360(HelDim(3),3,4,4,2,2)
        HelType Sub268(HelDim(3),3,3,4,4,2)
        HelType Sub273(HelDim(3),3,3,4,4,2)
        HelType Sub435(HelDim(3),3,3,4,4,2)
        HelType Sub339(HelDim(3),3,3,4,4,2)
        HelType Sub436(HelDim(3),3,3,4,4,2)
        HelType Sub272(HelDim(3),3,3,4,4,2)
        HelType Sub338(HelDim(3),3,3,4,4,2)
        HelType Sub447(HelDim(3),3,3,4,2,2)
        HelType Sub41(HelDim(3),3,4,4,2,2)
        HelType Sub64(HelDim(3),3,4,4,2,2)
        HelType Sub71(HelDim(3),3,4,4,2,2)
        HelType Sub14(HelDim(3),3,4,4,2,2), Sub160
        HelType Sub122, Sub162, Sub129, Sub126, Sub257, Sub255
        HelType Sub248, Sub42(HelDim(3)), Sub65(HelDim(3))
        HelType Sub43(HelDim(3)), Sub66(HelDim(3))
        HelType Sub49(HelDim(3)), Sub379(HelDim(3))
        HelType Sub374(HelDim(3)), Sub378(HelDim(3))
        HelType Sub373(HelDim(3)), Sub361(HelDim(3))
        HelType Sub340(HelDim(3)), Sub362(HelDim(3))
        HelType Sub341(HelDim(3)), Sub367(HelDim(3))
        HelType Sub366(HelDim(3)), Sub282(HelDim(4))
        HelType Sub288(HelDim(4)), Sub287(HelDim(4))
        HelType Sub283(HelDim(4)), Sub275(HelDim(4))
        HelType Sub292(HelDim(4)), Sub291(HelDim(4))
        HelType Sub276(HelDim(4)), Sub151(HelDim(3),3)
        HelType Sub146(HelDim(3),3), Sub170(HelDim(4),4)
        HelType Sub231(HelDim(3),4,4)
        HelType Sub245(HelDim(3),4,4)
        HelType Sub147(HelDim(3),3,3)
        HelType Sub152(HelDim(3),3,3)
        HelType Sub206(HelDim(3),3,3)
        HelType Sub208(HelDim(3),3,3)
        HelType Sub212(HelDim(3),3,3)
        HelType Sub214(HelDim(3),3,3)
        HelType Sub250(HelDim(3),4,4)
        HelType Sub256(HelDim(3),4,4)
        HelType Sub253(HelDim(3),4,4)
        HelType Sub258(HelDim(3),4,4)
        HelType Sub32(HelDim(3),3,2,2)
        HelType Sub53(HelDim(3),3,2,2)
        HelType Sub73(HelDim(3),3,2,2)
        HelType Sub381(HelDim(3),3,2,2)
        HelType Sub261(HelDim(3),3,4,4)
        HelType Sub51(HelDim(3),3,2,2)
        HelType Sub70(HelDim(3),3,2,2)
        HelType Sub37(HelDim(3),3,2,2)
        HelType Sub58(HelDim(3),3,2,2)
        HelType Sub343(HelDim(3),3,2,2)
        HelType Sub372(HelDim(3),3,2,2)
        HelType Sub369(HelDim(3),3,2,2)
        HelType Sub142(HelDim(3),3,3,4,4)
        HelType Sub181(HelDim(3),3,3,4,4)
        HelType Sub217(HelDim(3),3,3,4,4)
        HelType Sub134(HelDim(3),3,3,3,4,4)
        HelType Sub158(HelDim(3),3,3,3,4,4)
        HelType Sub423(HelDim(3),3,3,3,4,4)
        HelType Sub425(HelDim(3),3,3,3,4,4)
        HelType Sub308(HelDim(4)), Sub312(HelDim(4))
        HelType Sub346(HelDim(4)), Sub345(HelDim(4))
        HelType Sub331(HelDim(3),3), Sub205(HelDim(3),3)
        HelType Sub207(HelDim(3),3), Sub213(HelDim(3),3)
        HelType Sub211(HelDim(3),3)
        HelType Sub121(HelDim(3),3,3)
        HelType Sub131(HelDim(3),3,3)
        HelType Sub155(HelDim(3),3,3)
        HelType Sub323(HelDim(3),3,4)
        HelType Sub321(HelDim(3),3,4)
        HelType Sub332(HelDim(3),3,4)
        HelType Sub178(HelDim(3),3,4,4), Sub251
        HelType Sub120(HelDim(3),3), Sub145(HelDim(3),3)
        HelType Sub319(HelDim(3),3), Sub249(HelDim(4),4)
        HelType Sub252(HelDim(4),4)
        HelType Sub128(HelDim(3),3,3)
        HelType Sub223(HelDim(3),4,4)
        HelType Sub235(HelDim(3),4,4)
        HelType Sub242(HelDim(3),4,4)
        HelType Sub226(HelDim(3),4,4)
        HelType Sub221(HelDim(3),4,4)
        HelType Sub228(HelDim(3),4,4)
        HelType Sub237(HelDim(3),4,4)
        HelType Sub240(HelDim(3),4,4)
        HelType Sub171(HelDim(3),3,4,4)
        HelType Sub309(HelDim(4)), Sub311(HelDim(4))
        HelType Sub350(HelDim(3),3,3)
        HelType Sub108(HelDim(3),3,3)
        HelType Sub353(HelDim(3),3,3)
        HelType Sub104(HelDim(3),3,3)
        HelType Sub95(HelDim(3),3,3)
        HelType Sub99(HelDim(3),3,3)
        HelType Sub137(HelDim(3),3,3)
        HelType Sub299(HelDim(3),3,3)
        HelType Sub139(HelDim(3),3,3)
        HelType Sub300(HelDim(3),3,3)
        HelType Sub194(HelDim(3),3,3)
        HelType Sub198(HelDim(3),3,3)
        HelType Sub185(HelDim(3),3,3)
        HelType Sub189(HelDim(3),3,3)
        HelType Sub124(HelDim(3),3,3)
        HelType Sub149(HelDim(3),3,3)
        HelType Sub175(HelDim(3),3,4,4)
        HelType Sub107(HelDim(3),3,3)
        HelType Sub105(HelDim(3),3,3)
        HelType Sub98(HelDim(3),3,3)
        HelType Sub96(HelDim(3),3,3)
        HelType Sub197(HelDim(3),3,3)
        HelType Sub324(HelDim(3),3,4)
        HelType Sub333(HelDim(3),3,4)
        HelType Sub335(HelDim(3),3,4)
        HelType Sub195(HelDim(3),3,3)
        HelType Sub188(HelDim(3),3,3)
        HelType Sub186(HelDim(3),3,3)
        HelType Sub166(HelDim(3),3,4,4)
        common /varXh/ F4, F46, F18, F59, F29, F6, F47, F19, F61, F27
        common /varXh/ F64, F58, F79, F65, F60, F91, F69, F112, F73
        common /varXh/ F72, F113, F66, F87, F51, F144, F12, F89, F50
        common /varXh/ F145, F15, F152, F156, F153, F157, F67, F26
        common /varXh/ F110, F68, F2, F70, F28, F109, F74, F7, F104
        common /varXh/ F40, F34, F5, F14, F75, F107, F41, F35, F3
        common /varXh/ F13, F71, F86, F111, F158, F84, F108, F159
        common /varXh/ F21, F20, F63, F30, F8, F96, F52, F16, F119
        common /varXh/ F97, F31, F9, F62, F32, F10, F94, F53, F17
        common /varXh/ F117, F95, F33, F11, F100, F146, F128, F101
        common /varXh/ F129, F130, F154, F147, F148, F131, F102
        common /varXh/ F149, F132, F103, F133, F124, F155, F150
        common /varXh/ F151, F126, F105, F78, F135, F120, F106, F80
        common /varXh/ F121, F116, F141, F136, F137, F123, F115, F82
        common /varXh/ F81, F138, F125, F83, F85, F127, F118, F142
        common /varXh/ F139, F140, F122, F114, F36, F88, F42, F90
        common /varXh/ F92, F56, F54, F143, F93, F43, F37, F39, F76
        common /varXh/ F44, F77, F98, F57, F55, F134, F99, F45, F38
        common /varXh/ F24, F49, F25, F22, F48, F23, Sub165, Sub114
        common /varXh/ Sub174, Sub159, Sub112, Sub168, Sub176
        common /varXh/ Sub118, Sub117, Sub163, Sub148, Sub167
        common /varXh/ Sub153, Sub220, Sub222, Sub236, Sub234
        common /varXh/ Sub239, Sub241, Sub227, Sub225, Sub154
        common /varXh/ Sub173, Sub169, Sub177, Sub21, Sub2, Sub130
        common /varXh/ Sub127, Sub123, Sub80, Sub74, Sub85, Sub93
        common /varXh/ Sub88, Sub92, Sub204, Sub210, Sub266, Sub265
        common /varXh/ Sub271, Sub270, Sub135, Sub246, Sub202
        common /varXh/ Sub136, Sub143, Sub144, Sub247, Sub203
        common /varXh/ Sub218, Sub232, Sub233, Sub219, Sub116
        common /varXh/ Sub119, Sub161, Sub164, Sub133, Sub141
        common /varXh/ Sub157, Sub180, Sub216, Sub230, Sub244
        common /varXh/ Sub260, Sub224, Sub229, Sub238, Sub243, Sub91
        common /varXh/ Sub316, Sub296, Sub56, Sub87, Sub349, Sub48
        common /varXh/ Sub78, Sub279, Sub262, Sub284, Sub62, Sub278
        common /varXh/ Sub83, Sub274, Sub277, Sub45, Sub6, Sub94
        common /varXh/ Sub328, Sub358, Sub27, Sub103, Sub30, Sub254
        common /varXh/ Sub259, Sub25, Sub286, Sub182, Sub289, Sub290
        common /varXh/ Sub295, Sub9, Sub294, Sub293, Sub16, Sub31
        common /varXh/ Sub17, Sub15, Sub52, Sub72, Sub375, Sub380
        common /varXh/ Sub376, Sub46, Sub44, Sub67, Sub69, Sub50
        common /varXh/ Sub267, Sub36, Sub57, Sub342, Sub363, Sub364
        common /varXh/ Sub310, Sub313, Sub172, Sub179, Sub334
        common /varXh/ Sub337, Sub371, Sub368, Sub138, Sub140
        common /varXh/ Sub301, Sub303, Sub97, Sub100, Sub125, Sub132
        common /varXh/ Sub187, Sub190, Sub315, Sub318, Sub281
        common /varXh/ Sub307, Sub314, Sub285, Sub322, Sub325
        common /varXh/ Sub298, Sub150, Sub156, Sub209, Sub215
        common /varXh/ Sub264, Sub348, Sub344, Sub347, Sub269
        common /varXh/ Sub330, Sub184, Sub193, Sub414, Sub421
        common /varXh/ Sub424, Sub419, Sub417, Sub422, Sub106
        common /varXh/ Sub109, Sub352, Sub196, Sub199, Sub408
        common /varXh/ Sub370, Sub35, Sub360, Sub268, Sub273, Sub435
        common /varXh/ Sub339, Sub436, Sub272, Sub338, Sub447, Sub41
        common /varXh/ Sub64, Sub71, Sub14, Sub160, Sub122, Sub162
        common /varXh/ Sub129, Sub126, Sub257, Sub255, Sub248, Sub42
        common /varXh/ Sub65, Sub43, Sub66, Sub49, Sub379, Sub374
        common /varXh/ Sub378, Sub373, Sub361, Sub340, Sub362
        common /varXh/ Sub341, Sub367, Sub366, Sub282, Sub288
        common /varXh/ Sub287, Sub283, Sub275, Sub292, Sub291
        common /varXh/ Sub276, Sub151, Sub146, Sub170, Sub231
        common /varXh/ Sub245, Sub147, Sub152, Sub206, Sub208
        common /varXh/ Sub212, Sub214, Sub250, Sub256, Sub253
        common /varXh/ Sub258, Sub32, Sub53, Sub73, Sub381, Sub261
        common /varXh/ Sub51, Sub70, Sub37, Sub58, Sub343, Sub372
        common /varXh/ Sub369, Sub142, Sub181, Sub217, Sub134
        common /varXh/ Sub158, Sub423, Sub425, Sub308, Sub312
        common /varXh/ Sub346, Sub345, Sub331, Sub205, Sub207
        common /varXh/ Sub213, Sub211, Sub121, Sub131, Sub155
        common /varXh/ Sub323, Sub321, Sub332, Sub178, Sub251
        common /varXh/ Sub120, Sub145, Sub319, Sub249, Sub252
        common /varXh/ Sub128, Sub223, Sub235, Sub242, Sub226
        common /varXh/ Sub221, Sub228, Sub237, Sub240, Sub171
        common /varXh/ Sub309, Sub311, Sub350, Sub108, Sub353
        common /varXh/ Sub104, Sub95, Sub99, Sub137, Sub299, Sub139
        common /varXh/ Sub300, Sub194, Sub198, Sub185, Sub189
        common /varXh/ Sub124, Sub149, Sub175, Sub107, Sub105, Sub98
        common /varXh/ Sub96, Sub197, Sub324, Sub333, Sub335, Sub195
        common /varXh/ Sub188, Sub186, Sub166

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7, Sfe8
        common /indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqu_nInJququbar_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
