#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 10-Mar-2017 11:16
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub1(4), Sub2(3,4,2)
        ComplexType Sub8(3,4,2), Sub16(4)
        ComplexType Sub46(3,4,2), Sub47(3,4,2)
        ComplexType Sub53(3,4,2), Sub54(3,4,2)
        ComplexType Sub55(3,4,2), Sub343(3,2)
        ComplexType Sub353(3,2)
        common /qubarqu_nInJqubarqu_465_Sq1_varXs/ Sub1, Sub2, Sub8, Sub16, Sub46, Sub47, Sub53
        common /qubarqu_nInJqubarqu_465_Sq1_varXs/ Sub54, Sub55, Sub343, Sub353

        ComplexType Opt5(3,3), Sub337(3,3,3,3,4,4), Sub362(3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qubarqu_nInJqubarqu_465_Sq1_varXa/ Opt5, Sub337, Sub362, S, T, T14, T15, U, T24
        common /qubarqu_nInJqubarqu_465_Sq1_varXa/ T25, S34, S35, S45

        HelType F2, F4, F33, F34, F36, F38, F39, F41, F42, F43, F45
        HelType F46, F49, F50, F53, F54, F55, F56
        HelType Sub48(HelDim(3),4,2)
        HelType Sub56(HelDim(3),4,2)
        HelType Sub59(HelDim(3),3,4,4,2,2)
        HelType Sub60(HelDim(3),3,2,2)
        HelType Sub61(HelDim(3),3,2,2)
        HelType Sub62(HelDim(3),4,2)
        HelType Sub63(HelDim(3),3,2,2)
        HelType Sub64(HelDim(3),3,2,2)
        common /qubarqu_nInJqubarqu_465_Sq1_varXh/ F2, F4, F33, F34, F36, F38, F39, F41, F42, F43
        common /qubarqu_nInJqubarqu_465_Sq1_varXh/ F45, F46, F49, F50, F53, F54, F55, F56, Sub48
        common /qubarqu_nInJqubarqu_465_Sq1_varXh/ Sub56, Sub59, Sub60, Sub61, Sub62, Sub63
        common /qubarqu_nInJqubarqu_465_Sq1_varXh/ Sub64

        integer Sfe8
        common /qubarqu_nInJqubarqu_465_Sq1_indices/ Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqu_nInJqubarqu_465_Sq1_formfactors/ Ctree, MatSUN

#endif

