#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 26-Sep-2016 14:39
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Opt4(3,3,4,4), Sub36(4)
        ComplexType Sub25(4), Sub350(3,2), Sub354(3,2)
        ComplexType Sub358(3,2), Sub361(3,2), Sub357(3,2)
        ComplexType Sub360(3,2), Sub352(3,2), Sub355(3,2)
        ComplexType Sub390(3,2), Sub396(3,2), Sub55(4,4)
        ComplexType Sub56(4,4), Sub37(3,4,2)
        ComplexType Sub38(3,4,2), Sub26(3,4,2)
        ComplexType Sub28(3,4,2), Sub44(3,4,2)
        ComplexType Sub45(3,4,2), Sub309(3,4,2)
        ComplexType Sub310(3,4,2), Sub30(3,4,2)
        ComplexType Sub32(3,4,2), Sub294(3,4,2)
        ComplexType Sub295(3,4,2), Sub2(3,4,2)
        ComplexType Sub4(3,4,2), Sub3(3,4,2)
        ComplexType Sub301(3,4,2), Sub303(3,4,2)
        ComplexType Sub302(3,4,2), Sub34(3,4,2)
        ComplexType Sub41(3,4,2), Sub40(3,4,2)
        ComplexType Sub13(3,4,2), Sub19(3,4,2)
        ComplexType Sub18(3,4,2), Sub14(3,4,2)
        ComplexType Sub16(3,4,2), Sub15(3,4,2)
        ComplexType Sub333(3,4,2), Sub335(3,4,2)
        ComplexType Sub334(3,4,2), Sub47(3,4,2)
        ComplexType Sub50(3,4,2), Sub49(3,4,2)
        ComplexType Sub1(3,4,2), Sub7(3,4,2)
        ComplexType Sub6(3,4,2)
        common /varXs/ Opt4, Sub36, Sub25, Sub350, Sub354, Sub358
        common /varXs/ Sub361, Sub357, Sub360, Sub352, Sub355
        common /varXs/ Sub390, Sub396, Sub55, Sub56, Sub37, Sub38
        common /varXs/ Sub26, Sub28, Sub44, Sub45, Sub309, Sub310
        common /varXs/ Sub30, Sub32, Sub294, Sub295, Sub2, Sub4
        common /varXs/ Sub3, Sub301, Sub303, Sub302, Sub34, Sub41
        common /varXs/ Sub40, Sub13, Sub19, Sub18, Sub14, Sub16
        common /varXs/ Sub15, Sub333, Sub335, Sub334, Sub47, Sub50
        common /varXs/ Sub49, Sub1, Sub7, Sub6

        ComplexType Opt3(3,3,3,3), Opt5(3)
        ComplexType Opt6(3,3,3,3)
        ComplexType Sub376(3,3,3), Sub349(3,3,4)
        ComplexType Sub366(3,3,4), Sub379(3,4,4)
        ComplexType Sub351(3,3,3,3,4,4)
        ComplexType Sub367(3,3,3,3,4,4)
        ComplexType Sub378(3,3,3,3,4,4)
        ComplexType Sub384(3,3,3,3,4,4)
        ComplexType Sub380(3,3,3,3,4,4)
        ComplexType Sub363(3,3,3,3,4,4)
        ComplexType Sub372(3,3,3,3,4,4)
        ComplexType Sub375(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt3, Opt5, Opt6, Sub376, Sub349, Sub366
        common /varXa/ Sub379, Sub351, Sub367, Sub378, Sub384
        common /varXa/ Sub380, Sub363, Sub372, Sub375, S, T, T14
        common /varXa/ T15, U, T24, T25, S34, S35, S45

        HelType F29, F56, F91, F61, F26, F18, F42, F92, F64, F21, F27
        HelType F6, F23, F87, F45, F59, F22, F3, F30, F88, F55, F57
        HelType F74, F24, F17, F73, F19, F28, F139, F121, F1, F11
        HelType F144, F122, F5, F14, F155, F93, F156, F94, F49, F20
        HelType F65, F12, F2, F31, F25, F66, F13, F4, F82, F153, F44
        HelType F81, F154, F54, F58, F99, F62, F60, F100, F63, F111
        HelType F112, F137, F89, F47, F83, F50, F48, F80, F84, F51
        HelType F97, F138, F90, F40, F85, F36, F41, F77, F86, F37
        HelType F98, F101, F95, F38, F9, F71, F32, F39, F15, F72
        HelType F33, F10, F102, F96, F52, F7, F67, F34, F53, F16
        HelType F68, F35, F8, F123, F131, F124, F145, F151, F146
        HelType F147, F125, F132, F126, F127, F133, F128, F148, F152
        HelType F149, F150, F129, F134, F130, F103, F76, F117, F104
        HelType F140, F69, F141, F157, F75, F105, F118, F106, F43
        HelType F107, F78, F119, F108, F142, F70, F143, F158, F79
        HelType F109, F120, F110, F46, F115, F136, F116, F113, F135
        HelType F114, Sub124, Sub93, Sub97, Sub130, Sub121, Sub85
        HelType Sub99, Sub86, Sub119, Sub89, Sub91, Sub88, Sub111
        HelType Sub169, Sub108, Sub166, Sub131, Sub106, Sub164
        HelType Sub171, Sub113, Sub126, Sub122, Sub141
        HelType Sub54(HelDim(3),3), Sub53(HelDim(3),3)
        HelType Sub43(HelDim(3),3), Sub31(HelDim(3),3)
        HelType Sub48(HelDim(3),3), Sub52(HelDim(3),3)
        HelType Sub35(HelDim(3),3), Sub27(HelDim(3),3)
        HelType Sub116(HelDim(4),4), Sub134(HelDim(4),4)
        HelType Sub148(HelDim(4),4), Sub160(HelDim(4),4)
        HelType Sub174(HelDim(4),4), Sub57(HelDim(4),4)
        HelType Sub58(HelDim(4),4), Sub136(HelDim(4),4)
        HelType Sub104(HelDim(4),4), Sub71(HelDim(4),4)
        HelType Sub72(HelDim(4),4), Sub150(HelDim(4),4)
        HelType Sub162(HelDim(4),4), Sub151(HelDim(4),4)
        HelType Sub105(HelDim(4),4), Sub163(HelDim(4),4)
        HelType Sub137(HelDim(4),4), Sub120(HelDim(4),4)
        HelType Sub123(HelDim(4),4), Sub87(HelDim(4),4)
        HelType Sub90(HelDim(4),4), Sub69(HelDim(4),4)
        HelType Sub83(HelDim(4),4), Sub102(HelDim(4),4)
        HelType Sub110(HelDim(3),4,4)
        HelType Sub115(HelDim(3),4,4)
        HelType Sub168(HelDim(3),4,4)
        HelType Sub173(HelDim(3),4,4)
        HelType Sub195(HelDim(3),4,2)
        HelType Sub39(HelDim(3),4,2)
        HelType Sub280(HelDim(3),4,2)
        HelType Sub275(HelDim(3),4,2)
        HelType Sub29(HelDim(3),4,2)
        HelType Sub176(HelDim(3),4,2)
        HelType Sub128(HelDim(3),4,4)
        HelType Sub133(HelDim(3),4,4)
        HelType Sub96(HelDim(3),4,4)
        HelType Sub101(HelDim(3),4,4)
        HelType Sub46(HelDim(3),4,2)
        HelType Sub205(HelDim(3),4,2)
        HelType Sub243(HelDim(3),4,2)
        HelType Sub311(HelDim(3),4,2)
        HelType Sub33(HelDim(3),4,2)
        HelType Sub238(HelDim(3),4,2)
        HelType Sub185(HelDim(3),4,2)
        HelType Sub296(HelDim(3),4,2)
        HelType Sub63(HelDim(3),4,4)
        HelType Sub68(HelDim(3),4,4)
        HelType Sub77(HelDim(3),4,4)
        HelType Sub82(HelDim(3),4,4)
        HelType Sub226(HelDim(3),4,2)
        HelType Sub5(HelDim(3),4,2)
        HelType Sub264(HelDim(3),4,2)
        HelType Sub231(HelDim(3),4,2)
        HelType Sub269(HelDim(3),4,2)
        HelType Sub272(HelDim(3),4,2)
        HelType Sub304(HelDim(3),4,2)
        HelType Sub42(HelDim(3),4,2)
        HelType Sub285(HelDim(3),4,2)
        HelType Sub219(HelDim(3),4,2)
        HelType Sub20(HelDim(3),4,2)
        HelType Sub143(HelDim(3),4,4)
        HelType Sub147(HelDim(3),4,4)
        HelType Sub155(HelDim(3),4,4)
        HelType Sub159(HelDim(3),4,4)
        HelType Sub17(HelDim(3),4,2)
        HelType Sub233(HelDim(3),4,2)
        HelType Sub254(HelDim(3),4,2)
        HelType Sub236(HelDim(3),4,2)
        HelType Sub237(HelDim(3),4,2)
        HelType Sub257(HelDim(3),4,2)
        HelType Sub258(HelDim(3),4,2)
        HelType Sub336(HelDim(3),4,2)
        HelType Sub263(HelDim(3),4,2)
        HelType Sub51(HelDim(3),4,2)
        HelType Sub259(HelDim(3),4,2)
        HelType Sub224(HelDim(3),4,2)
        HelType Sub262(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub21(HelDim(3),3,2,2)
        HelType Sub11(HelDim(3),3,2,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub23(HelDim(3),3,2,2)
        HelType Sub347(HelDim(3),3,2,2)
        HelType Sub345(HelDim(3),3,2,2)
        HelType Sub299(HelDim(3),3,2,2)
        HelType Sub314(HelDim(3),3,2,2)
        HelType Sub323(HelDim(3),3,2,2)
        HelType Sub337(HelDim(3),3,2,2)
        HelType Sub320(HelDim(3),3,2,2)
        HelType Sub307(HelDim(3),3,2,2)
        HelType Sub319(HelDim(3),3,2,2)
        HelType Sub288(HelDim(3),4,4,2)
        HelType Sub291(HelDim(3),4,4,2)
        HelType Sub328(HelDim(3),3,2,2)
        HelType Sub341(HelDim(3),3,2,2)
        HelType Sub329(HelDim(3),3,2,2)
        HelType Sub331(HelDim(3),3,2,2)
        HelType Sub343(HelDim(3),3,2,2)
        HelType Sub284(HelDim(3),3,3,4,2)
        HelType Sub283(HelDim(3),3,3,4,2)
        HelType Sub248(HelDim(3),3,3,4,2)
        HelType Sub251(HelDim(3),3,3,4,2)
        HelType Sub399(HelDim(3),3,3,4,2)
        HelType Sub242(HelDim(3),3,3,4,2)
        HelType Sub279(HelDim(3),3,3,4,2)
        HelType Sub278(HelDim(3),3,3,4,2)
        HelType Sub241(HelDim(3),3,3,4,2)
        HelType Sub199(HelDim(3),3,3,4,2)
        HelType Sub202(HelDim(3),3,3,4,2)
        HelType Sub209(HelDim(3),3,3,4,2)
        HelType Sub212(HelDim(3),3,3,4,2)
        HelType Sub228(HelDim(3),3,4,4,2)
        HelType Sub232(HelDim(3),3,4,4,2)
        HelType Sub220(HelDim(3),3,4,4,2)
        HelType Sub216(HelDim(3),3,4,4,2)
        HelType Sub225(HelDim(3),3,4,4,2)
        HelType Sub221(HelDim(3),3,4,4,2)
        HelType Sub274(HelDim(3),3,4,4,2)
        HelType Sub266(HelDim(3),3,4,4,2)
        HelType Sub273(HelDim(3),3,4,4,2)
        HelType Sub292(HelDim(3),3,4,4,2)
        HelType Sub293(HelDim(3),3,4,4,2)
        HelType Sub245(HelDim(3),3,4,4,2)
        HelType Sub377(HelDim(3),3,3,3,4,4)
        HelType Sub383(HelDim(3),3,3,3,4,4)
        HelType Sub382(HelDim(3),3,3,3,4,4)
        HelType Sub386(HelDim(3),3,3,3,4,4)
        HelType Sub387(HelDim(3),3,3,3,4,4)
        HelType Sub388(HelDim(3),3,3,3,4,4)
        HelType Sub381(HelDim(3),3,3,3,4,4)
        HelType Sub385(HelDim(3),3,3,3,4,4)
        HelType Sub325(HelDim(3),3,4,4,2,2)
        HelType Sub316(HelDim(3),3,4,4,2,2)
        HelType Sub322(HelDim(3),3,4,4,2,2), Sub61
        HelType Sub59, Sub78, Sub64, Sub66, Sub80, Sub73, Sub118
        HelType Sub152, Sub156, Sub138, Sub144, Sub339(HelDim(3))
        HelType Sub340(HelDim(3)), Sub60(HelDim(3))
        HelType Sub62(HelDim(3)), Sub65(HelDim(3))
        HelType Sub67(HelDim(3)), Sub74(HelDim(3))
        HelType Sub76(HelDim(3)), Sub81(HelDim(3))
        HelType Sub79(HelDim(3)), Sub327(HelDim(3))
        HelType Sub326(HelDim(3)), Sub313(HelDim(3))
        HelType Sub298(HelDim(3)), Sub312(HelDim(3))
        HelType Sub297(HelDim(3)), Sub318(HelDim(3))
        HelType Sub306(HelDim(3)), Sub317(HelDim(3))
        HelType Sub305(HelDim(3)), Sub229(HelDim(4))
        HelType Sub230(HelDim(4)), Sub267(HelDim(4))
        HelType Sub234(HelDim(4)), Sub255(HelDim(4))
        HelType Sub235(HelDim(4)), Sub256(HelDim(4))
        HelType Sub271(HelDim(4)), Sub217(HelDim(4))
        HelType Sub218(HelDim(4)), Sub286(HelDim(4))
        HelType Sub287(HelDim(4)), Sub222(HelDim(4))
        HelType Sub260(HelDim(4)), Sub223(HelDim(4))
        HelType Sub261(HelDim(4)), Sub290(HelDim(4))
        HelType Sub289(HelDim(4)), Sub94(HelDim(4),4)
        HelType Sub107(HelDim(3),4,4)
        HelType Sub114(HelDim(3),4,4)
        HelType Sub165(HelDim(3),4,4)
        HelType Sub172(HelDim(3),4,4)
        HelType Sub112(HelDim(3),4,4)
        HelType Sub170(HelDim(3),4,4)
        HelType Sub117(HelDim(3),4,4)
        HelType Sub175(HelDim(3),4,4)
        HelType Sub135(HelDim(3),4,4)
        HelType Sub103(HelDim(3),4,4)
        HelType Sub140(HelDim(3),4,4)
        HelType Sub145(HelDim(3),4,4)
        HelType Sub153(HelDim(3),4,4)
        HelType Sub157(HelDim(3),4,4)
        HelType Sub12(HelDim(3),3,2,2)
        HelType Sub22(HelDim(3),3,2,2)
        HelType Sub24(HelDim(3),3,2,2)
        HelType Sub10(HelDim(3),3,2,2)
        HelType Sub70(HelDim(3),3,4,4)
        HelType Sub346(HelDim(3),3,2,2)
        HelType Sub348(HelDim(3),3,2,2)
        HelType Sub161(HelDim(3),3,4,4)
        HelType Sub300(HelDim(3),3,2,2)
        HelType Sub315(HelDim(3),3,2,2)
        HelType Sub84(HelDim(3),3,4,4)
        HelType Sub324(HelDim(3),3,2,2)
        HelType Sub338(HelDim(3),3,2,2)
        HelType Sub149(HelDim(3),3,4,4)
        HelType Sub308(HelDim(3),3,2,2)
        HelType Sub342(HelDim(3),3,2,2)
        HelType Sub332(HelDim(3),3,2,2)
        HelType Sub344(HelDim(3),3,2,2), Sub75
        HelType Sub127(HelDim(3),4,4)
        HelType Sub95(HelDim(3),4,4)
        HelType Sub100(HelDim(3),4,4), Sub206(HelDim(3))
        HelType Sub186(HelDim(3)), Sub196(HelDim(3))
        HelType Sub139(HelDim(4),4)
        HelType Sub109(HelDim(3),4,4)
        HelType Sub167(HelDim(3),4,4)
        HelType Sub132(HelDim(3),4,4)
        HelType Sub92(HelDim(3),4,4)
        HelType Sub98(HelDim(3),4,4)
        HelType Sub201(HelDim(3),3,3,4)
        HelType Sub197(HelDim(3),3,3,4)
        HelType Sub207(HelDim(3),3,3,4)
        HelType Sub187(HelDim(3),3,3,4)
        HelType Sub191(HelDim(3),3,3,4)
        HelType Sub281(HelDim(3),3,3)
        HelType Sub282(HelDim(3),3,3)
        HelType Sub246(HelDim(3),3,3)
        HelType Sub250(HelDim(3),3,3)
        HelType Sub239(HelDim(3),3,3)
        HelType Sub276(HelDim(3),3,3)
        HelType Sub240(HelDim(3),3,3)
        HelType Sub277(HelDim(3),3,3)
        HelType Sub125(HelDim(3),4,4)
        HelType Sub129(HelDim(3),4,4)
        HelType Sub142(HelDim(3),4,4)
        HelType Sub188(HelDim(3),3,3,4)
        HelType Sub146(HelDim(3),4,4)
        HelType Sub181(HelDim(3),3,3,4)
        HelType Sub177(HelDim(3),3,3,4)
        HelType Sub190(HelDim(3),3,3,4)
        HelType Sub154(HelDim(3),4,4)
        HelType Sub158(HelDim(3),4,4)
        HelType Sub198(HelDim(3),3,3,4)
        HelType Sub180(HelDim(3),3,3,4)
        HelType Sub178(HelDim(3),3,3,4)
        HelType Sub200(HelDim(3),3,3,4)
        HelType Sub211(HelDim(3),3,3,4)
        HelType Sub210(HelDim(3),3,3,4)
        HelType Sub208(HelDim(3),3,3,4)
        common /varXh/ F29, F56, F91, F61, F26, F18, F42, F92, F64
        common /varXh/ F21, F27, F6, F23, F87, F45, F59, F22, F3
        common /varXh/ F30, F88, F55, F57, F74, F24, F17, F73, F19
        common /varXh/ F28, F139, F121, F1, F11, F144, F122, F5, F14
        common /varXh/ F155, F93, F156, F94, F49, F20, F65, F12, F2
        common /varXh/ F31, F25, F66, F13, F4, F82, F153, F44, F81
        common /varXh/ F154, F54, F58, F99, F62, F60, F100, F63
        common /varXh/ F111, F112, F137, F89, F47, F83, F50, F48
        common /varXh/ F80, F84, F51, F97, F138, F90, F40, F85, F36
        common /varXh/ F41, F77, F86, F37, F98, F101, F95, F38, F9
        common /varXh/ F71, F32, F39, F15, F72, F33, F10, F102, F96
        common /varXh/ F52, F7, F67, F34, F53, F16, F68, F35, F8
        common /varXh/ F123, F131, F124, F145, F151, F146, F147
        common /varXh/ F125, F132, F126, F127, F133, F128, F148
        common /varXh/ F152, F149, F150, F129, F134, F130, F103, F76
        common /varXh/ F117, F104, F140, F69, F141, F157, F75, F105
        common /varXh/ F118, F106, F43, F107, F78, F119, F108, F142
        common /varXh/ F70, F143, F158, F79, F109, F120, F110, F46
        common /varXh/ F115, F136, F116, F113, F135, F114, Sub124
        common /varXh/ Sub93, Sub97, Sub130, Sub121, Sub85, Sub99
        common /varXh/ Sub86, Sub119, Sub89, Sub91, Sub88, Sub111
        common /varXh/ Sub169, Sub108, Sub166, Sub131, Sub106
        common /varXh/ Sub164, Sub171, Sub113, Sub126, Sub122
        common /varXh/ Sub141, Sub54, Sub53, Sub43, Sub31, Sub48
        common /varXh/ Sub52, Sub35, Sub27, Sub116, Sub134, Sub148
        common /varXh/ Sub160, Sub174, Sub57, Sub58, Sub136, Sub104
        common /varXh/ Sub71, Sub72, Sub150, Sub162, Sub151, Sub105
        common /varXh/ Sub163, Sub137, Sub120, Sub123, Sub87, Sub90
        common /varXh/ Sub69, Sub83, Sub102, Sub110, Sub115, Sub168
        common /varXh/ Sub173, Sub195, Sub39, Sub280, Sub275, Sub29
        common /varXh/ Sub176, Sub128, Sub133, Sub96, Sub101, Sub46
        common /varXh/ Sub205, Sub243, Sub311, Sub33, Sub238, Sub185
        common /varXh/ Sub296, Sub63, Sub68, Sub77, Sub82, Sub226
        common /varXh/ Sub5, Sub264, Sub231, Sub269, Sub272, Sub304
        common /varXh/ Sub42, Sub285, Sub219, Sub20, Sub143, Sub147
        common /varXh/ Sub155, Sub159, Sub17, Sub233, Sub254, Sub236
        common /varXh/ Sub237, Sub257, Sub258, Sub336, Sub263, Sub51
        common /varXh/ Sub259, Sub224, Sub262, Sub8, Sub21, Sub11
        common /varXh/ Sub9, Sub23, Sub347, Sub345, Sub299, Sub314
        common /varXh/ Sub323, Sub337, Sub320, Sub307, Sub319
        common /varXh/ Sub288, Sub291, Sub328, Sub341, Sub329
        common /varXh/ Sub331, Sub343, Sub284, Sub283, Sub248
        common /varXh/ Sub251, Sub399, Sub242, Sub279, Sub278
        common /varXh/ Sub241, Sub199, Sub202, Sub209, Sub212
        common /varXh/ Sub228, Sub232, Sub220, Sub216, Sub225
        common /varXh/ Sub221, Sub274, Sub266, Sub273, Sub292
        common /varXh/ Sub293, Sub245, Sub377, Sub383, Sub382
        common /varXh/ Sub386, Sub387, Sub388, Sub381, Sub385
        common /varXh/ Sub325, Sub316, Sub322, Sub61, Sub59, Sub78
        common /varXh/ Sub64, Sub66, Sub80, Sub73, Sub118, Sub152
        common /varXh/ Sub156, Sub138, Sub144, Sub339, Sub340, Sub60
        common /varXh/ Sub62, Sub65, Sub67, Sub74, Sub76, Sub81
        common /varXh/ Sub79, Sub327, Sub326, Sub313, Sub298, Sub312
        common /varXh/ Sub297, Sub318, Sub306, Sub317, Sub305
        common /varXh/ Sub229, Sub230, Sub267, Sub234, Sub255
        common /varXh/ Sub235, Sub256, Sub271, Sub217, Sub218
        common /varXh/ Sub286, Sub287, Sub222, Sub260, Sub223
        common /varXh/ Sub261, Sub290, Sub289, Sub94, Sub107, Sub114
        common /varXh/ Sub165, Sub172, Sub112, Sub170, Sub117
        common /varXh/ Sub175, Sub135, Sub103, Sub140, Sub145
        common /varXh/ Sub153, Sub157, Sub12, Sub22, Sub24, Sub10
        common /varXh/ Sub70, Sub346, Sub348, Sub161, Sub300, Sub315
        common /varXh/ Sub84, Sub324, Sub338, Sub149, Sub308, Sub342
        common /varXh/ Sub332, Sub344, Sub75, Sub127, Sub95, Sub100
        common /varXh/ Sub206, Sub186, Sub196, Sub139, Sub109
        common /varXh/ Sub167, Sub132, Sub92, Sub98, Sub201, Sub197
        common /varXh/ Sub207, Sub187, Sub191, Sub281, Sub282
        common /varXh/ Sub246, Sub250, Sub239, Sub276, Sub240
        common /varXh/ Sub277, Sub125, Sub129, Sub142, Sub188
        common /varXh/ Sub146, Sub181, Sub177, Sub190, Sub154
        common /varXh/ Sub158, Sub198, Sub180, Sub178, Sub200
        common /varXh/ Sub211, Sub210, Sub208

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7, Sfe8
        common /indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqubar_nInJqubarqubar_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
