#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 23-Oct-2017 10:44
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Opt1(3,3,3,3), Sub1(4)
        ComplexType Sub2(3,4,2), Sub3(3,4,2)
        ComplexType Sub6(2,3,2), Sub147(3,2)
        ComplexType Sub149(3,2), Sub151(3,2)
        ComplexType Sub152(3,2)
        common /quqdbar_nIxJququbar_3546_Sq1Sq2_varXs/ Opt1, Sub1, Sub2, Sub3, Sub6, Sub147, Sub149
        common /quqdbar_nIxJququbar_3546_Sq1Sq2_varXs/ Sub151, Sub152

        ComplexType Sub146(3,3,4)
        ComplexType Sub148(2,3,3,3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /quqdbar_nIxJququbar_3546_Sq1Sq2_varXa/ Sub146, Sub148, S, T, T14, T15, U, T24, T25
        common /quqdbar_nIxJququbar_3546_Sq1Sq2_varXa/ S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10
        HelType Sub4(HelDim(3),4,2)
        HelType Sub5(HelDim(3),3,2,2)
        HelType Sub7(HelDim(3),3,2,2)
        HelType Sub8(HelDim(2),3,3,2)
        common /quqdbar_nIxJququbar_3546_Sq1Sq2_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, Sub4
        common /quqdbar_nIxJququbar_3546_Sq1Sq2_varXh/ Sub5, Sub7, Sub8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /quqdbar_nIxJququbar_3546_Sq1Sq2_formfactors/ Ctree, MatSUN

#endif

