#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 26-Sep-2016 14:14
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub65(4), Sub1(4), Sub12(4), Sub35(4)
        ComplexType Sub15(4), Sub6(4), Sub206(3,2)
        ComplexType Sub210(3,2), Sub214(3,2), Sub218(3,2)
        ComplexType Sub216(3,2), Sub219(3,2), Sub208(3,2)
        ComplexType Sub211(3,2), Sub230(3,2), Sub234(3,2)
        ComplexType Sub40(4,4), Sub42(4,4)
        ComplexType Sub28(3,4,2), Sub30(3,4,2)
        ComplexType Sub29(3,4,2), Sub21(3,4,2)
        ComplexType Sub24(3,4,2), Sub23(3,4,2)
        ComplexType Sub66(3,4,2), Sub67(3,4,2)
        ComplexType Sub181(3,4,2), Sub182(3,4,2)
        ComplexType Sub36(3,4,2), Sub37(3,4,2)
        ComplexType Sub174(3,4,2), Sub175(3,4,2)
        ComplexType Sub2(3,4,2), Sub3(3,4,2)
        ComplexType Sub26(3,4,2), Sub32(3,4,2)
        ComplexType Sub16(3,4,2), Sub17(3,4,2)
        ComplexType Sub11(3,4,2), Sub13(3,4,2)
        ComplexType Sub194(3,4,2), Sub195(3,4,2)
        ComplexType Sub69(3,4,2), Sub70(3,4,2)
        ComplexType Sub5(3,4,2), Sub7(3,4,2)
        common /varXs/ Sub65, Sub1, Sub12, Sub35, Sub15, Sub6, Sub206
        common /varXs/ Sub210, Sub214, Sub218, Sub216, Sub219
        common /varXs/ Sub208, Sub211, Sub230, Sub234, Sub40, Sub42
        common /varXs/ Sub28, Sub30, Sub29, Sub21, Sub24, Sub23
        common /varXs/ Sub66, Sub67, Sub181, Sub182, Sub36, Sub37
        common /varXs/ Sub174, Sub175, Sub2, Sub3, Sub26, Sub32
        common /varXs/ Sub16, Sub17, Sub11, Sub13, Sub194, Sub195
        common /varXs/ Sub69, Sub70, Sub5, Sub7

        ComplexType Opt2(3,3,3,3), Opt3(3,4,4)
        ComplexType Sub222(3,3,3), Sub205(3,3,4)
        ComplexType Sub213(3,3,4), Sub226(3,4,4)
        ComplexType Sub207(3,3,3,3,4,4)
        ComplexType Sub215(3,3,3,3,4,4)
        ComplexType Sub224(3,3,3,3,4,4)
        ComplexType Sub221(3,3,3,3,4,4)
        ComplexType Sub225(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt2, Opt3, Sub222, Sub205, Sub213, Sub226
        common /varXa/ Sub207, Sub215, Sub224, Sub221, Sub225, S, T
        common /varXa/ T14, T15, U, T24, T25, S34, S35, S45

        HelType F58, F55, F3, F27, F75, F23, F65, F6, F26, F77, F32
        HelType F67, F17, F53, F24, F30, F56, F18, F109, F99, F127
        HelType F11, F110, F100, F128, F14, F125, F126, F21, F19
        HelType F34, F57, F1, F33, F25, F36, F54, F5, F20, F66, F112
        HelType F2, F12, F31, F28, F68, F111, F4, F13, F29, F35, F46
        HelType F114, F37, F22, F116, F78, F76, F117, F91, F7, F40
        HelType F60, F15, F41, F61, F8, F115, F92, F9, F51, F62, F16
        HelType F52, F63, F10, F101, F129, F130, F102, F131, F103
        HelType F132, F104, F105, F133, F134, F106, F135, F107, F136
        HelType F108, F59, F83, F137, F71, F138, F84, F139, F85, F93
        HelType F86, F44, F64, F87, F140, F72, F141, F88, F142, F89
        HelType F95, F90, F45, F113, F49, F123, F50, F47, F69, F143
        HelType F118, F48, F70, F120, F96, F121, F38, F124, F39, F42
        HelType F73, F144, F119, F43, F74, F122, F94, F79, F97, F80
        HelType F81, F98, F82, Sub47, Sub56, Sub44, Sub50, Sub51
        HelType Sub52, Sub41, Sub59, Sub45, Sub58, Sub55, Sub106
        HelType Sub73, Sub72, Sub75, Sub76, Sub86, Sub87, Sub90
        HelType Sub89, Sub95, Sub48(HelDim(3))
        HelType Sub64(HelDim(3),3), Sub34(HelDim(3),3)
        HelType Sub27(HelDim(3),3), Sub22(HelDim(3),3)
        HelType Sub144(HelDim(3),3), Sub147(HelDim(3),3)
        HelType Sub121(HelDim(3),4), Sub122(HelDim(3),4)
        HelType Sub127(HelDim(3),4), Sub126(HelDim(3),4)
        HelType Sub116(HelDim(4),4), Sub101(HelDim(4),4)
        HelType Sub102(HelDim(4),4), Sub43(HelDim(4),4)
        HelType Sub46(HelDim(4),4), Sub74(HelDim(4),4)
        HelType Sub77(HelDim(4),4), Sub88(HelDim(4),4)
        HelType Sub91(HelDim(4),4), Sub62(HelDim(4),4)
        HelType Sub84(HelDim(4),4), Sub99(HelDim(4),4)
        HelType Sub80(HelDim(3),4,4)
        HelType Sub83(HelDim(3),4,4)
        HelType Sub31(HelDim(3),4,2)
        HelType Sub118(HelDim(3),4,2)
        HelType Sub25(HelDim(3),4,2)
        HelType Sub125(HelDim(3),4,2)
        HelType Sub94(HelDim(3),4,4)
        HelType Sub98(HelDim(3),4,4)
        HelType Sub68(HelDim(3),4,2)
        HelType Sub159(HelDim(3),4,2)
        HelType Sub183(HelDim(3),4,2)
        HelType Sub154(HelDim(3),4,2)
        HelType Sub38(HelDim(3),4,2)
        HelType Sub176(HelDim(3),4,2)
        HelType Sub139(HelDim(3),4,2)
        HelType Sub4(HelDim(3),4,2)
        HelType Sub33(HelDim(3),4,2)
        HelType Sub130(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub108(HelDim(3),4,4)
        HelType Sub115(HelDim(3),4,4)
        HelType Sub14(HelDim(3),4,2)
        HelType Sub164(HelDim(3),4,2)
        HelType Sub167(HelDim(3),4,2)
        HelType Sub168(HelDim(3),4,2)
        HelType Sub196(HelDim(3),4,2)
        HelType Sub173(HelDim(3),4,2)
        HelType Sub71(HelDim(3),4,2)
        HelType Sub169(HelDim(3),4,2)
        HelType Sub172(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub19(HelDim(3),3,2,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub123(HelDim(3),3,4,2)
        HelType Sub129(HelDim(3),3,4,2)
        HelType Sub128(HelDim(3),3,4,2)
        HelType Sub179(HelDim(3),3,2,2)
        HelType Sub186(HelDim(3),3,2,2)
        HelType Sub133(HelDim(3),4,4,2)
        HelType Sub136(HelDim(3),4,4,2)
        HelType Sub190(HelDim(3),3,2,2)
        HelType Sub199(HelDim(3),3,2,2)
        HelType Sub54(HelDim(3),3,4,4)
        HelType Sub61(HelDim(3),3,4,4)
        HelType Sub146(HelDim(3),3,4,2)
        HelType Sub151(HelDim(3),3,4,2)
        HelType Sub192(HelDim(3),3,2,2)
        HelType Sub203(HelDim(3),3,2,2)
        HelType Sub163(HelDim(3),3,3,4,2)
        HelType Sub162(HelDim(3),3,3,4,2)
        HelType Sub158(HelDim(3),3,3,4,2)
        HelType Sub157(HelDim(3),3,3,4,2)
        HelType Sub141(HelDim(3),3,4,4,2)
        HelType Sub138(HelDim(3),3,4,4,2)
        HelType Sub120(HelDim(3),3,4,4,2)
        HelType Sub137(HelDim(3),3,4,4,2)
        HelType Sub223(HelDim(3),3,3,3,4,4)
        HelType Sub228(HelDim(3),3,3,3,4,4)
        HelType Sub227(HelDim(3),3,3,3,4,4)
        HelType Sub153(HelDim(3),3,3,4,4,2)
        HelType Sub229(HelDim(3),3,3,4,4,2)
        HelType Sub152(HelDim(3),3,3,4,4,2)
        HelType Sub124(HelDim(3),3,3,4,4,2)
        HelType Sub241(HelDim(3),3,3,4,2,2), Sub39
        HelType Sub112, Sub109, Sub103, Sub198(HelDim(3))
        HelType Sub189(HelDim(3)), Sub197(HelDim(3))
        HelType Sub188(HelDim(3)), Sub202(HelDim(3))
        HelType Sub201(HelDim(3)), Sub178(HelDim(3))
        HelType Sub185(HelDim(3)), Sub177(HelDim(3))
        HelType Sub184(HelDim(3)), Sub165(HelDim(4))
        HelType Sub166(HelDim(4)), Sub170(HelDim(4))
        HelType Sub171(HelDim(4)), Sub85(HelDim(3),4,4)
        HelType Sub100(HelDim(3),4,4)
        HelType Sub111(HelDim(3),4,4)
        HelType Sub114(HelDim(3),4,4)
        HelType Sub20(HelDim(3),3,2,2)
        HelType Sub10(HelDim(3),3,2,2)
        HelType Sub180(HelDim(3),3,2,2)
        HelType Sub187(HelDim(3),3,2,2)
        HelType Sub191(HelDim(3),3,2,2)
        HelType Sub200(HelDim(3),3,2,2)
        HelType Sub117(HelDim(3),3,4,4)
        HelType Sub193(HelDim(3),3,2,2)
        HelType Sub204(HelDim(3),3,2,2)
        HelType Sub63(HelDim(3),3,3,4,4)
        HelType Sub104(HelDim(4)), Sub135(HelDim(4))
        HelType Sub131(HelDim(4)), Sub149(HelDim(3),3)
        HelType Sub142(HelDim(3),3)
        HelType Sub143(HelDim(3),3,4)
        HelType Sub150(HelDim(3),3,4)
        HelType Sub105(HelDim(3),4,4), Sub134(HelDim(4))
        HelType Sub132(HelDim(4)), Sub113(HelDim(4),4)
        HelType Sub110(HelDim(4),4)
        HelType Sub96(HelDim(3),4,4)
        HelType Sub49(HelDim(3),3,4,4)
        HelType Sub79(HelDim(3),4), Sub81(HelDim(3),4)
        HelType Sub78(HelDim(3),4), Sub82(HelDim(3),4)
        HelType Sub156(HelDim(3),3,3)
        HelType Sub161(HelDim(3),3,3)
        HelType Sub155(HelDim(3),3,3)
        HelType Sub160(HelDim(3),3,3)
        HelType Sub93(HelDim(3),4,4)
        HelType Sub92(HelDim(3),4,4)
        HelType Sub145(HelDim(3),3,4)
        HelType Sub107(HelDim(3),4,4)
        HelType Sub53(HelDim(3),3,4,4)
        HelType Sub57(HelDim(3),3,4,4)
        HelType Sub97(HelDim(3),4,4)
        HelType Sub148(HelDim(3),3,4)
        HelType Sub60(HelDim(3),3,4,4)
        common /varXh/ F58, F55, F3, F27, F75, F23, F65, F6, F26, F77
        common /varXh/ F32, F67, F17, F53, F24, F30, F56, F18, F109
        common /varXh/ F99, F127, F11, F110, F100, F128, F14, F125
        common /varXh/ F126, F21, F19, F34, F57, F1, F33, F25, F36
        common /varXh/ F54, F5, F20, F66, F112, F2, F12, F31, F28
        common /varXh/ F68, F111, F4, F13, F29, F35, F46, F114, F37
        common /varXh/ F22, F116, F78, F76, F117, F91, F7, F40, F60
        common /varXh/ F15, F41, F61, F8, F115, F92, F9, F51, F62
        common /varXh/ F16, F52, F63, F10, F101, F129, F130, F102
        common /varXh/ F131, F103, F132, F104, F105, F133, F134
        common /varXh/ F106, F135, F107, F136, F108, F59, F83, F137
        common /varXh/ F71, F138, F84, F139, F85, F93, F86, F44, F64
        common /varXh/ F87, F140, F72, F141, F88, F142, F89, F95
        common /varXh/ F90, F45, F113, F49, F123, F50, F47, F69
        common /varXh/ F143, F118, F48, F70, F120, F96, F121, F38
        common /varXh/ F124, F39, F42, F73, F144, F119, F43, F74
        common /varXh/ F122, F94, F79, F97, F80, F81, F98, F82
        common /varXh/ Sub47, Sub56, Sub44, Sub50, Sub51, Sub52
        common /varXh/ Sub41, Sub59, Sub45, Sub58, Sub55, Sub106
        common /varXh/ Sub73, Sub72, Sub75, Sub76, Sub86, Sub87
        common /varXh/ Sub90, Sub89, Sub95, Sub48, Sub64, Sub34
        common /varXh/ Sub27, Sub22, Sub144, Sub147, Sub121, Sub122
        common /varXh/ Sub127, Sub126, Sub116, Sub101, Sub102, Sub43
        common /varXh/ Sub46, Sub74, Sub77, Sub88, Sub91, Sub62
        common /varXh/ Sub84, Sub99, Sub80, Sub83, Sub31, Sub118
        common /varXh/ Sub25, Sub125, Sub94, Sub98, Sub68, Sub159
        common /varXh/ Sub183, Sub154, Sub38, Sub176, Sub139, Sub4
        common /varXh/ Sub33, Sub130, Sub18, Sub108, Sub115, Sub14
        common /varXh/ Sub164, Sub167, Sub168, Sub196, Sub173, Sub71
        common /varXh/ Sub169, Sub172, Sub8, Sub19, Sub9, Sub123
        common /varXh/ Sub129, Sub128, Sub179, Sub186, Sub133
        common /varXh/ Sub136, Sub190, Sub199, Sub54, Sub61, Sub146
        common /varXh/ Sub151, Sub192, Sub203, Sub163, Sub162
        common /varXh/ Sub158, Sub157, Sub141, Sub138, Sub120
        common /varXh/ Sub137, Sub223, Sub228, Sub227, Sub153
        common /varXh/ Sub229, Sub152, Sub124, Sub241, Sub39, Sub112
        common /varXh/ Sub109, Sub103, Sub198, Sub189, Sub197
        common /varXh/ Sub188, Sub202, Sub201, Sub178, Sub185
        common /varXh/ Sub177, Sub184, Sub165, Sub166, Sub170
        common /varXh/ Sub171, Sub85, Sub100, Sub111, Sub114, Sub20
        common /varXh/ Sub10, Sub180, Sub187, Sub191, Sub200, Sub117
        common /varXh/ Sub193, Sub204, Sub63, Sub104, Sub135, Sub131
        common /varXh/ Sub149, Sub142, Sub143, Sub150, Sub105
        common /varXh/ Sub134, Sub132, Sub113, Sub110, Sub96, Sub49
        common /varXh/ Sub79, Sub81, Sub78, Sub82, Sub156, Sub161
        common /varXh/ Sub155, Sub160, Sub93, Sub92, Sub145, Sub107
        common /varXh/ Sub53, Sub57, Sub97, Sub148, Sub60

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7, Sfe8
        common /indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /quqdbar_nInJquqdbar_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
