#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 9-Mar-2017 14:32
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub9(3,4,2), Sub10(4)
        ComplexType Sub11(3,4,2), Sub13(4)
        ComplexType Sub14(3,4,2), Sub15(3,4,2)
        ComplexType Sub174(3,2), Sub176(3,2)
        ComplexType Sub178(3,2), Sub179(3,2)
        common /ququbar_nInJqdqdbar_3645_Sq1Sq2_varXs/ Sub9, Sub10, Sub11, Sub13, Sub14, Sub15
        common /ququbar_nInJqdqdbar_3645_Sq1Sq2_varXs/ Sub174, Sub176, Sub178, Sub179

        ComplexType Opt3(3,3,3,3)
        ComplexType Sub181(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /ququbar_nInJqdqdbar_3645_Sq1Sq2_varXa/ Opt3, Sub181, S, T, T14, T15, U, T24, T25, S34
        common /ququbar_nInJqdqdbar_3645_Sq1Sq2_varXa/ S35, S45

        HelType F6, F8, F9, F10, F11, F12, F13, F14
        HelType Sub12(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        common /ququbar_nInJqdqdbar_3645_Sq1Sq2_varXh/ F6, F8, F9, F10, F11, F12, F13, F14, Sub12
        common /ququbar_nInJqdqdbar_3645_Sq1Sq2_varXh/ Sub16

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /ququbar_nInJqdqdbar_3645_Sq1Sq2_formfactors/ Ctree, MatSUN

#endif

