#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 9-Mar-2017 14:32
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub1(4), Sub15(4), Sub16(3,4,2)
        ComplexType Sub17(3,4,2), Sub29(3,4,2)
        ComplexType Sub30(3,4,2), Sub31(3,4,2)
        ComplexType Sub35(3,4,2), Sub36(3,4,2)
        ComplexType Sub328(3,2), Sub334(3,2)
        common /ququbar_nInJqubarqu_365_Sq1_varXs/ Sub1, Sub15, Sub16, Sub17, Sub29, Sub30, Sub31
        common /ququbar_nInJqubarqu_365_Sq1_varXs/ Sub35, Sub36, Sub328, Sub334

        ComplexType Opt6(3,3,3,3)
        ComplexType Sub340(3,3,3,3,4,4)
        ComplexType Sub350(3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /ququbar_nInJqubarqu_365_Sq1_varXa/ Opt6, Sub340, Sub350, S, T, T14, T15, U, T24
        common /ququbar_nInJqubarqu_365_Sq1_varXa/ T25, S34, S35, S45

        HelType F12, F14, F18, F19, F26, F27, F33, F34, F35, F36, F37
        HelType F38, F39, F40, F41, F42, F43, F44
        HelType Sub18(HelDim(3),4,2)
        HelType Sub40(HelDim(3),3,4,4,2,2)
        HelType Sub41(HelDim(3),3,2,2)
        HelType Sub42(HelDim(3),3,2,2)
        HelType Sub43(HelDim(3),3,4,4,2,2)
        HelType Sub44(HelDim(3),3,2,2)
        HelType Sub45(HelDim(3),3,2,2)
        common /ququbar_nInJqubarqu_365_Sq1_varXh/ F12, F14, F18, F19, F26, F27, F33, F34, F35
        common /ququbar_nInJqubarqu_365_Sq1_varXh/ F36, F37, F38, F39, F40, F41, F42, F43, F44
        common /ququbar_nInJqubarqu_365_Sq1_varXh/ Sub18, Sub40, Sub41, Sub42, Sub43, Sub44
        common /ququbar_nInJqubarqu_365_Sq1_varXh/ Sub45

        integer Sfe8
        common /ququbar_nInJqubarqu_365_Sq1_indices/ Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /ququbar_nInJqubarqu_365_Sq1_formfactors/ Ctree, MatSUN

#endif

