#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 3-Aug-2016 18:36
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub18(4), Sub16(3,4,2)
        ComplexType Sub23(3,4,2), Sub22(3,4,2)
        ComplexType Sub25(3,4,Sfe8), Sub27(3,4,Sfe8)
        ComplexType Sub26(3,4,Sfe8), Sub19(3,4,2)
        ComplexType Sub20(3,4,2)
        common /varXs/ Sub18, Sub16, Sub23, Sub22, Sub25, Sub27
        common /varXs/ Sub26, Sub19, Sub20

        ComplexType Opt3(3,3,3,3)
        ComplexType Opt4(3,3,3,3)
        ComplexType Sub395(3,3,3,3,4,4)
        ComplexType Sub396(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt3, Opt4, Sub395, Sub396, S, T, T14, T15, U
        common /varXa/ T24, T25, S34, S35, S45

        HelType F4, F3, F11, F14, F12, F13, F15, F7, F16, F10
        HelType Sub17(HelDim(3),3)
        HelType Sub24(HelDim(3),4,2)
        HelType Sub28(HelDim(3),4,Sfe8)
        HelType Sub21(HelDim(3),4,2)
        HelType Sub29(HelDim(3),3,2,Sfe8)
        HelType Sub30(HelDim(3),3,2,Sfe8)
        common /varXh/ F4, F3, F11, F14, F12, F13, F15, F7, F16, F10
        common /varXh/ Sub17, Sub24, Sub28, Sub21, Sub29, Sub30

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /ququbar_nInJqubarqu_3645_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
