#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 15-Jul-2016 11:17
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub5, Sub23, Sub119, Sub125, Sub331(2), Sub29(2)
	ComplexType Sub6(2), Sub1(2), Sub24(2), Sub34(2), Sub33(2)
	ComplexType Sub7(2), Sub12(2), Sub11(2), Sub35(2)
	common /varXs/ Sub5, Sub23, Sub119, Sub125, Sub331, Sub29
	common /varXs/ Sub6, Sub1, Sub24, Sub34, Sub33, Sub7, Sub12
	common /varXs/ Sub11, Sub35

	ComplexType Opt1, Opt3, Sub299, Sub147, Sub352, Sub158, Sub18
	ComplexType Sub183, Sub347, Sub322, Sub106, Sub273, Sub323
	ComplexType Sub325, Sub328, Sub202, Sub327, Sub338, Sub332
	RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
	common /varXa/ Opt1, Opt3, Sub299, Sub147, Sub352, Sub158
	common /varXa/ Sub18, Sub183, Sub347, Sub322, Sub106, Sub273
	common /varXa/ Sub323, Sub325, Sub328, Sub202, Sub327
	common /varXa/ Sub338, Sub332, S, T, T14, T15, U, T24, T25
	common /varXa/ S34, S35, S45

	HelType F6, F110, F16, F2, F104, F14, F15, F10, F123, F134
	HelType F1, F51, F7, F53, F32, F8, F176, F27, F37, F9, F178
	HelType F11, F84, F67, F40, F12, F188, F13, F31, F3, F179
	HelType F17, F18, F5, F182, F20, F75, F77, F22, F4, F190
	HelType F25, F111, F114, F151, F115, F117, F152, F99, F60
	HelType F89, F58, F64, F23, F112, F62, F101, F56, F90, F59
	HelType F65, F19, F107, F63, F45, F153, F44, F170, F157
	HelType F158, F33, F36, F71, F167, F69, F171, F159, F160
	HelType F34, F39, F72, F187, F70, F175, F183, F184, F35, F41
	HelType F43, F154, F42, F173, F163, F164, F26, F30, F78
	HelType F168, F79, F174, F165, F166, F28, F21, F81, F189
	HelType F80, F180, F185, F186, F29, F24, F105, F127, F129
	HelType F130, F131, F132, F133, F150, F147, F108, F139, F140
	HelType F141, F142, F143, F144, F148, F149, F97, F120, F121
	HelType F122, F91, F92, F93, F135, F136, F98, F103, F106
	HelType F109, F94, F95, F96, F145, F146, F85, F86, F54, F38
	HelType F177, F49, F82, F83, F87, F88, F76, F61, F46, F47
	HelType F181, F48, F66, F68, F73, F74, F113, F116, F100
	HelType F102, F169, F155, F156, F57, F52, F172, F161, F162
	HelType F55, F50, F124, F125, F137, F138, F118, F119, F126
	HelType F128, Pair1, Pair6, Pair2, Pair7, Pair3, Pair10
	HelType Pair4, Pair8, Pair5, Pair9, Pair11, Abb1, Abb18
	HelType Abb17, Abb2, Abb34, Abb33, Abb26, Abb24, Abb35
	HelType Abb27, Abb25, Abb29, Abb10, Abb28, Abb8, Abb22
	HelType Abb20, Abb4, Abb23, Abb11, Abb19, Abb31, Abb14, Abb7
	HelType Abb12, Abb15, Abb5, Abb13, Abb32, Abb16, Abb9, Abb6
	HelType Abb30, Abb21, Abb3, Opt2, Sub54, Sub57, Sub279
	HelType Sub190, Sub179, Sub195, Sub186, Sub16, Sub20, Sub280
	HelType Sub205, Sub203, Sub109, Sub107, Sub307, Sub293
	HelType Sub315, Sub253, Sub26, Sub229, Sub221, Sub209
	HelType Sub215, Sub8, Sub2, Sub30, Sub132, Sub155, Sub166
	HelType Sub243, Sub175, Sub17, Sub58, Sub55, Sub146, Sub165
	HelType Sub21, Sub61, Sub254, Sub248, Sub260, Sub266, Sub308
	HelType Sub63, Sub60, Sub250, Sub298, Sub259, Sub291, Sub43
	HelType Sub313, Sub36, Sub237, Sub240, Sub306, Sub290
	HelType Sub118, Sub284, Sub130, Sub129, Sub277, Sub136
	HelType Sub225, Sub278, Sub286, Sub289, Sub305, Sub312
	HelType Sub317, Sub137, Sub178, Sub201, Sub234, Sub246
	HelType Sub271, Sub287, Sub321, Sub324, Sub326, Sub329
	HelType Sub127, Sub122, Sub27, Sub223, Sub216, Sub238
	HelType Sub241, Sub102, Sub99, Sub128, Sub121, Sub217
	HelType Sub133, Sub231, Sub116, Sub210, Sub309, Sub235
	HelType Sub244, Sub269, Sub294, Sub316, Sub117, Sub211
	HelType Sub333(HelDim(2)), Sub339(HelDim(2))
	HelType Sub348(HelDim(2)), Sub353(HelDim(2))
	HelType Sub49(HelDim(2)), Sub15(HelDim(2)), Sub72(HelDim(2))
	HelType Sub354(HelDim(2)), Sub53(HelDim(2))
	HelType Sub52(HelDim(2)), Sub78(HelDim(2)), Sub82(HelDim(2))
	HelType Sub67(HelDim(2)), Sub335(HelDim(2))
	HelType Sub350(HelDim(2)), Sub334(HelDim(2))
	HelType Sub345(HelDim(2)), Sub68(HelDim(2))
	HelType Sub105(HelDim(2)), Sub349(HelDim(2))
	HelType Sub341(HelDim(2)), Sub336(HelDim(2))
	HelType Sub48(HelDim(2)), Sub342(HelDim(2))
	HelType Sub351(HelDim(2)), Sub337(HelDim(2))
	HelType Sub357(HelDim(2)), Sub70(HelDim(2))
	HelType Sub41(HelDim(2)), Sub47(HelDim(2))
	HelType Sub361(HelDim(2)), Sub113(HelDim(2))
	HelType Sub343(HelDim(2)), Sub88(HelDim(2))
	HelType Sub344(HelDim(2)), Sub356(HelDim(2))
	HelType Sub83(HelDim(2)), Sub358(HelDim(2)), Sub151, Sub143
	HelType Sub161, Sub164, Sub171, Sub163, Sub174, Sub173
	HelType Sub152, Sub191, Sub138, Sub196, Sub150, Sub139
	HelType Sub220, Sub227, Sub288, Sub296, Sub144, Sub154
	HelType Sub153, Sub140, Sub172, Sub180, Sub160, Sub170
	HelType Sub162, Sub304, Sub207, Sub214, Sub131, Sub114
	HelType Sub126, Sub120, Sub301, Sub272, Sub263, Sub38, Sub42
	HelType Sub262, Sub268, Sub3, Sub31, Sub25, Sub93, Sub228
	HelType Sub208, Sub142, Sub89, Sub9, Sub75, Sub80, Sub181
	HelType Sub86, Sub103, Sub123, Sub124, Sub135, Sub141
	HelType Sub156, Sub167, Sub176, Sub197, Sub264, Sub219
	HelType Sub247, Sub226, Sub257, Sub242, Sub249, Sub255
	HelType Sub261, Sub267, Sub285, Sub297, Sub92, Sub96, Sub100
	HelType Sub330, Sub145, Sub314, Sub91, Sub95, Sub213, Sub115
	HelType Sub222, Sub212, Sub232, Sub251, Sub292, Sub224
	HelType Sub94, Sub90, Sub157, Sub199, Sub168, Sub28, Sub32
	HelType Sub104, Sub101, Sub184, Sub39, Sub44, Sub148, Sub193
	HelType Sub302, Sub319, Sub4, Sub10, Sub233, Sub134
	HelType Sub355(HelDim(2)), Sub340(HelDim(2))
	HelType Sub359(HelDim(2)), Sub65, Sub66, Sub187, Sub311
	HelType Sub69, Sub71, Sub256, Sub198, Sub192, Sub182, Sub188
	HelType Sub236, Sub239, Sub275, Sub282, Sub318, Sub51, Sub50
	HelType Sub74, Sub73, Sub218, Sub97, Sub98, Sub230, Sub14
	HelType Sub13, Sub300, Sub283, Sub245, Sub281, Sub274
	HelType Sub346(HelDim(2)), Sub360(HelDim(2)), Sub40, Sub45
	HelType Sub76, Sub81, Sub85, Sub87, Sub84, Sub303, Sub77
	HelType Sub79, Sub276, Sub320, Sub206, Sub204, Sub112
	HelType Sub108, Sub19, Sub62, Sub200, Sub56, Sub59, Sub22
	HelType Sub252, Sub64, Sub37, Sub46, Sub110, Sub194, Sub310
	HelType Sub111, Sub185, Sub189, Sub149, Sub295, Sub265
	HelType Sub258, Sub177, Sub159, Sub270, Sub169
	common /varXh/ F6, F110, F16, F2, F104, F14, F15, F10, F123
	common /varXh/ F134, F1, F51, F7, F53, F32, F8, F176, F27
	common /varXh/ F37, F9, F178, F11, F84, F67, F40, F12, F188
	common /varXh/ F13, F31, F3, F179, F17, F18, F5, F182, F20
	common /varXh/ F75, F77, F22, F4, F190, F25, F111, F114
	common /varXh/ F151, F115, F117, F152, F99, F60, F89, F58
	common /varXh/ F64, F23, F112, F62, F101, F56, F90, F59, F65
	common /varXh/ F19, F107, F63, F45, F153, F44, F170, F157
	common /varXh/ F158, F33, F36, F71, F167, F69, F171, F159
	common /varXh/ F160, F34, F39, F72, F187, F70, F175, F183
	common /varXh/ F184, F35, F41, F43, F154, F42, F173, F163
	common /varXh/ F164, F26, F30, F78, F168, F79, F174, F165
	common /varXh/ F166, F28, F21, F81, F189, F80, F180, F185
	common /varXh/ F186, F29, F24, F105, F127, F129, F130, F131
	common /varXh/ F132, F133, F150, F147, F108, F139, F140
	common /varXh/ F141, F142, F143, F144, F148, F149, F97, F120
	common /varXh/ F121, F122, F91, F92, F93, F135, F136, F98
	common /varXh/ F103, F106, F109, F94, F95, F96, F145, F146
	common /varXh/ F85, F86, F54, F38, F177, F49, F82, F83, F87
	common /varXh/ F88, F76, F61, F46, F47, F181, F48, F66, F68
	common /varXh/ F73, F74, F113, F116, F100, F102, F169, F155
	common /varXh/ F156, F57, F52, F172, F161, F162, F55, F50
	common /varXh/ F124, F125, F137, F138, F118, F119, F126
	common /varXh/ F128, Pair1, Pair6, Pair2, Pair7, Pair3
	common /varXh/ Pair10, Pair4, Pair8, Pair5, Pair9, Pair11
	common /varXh/ Abb1, Abb18, Abb17, Abb2, Abb34, Abb33, Abb26
	common /varXh/ Abb24, Abb35, Abb27, Abb25, Abb29, Abb10
	common /varXh/ Abb28, Abb8, Abb22, Abb20, Abb4, Abb23, Abb11
	common /varXh/ Abb19, Abb31, Abb14, Abb7, Abb12, Abb15, Abb5
	common /varXh/ Abb13, Abb32, Abb16, Abb9, Abb6, Abb30, Abb21
	common /varXh/ Abb3, Opt2, Sub54, Sub57, Sub279, Sub190
	common /varXh/ Sub179, Sub195, Sub186, Sub16, Sub20, Sub280
	common /varXh/ Sub205, Sub203, Sub109, Sub107, Sub307
	common /varXh/ Sub293, Sub315, Sub253, Sub26, Sub229, Sub221
	common /varXh/ Sub209, Sub215, Sub8, Sub2, Sub30, Sub132
	common /varXh/ Sub155, Sub166, Sub243, Sub175, Sub17, Sub58
	common /varXh/ Sub55, Sub146, Sub165, Sub21, Sub61, Sub254
	common /varXh/ Sub248, Sub260, Sub266, Sub308, Sub63, Sub60
	common /varXh/ Sub250, Sub298, Sub259, Sub291, Sub43, Sub313
	common /varXh/ Sub36, Sub237, Sub240, Sub306, Sub290, Sub118
	common /varXh/ Sub284, Sub130, Sub129, Sub277, Sub136
	common /varXh/ Sub225, Sub278, Sub286, Sub289, Sub305
	common /varXh/ Sub312, Sub317, Sub137, Sub178, Sub201
	common /varXh/ Sub234, Sub246, Sub271, Sub287, Sub321
	common /varXh/ Sub324, Sub326, Sub329, Sub127, Sub122, Sub27
	common /varXh/ Sub223, Sub216, Sub238, Sub241, Sub102, Sub99
	common /varXh/ Sub128, Sub121, Sub217, Sub133, Sub231
	common /varXh/ Sub116, Sub210, Sub309, Sub235, Sub244
	common /varXh/ Sub269, Sub294, Sub316, Sub117, Sub211
	common /varXh/ Sub333, Sub339, Sub348, Sub353, Sub49, Sub15
	common /varXh/ Sub72, Sub354, Sub53, Sub52, Sub78, Sub82
	common /varXh/ Sub67, Sub335, Sub350, Sub334, Sub345, Sub68
	common /varXh/ Sub105, Sub349, Sub341, Sub336, Sub48, Sub342
	common /varXh/ Sub351, Sub337, Sub357, Sub70, Sub41, Sub47
	common /varXh/ Sub361, Sub113, Sub343, Sub88, Sub344, Sub356
	common /varXh/ Sub83, Sub358, Sub151, Sub143, Sub161, Sub164
	common /varXh/ Sub171, Sub163, Sub174, Sub173, Sub152
	common /varXh/ Sub191, Sub138, Sub196, Sub150, Sub139
	common /varXh/ Sub220, Sub227, Sub288, Sub296, Sub144
	common /varXh/ Sub154, Sub153, Sub140, Sub172, Sub180
	common /varXh/ Sub160, Sub170, Sub162, Sub304, Sub207
	common /varXh/ Sub214, Sub131, Sub114, Sub126, Sub120
	common /varXh/ Sub301, Sub272, Sub263, Sub38, Sub42, Sub262
	common /varXh/ Sub268, Sub3, Sub31, Sub25, Sub93, Sub228
	common /varXh/ Sub208, Sub142, Sub89, Sub9, Sub75, Sub80
	common /varXh/ Sub181, Sub86, Sub103, Sub123, Sub124, Sub135
	common /varXh/ Sub141, Sub156, Sub167, Sub176, Sub197
	common /varXh/ Sub264, Sub219, Sub247, Sub226, Sub257
	common /varXh/ Sub242, Sub249, Sub255, Sub261, Sub267
	common /varXh/ Sub285, Sub297, Sub92, Sub96, Sub100, Sub330
	common /varXh/ Sub145, Sub314, Sub91, Sub95, Sub213, Sub115
	common /varXh/ Sub222, Sub212, Sub232, Sub251, Sub292
	common /varXh/ Sub224, Sub94, Sub90, Sub157, Sub199, Sub168
	common /varXh/ Sub28, Sub32, Sub104, Sub101, Sub184, Sub39
	common /varXh/ Sub44, Sub148, Sub193, Sub302, Sub319, Sub4
	common /varXh/ Sub10, Sub233, Sub134, Sub355, Sub340, Sub359
	common /varXh/ Sub65, Sub66, Sub187, Sub311, Sub69, Sub71
	common /varXh/ Sub256, Sub198, Sub192, Sub182, Sub188
	common /varXh/ Sub236, Sub239, Sub275, Sub282, Sub318, Sub51
	common /varXh/ Sub50, Sub74, Sub73, Sub218, Sub97, Sub98
	common /varXh/ Sub230, Sub14, Sub13, Sub300, Sub283, Sub245
	common /varXh/ Sub281, Sub274, Sub346, Sub360, Sub40, Sub45
	common /varXh/ Sub76, Sub81, Sub85, Sub87, Sub84, Sub303
	common /varXh/ Sub77, Sub79, Sub276, Sub320, Sub206, Sub204
	common /varXh/ Sub112, Sub108, Sub19, Sub62, Sub200, Sub56
	common /varXh/ Sub59, Sub22, Sub252, Sub64, Sub37, Sub46
	common /varXh/ Sub110, Sub194, Sub310, Sub111, Sub185
	common /varXh/ Sub189, Sub149, Sub295, Sub265, Sub258
	common /varXh/ Sub177, Sub159, Sub270, Sub169

	integer seq(2), Hel(6)
	common /helind/ seq, Hel

	integer Sfe7
	common /indices/ Sfe7

	HelType Ctree(HelDim(2))
	ComplexType MatSUN(2,2)
	common /ubaru_n1n2gg_formfactors/ Ctree, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
