#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 15-Jul-2016 12:07
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub262, Sub265, Sub1, Sub13, Sub4, Sub5, Sub14
	ComplexType Sub6
	common /varXs/ Sub262, Sub265, Sub1, Sub13, Sub4, Sub5, Sub14
	common /varXs/ Sub6

	ComplexType Opt3, Sub261, Sub263
	RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
	common /varXa/ Opt3, Sub261, Sub263, S, T, T14, T15, U, T24
	common /varXa/ T25, S34, S35, S45

	HelType F10, F1, F2, F3, F4, F5, F6, F7, F8, F9, Sub15, Sub16
	common /varXh/ F10, F1, F2, F3, F4, F5, F6, F7, F8, F9, Sub15
	common /varXh/ Sub16

	integer seq(2), Hel(6)
	common /helind/ seq, Hel

	HelType Ctree(HelDim(2))
	ComplexType MatSUN(2,2)
	common /ud_n1n2du_R35L46_formfactors/ Ctree, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
