#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 10-Jun-2016 12:27
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 5

#include "decl.h"

#else

#include "decl.h"

	ComplexType Opt1, Sub8, Sub4, Sub2, Sub20, Sub12, Sub22
	ComplexType Sub1(2), Sub9(2), Sub11(2), Sub5(2), Sub3(2)
	ComplexType Sub10(2), Sub13(2), Sub6(2)
	common /varXs/ Opt1, Sub8, Sub4, Sub2, Sub20, Sub12, Sub22
	common /varXs/ Sub1, Sub9, Sub11, Sub5, Sub3, Sub10, Sub13
	common /varXs/ Sub6

	ComplexType Sub31, Sub32
	RealType S, T, T14, U, T24, S34
	common /varXa/ Sub31, Sub32, S, T, T14, U, T24, S34

	HelType F1, F4, F28, F40, F23, F26, F38, F20, F31, F35, F2
	HelType F17, F3, F18, F15, F7, F33, F8, F25, F30, F10, F6
	HelType F36, F5, F21, F27, F42, F44, F51, F22, F11, F29, F48
	HelType F24, F12, F19, F41, F32, F34, F14, F16, F43, F37
	HelType F39, F9, F13, F45, F46, F47, F49, F53, F50, F52, F54
	HelType Pair1, Pair4, Pair3, Pair2, Abb1, Abb2, Sub25, Sub30
	HelType Sub23, Sub21, Sub24, Sub19, Sub35(HelDim(2))
	HelType Sub33(HelDim(2)), Sub7(HelDim(2)), Sub34(HelDim(2))
	HelType Sub14(HelDim(2)), Sub16, Sub15, Sub17, Sub18, Sub26
	HelType Sub28, Sub29, Sub27
	common /varXh/ F1, F4, F28, F40, F23, F26, F38, F20, F31, F35
	common /varXh/ F2, F17, F3, F18, F15, F7, F33, F8, F25, F30
	common /varXh/ F10, F6, F36, F5, F21, F27, F42, F44, F51
	common /varXh/ F22, F11, F29, F48, F24, F12, F19, F41, F32
	common /varXh/ F34, F14, F16, F43, F37, F39, F9, F13, F45
	common /varXh/ F46, F47, F49, F53, F50, F52, F54, Pair1
	common /varXh/ Pair4, Pair3, Pair2, Abb1, Abb2, Sub25, Sub30
	common /varXh/ Sub23, Sub21, Sub24, Sub19, Sub35, Sub33
	common /varXh/ Sub7, Sub34, Sub14, Sub16, Sub15, Sub17
	common /varXh/ Sub18, Sub26, Sub28, Sub29, Sub27

	integer seq(2), Hel(5)
	common /helind/ seq, Hel

	integer Sfe6
	common /indices/ Sfe6

	HelType Ctree(HelDim(1))
	ComplexType MatSUN(1,1)
	common /ddbar_n1n2j_formfactors/ Ctree, MatSUN

#if PARALLEL
	marker ends, enda, endhel
	common /varXs/ ends
	common /varXa/ enda
	common /helind/ endhel
#endif

#endif
