#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 26-Jan-2017 14:12
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 5

#include "virt_decl.h"

#else

#include "virt_decl.h"

        ComplexType Sub1(4), Sub2(3,4,2), Sub3(3,4,2)
        ComplexType Sub5(3,4,2), Sub6(4), Sub7(3,4,2)
        ComplexType Sub9(3,4,2), Sub10(4)
        ComplexType Sub11(3,4,2), Sub13(4)
        ComplexType Sub14(3,4,2), Sub15(3,4,2)
        ComplexType Sub22(4,4), Sub23(4,4)
        ComplexType AaA01(2), AaA02, AaB0i3(Nbb), AaB0i4(Nbb)
        ComplexType AaB0i5(Nbb,2), AaB0i6(Nbb,2), AaB0i9(Nbb)
        ComplexType AaB0i14(Nbb,2), AaB0i18(Nbb,2)
        ComplexType Opt2(3,3,4), Sub57(3,2,2)
        ComplexType Sub60(3,3), Sub61(3,3)
        ComplexType Sub62(3,3), Sub63(3,2,2)
        ComplexType Sub64(3,3), Sub65(3,2,2)
        ComplexType Sub66(3,2,2), Sub67(3,3)
        ComplexType Sub68(3,3), Sub69(3,3)
        ComplexType Sub70(3,3), Sub71(3,2,2)
        ComplexType Sub72(3,2,2), Sub76(3,4,2)
        ComplexType Sub77(3,4,2), Sub86(3,4,2)
        ComplexType Sub87(3,4,2), Sub89(3,2,2)
        ComplexType Sub95(3,4,2), Sub96(3,4,2)
        ComplexType Sub106(3,2,2), Sub124(3,4,2)
        ComplexType Sub125(3,4,2), Sub139(3,4,2)
        ComplexType Sub140(3,4,2), Sub205(3,3)
        ComplexType Sub223(3,4,2), Sub224(3,4,2)
        ComplexType Sub233(3,4,2), Sub234(3,4,2)
        ComplexType Sub261(3,2,2), Sub269(3,3)
        ComplexType Sub270(3,3), Sub271(3)
        ComplexType Sub299(3,2,2), Sub304(3,3)
        ComplexType Sub305(3,3), Sub306(3,3)
        ComplexType Sub307(3), Sub337(3), Sub341(3,3)
        ComplexType Sub389(3,2,2), Sub390(3,2,2)
        ComplexType Sub391(3,2,2), Sub392(3,3,2,2)
        ComplexType Sub393(3,2,2), Sub394(3,3,2,2)
        ComplexType Sub395(3,3,2,2,2), Sub396(3,3,2,2,2)
        ComplexType Sub407(3,2,2), Sub408(3,2,2)
        ComplexType Sub409(3,2,2), Sub410(3,3,2,2)
        ComplexType Sub411(3,2,2), Sub412(3,3,2,2)
        ComplexType Sub413(3,3,2,2,2), Sub414(3,3,2,2,2)
        ComplexType Sub428(3,3,4,4)
        ComplexType Sub440(3,3,4,4)
        ComplexType Sub448(3,3,4,4), AaB0i7(Nbb)
        ComplexType AaB0i8(Nbb), AaB0i10(Nbb), AaB0i11(Nbb,2)
        ComplexType AaB0i12(Nbb,2), AaB0i13(Nbb), AaB0i15(Nbb,2)
        ComplexType AaB0i16(Nbb,2), AaB0i17(Nbb), AaB0i19(Nbb,2)
        ComplexType Sub58(3,3), Sub59(3,3)
        common /qdbarg_nInJqdbar_varXs/ Sub1, Sub2, Sub3, Sub5, Sub6, Sub7, Sub9
        common /qdbarg_nInJqdbar_varXs/ Sub10, Sub11, Sub13, Sub14, Sub15, Sub22
        common /qdbarg_nInJqdbar_varXs/ Sub23, AaA01, AaA02, AaB0i3, AaB0i4, AaB0i5
        common /qdbarg_nInJqdbar_varXs/ AaB0i6, AaB0i9, AaB0i14, AaB0i18, Opt2, Sub57
        common /qdbarg_nInJqdbar_varXs/ Sub60, Sub61, Sub62, Sub63, Sub64, Sub65
        common /qdbarg_nInJqdbar_varXs/ Sub66, Sub67, Sub68, Sub69, Sub70, Sub71
        common /qdbarg_nInJqdbar_varXs/ Sub72, Sub76, Sub77, Sub86, Sub87, Sub89
        common /qdbarg_nInJqdbar_varXs/ Sub95, Sub96, Sub106, Sub124, Sub125, Sub139
        common /qdbarg_nInJqdbar_varXs/ Sub140, Sub205, Sub223, Sub224, Sub233
        common /qdbarg_nInJqdbar_varXs/ Sub234, Sub261, Sub269, Sub270, Sub271
        common /qdbarg_nInJqdbar_varXs/ Sub299, Sub304, Sub305, Sub306, Sub307
        common /qdbarg_nInJqdbar_varXs/ Sub337, Sub341, Sub389, Sub390, Sub391
        common /qdbarg_nInJqdbar_varXs/ Sub392, Sub393, Sub394, Sub395, Sub396
        common /qdbarg_nInJqdbar_varXs/ Sub407, Sub408, Sub409, Sub410, Sub411
        common /qdbarg_nInJqdbar_varXs/ Sub412, Sub413, Sub414, Sub428, Sub440
        common /qdbarg_nInJqdbar_varXs/ Sub448, AaB0i7, AaB0i8, AaB0i10, AaB0i11
        common /qdbarg_nInJqdbar_varXs/ AaB0i12, AaB0i13, AaB0i15, AaB0i16, AaB0i17
        common /qdbarg_nInJqdbar_varXs/ AaB0i19, Sub58, Sub59

        ComplexType Sub186(3,4,4)
        ComplexType Sub419(3,3,4,4)
        ComplexType Sub422(3,3,4,4)
        ComplexType Sub183(3,3,4,4)
        ComplexType Opt1(4), Sub90(3,4)
        ComplexType Sub100(3,3,4,2,2), Sub108(3,4)
        ComplexType Sub155(3,2,2), Sub184(3,4,4)
        ComplexType Sub189(3,3,4,4), Sub256(3,2,2)
        ComplexType Sub263(3,2,2), Sub264(3,2,2)
        ComplexType Sub294(3,3,4)
        ComplexType Sub303(3,3,4,4), Sub345(3,4)
        ComplexType Sub436(3,2), Sub437(3,2)
        ComplexType Sub455(3,3,4,4,2,2)
        ComplexType Sub457(3,3,4,4,2,2), Sub473(3)
        ComplexType Sub474(3,2,2), Sub475(3), Sub476(3,2,2)
        ComplexType Sub185(3,3,4,4)
        ComplexType Sub203(3,3,4,4)
        ComplexType Sub204(3,3,4,4)
        ComplexType Sub206(3,3,4,4)
        ComplexType Sub207(3,3,4,4)
        ComplexType Sub210(3,3,4,4)
        ComplexType Sub230(3,3,4,4)
        ComplexType Sub311(3,3,4,4)
        ComplexType Sub313(3,3,4,4)
        ComplexType Sub324(3,3,4,4)
        ComplexType Sub379(3,3,4,4)
        ComplexType Sub383(3,3,4,4)
        ComplexType Sub308(3,3,4,4)
        RealType S, T, T14, U, T24, S34
        common /qdbarg_nInJqdbar_varXa/ Sub186, Sub419, Sub422, Sub183, Opt1, Sub90
        common /qdbarg_nInJqdbar_varXa/ Sub100, Sub108, Sub155, Sub184, Sub189
        common /qdbarg_nInJqdbar_varXa/ Sub256, Sub263, Sub264, Sub294, Sub303
        common /qdbarg_nInJqdbar_varXa/ Sub345, Sub436, Sub437, Sub455, Sub457
        common /qdbarg_nInJqdbar_varXa/ Sub473, Sub474, Sub475, Sub476, Sub185
        common /qdbarg_nInJqdbar_varXa/ Sub203, Sub204, Sub206, Sub207, Sub210
        common /qdbarg_nInJqdbar_varXa/ Sub230, Sub311, Sub313, Sub324, Sub379
        common /qdbarg_nInJqdbar_varXa/ Sub383, Sub308, S, T, T14, U, T24, S34

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType Pair1, Pair2, Pair3, Pair4
        HelType Sub4(HelDim(3),4,2), Sub8(HelDim(3),4,2)
        HelType Sub12(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub17(HelDim(3),4,2), Sub18(HelDim(3))
        HelType Sub19(HelDim(3)), Sub20(HelDim(3),4,2)
        HelType Sub21(HelDim(3),4,2), Sub24(HelDim(4),4)
        HelType Sub25(HelDim(4),4), Sub26(HelDim(3))
        HelType Sub27(HelDim(3)), Sub28(HelDim(3),4,4)
        HelType Sub29(HelDim(3)), Sub30(HelDim(3))
        HelType Sub31(HelDim(3),4,4)
        HelType Sub32(HelDim(4),4), Sub34(HelDim(3),4,2)
        HelType Sub35(HelDim(3),4,2)
        HelType Sub36(HelDim(3),4,2), Sub37(HelDim(4),4)
        HelType Sub38(HelDim(4),4), Sub39(HelDim(3))
        HelType Sub45(HelDim(4),4), Sub47(HelDim(3),4,2)
        HelType Sub48(HelDim(3)), Sub49(HelDim(3))
        HelType Sub50(HelDim(3),4,2)
        HelType Sub51(HelDim(3),4,2)
        HelType Sub52(HelDim(3),4,2), Sub53(HelDim(3))
        HelType Sub54(HelDim(3)), Sub55(HelDim(3),4,2)
        HelType Sub56(HelDim(3),4,2)
        HelType Sub181(HelDim(3),4,4), Sub193(HelDim(3))
        HelType Sub197(HelDim(3)), Sub200(HelDim(3))
        HelType Sub421(HelDim(3),3,4,4,2), Abb1, Abb2
        HelType Sub33(HelDim(3),4,4), Sub40(HelDim(3))
        HelType Sub41(HelDim(3),4,4), Sub42(HelDim(3))
        HelType Sub43(HelDim(3)), Sub44(HelDim(3),4,4)
        HelType Sub212(HelDim(3),4,4)
        HelType Sub420(HelDim(3),4,2)
        HelType Sub423(HelDim(3),4,2)
        HelType Sub46(HelDim(3),3,4,4)
        HelType Sub78(HelDim(3),4,2)
        HelType Sub88(HelDim(3),4,2)
        HelType Sub97(HelDim(3),4,2)
        HelType Sub98(HelDim(3),4,2)
        HelType Sub116(HelDim(3),4,2)
        HelType Sub126(HelDim(3),4,2)
        HelType Sub127(HelDim(3),3,4,2)
        HelType Sub133(HelDim(3),3,4,2)
        HelType Sub141(HelDim(3),4,2)
        HelType Sub142(HelDim(3),3,4,2)
        HelType Sub149(HelDim(3),3,4,2,2)
        HelType Sub150(HelDim(3),3,4,2,2)
        HelType Sub151(HelDim(3),3,4,2,2)
        HelType Sub153(HelDim(3),3,4,2,2)
        HelType Sub161(HelDim(3),4,4)
        HelType Sub163(HelDim(3),3,4,4)
        HelType Sub166(HelDim(3),3,4,2,2)
        HelType Sub167(HelDim(3),3,4,2,2)
        HelType Sub168(HelDim(3),3,4,2,2)
        HelType Sub170(HelDim(3),3,4,2,2)
        HelType Sub173(HelDim(3),3,4,4)
        HelType Sub175(HelDim(3),4,4)
        HelType Sub179(HelDim(3),3,4,2)
        HelType Sub188(HelDim(3)), Sub192(HelDim(3))
        HelType Sub196(HelDim(3)), Sub199(HelDim(3))
        HelType Sub214(HelDim(3),4,2)
        HelType Sub215(HelDim(3),4,2)
        HelType Sub216(HelDim(3),4,2)
        HelType Sub222(HelDim(3),3,4,2,2)
        HelType Sub225(HelDim(3),4,2)
        HelType Sub226(HelDim(3),3,4,2)
        HelType Sub231(HelDim(3),3,4,4,2)
        HelType Sub235(HelDim(3),4,2)
        HelType Sub236(HelDim(3),3,4,2)
        HelType Sub240(HelDim(3),3,4,4,2)
        HelType Sub244(HelDim(3),3,4,2,2)
        HelType Sub246(HelDim(3),3,4,2,2)
        HelType Sub247(HelDim(3),3,4,2,2)
        HelType Sub248(HelDim(3),3,4,4,2,2)
        HelType Sub250(HelDim(3),3,4,2,2)
        HelType Sub252(HelDim(3),3,4,2,2)
        HelType Sub253(HelDim(3),3,4,2,2)
        HelType Sub254(HelDim(3),3,4,4,2,2)
        HelType Sub258(HelDim(3),4,2)
        HelType Sub259(HelDim(3),4,2)
        HelType Sub260(HelDim(3),4,2)
        HelType Sub266(HelDim(3),3,4,2,2)
        HelType Sub272(HelDim(3),3,4,2)
        HelType Sub277(HelDim(3),3), Sub278(HelDim(3),3)
        HelType Sub279(HelDim(3),3,4,2)
        HelType Sub284(HelDim(3),3,4,2)
        HelType Sub289(HelDim(3),3), Sub290(HelDim(3),3)
        HelType Sub291(HelDim(3),3,4,2)
        HelType Sub312(HelDim(3),3,4,4)
        HelType Sub314(HelDim(3),3,4,4)
        HelType Sub317(HelDim(3),4,4)
        HelType Sub318(HelDim(3),3,4,4)
        HelType Sub319(HelDim(3),3,4,4)
        HelType Sub320(HelDim(3),3,4,4)
        HelType Sub321(HelDim(3),3,4,4,2)
        HelType Sub328(HelDim(3),3,4,4)
        HelType Sub329(HelDim(3),3,4,4)
        HelType Sub338(HelDim(3),3,4,4)
        HelType Sub339(HelDim(3),3,4,4)
        HelType Sub340(HelDim(3),4,4)
        HelType Sub350(HelDim(3),4,2), Sub352(HelDim(3))
        HelType Sub353(HelDim(3),3,4,2)
        HelType Sub354(HelDim(3),3,4,2)
        HelType Sub355(HelDim(3),3,4,2)
        HelType Sub356(HelDim(3),3,4,2,2)
        HelType Sub357(HelDim(3),3,4,2)
        HelType Sub358(HelDim(3),3,4,4,2)
        HelType Sub359(HelDim(3),3,4,2)
        HelType Sub360(HelDim(3),3,4,4,2)
        HelType Sub361(HelDim(3),3,4,4,2,2)
        HelType Sub362(HelDim(3))
        HelType Sub363(HelDim(3),3,4,2)
        HelType Sub364(HelDim(3),3,4,2)
        HelType Sub365(HelDim(3),3,4,2)
        HelType Sub366(HelDim(3),3,4,2,2)
        HelType Sub368(HelDim(3)), Sub370(HelDim(3))
        HelType Sub373(HelDim(3)), Sub375(HelDim(3))
        HelType Sub397(HelDim(3),3,4,2)
        HelType Sub398(HelDim(3),3,4,4,2)
        HelType Sub399(HelDim(3),3,4,2)
        HelType Sub400(HelDim(3),3,4,4,2)
        HelType Sub401(HelDim(3),3,4,4,2,2)
        HelType Sub415(HelDim(3),3,4,2,2,2)
        HelType Sub416(HelDim(3),3,4,2,2,2)
        HelType Sub417(HelDim(3),3,4,2,2,2)
        HelType Sub418(HelDim(3),3,4,2,2,2)
        HelType Sub438(HelDim(3),3,4,4,2)
        HelType Sub477(HelDim(3),3,4,4,2,2), Abb3, Abb4
        HelType Abb5, Abb6, Abb7, Abb8, Abb9, Abb10
        HelType Sub91(HelDim(3),4), Sub92(HelDim(3),4)
        HelType Sub93(HelDim(3),4,2)
        HelType Sub94(HelDim(3),4,2)
        HelType Sub99(HelDim(3),4,2)
        HelType Sub101(HelDim(3),3,4,2,2)
        HelType Sub102(HelDim(3),3,4,2)
        HelType Sub103(HelDim(3),3,4,2)
        HelType Sub104(HelDim(3),3,4,2)
        HelType Sub105(HelDim(3),3,4,2)
        HelType Sub107(HelDim(3),4,2)
        HelType Sub109(HelDim(3),4), Sub110(HelDim(3),4)
        HelType Sub111(HelDim(3),4,2)
        HelType Sub112(HelDim(3),4,2)
        HelType Sub120(HelDim(3),4,2)
        HelType Sub121(HelDim(3),4,2)
        HelType Sub122(HelDim(3),4,2)
        HelType Sub123(HelDim(3),4,2), Sub128(HelDim(3))
        HelType Sub129(HelDim(3)), Sub130(HelDim(3))
        HelType Sub131(HelDim(3))
        HelType Sub132(HelDim(3),3,4,2)
        HelType Sub134(HelDim(3),3,4,2)
        HelType Sub137(HelDim(3),3,4,2)
        HelType Sub138(HelDim(3),3,4,2,2)
        HelType Sub143(HelDim(3)), Sub144(HelDim(3))
        HelType Sub145(HelDim(3)), Sub146(HelDim(3))
        HelType Sub147(HelDim(3),3,4,2)
        HelType Sub148(HelDim(3),3,4,2)
        HelType Sub152(HelDim(3),3,4,2,2)
        HelType Sub154(HelDim(3),3,4,2,2)
        HelType Sub156(HelDim(3)), Sub157(HelDim(3),4,4)
        HelType Sub158(HelDim(3)), Sub159(HelDim(3),4,4)
        HelType Sub160(HelDim(3),4,4)
        HelType Sub162(HelDim(3),3,4,4)
        HelType Sub164(HelDim(3),3,4,4)
        HelType Sub165(HelDim(3),3,4,4,2)
        HelType Sub169(HelDim(3),3,4,2,2)
        HelType Sub171(HelDim(3),3,4,2,2)
        HelType Sub174(HelDim(3),3,4,4)
        HelType Sub176(HelDim(3),3,4,4)
        HelType Sub177(HelDim(3),3,4,4)
        HelType Sub178(HelDim(3),2,2)
        HelType Sub180(HelDim(3),3,4,2)
        HelType Sub187(HelDim(3),4,4)
        HelType Sub190(HelDim(3),3,4,4)
        HelType Sub191(HelDim(3))
        HelType Sub194(HelDim(3),3,4,4)
        HelType Sub195(HelDim(3),3,4,4)
        HelType Sub198(HelDim(3),3,4,4)
        HelType Sub201(HelDim(3),3,4,4)
        HelType Sub202(HelDim(3),3,4,4)
        HelType Sub208(HelDim(3),3,4,4)
        HelType Sub209(HelDim(3),3,4,4)
        HelType Sub211(HelDim(3),3,4,4)
        HelType Sub213(HelDim(3),3,4,4)
        HelType Sub217(HelDim(3),3,4,4)
        HelType Sub218(HelDim(3),3,4,4)
        HelType Sub219(HelDim(3),3,4,4)
        HelType Sub220(HelDim(3),3,4,4)
        HelType Sub221(HelDim(3),3,4,4,2)
        HelType Sub227(HelDim(3),3,4,4)
        HelType Sub228(HelDim(3),3,4,4)
        HelType Sub229(HelDim(3),3,4,4,2)
        HelType Sub232(HelDim(3),3,4,4,2)
        HelType Sub237(HelDim(3),3,4,4)
        HelType Sub238(HelDim(3),3,4,4)
        HelType Sub239(HelDim(3),3,4,4,2)
        HelType Sub241(HelDim(3),3,4,4,2)
        HelType Sub242(HelDim(3),3,4,4,2)
        HelType Sub243(HelDim(3),3,4,4,2)
        HelType Sub245(HelDim(3),3,4,4,2,2)
        HelType Sub249(HelDim(3),3,4,4,2,2)
        HelType Sub251(HelDim(3),3,4,4,2,2)
        HelType Sub255(HelDim(3),3,4,4,2,2)
        HelType Sub257(HelDim(3),2,2), Sub262(HelDim(3),2,2)
        HelType Sub265(HelDim(3),2,2), Sub267(HelDim(3))
        HelType Sub268(HelDim(3))
        HelType Sub273(HelDim(3),3,4,2)
        HelType Sub274(HelDim(3),3), Sub275(HelDim(3),3)
        HelType Sub276(HelDim(3),3,4,2)
        HelType Sub280(HelDim(3),3,4,2)
        HelType Sub281(HelDim(3),3,4,2)
        HelType Sub282(HelDim(3)), Sub283(HelDim(3))
        HelType Sub285(HelDim(3),3,4,2)
        HelType Sub286(HelDim(3),3), Sub287(HelDim(3),3)
        HelType Sub288(HelDim(3),3,4,2)
        HelType Sub292(HelDim(3),3,4,2)
        HelType Sub293(HelDim(3),3,4,2)
        HelType Sub295(HelDim(3),3,4)
        HelType Sub296(HelDim(3),3,4)
        HelType Sub297(HelDim(3),3,4,2)
        HelType Sub298(HelDim(3),3,4,2)
        HelType Sub300(HelDim(3),3,4,2,2)
        HelType Sub301(HelDim(3),3,4,4)
        HelType Sub302(HelDim(3),3,4,4)
        HelType Sub309(HelDim(3),3,4,4,2)
        HelType Sub310(HelDim(3),3,4,4,2)
        HelType Sub315(HelDim(3),3,4,4,2)
        HelType Sub316(HelDim(3),3,4,4,2)
        HelType Sub322(HelDim(3),3,4,4)
        HelType Sub323(HelDim(3),3,4,4)
        HelType Sub325(HelDim(3),3,4,4,2)
        HelType Sub326(HelDim(3),3,4,4,2)
        HelType Sub327(HelDim(3),3,4,4,2)
        HelType Sub330(HelDim(3),3,4,4,2)
        HelType Sub331(HelDim(3),3,4,4,2)
        HelType Sub332(HelDim(3)), Sub333(HelDim(3),4,4)
        HelType Sub334(HelDim(3)), Sub335(HelDim(3),4,4)
        HelType Sub336(HelDim(3),4,4)
        HelType Sub342(HelDim(3),3,4,4)
        HelType Sub343(HelDim(3),3,4,4)
        HelType Sub344(HelDim(3),3,4,4)
        HelType Sub346(HelDim(3),4), Sub347(HelDim(3),4)
        HelType Sub348(HelDim(3),4,2)
        HelType Sub349(HelDim(3),4,2)
        HelType Sub351(HelDim(3),4,2,2)
        HelType Sub369(HelDim(3),3,4,4)
        HelType Sub371(HelDim(3),3,4,4)
        HelType Sub372(HelDim(3),3,4,4)
        HelType Sub374(HelDim(3),3,4,4)
        HelType Sub376(HelDim(3),3,4,4)
        HelType Sub377(HelDim(3),3,4,4)
        HelType Sub378(HelDim(3),3,4,4)
        HelType Sub380(HelDim(3),3,4,4)
        HelType Sub381(HelDim(3),3,4,4)
        HelType Sub382(HelDim(3),3,4,4)
        HelType Sub384(HelDim(3),3,4,4)
        HelType Sub385(HelDim(3),3,4,4)
        HelType Sub386(HelDim(3),3,4,4)
        HelType Sub387(HelDim(3),3,4,4)
        HelType Sub388(HelDim(3),3,4,4)
        HelType Sub402(HelDim(3),3,4,4)
        HelType Sub403(HelDim(3),3,4,4)
        HelType Sub404(HelDim(3),3,4,4)
        HelType Sub405(HelDim(3),3,4,4)
        HelType Sub406(HelDim(3),3,4,4,2)
        HelType Sub424(HelDim(3),3,4,2)
        HelType Sub425(HelDim(3),3,4,2)
        HelType Sub426(HelDim(3),3,4,4,2)
        HelType Sub427(HelDim(3),3,4,4,2)
        HelType Sub429(HelDim(3),3,4,4,2)
        HelType Sub430(HelDim(3),3,4,4,2)
        HelType Sub431(HelDim(3),3,4,4,2)
        HelType Sub432(HelDim(3),3,4,4,2)
        HelType Sub433(HelDim(3),3,4,4,2)
        HelType Sub434(HelDim(3),3,4,4,2)
        HelType Sub435(HelDim(3),3,4,4,2)
        HelType Sub439(HelDim(3),3,4,4,2)
        HelType Sub441(HelDim(3),3,4,4,2)
        HelType Sub442(HelDim(3),3,4,2)
        HelType Sub443(HelDim(3),3,4,2)
        HelType Sub444(HelDim(3),3,4,4,2)
        HelType Sub445(HelDim(3),3,4,4,2)
        HelType Sub446(HelDim(3),3,4,4,2)
        HelType Sub447(HelDim(3),3,4,4,2)
        HelType Sub449(HelDim(3),3,4,4,2)
        HelType Sub450(HelDim(3),3,4,4,2)
        HelType Sub451(HelDim(3),3,4,4,2)
        HelType Sub452(HelDim(3),3,4,4,2)
        HelType Sub453(HelDim(3),3,4,4,2)
        HelType Sub458(HelDim(3),3,4,4,2,2)
        HelType Sub459(HelDim(3),3,4,4,2,2)
        HelType Sub460(HelDim(3),3,4,4,2,2)
        HelType Sub461(HelDim(3),3,4,4,2,2)
        HelType Sub462(HelDim(3),3,4,4,2,2)
        HelType Sub463(HelDim(3),3,4,4,2,2)
        HelType Sub464(HelDim(3),3,4,4,2,2)
        HelType Sub465(HelDim(3),3,4,4,2,2)
        HelType Sub466(HelDim(3),3,4,4,2,2)
        HelType Sub467(HelDim(3),3,4,4,2)
        HelType Sub468(HelDim(3),3,4,4,2,2)
        HelType Sub469(HelDim(3),3,4,2,2)
        HelType Sub470(HelDim(3),3,4,4,2,2)
        HelType Sub471(HelDim(3),3,4,2,2)
        HelType Sub472(HelDim(3),3,4,4,2,2)
        HelType Sub478(HelDim(3),3,4,4)
        HelType Sub479(HelDim(3),3,4,4,2,2)
        HelType Sub480(HelDim(3),3,4,4,2,2)
        HelType Sub481(HelDim(3),3,4,4,2)
        HelType Sub482(HelDim(3),3,4,4,2,2)
        HelType Sub483(HelDim(3),3,4,4)
        HelType Sub484(HelDim(3),3,4,4,2,2)
        HelType Sub485(HelDim(3),3,4,4,2,2)
        HelType Sub486(HelDim(3),3,4,4,2,2)
        HelType Sub487(HelDim(3),3,4,4,2,2)
        HelType Sub490(HelDim(3),3,4,4)
        HelType Sub491(HelDim(3),3,4,4)
        HelType Sub182(HelDim(3),3,4,4)
        HelType Sub488(HelDim(3),3,4,4)
        HelType Sub489(HelDim(3),3,4,4)
        common /qdbarg_nInJqdbar_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /qdbarg_nInJqdbar_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /qdbarg_nInJqdbar_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /qdbarg_nInJqdbar_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /qdbarg_nInJqdbar_varXh/ F39, F40, F41, F42, Pair1, Pair2, Pair3
        common /qdbarg_nInJqdbar_varXh/ Pair4, Sub4, Sub8, Sub12, Sub16, Sub17, Sub18
        common /qdbarg_nInJqdbar_varXh/ Sub19, Sub20, Sub21, Sub24, Sub25, Sub26
        common /qdbarg_nInJqdbar_varXh/ Sub27, Sub28, Sub29, Sub30, Sub31, Sub32
        common /qdbarg_nInJqdbar_varXh/ Sub34, Sub35, Sub36, Sub37, Sub38, Sub39
        common /qdbarg_nInJqdbar_varXh/ Sub45, Sub47, Sub48, Sub49, Sub50, Sub51
        common /qdbarg_nInJqdbar_varXh/ Sub52, Sub53, Sub54, Sub55, Sub56, Sub181
        common /qdbarg_nInJqdbar_varXh/ Sub193, Sub197, Sub200, Sub421, Abb1, Abb2
        common /qdbarg_nInJqdbar_varXh/ Sub33, Sub40, Sub41, Sub42, Sub43, Sub44
        common /qdbarg_nInJqdbar_varXh/ Sub212, Sub420, Sub423, Sub46, Sub78, Sub88
        common /qdbarg_nInJqdbar_varXh/ Sub97, Sub98, Sub116, Sub126, Sub127, Sub133
        common /qdbarg_nInJqdbar_varXh/ Sub141, Sub142, Sub149, Sub150, Sub151
        common /qdbarg_nInJqdbar_varXh/ Sub153, Sub161, Sub163, Sub166, Sub167
        common /qdbarg_nInJqdbar_varXh/ Sub168, Sub170, Sub173, Sub175, Sub179
        common /qdbarg_nInJqdbar_varXh/ Sub188, Sub192, Sub196, Sub199, Sub214
        common /qdbarg_nInJqdbar_varXh/ Sub215, Sub216, Sub222, Sub225, Sub226
        common /qdbarg_nInJqdbar_varXh/ Sub231, Sub235, Sub236, Sub240, Sub244
        common /qdbarg_nInJqdbar_varXh/ Sub246, Sub247, Sub248, Sub250, Sub252
        common /qdbarg_nInJqdbar_varXh/ Sub253, Sub254, Sub258, Sub259, Sub260
        common /qdbarg_nInJqdbar_varXh/ Sub266, Sub272, Sub277, Sub278, Sub279
        common /qdbarg_nInJqdbar_varXh/ Sub284, Sub289, Sub290, Sub291, Sub312
        common /qdbarg_nInJqdbar_varXh/ Sub314, Sub317, Sub318, Sub319, Sub320
        common /qdbarg_nInJqdbar_varXh/ Sub321, Sub328, Sub329, Sub338, Sub339
        common /qdbarg_nInJqdbar_varXh/ Sub340, Sub350, Sub352, Sub353, Sub354
        common /qdbarg_nInJqdbar_varXh/ Sub355, Sub356, Sub357, Sub358, Sub359
        common /qdbarg_nInJqdbar_varXh/ Sub360, Sub361, Sub362, Sub363, Sub364
        common /qdbarg_nInJqdbar_varXh/ Sub365, Sub366, Sub368, Sub370, Sub373
        common /qdbarg_nInJqdbar_varXh/ Sub375, Sub397, Sub398, Sub399, Sub400
        common /qdbarg_nInJqdbar_varXh/ Sub401, Sub415, Sub416, Sub417, Sub418
        common /qdbarg_nInJqdbar_varXh/ Sub438, Sub477, Abb3, Abb4, Abb5, Abb6, Abb7
        common /qdbarg_nInJqdbar_varXh/ Abb8, Abb9, Abb10, Sub91, Sub92, Sub93, Sub94
        common /qdbarg_nInJqdbar_varXh/ Sub99, Sub101, Sub102, Sub103, Sub104, Sub105
        common /qdbarg_nInJqdbar_varXh/ Sub107, Sub109, Sub110, Sub111, Sub112
        common /qdbarg_nInJqdbar_varXh/ Sub120, Sub121, Sub122, Sub123, Sub128
        common /qdbarg_nInJqdbar_varXh/ Sub129, Sub130, Sub131, Sub132, Sub134
        common /qdbarg_nInJqdbar_varXh/ Sub137, Sub138, Sub143, Sub144, Sub145
        common /qdbarg_nInJqdbar_varXh/ Sub146, Sub147, Sub148, Sub152, Sub154
        common /qdbarg_nInJqdbar_varXh/ Sub156, Sub157, Sub158, Sub159, Sub160
        common /qdbarg_nInJqdbar_varXh/ Sub162, Sub164, Sub165, Sub169, Sub171
        common /qdbarg_nInJqdbar_varXh/ Sub174, Sub176, Sub177, Sub178, Sub180
        common /qdbarg_nInJqdbar_varXh/ Sub187, Sub190, Sub191, Sub194, Sub195
        common /qdbarg_nInJqdbar_varXh/ Sub198, Sub201, Sub202, Sub208, Sub209
        common /qdbarg_nInJqdbar_varXh/ Sub211, Sub213, Sub217, Sub218, Sub219
        common /qdbarg_nInJqdbar_varXh/ Sub220, Sub221, Sub227, Sub228, Sub229
        common /qdbarg_nInJqdbar_varXh/ Sub232, Sub237, Sub238, Sub239, Sub241
        common /qdbarg_nInJqdbar_varXh/ Sub242, Sub243, Sub245, Sub249, Sub251
        common /qdbarg_nInJqdbar_varXh/ Sub255, Sub257, Sub262, Sub265, Sub267
        common /qdbarg_nInJqdbar_varXh/ Sub268, Sub273, Sub274, Sub275, Sub276
        common /qdbarg_nInJqdbar_varXh/ Sub280, Sub281, Sub282, Sub283, Sub285
        common /qdbarg_nInJqdbar_varXh/ Sub286, Sub287, Sub288, Sub292, Sub293
        common /qdbarg_nInJqdbar_varXh/ Sub295, Sub296, Sub297, Sub298, Sub300
        common /qdbarg_nInJqdbar_varXh/ Sub301, Sub302, Sub309, Sub310, Sub315
        common /qdbarg_nInJqdbar_varXh/ Sub316, Sub322, Sub323, Sub325, Sub326
        common /qdbarg_nInJqdbar_varXh/ Sub327, Sub330, Sub331, Sub332, Sub333
        common /qdbarg_nInJqdbar_varXh/ Sub334, Sub335, Sub336, Sub342, Sub343
        common /qdbarg_nInJqdbar_varXh/ Sub344, Sub346, Sub347, Sub348, Sub349
        common /qdbarg_nInJqdbar_varXh/ Sub351, Sub369, Sub371, Sub372, Sub374
        common /qdbarg_nInJqdbar_varXh/ Sub376, Sub377, Sub378, Sub380, Sub381
        common /qdbarg_nInJqdbar_varXh/ Sub382, Sub384, Sub385, Sub386, Sub387
        common /qdbarg_nInJqdbar_varXh/ Sub388, Sub402, Sub403, Sub404, Sub405
        common /qdbarg_nInJqdbar_varXh/ Sub406, Sub424, Sub425, Sub426, Sub427
        common /qdbarg_nInJqdbar_varXh/ Sub429, Sub430, Sub431, Sub432, Sub433
        common /qdbarg_nInJqdbar_varXh/ Sub434, Sub435, Sub439, Sub441, Sub442
        common /qdbarg_nInJqdbar_varXh/ Sub443, Sub444, Sub445, Sub446, Sub447
        common /qdbarg_nInJqdbar_varXh/ Sub449, Sub450, Sub451, Sub452, Sub453
        common /qdbarg_nInJqdbar_varXh/ Sub458, Sub459, Sub460, Sub461, Sub462
        common /qdbarg_nInJqdbar_varXh/ Sub463, Sub464, Sub465, Sub466, Sub467
        common /qdbarg_nInJqdbar_varXh/ Sub468, Sub469, Sub470, Sub471, Sub472
        common /qdbarg_nInJqdbar_varXh/ Sub478, Sub479, Sub480, Sub481, Sub482
        common /qdbarg_nInJqdbar_varXh/ Sub483, Sub484, Sub485, Sub486, Sub487
        common /qdbarg_nInJqdbar_varXh/ Sub490, Sub491, Sub182, Sub488, Sub489

        integer Sfe6, Sfe7, Sfe8
        common /qdbarg_nInJqdbar_indices/ Sfe6, Sfe7, Sfe8

        HelType Ctree(HelDim(1)), Cloop(HelDim(1))
        ComplexType MatSUN(1,1)
        common /qdbarg_nInJqdbar_formfactors/ Ctree, Cloop, MatSUN

#endif

#ifndef vars2_h
#define vars2_h
#else
        ComplexType SC, TC, T14C, UC, T24C, S34C
        common /qdbarg_nInJqdbar_ckin/ SC, TC, T14C, UC, T24C, S34C
#endif
