#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 23-Oct-2017 10:57
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub1(3,4,2), Sub2(3,4,2)
        ComplexType Sub3(3,4,2), Sub6(2,3,2)
        ComplexType Sub10(3,4,2), Sub11(3,4,2)
        ComplexType Sub12(3,4,2), Sub19(2,4)
        ComplexType Sub22(2,4), Sub24(3,3)
        ComplexType Sub39(2,3,2), Sub43(3,3)
        ComplexType Sub52(2,3,2), Sub62(2,3,2)
        ComplexType Sub63(4), Sub64(3,4,2)
        ComplexType Sub65(3,4,2), Sub74(2,3,2)
        ComplexType Sub79(2,3,2), Sub96(2,3,2)
        ComplexType Sub98(3,4,2), Sub99(3,4,2)
        ComplexType Sub100(3,4,2), Sub109(4)
        ComplexType Sub110(3,4,2), Sub111(3,4,2)
        ComplexType Sub116(4), Sub117(2,4), Sub119(4)
        ComplexType Sub120(2,4), Sub131(3,4,2)
        ComplexType Sub132(3,4,2), Sub133(3,4,2)
        ComplexType Sub153(3,2), Sub155(3,2), Sub157(3,2)
        ComplexType Sub158(3,2), Sub189(3,2), Sub190(3,2)
        ComplexType Sub191(3,2), Sub194(3,2), Sub196(3,2)
        ComplexType Sub197(3,2), Sub207(3,2)
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub1, Sub2, Sub3, Sub6, Sub10, Sub11, Sub12
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub19, Sub22, Sub24, Sub39, Sub43, Sub52
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub62, Sub63, Sub64, Sub65, Sub74, Sub79
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub96, Sub98, Sub99, Sub100, Sub109, Sub110
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub111, Sub116, Sub117, Sub119, Sub120
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub131, Sub132, Sub133, Sub153, Sub155
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub157, Sub158, Sub189, Sub190, Sub191
        common /qdbarqubar_nIxJqubarqubar_varXs/ Sub194, Sub196, Sub197, Sub207

        ComplexType Opt5(2,4), Opt6(2,3,3,3)
        ComplexType Opt7(2,3), Opt8(3,4)
        ComplexType Sub25(2,3,4), Sub44(2,3,4)
        ComplexType Sub154(2,3,3,3,3,4)
        ComplexType Sub160(2,3,3,3,3,4)
        ComplexType Sub161(2,3,3)
        ComplexType Sub162(2,3,3,3,3,4)
        ComplexType Sub165(3,3,3), Sub166(2,3,4)
        ComplexType Sub168(2,3,3,3,3,4)
        ComplexType Sub169(2,3,3,3,3,4)
        ComplexType Sub45(3,3,3,3)
        ComplexType Sub177(2,3,3,3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qdbarqubar_nIxJqubarqubar_varXa/ Opt5, Opt6, Opt7, Opt8, Sub25, Sub44, Sub154
        common /qdbarqubar_nIxJqubarqubar_varXa/ Sub160, Sub161, Sub162, Sub165, Sub166
        common /qdbarqubar_nIxJqubarqubar_varXa/ Sub168, Sub169, Sub45, Sub177, S, T, T14, T15
        common /qdbarqubar_nIxJqubarqubar_varXa/ U, T24, T25, S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, F107, F108, F109, F110, F111
        HelType F112, F113, F114, F115, F116, F117, F118, F119, F120
        HelType F121, F122, F123, F124, F125, F126, F127, F128, F129
        HelType F130, F131, F132, F133, F134, F135, F136
        HelType Sub4(HelDim(3),4,2)
        HelType Sub5(HelDim(3),3,2,2)
        HelType Sub8(HelDim(3),3,2,2)
        HelType Sub13(HelDim(3),4,2)
        HelType Sub14(HelDim(3),3,2,2)
        HelType Sub15(HelDim(3),3,2,2)
        HelType Sub16(HelDim(2),3,3,2), Sub17, Sub18, Sub20
        HelType Sub21, Sub23(HelDim(2),4)
        HelType Sub26(HelDim(2),4), Sub27(HelDim(2),4)
        HelType Sub28(HelDim(2),4), Sub29
        HelType Sub30(HelDim(2),4), Sub31
        HelType Sub32(HelDim(2),4), Sub33, Sub34
        HelType Sub35(HelDim(2),4), Sub36(HelDim(2),4)
        HelType Sub37, Sub38, Sub40(HelDim(2))
        HelType Sub41(HelDim(2)), Sub42(HelDim(2),3,3,2)
        HelType Sub46, Sub47, Sub48, Sub49, Sub50(HelDim(2),4)
        HelType Sub51(HelDim(2),4), Sub53(HelDim(2),3,2)
        HelType Sub54, Sub55(HelDim(2),4), Sub56
        HelType Sub57(HelDim(2),4), Sub58, Sub59
        HelType Sub60(HelDim(2),4), Sub61(HelDim(2),4)
        HelType Sub66(HelDim(3),4,2), Sub67, Sub68
        HelType Sub69(HelDim(3),4,2)
        HelType Sub70(HelDim(3),4,2)
        HelType Sub71(HelDim(2),3,2)
        HelType Sub72(HelDim(3),4,2), Sub73, Sub75
        HelType Sub76(HelDim(2)), Sub77(HelDim(2))
        HelType Sub78(HelDim(2),3,3,2)
        HelType Sub80(HelDim(2),3,2)
        HelType Sub81(HelDim(3),4,2), Sub82, Sub83
        HelType Sub84(HelDim(3),4,2)
        HelType Sub85(HelDim(3),4,2), Sub86, Sub87
        HelType Sub88(HelDim(2)), Sub89(HelDim(2))
        HelType Sub90(HelDim(2),3,3,2), Sub91, Sub92
        HelType Sub93(HelDim(3),4,2), Sub94, Sub95
        HelType Sub97(HelDim(2),3,3,2)
        HelType Sub101(HelDim(3),4,2)
        HelType Sub102(HelDim(3),3,2,2)
        HelType Sub103(HelDim(3),3,2,2)
        HelType Sub104(HelDim(3),4,2), Sub105, Sub106
        HelType Sub107(HelDim(3),4,2)
        HelType Sub108(HelDim(3),4,2)
        HelType Sub112(HelDim(3),4,2)
        HelType Sub113(HelDim(3),3,2,2)
        HelType Sub114(HelDim(3),3,2,2)
        HelType Sub122(HelDim(2),4)
        HelType Sub123(HelDim(3),3,2,2)
        HelType Sub124(HelDim(3),3,2,2)
        HelType Sub125(HelDim(2),3,3,2)
        HelType Sub126(HelDim(3),3,2,2)
        HelType Sub127(HelDim(3),3,2,2), Sub128, Sub129
        HelType Sub130(HelDim(3)), Sub134(HelDim(3),4,2)
        HelType Sub135(HelDim(3),3,2,2)
        HelType Sub136(HelDim(3),3,2,2)
        HelType Sub137(HelDim(3),3,2,2)
        HelType Sub138(HelDim(3),3,2,2)
        HelType Sub139(HelDim(2),3,3,2), Sub143, Sub144
        HelType Sub145(HelDim(3)), Sub146(HelDim(3))
        HelType Sub147(HelDim(2),4), Sub148(HelDim(3))
        HelType Sub172(HelDim(2),3,3,3,3,4)
        HelType Sub175(HelDim(2),3,3,3,4)
        HelType Sub176(HelDim(2),3,3,3,3,4)
        HelType Sub178(HelDim(2),3,3,3,3,4)
        HelType Sub179(HelDim(2),3,3,3,4)
        HelType Sub180(HelDim(2),3,3,3,3,4)
        HelType Sub183(HelDim(2),3,3,3,3,4)
        HelType Sub186(HelDim(2),3,3,3,3,4)
        HelType Sub187(HelDim(2),3,3,3,3,4)
        HelType Sub199(HelDim(2),3,3,4,2)
        HelType Sub209(HelDim(3),3,3,4,2,2), Sub115
        HelType Sub118, Sub121(HelDim(3),3), Sub140, Sub141
        HelType Sub142(HelDim(3),3), Sub149(HelDim(3),3)
        HelType Sub150(HelDim(2),3,3,4)
        HelType Sub151(HelDim(3),3)
        HelType Sub152(HelDim(2),3,3,4)
        HelType Sub167(HelDim(2),3,3,3,3,4)
        HelType Sub170(HelDim(2),3,3,3,3,4)
        HelType Sub171(HelDim(2),3,3,3,3,4)
        HelType Sub173(HelDim(2),3,3,3,3,4)
        HelType Sub174(HelDim(2),3,3,3,3,4)
        HelType Sub181(HelDim(2),3,3,3,3,4)
        HelType Sub182(HelDim(2),3,3,3,3,4)
        HelType Sub184(HelDim(2),3,3,3,3,4)
        HelType Sub185(HelDim(2),3,3,3,3,4)
        HelType Sub188(HelDim(2),3,3,3,3,4)
        common /qdbarqubar_nIxJqubarqubar_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /qdbarqubar_nIxJqubarqubar_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /qdbarqubar_nIxJqubarqubar_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /qdbarqubar_nIxJqubarqubar_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /qdbarqubar_nIxJqubarqubar_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /qdbarqubar_nIxJqubarqubar_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /qdbarqubar_nIxJqubarqubar_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /qdbarqubar_nIxJqubarqubar_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /qdbarqubar_nIxJqubarqubar_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /qdbarqubar_nIxJqubarqubar_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /qdbarqubar_nIxJqubarqubar_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /qdbarqubar_nIxJqubarqubar_varXh/ F102, F103, F104, F105, F106, F107, F108
        common /qdbarqubar_nIxJqubarqubar_varXh/ F109, F110, F111, F112, F113, F114, F115
        common /qdbarqubar_nIxJqubarqubar_varXh/ F116, F117, F118, F119, F120, F121, F122
        common /qdbarqubar_nIxJqubarqubar_varXh/ F123, F124, F125, F126, F127, F128, F129
        common /qdbarqubar_nIxJqubarqubar_varXh/ F130, F131, F132, F133, F134, F135, F136
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub4, Sub5, Sub8, Sub13, Sub14, Sub15, Sub16
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub17, Sub18, Sub20, Sub21, Sub23, Sub26
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub27, Sub28, Sub29, Sub30, Sub31, Sub32
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub33, Sub34, Sub35, Sub36, Sub37, Sub38
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub40, Sub41, Sub42, Sub46, Sub47, Sub48
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub49, Sub50, Sub51, Sub53, Sub54, Sub55
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub56, Sub57, Sub58, Sub59, Sub60, Sub61
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub66, Sub67, Sub68, Sub69, Sub70, Sub71
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub72, Sub73, Sub75, Sub76, Sub77, Sub78
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub80, Sub81, Sub82, Sub83, Sub84, Sub85
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub86, Sub87, Sub88, Sub89, Sub90, Sub91
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub92, Sub93, Sub94, Sub95, Sub97, Sub101
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub102, Sub103, Sub104, Sub105, Sub106
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub107, Sub108, Sub112, Sub113, Sub114
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub122, Sub123, Sub124, Sub125, Sub126
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub127, Sub128, Sub129, Sub130, Sub134
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub135, Sub136, Sub137, Sub138, Sub139
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub143, Sub144, Sub145, Sub146, Sub147
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub148, Sub172, Sub175, Sub176, Sub178
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub179, Sub180, Sub183, Sub186, Sub187
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub199, Sub209, Sub115, Sub118, Sub121
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub140, Sub141, Sub142, Sub149, Sub150
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub151, Sub152, Sub167, Sub170, Sub171
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub173, Sub174, Sub181, Sub182, Sub184
        common /qdbarqubar_nIxJqubarqubar_varXh/ Sub185, Sub188

        integer Sfe7, Sfe8
        common /qdbarqubar_nIxJqubarqubar_indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdbarqubar_nIxJqubarqubar_formfactors/ Ctree, MatSUN

#endif

