#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 23-Oct-2017 10:55
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub1(4), Sub2(3,4,2)
        ComplexType Sub3(3,4,2), Sub10(2,3,2)
        ComplexType Sub13(2,3,2), Sub148(3,2)
        ComplexType Sub150(3,2), Sub151(3,2)
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXs/ Sub1, Sub2, Sub3, Sub10, Sub13, Sub148, Sub150
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXs/ Sub151

        ComplexType Sub149(2,3,3)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXa/ Sub149, S, T, T14, T15, U, T24, T25, S34, S35
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXa/ S45

        HelType F2, F5, F11, F12, F13, F14, F15, F16, F17, F18, F19
        HelType F20, F21, F22, F23, F24, F25, F26
        HelType Sub4(HelDim(3),4,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub11(HelDim(2),3,2)
        HelType Sub12(HelDim(3),3,2,2)
        HelType Sub14(HelDim(3),3,2,2)
        HelType Sub15(HelDim(3),3,2,2)
        HelType Sub16(HelDim(2),3,3,2)
        HelType Sub152(HelDim(2),3,3,3,2,2)
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXh/ F2, F5, F11, F12, F13, F14, F15, F16, F17, F18
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXh/ F19, F20, F21, F22, F23, F24, F25, F26, Sub4
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXh/ Sub9, Sub11, Sub12, Sub14, Sub15, Sub16
        common /qdqubar_nIxJqdqdbar_356_Sq1_varXh/ Sub152

        integer Sfe8
        common /qdqubar_nIxJqdqdbar_356_Sq1_indices/ Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqubar_nIxJqdqdbar_356_Sq1_formfactors/ Ctree, MatSUN

#endif

