#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 15-May-2017 11:52
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub1(3,4,2), Sub2(3,4,2)
        ComplexType Sub3(3,4,2), Sub6(2,3,2)
        ComplexType Sub14(2,3,2), Sub143(3,2)
        ComplexType Sub150(3,2), Sub152(3,2)
        common /qdqubar_nIxJququbar_365_Sq1_varXs/ Sub1, Sub2, Sub3, Sub6, Sub14, Sub143, Sub150
        common /qdqubar_nIxJququbar_365_Sq1_varXs/ Sub152

        ComplexType Sub144(2,3,3,3,3,4)
        ComplexType Sub151(2,3,3)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qdqubar_nIxJququbar_365_Sq1_varXa/ Sub144, Sub151, S, T, T14, T15, U, T24, T25
        common /qdqubar_nIxJququbar_365_Sq1_varXa/ S34, S35, S45

        HelType F2, F5, F13, F20, F22, F23, F29, F30, F31, F32, F33
        HelType F34, F35, F36, F37, F38, F39, F40
        HelType Sub4(HelDim(3),4,2)
        HelType Sub15(HelDim(2),3,2)
        HelType Sub19(HelDim(2),3,3,2)
        HelType Sub20(HelDim(3),3,2,2)
        HelType Sub21(HelDim(3),3,2,2)
        HelType Sub22(HelDim(3),3,2,2)
        HelType Sub23(HelDim(3),3,2,2)
        HelType Sub154(HelDim(2),3,3,3,2,2)
        common /qdqubar_nIxJququbar_365_Sq1_varXh/ F2, F5, F13, F20, F22, F23, F29, F30, F31, F32
        common /qdqubar_nIxJququbar_365_Sq1_varXh/ F33, F34, F35, F36, F37, F38, F39, F40, Sub4
        common /qdqubar_nIxJququbar_365_Sq1_varXh/ Sub15, Sub19, Sub20, Sub21, Sub22, Sub23
        common /qdqubar_nIxJququbar_365_Sq1_varXh/ Sub154

        integer Sfe8
        common /qdqubar_nIxJququbar_365_Sq1_indices/ Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqubar_nIxJququbar_365_Sq1_formfactors/ Ctree, MatSUN

#endif

