#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 15-May-2017 11:53
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "realOS_decl.h"

#else

#include "realOS_decl.h"

        ComplexType Sub1(3,4,2), Sub2(3,4,2)
        ComplexType Sub3(3,4,2), Sub6(2,3,2)
        ComplexType Sub10(2,3,2), Sub146(3,2)
        ComplexType Sub148(3,2), Sub150(3,2)
        ComplexType Sub151(3,2), Sub155(3,2)
        ComplexType Sub156(3,2), Sub158(3,2)
        ComplexType Sub159(3,2)
        common /qubarqubar_nIxJqdbarqubar_3645_Sq1Sq2_varXs/ Sub1, Sub2, Sub3, Sub6, Sub10, Sub146, Sub148
        common /qubarqubar_nIxJqdbarqubar_3645_Sq1Sq2_varXs/ Sub150, Sub151, Sub155, Sub156, Sub158, Sub159

        ComplexType Opt1(3,4), Sub147(2,3,3,3,3,3), Sub153(2,3,3,3,3,4)
        ComplexType Sub154(2,3,3)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /qubarqubar_nIxJqdbarqubar_3645_Sq1Sq2_varXa/ Opt1, Sub147, Sub153, Sub154, S, T, T14, T15
        common /qubarqubar_nIxJqdbarqubar_3645_Sq1Sq2_varXa/ U, T24, T25, S34, S35, S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10
        HelType Sub4(HelDim(3),4,2)
        HelType Sub5(HelDim(3),3,2,2)
        HelType Sub7(HelDim(2),3,3,2)
        HelType Sub8(HelDim(3),3,2,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub11(HelDim(2),3,3,2)
        HelType Sub12(HelDim(3),3,2,2)
        common /qubarqubar_nIxJqdbarqubar_3645_Sq1Sq2_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, Sub4
        common /qubarqubar_nIxJqdbarqubar_3645_Sq1Sq2_varXh/ Sub5, Sub7, Sub8, Sub9, Sub11, Sub12

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qubarqubar_nIxJqdbarqubar_3645_Sq1Sq2_formfactors/ Ctree, MatSUN

#endif

