#if 0
* vars.h
* variable declarations
* generated by FormCalc 9.4 (7 Jun 2016) on 23-Oct-2017 10:57
#endif

#ifndef vars_h
#define vars_h

#define SQUAREDME
#define LEGS 6

#include "real_decl.h"

#else

#include "real_decl.h"

        ComplexType Sub1(4), Sub2(3,4,2), Sub3(3,4,2)
        ComplexType Sub6(2,3,2), Sub10(2,3,2)
        ComplexType Sub13(2,3,2), Sub17(3,4,2)
        ComplexType Sub18(3,4,2), Sub19(3,4,2)
        ComplexType Sub25(2,4), Sub26(2,4)
        ComplexType Sub31(3,3), Sub43(3,3)
        ComplexType Sub58(3,4,2), Sub59(3,4,2)
        ComplexType Sub60(3,4,2), Sub63(2,3,2)
        ComplexType Sub67(2,3,2), Sub69(2,3,2)
        ComplexType Sub70(4), Sub71(3,4,2)
        ComplexType Sub72(3,4,2), Sub80(2,3,2)
        ComplexType Sub91(2,3,2), Sub98(2,3,2)
        ComplexType Sub110(2,3,2), Sub119(4)
        ComplexType Sub120(2,4), Sub122(4)
        ComplexType Sub123(2,4), Sub145(3,2)
        ComplexType Sub147(3,2), Sub149(3,2), Sub150(3,2)
        ComplexType Sub152(3,2), Sub154(3,2), Sub155(3,2)
        ComplexType Sub184(3,2), Sub185(3,2), Sub188(3,2)
        ComplexType Sub189(3,2), Sub193(3,2), Sub200(3,2)
        common /quqdbar_nIxJququbar_varXs/ Sub1, Sub2, Sub3, Sub6, Sub10, Sub13, Sub17
        common /quqdbar_nIxJququbar_varXs/ Sub18, Sub19, Sub25, Sub26, Sub31, Sub43
        common /quqdbar_nIxJququbar_varXs/ Sub58, Sub59, Sub60, Sub63, Sub67, Sub69
        common /quqdbar_nIxJququbar_varXs/ Sub70, Sub71, Sub72, Sub80, Sub91, Sub98
        common /quqdbar_nIxJququbar_varXs/ Sub110, Sub119, Sub120, Sub122, Sub123
        common /quqdbar_nIxJququbar_varXs/ Sub145, Sub147, Sub149, Sub150, Sub152
        common /quqdbar_nIxJququbar_varXs/ Sub154, Sub155, Sub184, Sub185, Sub188
        common /quqdbar_nIxJququbar_varXs/ Sub189, Sub193, Sub200

        ComplexType Opt4(2,3,3,3), Sub44(2,3,4)
        ComplexType Sub144(3,3,4)
        ComplexType Sub146(2,3,3,3,3,4)
        ComplexType Sub153(2,3,3)
        ComplexType Sub157(2,3,3,3,3,4)
        ComplexType Sub159(2,3,3,3,3,4)
        ComplexType Sub160(2,3,4)
        ComplexType Sub161(2,3,3,3,3,4)
        ComplexType Sub163(3,3,3)
        ComplexType Sub32(2,3,3,4)
        ComplexType Sub45(3,3,3,3)
        ComplexType Sub173(2,3,3,3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /quqdbar_nIxJququbar_varXa/ Opt4, Sub44, Sub144, Sub146, Sub153, Sub157
        common /quqdbar_nIxJququbar_varXa/ Sub159, Sub160, Sub161, Sub163, Sub32, Sub45
        common /quqdbar_nIxJququbar_varXa/ Sub173, S, T, T14, T15, U, T24, T25, S34, S35
        common /quqdbar_nIxJququbar_varXa/ S45

        HelType F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12
        HelType F13, F14, F15, F16, F17, F18, F19, F20, F21, F22
        HelType F23, F24, F25, F26, F27, F28, F29, F30, F31, F32
        HelType F33, F34, F35, F36, F37, F38, F39, F40, F41, F42
        HelType F43, F44, F45, F46, F47, F48, F49, F50, F51, F52
        HelType F53, F54, F55, F56, F57, F58, F59, F60, F61, F62
        HelType F63, F64, F65, F66, F67, F68, F69, F70, F71, F72
        HelType F73, F74, F75, F76, F77, F78, F79, F80, F81, F82
        HelType F83, F84, F85, F86, F87, F88, F89, F90, F91, F92
        HelType F93, F94, F95, F96, F97, F98, F99, F100, F101, F102
        HelType F103, F104, F105, F106, F107, F108, F109, F110, F111
        HelType F112, F113, F114, F115, F116, F117, F118, F119, F120
        HelType F121, F122, F123, F124, F125, F126, F127, F128, F129
        HelType F130, F131, F132, Sub4(HelDim(3),4,2)
        HelType Sub5(HelDim(3),3,2,2)
        HelType Sub7(HelDim(3),3,2,2)
        HelType Sub8(HelDim(2),3,3,2)
        HelType Sub9(HelDim(3),3,2,2)
        HelType Sub11(HelDim(3),3,2,2)
        HelType Sub12(HelDim(2),3,2)
        HelType Sub14(HelDim(3),3,2,2)
        HelType Sub15(HelDim(3),3,2,2)
        HelType Sub16(HelDim(2),3,3,2)
        HelType Sub20(HelDim(3),4,2)
        HelType Sub21(HelDim(3),3,2,2)
        HelType Sub22(HelDim(3),3,2,2)
        HelType Sub23(HelDim(3),3,2,2)
        HelType Sub24(HelDim(3),3,2,2), Sub27, Sub28
        HelType Sub29(HelDim(2),4), Sub30(HelDim(2),4)
        HelType Sub33(HelDim(2),4), Sub34(HelDim(2),4)
        HelType Sub35(HelDim(2),4), Sub36, Sub37, Sub38, Sub39
        HelType Sub40, Sub41(HelDim(2),4)
        HelType Sub42(HelDim(2),4), Sub46, Sub47, Sub48, Sub49
        HelType Sub50(HelDim(2),4), Sub51(HelDim(2),4)
        HelType Sub52, Sub53, Sub54, Sub55(HelDim(2),4)
        HelType Sub56(HelDim(2),4), Sub57
        HelType Sub61(HelDim(3),4,2), Sub62
        HelType Sub64(HelDim(2)), Sub65(HelDim(2))
        HelType Sub66(HelDim(2),3,3,2)
        HelType Sub68(HelDim(2),3,2)
        HelType Sub73(HelDim(3),4,2), Sub74, Sub75
        HelType Sub76(HelDim(3),4,2)
        HelType Sub77(HelDim(3),4,2)
        HelType Sub78(HelDim(2),3,2)
        HelType Sub79(HelDim(3),4,2), Sub81, Sub82
        HelType Sub83(HelDim(3),4,2)
        HelType Sub84(HelDim(2),3,2)
        HelType Sub85(HelDim(3),4,2), Sub86, Sub87
        HelType Sub88(HelDim(3),4,2)
        HelType Sub89(HelDim(3),4,2), Sub90, Sub92
        HelType Sub93(HelDim(2)), Sub94(HelDim(2))
        HelType Sub95(HelDim(2),3,3,2), Sub96, Sub97
        HelType Sub99(HelDim(2),3,3,2)
        HelType Sub100(HelDim(3),4,2), Sub101, Sub102
        HelType Sub103(HelDim(3),4,2)
        HelType Sub104(HelDim(3),4,2), Sub105, Sub106
        HelType Sub107(HelDim(2)), Sub108(HelDim(2))
        HelType Sub109(HelDim(2),3,3,2)
        HelType Sub111(HelDim(3),3,2,2)
        HelType Sub112(HelDim(3),3,2,2)
        HelType Sub113(HelDim(2),3,2)
        HelType Sub114(HelDim(3),3,2,2)
        HelType Sub116(HelDim(3),3,2,2)
        HelType Sub125(HelDim(2),4)
        HelType Sub126(HelDim(3),3,2,2)
        HelType Sub127(HelDim(3),3,2,2)
        HelType Sub128(HelDim(2),3,3,4,2,2), Sub130
        HelType Sub132, Sub133, Sub134(HelDim(3),3), Sub135
        HelType Sub136, Sub137(HelDim(3))
        HelType Sub138(HelDim(3),3), Sub139(HelDim(2),4)
        HelType Sub143(HelDim(3))
        HelType Sub156(HelDim(2),3,3,3,2,2)
        HelType Sub158(HelDim(2),3,3,3,2,2)
        HelType Sub170(HelDim(2),3,3,3,3,4)
        HelType Sub171(HelDim(2),3,3,3,4)
        HelType Sub172(HelDim(2),3,3,3,3,4)
        HelType Sub174(HelDim(2),3,3,3,3,4)
        HelType Sub175(HelDim(2),3,3,3,3,4)
        HelType Sub176(HelDim(2),3,3,3,3,4)
        HelType Sub182(HelDim(2),3,3,3,3,4)
        HelType Sub192(HelDim(2),3,3,4,2)
        HelType Sub194(HelDim(3),3,3,4,2), Sub118
        HelType Sub121, Sub124(HelDim(3)), Sub129
        HelType Sub131(HelDim(3),3), Sub140(HelDim(3),3)
        HelType Sub141(HelDim(2),3,3,4)
        HelType Sub142(HelDim(3))
        HelType Sub162(HelDim(2),3,3,3,3,4)
        HelType Sub164(HelDim(2),3,3,3,3,4)
        HelType Sub165(HelDim(2),3,3,3,3,4)
        HelType Sub166(HelDim(2),3,3,3,3,4)
        HelType Sub167(HelDim(2),3,3,3,3,4)
        HelType Sub168(HelDim(2),3,3,3,3,4)
        HelType Sub169(HelDim(2),3,3,3,3,4)
        HelType Sub177(HelDim(2),3,3,3,3,4)
        HelType Sub178(HelDim(2),3,3,3,3,4)
        HelType Sub179(HelDim(2),3,3,3,3,4)
        HelType Sub180(HelDim(2),3,3,3,3,4)
        HelType Sub181(HelDim(2),3,3,3,3,4)
        HelType Sub183(HelDim(2),3,3,3,3,4)
        common /quqdbar_nIxJququbar_varXh/ F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11
        common /quqdbar_nIxJququbar_varXh/ F12, F13, F14, F15, F16, F17, F18, F19, F20
        common /quqdbar_nIxJququbar_varXh/ F21, F22, F23, F24, F25, F26, F27, F28, F29
        common /quqdbar_nIxJququbar_varXh/ F30, F31, F32, F33, F34, F35, F36, F37, F38
        common /quqdbar_nIxJququbar_varXh/ F39, F40, F41, F42, F43, F44, F45, F46, F47
        common /quqdbar_nIxJququbar_varXh/ F48, F49, F50, F51, F52, F53, F54, F55, F56
        common /quqdbar_nIxJququbar_varXh/ F57, F58, F59, F60, F61, F62, F63, F64, F65
        common /quqdbar_nIxJququbar_varXh/ F66, F67, F68, F69, F70, F71, F72, F73, F74
        common /quqdbar_nIxJququbar_varXh/ F75, F76, F77, F78, F79, F80, F81, F82, F83
        common /quqdbar_nIxJququbar_varXh/ F84, F85, F86, F87, F88, F89, F90, F91, F92
        common /quqdbar_nIxJququbar_varXh/ F93, F94, F95, F96, F97, F98, F99, F100, F101
        common /quqdbar_nIxJququbar_varXh/ F102, F103, F104, F105, F106, F107, F108
        common /quqdbar_nIxJququbar_varXh/ F109, F110, F111, F112, F113, F114, F115
        common /quqdbar_nIxJququbar_varXh/ F116, F117, F118, F119, F120, F121, F122
        common /quqdbar_nIxJququbar_varXh/ F123, F124, F125, F126, F127, F128, F129
        common /quqdbar_nIxJququbar_varXh/ F130, F131, F132, Sub4, Sub5, Sub7, Sub8
        common /quqdbar_nIxJququbar_varXh/ Sub9, Sub11, Sub12, Sub14, Sub15, Sub16
        common /quqdbar_nIxJququbar_varXh/ Sub20, Sub21, Sub22, Sub23, Sub24, Sub27
        common /quqdbar_nIxJququbar_varXh/ Sub28, Sub29, Sub30, Sub33, Sub34, Sub35
        common /quqdbar_nIxJququbar_varXh/ Sub36, Sub37, Sub38, Sub39, Sub40, Sub41
        common /quqdbar_nIxJququbar_varXh/ Sub42, Sub46, Sub47, Sub48, Sub49, Sub50
        common /quqdbar_nIxJququbar_varXh/ Sub51, Sub52, Sub53, Sub54, Sub55, Sub56
        common /quqdbar_nIxJququbar_varXh/ Sub57, Sub61, Sub62, Sub64, Sub65, Sub66
        common /quqdbar_nIxJququbar_varXh/ Sub68, Sub73, Sub74, Sub75, Sub76, Sub77
        common /quqdbar_nIxJququbar_varXh/ Sub78, Sub79, Sub81, Sub82, Sub83, Sub84
        common /quqdbar_nIxJququbar_varXh/ Sub85, Sub86, Sub87, Sub88, Sub89, Sub90
        common /quqdbar_nIxJququbar_varXh/ Sub92, Sub93, Sub94, Sub95, Sub96, Sub97
        common /quqdbar_nIxJququbar_varXh/ Sub99, Sub100, Sub101, Sub102, Sub103, Sub104
        common /quqdbar_nIxJququbar_varXh/ Sub105, Sub106, Sub107, Sub108, Sub109
        common /quqdbar_nIxJququbar_varXh/ Sub111, Sub112, Sub113, Sub114, Sub116
        common /quqdbar_nIxJququbar_varXh/ Sub125, Sub126, Sub127, Sub128, Sub130
        common /quqdbar_nIxJququbar_varXh/ Sub132, Sub133, Sub134, Sub135, Sub136
        common /quqdbar_nIxJququbar_varXh/ Sub137, Sub138, Sub139, Sub143, Sub156
        common /quqdbar_nIxJququbar_varXh/ Sub158, Sub170, Sub171, Sub172, Sub174
        common /quqdbar_nIxJququbar_varXh/ Sub175, Sub176, Sub182, Sub192, Sub194
        common /quqdbar_nIxJququbar_varXh/ Sub118, Sub121, Sub124, Sub129, Sub131
        common /quqdbar_nIxJququbar_varXh/ Sub140, Sub141, Sub142, Sub162, Sub164
        common /quqdbar_nIxJququbar_varXh/ Sub165, Sub166, Sub167, Sub168, Sub169
        common /quqdbar_nIxJququbar_varXh/ Sub177, Sub178, Sub179, Sub180, Sub181, Sub183

        integer Sfe7, Sfe8
        common /quqdbar_nIxJququbar_indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /quqdbar_nIxJququbar_formfactors/ Ctree, MatSUN

#endif

