c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  1,  4/          !  MT1     WT1     
      data tprid(  -1,   1) / 1000006/
      data(iforest(i, -2,   1),i=1,2) / -1,  3/          !  BMASS   ZERO    
      data tprid(  -2,   1) /      -5/
      data(iforest(i, -3,   1),i=1,2) / -2,  5/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  1,  4/          !  MT2     WT2     
      data tprid(  -1,   2) / 2000006/
      data(iforest(i, -2,   2),i=1,2) / -1,  3/          !  BMASS   ZERO    
      data tprid(  -2,   2) /      -5/
      data(iforest(i, -3,   2),i=1,2) / -2,  5/          !  
c   Graph      3
      data mapconfig(   3) /   3/
      data(iforest(i, -1,   3),i=1,2) /  5,  3/          !  MT1     WT1     
      data sprop(  -1,   3) / 1000006/
      data(iforest(i, -2,   3),i=1,2) /  1,  4/          !  MT1     WT1     
      data tprid(  -2,   3) / 1000006/
      data(iforest(i, -3,   3),i=1,2) / -2, -1/          !  
c   Graph      4
      data mapconfig(   4) /   4/
      data(iforest(i, -1,   4),i=1,2) /  5,  3/          !  MT2     WT2     
      data sprop(  -1,   4) / 2000006/
      data(iforest(i, -2,   4),i=1,2) /  1,  4/          !  MT2     WT2     
      data tprid(  -2,   4) / 2000006/
      data(iforest(i, -3,   4),i=1,2) / -2, -1/          !  
c   Graph      5
      data mapconfig(   5) /   5/
      data(iforest(i, -1,   5),i=1,2) /  5,  3/          !  MT1     WT1     
      data sprop(  -1,   5) / 1000006/
      data(iforest(i, -2,   5),i=1,2) /  4, -1/          !  BMASS   ZERO    
      data sprop(  -2,   5) /       5/
c   Graph      6
      data mapconfig(   6) /   6/
      data(iforest(i, -1,   6),i=1,2) /  5,  3/          !  MT2     WT2     
      data sprop(  -1,   6) / 2000006/
      data(iforest(i, -2,   6),i=1,2) /  4, -1/          !  BMASS   ZERO    
      data sprop(  -2,   6) /       5/
c   Graph      7
      data mapconfig(   7) /   7/
      data(iforest(i, -1,   7),i=1,2) /  4,  3/          !  ZERO    AWIDTH  
      data sprop(  -1,   7) /      22/
      data(iforest(i, -2,   7),i=1,2) /  1, -1/          !  BMASS   ZERO    
      data tprid(  -2,   7) /      -5/
      data(iforest(i, -3,   7),i=1,2) / -2,  5/          !  
c   Graph      8
      data mapconfig(   8) /   8/
      data(iforest(i, -1,   8),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data sprop(  -1,   8) /      23/
      data(iforest(i, -2,   8),i=1,2) /  1, -1/          !  BMASS   ZERO    
      data tprid(  -2,   8) /      -5/
      data(iforest(i, -3,   8),i=1,2) / -2,  5/          !  
c   Graph      9
      data mapconfig(   9) /   9/
      data(iforest(i, -1,   9),i=1,2) /  4,  3/          !  MH1     WH1     
      data sprop(  -1,   9) /      25/
      data(iforest(i, -2,   9),i=1,2) /  1, -1/          !  BMASS   ZERO    
      data tprid(  -2,   9) /      -5/
      data(iforest(i, -3,   9),i=1,2) / -2,  5/          !  
c   Graph     10
      data mapconfig(  10) /  10/
      data(iforest(i, -1,  10),i=1,2) /  4,  3/          !  MH2     WH2     
      data sprop(  -1,  10) /      35/
      data(iforest(i, -2,  10),i=1,2) /  1, -1/          !  BMASS   ZERO    
      data tprid(  -2,  10) /      -5/
      data(iforest(i, -3,  10),i=1,2) / -2,  5/          !  
c   Graph     11
      data mapconfig(  11) /  11/
      data(iforest(i, -1,  11),i=1,2) /  4,  3/          !  MH3     WH3     
      data sprop(  -1,  11) /      36/
      data(iforest(i, -2,  11),i=1,2) /  1, -1/          !  BMASS   ZERO    
      data tprid(  -2,  11) /      -5/
      data(iforest(i, -3,  11),i=1,2) / -2,  5/          !  
c   Graph     12
      data mapconfig(  12) /  12/
      data(iforest(i, -1,  12),i=1,2) /  4,  3/          !  ZERO    AWIDTH  
      data sprop(  -1,  12) /      22/
      data(iforest(i, -2,  12),i=1,2) /  5, -1/          !  BMASS   ZERO    
      data sprop(  -2,  12) /       5/
c   Graph     13
      data mapconfig(  13) /  13/
      data(iforest(i, -1,  13),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data sprop(  -1,  13) /      23/
      data(iforest(i, -2,  13),i=1,2) /  5, -1/          !  BMASS   ZERO    
      data sprop(  -2,  13) /       5/
c   Graph     14
      data mapconfig(  14) /  14/
      data(iforest(i, -1,  14),i=1,2) /  4,  3/          !  MH1     WH1     
      data sprop(  -1,  14) /      25/
      data(iforest(i, -2,  14),i=1,2) /  5, -1/          !  BMASS   ZERO    
      data sprop(  -2,  14) /       5/
c   Graph     15
      data mapconfig(  15) /  15/
      data(iforest(i, -1,  15),i=1,2) /  4,  3/          !  MH2     WH2     
      data sprop(  -1,  15) /      35/
      data(iforest(i, -2,  15),i=1,2) /  5, -1/          !  BMASS   ZERO    
      data sprop(  -2,  15) /       5/
c   Graph     16
      data mapconfig(  16) /  16/
      data(iforest(i, -1,  16),i=1,2) /  4,  3/          !  MH3     WH3     
      data sprop(  -1,  16) /      36/
      data(iforest(i, -2,  16),i=1,2) /  5, -1/          !  BMASS   ZERO    
      data sprop(  -2,  16) /       5/
      data mapconfig(   0) /  16/
