#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Oct-2016 12:29
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub9(4), Sub2(4), Sub5(4), Sub14(4)
        ComplexType Sub289(3,3), Sub67(3,3)
        ComplexType Sub763(3,2), Sub752(3,2), Sub38(4,4)
        ComplexType Sub39(4,4), Sub10(3,4,2)
        ComplexType Sub11(3,4,2), Sub6(3,4,2)
        ComplexType Sub7(3,4,2), Sub1(3,4,2)
        ComplexType Sub3(3,4,2), Sub13(3,4,2)
        ComplexType Sub15(3,4,2), Sub219(3,3)
        ComplexType Sub638(3,4), Sub441(3,4)
        ComplexType Sub660(3,4), Sub743(3,4)
        ComplexType Sub71(3,3,4), Sub49(3,3,4)
        ComplexType Sub52(3,3,4)
        ComplexType Sub207(3,3,4,4)
        common /varXs/ Sub9, Sub2, Sub5, Sub14, Sub289, Sub67, Sub763
        common /varXs/ Sub752, Sub38, Sub39, Sub10, Sub11, Sub6
        common /varXs/ Sub7, Sub1, Sub3, Sub13, Sub15, Sub219
        common /varXs/ Sub638, Sub441, Sub660, Sub743, Sub71, Sub49
        common /varXs/ Sub52, Sub207

        ComplexType Opt2(3,4,4), Opt3
        ComplexType Sub392(3,3,4)
        ComplexType Sub278(3,3,4,4), Sub773(3,4)
        ComplexType Sub779(3,4), Sub757(3,4)
        ComplexType Sub759(3,4), Sub50(3,3,4,4)
        ComplexType Sub391(3,4,4)
        ComplexType Sub564(3,3,4,4)
        ComplexType Sub677(3,3,4,4)
        ComplexType Sub699(3,3,4,4)
        ComplexType Sub778(3,3,4,4)
        ComplexType Sub755(3,3,4,4)
        ComplexType Sub754(3,3,4,4)
        ComplexType Sub488(3,3,4,4)
        ComplexType Sub208(3,3,4,4)
        ComplexType Sub729(3,3,4,4)
        ComplexType Sub714(3,3,4,4)
        ComplexType Sub753(3,3,4,4)
        ComplexType Sub606(3,3,4,4)
        ComplexType Sub764(3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt2, Opt3, Sub392, Sub278, Sub773, Sub779
        common /varXa/ Sub757, Sub759, Sub50, Sub391, Sub564, Sub677
        common /varXa/ Sub699, Sub778, Sub755, Sub754, Sub488
        common /varXa/ Sub208, Sub729, Sub714, Sub753, Sub606
        common /varXa/ Sub764, S, T, T14, T15, U, T24, T25, S34, S35
        common /varXa/ S45

        HelType F14, F27, F103, F11, F25, F101, F33, F37, F29, F32
        HelType F38, F81, F16, F34, F82, F10, F2, F18, F63, F52
        HelType F116, F65, F134, F167, F137, F175, F107, F135, F108
        HelType F181, F176, F5, F19, F45, F73, F118, F47, F139, F168
        HelType F133, F177, F99, F156, F100, F182, F178, F183, F17
        HelType F202, F193, F194, F184, F20, F204, F198, F199, F74
        HelType F152, F189, F70, F79, F1, F71, F85, F228, F86, F221
        HelType F76, F222, F44, F53, F149, F190, F49, F80, F7, F50
        HelType F87, F230, F88, F225, F55, F226, F48, F40, F109, F57
        HelType F12, F30, F104, F121, F83, F67, F84, F141, F122
        HelType F148, F169, F155, F123, F153, F68, F154, F142, F124
        HelType F171, F138, F179, F172, F36, F110, F77, F13, F31
        HelType F102, F127, F89, F42, F90, F146, F128, F158, F170
        HelType F157, F129, F165, F43, F166, F147, F130, F173, F164
        HelType F180, F174, F187, F185, F215, F216, F21, F22, F23
        HelType F207, F208, F188, F186, F217, F218, F24, F26, F28
        HelType F211, F212, F39, F213, F59, F196, F239, F136, F240
        HelType F60, F3, F4, F61, F6, F233, F62, F234, F35, F214
        HelType F92, F200, F241, F163, F242, F93, F8, F9, F94, F15
        HelType F237, F95, F238, F51, F115, F64, F111, F143, F56
        HelType F144, F131, F112, F105, F106, F150, F151, F72, F117
        HelType F46, F113, F161, F78, F162, F132, F114, F97, F98
        HelType F159, F160, F201, F191, F192, F203, F195, F197, F69
        HelType F227, F219, F75, F220, F41, F229, F223, F54, F224
        HelType F119, F66, F140, F120, F125, F96, F145, F126, F205
        HelType F206, F209, F210, F231, F58, F232, F235, F91, F236
        HelType Pair4, Pair3, Pair5, Pair6, Pair7, Pair11, Pair10
        HelType Pair8, Pair9, Pair1, Pair2, Abb1, Abb2, Abb15, Abb3
        HelType Abb26, Abb19, Abb11, Abb23, Abb24, Abb30, Abb22
        HelType Abb28, Abb21, Abb10, Abb17, Abb9, Abb14, Abb25
        HelType Abb27, Abb34, Abb4, Abb18, Abb32, Abb13, Abb20, Abb8
        HelType Abb7, Abb29, Abb16, Abb6, Abb33, Abb12, Abb31, Abb5
        HelType Opt1(HelDim(4)), Opt4(HelDim(3),3)
        HelType Opt5(HelDim(3),3), Sub379, Sub420, Sub217
        HelType Sub190, Sub394, Sub565, Sub389, Sub146, Sub387
        HelType Sub384, Sub422, Sub418, Sub731, Sub440, Sub444
        HelType Sub641, Sub349, Sub637, Sub335, Sub313, Sub299
        HelType Sub274, Sub285, Sub244, Sub247, Sub90, Sub106, Sub65
        HelType Sub104, Sub55, Sub119, Sub475, Sub116, Sub461
        HelType Sub161, Sub148, Sub674, Sub680, Sub669, Sub671
        HelType Sub696, Sub691, Sub693, Sub701, Sub746, Sub212
        HelType Sub268, Sub297, Sub283, Sub307, Sub355, Sub545
        HelType Sub553, Sub363, Sub206, Sub218, Sub365, Sub401
        HelType Sub603, Sub602, Sub424, Sub112, Sub171, Sub137
        HelType Sub464, Sub390, Sub110, Sub462, Sub404, Sub152
        HelType Sub410, Sub205, Sub556, Sub478, Sub514, Sub679
        HelType Sub371, Sub368, Sub540, Sub537, Sub583, Sub574
        HelType Sub510, Sub499, Sub732, Sub585, Sub402, Sub561
        HelType Sub414, Sub725, Sub710, Sub711, Sub512, Sub486
        HelType Sub726, Sub386, Sub70, Sub173, Sub51, Sub395, Sub426
        HelType Sub523, Sub467, Sub457, Sub411, Sub267, Sub143
        HelType Sub158, Sub221, Sub269, Sub284, Sub298, Sub308
        HelType Sub385, Sub471, Sub491, Sub350(HelDim(3))
        HelType Sub336(HelDim(3)), Sub28(HelDim(3))
        HelType Sub26(HelDim(3)), Sub330(HelDim(3))
        HelType Sub276(HelDim(3)), Sub356(HelDim(3))
        HelType Sub316(HelDim(3)), Sub237(HelDim(3))
        HelType Sub236(HelDim(3)), Sub233(HelDim(3))
        HelType Sub337(HelDim(3)), Sub287(HelDim(3))
        HelType Sub351(HelDim(3)), Sub301(HelDim(3))
        HelType Sub232(HelDim(3)), Sub650(HelDim(3))
        HelType Sub300(HelDim(3)), Sub317(HelDim(3))
        HelType Sub270(HelDim(3)), Sub290(HelDim(3))
        HelType Sub286(HelDim(3)), Sub277(HelDim(3))
        HelType Sub309(HelDim(3)), Sub303(HelDim(3))
        HelType Sub562(HelDim(3)), Sub271(HelDim(3))
        HelType Sub310(HelDim(3)), Sub195(HelDim(4))
        HelType Sub721(HelDim(4)), Sub720(HelDim(4))
        HelType Sub747(HelDim(4)), Sub686(HelDim(4))
        HelType Sub633(HelDim(3),4), Sub635(HelDim(3),4)
        HelType Sub305(HelDim(3),4), Sub292(HelDim(3),4)
        HelType Sub436(HelDim(3),4), Sub438(HelDim(3),4)
        HelType Sub415(HelDim(3),4), Sub655(HelDim(3),4)
        HelType Sub657(HelDim(3),4), Sub738(HelDim(3),4)
        HelType Sub740(HelDim(3),4), Sub177(HelDim(4),4)
        HelType Sub229(HelDim(4),4), Sub431(HelDim(4),4)
        HelType Sub181(HelDim(4),4), Sub40(HelDim(4),4)
        HelType Sub364(HelDim(4),4), Sub111(HelDim(4),4)
        HelType Sub182(HelDim(4),4), Sub41(HelDim(4),4)
        HelType Sub113(HelDim(4),4), Sub366(HelDim(4),4)
        HelType Sub451(HelDim(4),4), Sub454(HelDim(4),4)
        HelType Sub533(HelDim(4),4), Sub535(HelDim(4),4)
        HelType Sub75(HelDim(4),4), Sub527(HelDim(4),4)
        HelType Sub597(HelDim(4),4)
        HelType Sub327(HelDim(3),3,4)
        HelType Sub344(HelDim(3),3,4)
        HelType Sub352(HelDim(3),3,4)
        HelType Sub338(HelDim(3),3,4)
        HelType Sub416(HelDim(3),3,4)
        HelType Sub325(HelDim(3),3,4)
        HelType Sub347(HelDim(3),3,4)
        HelType Sub118(HelDim(3),4,4)
        HelType Sub123(HelDim(3),4,4)
        HelType Sub128(HelDim(3),4,4)
        HelType Sub156(HelDim(3),4,4)
        HelType Sub44(HelDim(3),4,4)
        HelType Sub459(HelDim(3),4,4)
        HelType Sub47(HelDim(3),4,4)
        HelType Sub466(HelDim(3),4,4)
        HelType Sub473(HelDim(3),4,4)
        HelType Sub477(HelDim(3),4,4)
        HelType Sub528(HelDim(3),4,4)
        HelType Sub549(HelDim(3),4,4)
        HelType Sub555(HelDim(3),4,4)
        HelType Sub599(HelDim(3),4,4)
        HelType Sub12(HelDim(3),4,2)
        HelType Sub17(HelDim(3),4,2)
        HelType Sub100(HelDim(3),4,2)
        HelType Sub622(HelDim(3),4,2)
        HelType Sub646(HelDim(3),4,2)
        HelType Sub647(HelDim(3),4,2)
        HelType Sub103(HelDim(3),4,2)
        HelType Sub108(HelDim(3),4,2)
        HelType Sub21(HelDim(3),4,2)
        HelType Sub36(HelDim(3),4,2)
        HelType Sub234(HelDim(3),4,2)
        HelType Sub235(HelDim(3),4,2)
        HelType Sub626(HelDim(3),4,2)
        HelType Sub630(HelDim(3),4,2)
        HelType Sub636(HelDim(3),4,2)
        HelType Sub644(HelDim(3),4,2)
        HelType Sub645(HelDim(3),4,2)
        HelType Sub448(HelDim(3),4,2)
        HelType Sub616(HelDim(3),4,2)
        HelType Sub240(HelDim(3),4,2)
        HelType Sub612(HelDim(3),4,2)
        HelType Sub81(HelDim(3),4,2)
        HelType Sub8(HelDim(3),4,2)
        HelType Sub601(HelDim(3),4,2)
        HelType Sub604(HelDim(3),4,2)
        HelType Sub238(HelDim(3),4,2)
        HelType Sub243(HelDim(3),4,2)
        HelType Sub250(HelDim(3),4,2)
        HelType Sub439(HelDim(3),4,2)
        HelType Sub447(HelDim(3),4,2)
        HelType Sub615(HelDim(3),4,2)
        HelType Sub239(HelDim(3),4,2)
        HelType Sub87(HelDim(3),4,2)
        HelType Sub228(HelDim(3),4,4)
        HelType Sub433(HelDim(3),4,4)
        HelType Sub187(HelDim(3),4,4)
        HelType Sub193(HelDim(3),4,4)
        HelType Sub199(HelDim(3),4,4)
        HelType Sub204(HelDim(3),4,4)
        HelType Sub370(HelDim(3),4,4)
        HelType Sub375(HelDim(3),4,4)
        HelType Sub378(HelDim(3),4,4)
        HelType Sub383(HelDim(3),4,4)
        HelType Sub539(HelDim(3),4,4)
        HelType Sub544(HelDim(3),4,4)
        HelType Sub60(HelDim(3),4,4)
        HelType Sub64(HelDim(3),4,4)
        HelType Sub617(HelDim(3),4,2)
        HelType Sub709(HelDim(3),4,2)
        HelType Sub80(HelDim(3),4,2)
        HelType Sub4(HelDim(3),4,2)
        HelType Sub668(HelDim(3),4,2)
        HelType Sub712(HelDim(3),4,2)
        HelType Sub620(HelDim(3),4,2)
        HelType Sub708(HelDim(3),4,2)
        HelType Sub658(HelDim(3),4,2)
        HelType Sub666(HelDim(3),4,2)
        HelType Sub667(HelDim(3),4,2)
        HelType Sub673(HelDim(3),4,2)
        HelType Sub722(HelDim(3),4,2)
        HelType Sub723(HelDim(3),4,2)
        HelType Sub84(HelDim(3),4,2)
        HelType Sub98(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub623(HelDim(3),4,2)
        HelType Sub724(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub690(HelDim(3),4,2)
        HelType Sub727(HelDim(3),4,2)
        HelType Sub24(HelDim(3),4,2)
        HelType Sub629(HelDim(3),4,2)
        HelType Sub736(HelDim(3),4,2)
        HelType Sub688(HelDim(3),4,2)
        HelType Sub689(HelDim(3),4,2)
        HelType Sub695(HelDim(3),4,2)
        HelType Sub741(HelDim(3),4,2)
        HelType Sub750(HelDim(3),4,2)
        HelType Sub751(HelDim(3),4,2)
        HelType Sub768(HelDim(3),3,4,4)
        HelType Sub774(HelDim(3),3,4,4)
        HelType Sub179(HelDim(3),3,4,4)
        HelType Sub224(HelDim(3),3,4,4)
        HelType Sub321(HelDim(3),3,4,4)
        HelType Sub790(HelDim(3),3,4,4)
        HelType Sub361(HelDim(3),3,4,4)
        HelType Sub794(HelDim(3),3,4,4)
        HelType Sub151(HelDim(3),3,4,4)
        HelType Sub176(HelDim(3),3,4,4)
        HelType Sub216(HelDim(3),3,4,4)
        HelType Sub227(HelDim(3),3,4,4)
        HelType Sub258(HelDim(3),3,4,4)
        HelType Sub265(HelDim(3),3,4,4)
        HelType Sub294(HelDim(3),3,4,4)
        HelType Sub320(HelDim(3),3,4,4)
        HelType Sub328(HelDim(3),3,4,4)
        HelType Sub341(HelDim(3),3,4,4)
        HelType Sub348(HelDim(3),3,4,4)
        HelType Sub360(HelDim(3),3,4,4)
        HelType Sub407(HelDim(3),3,4,4)
        HelType Sub427(HelDim(3),3,4,4)
        HelType Sub430(HelDim(3),3,4,4)
        HelType Sub357(HelDim(3),3,4,4)
        HelType Sub332(HelDim(3),3,4,4)
        HelType Sub522(HelDim(3),3,4,4)
        HelType Sub139(HelDim(3),3,4,4)
        HelType Sub594(HelDim(3),3,4,4)
        HelType Sub393(HelDim(3),3,4,4)
        HelType Sub502(HelDim(3),3,4,4)
        HelType Sub526(HelDim(3),3,4,4)
        HelType Sub530(HelDim(3),3,4,4)
        HelType Sub795(HelDim(3),3,4,4)
        HelType Sub57(HelDim(3),3,4,4)
        HelType Sub577(HelDim(3),3,4,4)
        HelType Sub596(HelDim(3),3,4,4)
        HelType Sub77(HelDim(3),3,4,4)
        HelType Sub791(HelDim(3),3,4,4)
        HelType Sub74(HelDim(3),3,4,4)
        HelType Sub78(HelDim(3),3,4,4)
        HelType Sub792(HelDim(3),3,4,4)
        HelType Sub793(HelDim(3),3,4,4)
        HelType Sub93(HelDim(3),3,4,2)
        HelType Sub96(HelDim(3),3,4,2)
        HelType Sub30(HelDim(3),4,4,2)
        HelType Sub34(HelDim(3),4,4,2)
        HelType Sub776(HelDim(3),3,4,4,2)
        HelType Sub780(HelDim(3),3,4,4,2)
        HelType Sub35(HelDim(3),3,4,4,2)
        HelType Sub756(HelDim(3),3,4,4,2)
        HelType Sub621(HelDim(3),3,4,4,2)
        HelType Sub758(HelDim(3),3,4,4,2)
        HelType Sub631(HelDim(3),3,4,4,2)
        HelType Sub760(HelDim(3),3,4,4,2)
        HelType Sub782(HelDim(3),3,4,4,2)
        HelType Sub652(HelDim(3),3,4,4,2)
        HelType Sub762(HelDim(3),3,4,4,2)
        HelType Sub684(HelDim(3),3,4,4,2)
        HelType Sub770(HelDim(3),3,4,4,2)
        HelType Sub610(HelDim(3),3,4,4,2)
        HelType Sub706(HelDim(3),3,4,4,2)
        HelType Sub718(HelDim(3),3,4,4,2)
        HelType Sub786(HelDim(3),3,4,4,2)
        HelType Sub734(HelDim(3),3,4,4,2)
        HelType Sub783(HelDim(3),3,4,4,2)
        HelType Sub761(HelDim(3),3,4,4,2)
        HelType Sub765(HelDim(3),3,4,4,2)
        HelType Sub769(HelDim(3),3,4,4,2)
        HelType Sub775(HelDim(3),3,4,4,2)
        HelType Sub777(HelDim(3),3,4,4,2)
        HelType Sub781(HelDim(3),3,4,4,2)
        HelType Sub784(HelDim(3),3,4,4,2)
        HelType Sub787(HelDim(3),3,4,4,2)
        HelType Sub97(HelDim(3),3,4,4,2)
        HelType Sub788(HelDim(3),3,4,4,2), Sub509
        HelType Sub452, Sub560, Sub483, Sub592, Sub518, Sub498
        HelType Sub450, Sub505, Sub503, Sub480, Sub479, Sub273
        HelType Sub272, Sub266, Sub129, Sub397, Sub495, Sub493
        HelType Sub567, Sub281, Sub282, Sub142, Sub516, Sub515
        HelType Sub311, Sub295, Sub296, Sub157, Sub312, Sub165
        HelType Sub578, Sub315, Sub408, Sub373, Sub399, Sub413
        HelType Sub121, Sub169, Sub126, Sub140, Sub114, Sub135
        HelType Sub329, Sub551, Sub547, Sub532, Sub213, Sub534
        HelType Sub573, Sub453, Sub520, Sub485, Sub449, Sub125
        HelType Sub133, Sub130, Sub167, Sub223, Sub69, Sub588
        HelType Sub713, Sub716, Sub728, Sub521, Sub144, Sub159
        HelType Sub469, Sub131, Sub455, Sub62, Sub48, Sub489, Sub145
        HelType Sub134, Sub153, Sub166, Sub168, Sub398, Sub409
        HelType Sub419, Sub497, Sub507, Sub463, Sub481, Sub559
        HelType Sub494, Sub500, Sub504, Sub511, Sub587, Sub524
        HelType Sub591, Sub568, Sub579, Sub248(HelDim(3))
        HelType Sub259(HelDim(3)), Sub245(HelDim(3))
        HelType Sub255(HelDim(3)), Sub86(HelDim(3))
        HelType Sub85(HelDim(3)), Sub20(HelDim(3))
        HelType Sub262(HelDim(3)), Sub45(HelDim(3))
        HelType Sub252(HelDim(3)), Sub43(HelDim(3))
        HelType Sub19(HelDim(3)), Sub163(HelDim(3))
        HelType Sub136(HelDim(3)), Sub66(HelDim(3))
        HelType Sub648(HelDim(3)), Sub675(HelDim(3))
        HelType Sub618(HelDim(3)), Sub619(HelDim(3))
        HelType Sub627(HelDim(3)), Sub628(HelDim(3))
        HelType Sub698(HelDim(3)), Sub704(HelDim(3))
        HelType Sub682(HelDim(3)), Sub676(HelDim(3))
        HelType Sub697(HelDim(3)), Sub703(HelDim(3))
        HelType Sub575(HelDim(3)), Sub185(HelDim(4))
        HelType Sub200(HelDim(4)), Sub663(HelDim(4))
        HelType Sub659(HelDim(4)), Sub742(HelDim(4))
        HelType Sub275(HelDim(4)), Sub314(HelDim(4))
        HelType Sub170(HelDim(3),3), Sub421(HelDim(3),3)
        HelType Sub147(HelDim(3),3), Sub400(HelDim(3),3)
        HelType Sub508(HelDim(3),3), Sub331(HelDim(3),3)
        HelType Sub572(HelDim(3),3), Sub302(HelDim(3),3)
        HelType Sub288(HelDim(3),3), Sub92(HelDim(3),4)
        HelType Sub95(HelDim(3),4), Sub59(HelDim(3),4)
        HelType Sub61(HelDim(3),4), Sub662(HelDim(3),4)
        HelType Sub665(HelDim(3),4), Sub184(HelDim(3),4)
        HelType Sub189(HelDim(3),4), Sub203(HelDim(3),4)
        HelType Sub748(HelDim(3),4), Sub745(HelDim(3),4)
        HelType Sub326(HelDim(3),3,4)
        HelType Sub343(HelDim(3),3,4)
        HelType Sub353(HelDim(3),3,4)
        HelType Sub339(HelDim(3),3,4)
        HelType Sub324(HelDim(3),3,4)
        HelType Sub346(HelDim(3),3,4)
        HelType Sub178(HelDim(3),4,4)
        HelType Sub76(HelDim(3),4,4)
        HelType Sub109(HelDim(3),4,2)
        HelType Sub251(HelDim(3),4,2)
        HelType Sub230(HelDim(3),4,4)
        HelType Sub432(HelDim(3),4,4)
        HelType Sub598(HelDim(3),4,4)
        HelType Sub220(HelDim(3),3,4,4)
        HelType Sub254(HelDim(3),3,4,4)
        HelType Sub257(HelDim(3),3,4,4)
        HelType Sub261(HelDim(3),3,4,4)
        HelType Sub264(HelDim(3),3,4,4)
        HelType Sub279(HelDim(3),3,4,4)
        HelType Sub322(HelDim(3),3,4,4)
        HelType Sub333(HelDim(3),3,4,4)
        HelType Sub358(HelDim(3),3,4,4)
        HelType Sub362(HelDim(3),3,4,4)
        HelType Sub209(HelDim(3),3,4,4)
        HelType Sub425(HelDim(3),3,4,4)
        HelType Sub529(HelDim(3),3,4,4)
        HelType Sub531(HelDim(3),3,4,4)
        HelType Sub79(HelDim(3),3,4,4)
        HelType Sub796(HelDim(3),3,4,4)
        HelType Sub766(HelDim(3),3,4,4,2)
        HelType Sub785(HelDim(3),3,4,4,2)
        HelType Sub37(HelDim(3),3,4,4,2)
        HelType Sub611(HelDim(3),3,4,4,2)
        HelType Sub653(HelDim(3),3,4,4,2)
        HelType Sub685(HelDim(3),3,4,4,2)
        HelType Sub707(HelDim(3),3,4,4,2)
        HelType Sub719(HelDim(3),3,4,4,2)
        HelType Sub735(HelDim(3),3,4,4,2)
        HelType Sub767(HelDim(3),3,4,4,2)
        HelType Sub771(HelDim(3),3,4,4,2)
        HelType Sub99(HelDim(3),3,4,4,2), Sub31, Sub25
        HelType Sub542, Sub550, Sub702, Sub470, Sub487, Sub160
        HelType Sub88, Sub91, Sub132, Sub412, Sub571, Sub582, Sub484
        HelType Sub519, Sub681, Sub120(HelDim(3))
        HelType Sub117(HelDim(3)), Sub162(HelDim(3))
        HelType Sub149(HelDim(3)), Sub46(HelDim(3))
        HelType Sub42(HelDim(3)), Sub115(HelDim(3))
        HelType Sub122(HelDim(3)), Sub172(HelDim(3))
        HelType Sub605(HelDim(3)), Sub608(HelDim(3))
        HelType Sub584(HelDim(3)), Sub563(HelDim(3))
        HelType Sub194(HelDim(4)), Sub624(HelDim(4))
        HelType Sub625(HelDim(4)), Sub191(HelDim(4))
        HelType Sub687(HelDim(4)), Sub613(HelDim(4))
        HelType Sub614(HelDim(4)), Sub183(HelDim(4))
        HelType Sub202(HelDim(4)), Sub342(HelDim(3),4)
        HelType Sub642(HelDim(3),4), Sub639(HelDim(3),4)
        HelType Sub640(HelDim(3),4), Sub643(HelDim(3),4)
        HelType Sub89(HelDim(3),4), Sub94(HelDim(3),4)
        HelType Sub323(HelDim(3),4), Sub345(HelDim(3),4)
        HelType Sub32(HelDim(3),4), Sub27(HelDim(3),4)
        HelType Sub33(HelDim(3),4), Sub29(HelDim(3),4)
        HelType Sub445(HelDim(3),4), Sub442(HelDim(3),4)
        HelType Sub443(HelDim(3),4), Sub446(HelDim(3),4)
        HelType Sub186(HelDim(3),4), Sub192(HelDim(3),4)
        HelType Sub196(HelDim(3),4), Sub201(HelDim(3),4)
        HelType Sub661(HelDim(3),4), Sub664(HelDim(3),4)
        HelType Sub58(HelDim(3),4), Sub63(HelDim(3),4)
        HelType Sub376(HelDim(3),4), Sub198(HelDim(3),4)
        HelType Sub382(HelDim(3),4), Sub744(HelDim(3),4)
        HelType Sub749(HelDim(3),4)
        HelType Sub340(HelDim(3),3,4)
        HelType Sub354(HelDim(3),3,4)
        HelType Sub403(HelDim(3),3,4)
        HelType Sub291(HelDim(3),3,4)
        HelType Sub304(HelDim(3),3,4)
        HelType Sub180(HelDim(3),3,4,4)
        HelType Sub215(HelDim(3),3,4,4)
        HelType Sub226(HelDim(3),3,4,4)
        HelType Sub231(HelDim(3),3,4,4)
        HelType Sub253(HelDim(3),3,4,4)
        HelType Sub256(HelDim(3),3,4,4)
        HelType Sub260(HelDim(3),3,4,4)
        HelType Sub263(HelDim(3),3,4,4)
        HelType Sub318(HelDim(3),3,4,4)
        HelType Sub334(HelDim(3),3,4,4)
        HelType Sub434(HelDim(3),3,4,4)
        HelType Sub490(HelDim(3),3,4,4)
        HelType Sub600(HelDim(3),3,4,4), Sub569, Sub580
        HelType Sub138(HelDim(3)), Sub369(HelDim(3))
        HelType Sub372(HelDim(3)), Sub593(HelDim(3))
        HelType Sub367(HelDim(3)), Sub83(HelDim(4))
        HelType Sub82(HelDim(4)), Sub23(HelDim(4))
        HelType Sub188(HelDim(4)), Sub197(HelDim(4))
        HelType Sub381(HelDim(4)), Sub22(HelDim(4))
        HelType Sub632(HelDim(3),4), Sub634(HelDim(3),4)
        HelType Sub107(HelDim(3),4), Sub105(HelDim(3),4)
        HelType Sub435(HelDim(3),4), Sub437(HelDim(3),4)
        HelType Sub246(HelDim(3),4), Sub249(HelDim(3),4)
        HelType Sub656(HelDim(3),4), Sub654(HelDim(3),4)
        HelType Sub737(HelDim(3),4), Sub739(HelDim(3),4)
        HelType Sub214(HelDim(3),3,4,4)
        HelType Sub211(HelDim(3),3,4,4)
        HelType Sub222(HelDim(3),3,4,4)
        HelType Sub225(HelDim(3),3,4,4)
        HelType Sub280(HelDim(3),3,4,4)
        HelType Sub293(HelDim(3),3,4,4)
        HelType Sub306(HelDim(3),3,4,4)
        HelType Sub319(HelDim(3),3,4,4)
        HelType Sub359(HelDim(3),3,4,4)
        HelType Sub428(HelDim(3),3,4,4)
        HelType Sub174(HelDim(3),3,4,4)
        HelType Sub54(HelDim(3),3,4,4)
        HelType Sub72(HelDim(3),3,4,4)
        HelType Sub73(HelDim(3),3,4,4)
        HelType Sub772(HelDim(3),3,4,4,2), Sub557
        HelType Sub589, Sub482, Sub506, Sub496, Sub517, Sub388
        HelType Sub374(HelDim(3)), Sub541(HelDim(3))
        HelType Sub538(HelDim(3)), Sub405(HelDim(4))
        HelType Sub101(HelDim(3),4), Sub102(HelDim(3),4)
        HelType Sub242(HelDim(3),4), Sub241(HelDim(3),4)
        HelType Sub380(HelDim(3),4)
        HelType Sub56(HelDim(3),3,4)
        HelType Sub68(HelDim(3),3,4)
        HelType Sub127(HelDim(3),4,4)
        HelType Sub155(HelDim(3),4,4)
        HelType Sub210(HelDim(3),3,4,4)
        HelType Sub53(HelDim(3),3,4,4)
        HelType Sub789(HelDim(3),3,4,4,2)
        HelType Sub581(HelDim(3)), Sub570(HelDim(3))
        HelType Sub590(HelDim(3)), Sub558(HelDim(3))
        HelType Sub536(HelDim(3)), Sub543(HelDim(3))
        HelType Sub423(HelDim(4)), Sub377(HelDim(3),4)
        HelType Sub672(HelDim(3),4), Sub670(HelDim(3),4)
        HelType Sub692(HelDim(3),4), Sub694(HelDim(3),4)
        HelType Sub124(HelDim(3),4,4)
        HelType Sub154(HelDim(3),4,4)
        HelType Sub476(HelDim(3),4,4)
        HelType Sub607(HelDim(3),3,4,4)
        HelType Sub609(HelDim(3),3,4,4)
        HelType Sub649(HelDim(3),3,4,4)
        HelType Sub715(HelDim(3),3,4,4)
        HelType Sub717(HelDim(3),3,4,4)
        HelType Sub730(HelDim(3),3,4,4)
        HelType Sub733(HelDim(3),3,4,4)
        HelType Sub458(HelDim(3),4,4)
        HelType Sub468(HelDim(3),4,4)
        HelType Sub472(HelDim(3),4,4)
        HelType Sub456(HelDim(3),4,4)
        HelType Sub465(HelDim(3),4,4)
        HelType Sub651(HelDim(3),3,4,4)
        HelType Sub700(HelDim(3),3,4,4)
        HelType Sub705(HelDim(3),3,4,4)
        HelType Sub460(HelDim(3),4,4)
        HelType Sub548(HelDim(3),4,4)
        HelType Sub552(HelDim(3),4,4)
        HelType Sub546(HelDim(3),4,4)
        HelType Sub554(HelDim(3),4,4)
        HelType Sub406(HelDim(3),3,4,4)
        HelType Sub429(HelDim(3),3,4,4)
        HelType Sub678(HelDim(3),3,4,4)
        HelType Sub683(HelDim(3),3,4,4)
        HelType Sub175(HelDim(3),3,4,4)
        HelType Sub150(HelDim(3),3,4,4)
        HelType Sub474(HelDim(3),4,4)
        HelType Sub141(HelDim(3),3,4,4)
        HelType Sub417(HelDim(3),3,4,4)
        HelType Sub164(HelDim(3),3,4,4)
        HelType Sub492(HelDim(3),3,4,4)
        HelType Sub513(HelDim(3),3,4,4)
        HelType Sub396(HelDim(3),3,4,4)
        HelType Sub576(HelDim(3),3,4,4)
        HelType Sub501(HelDim(3),3,4,4)
        HelType Sub586(HelDim(3),3,4,4)
        HelType Sub525(HelDim(3),3,4,4)
        HelType Sub595(HelDim(3),3,4,4)
        HelType Sub566(HelDim(3),3,4,4)
        common /varXh/ F14, F27, F103, F11, F25, F101, F33, F37, F29
        common /varXh/ F32, F38, F81, F16, F34, F82, F10, F2, F18
        common /varXh/ F63, F52, F116, F65, F134, F167, F137, F175
        common /varXh/ F107, F135, F108, F181, F176, F5, F19, F45
        common /varXh/ F73, F118, F47, F139, F168, F133, F177, F99
        common /varXh/ F156, F100, F182, F178, F183, F17, F202, F193
        common /varXh/ F194, F184, F20, F204, F198, F199, F74, F152
        common /varXh/ F189, F70, F79, F1, F71, F85, F228, F86, F221
        common /varXh/ F76, F222, F44, F53, F149, F190, F49, F80, F7
        common /varXh/ F50, F87, F230, F88, F225, F55, F226, F48
        common /varXh/ F40, F109, F57, F12, F30, F104, F121, F83
        common /varXh/ F67, F84, F141, F122, F148, F169, F155, F123
        common /varXh/ F153, F68, F154, F142, F124, F171, F138, F179
        common /varXh/ F172, F36, F110, F77, F13, F31, F102, F127
        common /varXh/ F89, F42, F90, F146, F128, F158, F170, F157
        common /varXh/ F129, F165, F43, F166, F147, F130, F173, F164
        common /varXh/ F180, F174, F187, F185, F215, F216, F21, F22
        common /varXh/ F23, F207, F208, F188, F186, F217, F218, F24
        common /varXh/ F26, F28, F211, F212, F39, F213, F59, F196
        common /varXh/ F239, F136, F240, F60, F3, F4, F61, F6, F233
        common /varXh/ F62, F234, F35, F214, F92, F200, F241, F163
        common /varXh/ F242, F93, F8, F9, F94, F15, F237, F95, F238
        common /varXh/ F51, F115, F64, F111, F143, F56, F144, F131
        common /varXh/ F112, F105, F106, F150, F151, F72, F117, F46
        common /varXh/ F113, F161, F78, F162, F132, F114, F97, F98
        common /varXh/ F159, F160, F201, F191, F192, F203, F195
        common /varXh/ F197, F69, F227, F219, F75, F220, F41, F229
        common /varXh/ F223, F54, F224, F119, F66, F140, F120, F125
        common /varXh/ F96, F145, F126, F205, F206, F209, F210, F231
        common /varXh/ F58, F232, F235, F91, F236, Pair4, Pair3
        common /varXh/ Pair5, Pair6, Pair7, Pair11, Pair10, Pair8
        common /varXh/ Pair9, Pair1, Pair2, Abb1, Abb2, Abb15, Abb3
        common /varXh/ Abb26, Abb19, Abb11, Abb23, Abb24, Abb30
        common /varXh/ Abb22, Abb28, Abb21, Abb10, Abb17, Abb9
        common /varXh/ Abb14, Abb25, Abb27, Abb34, Abb4, Abb18
        common /varXh/ Abb32, Abb13, Abb20, Abb8, Abb7, Abb29, Abb16
        common /varXh/ Abb6, Abb33, Abb12, Abb31, Abb5, Opt1, Opt4
        common /varXh/ Opt5, Sub379, Sub420, Sub217, Sub190, Sub394
        common /varXh/ Sub565, Sub389, Sub146, Sub387, Sub384
        common /varXh/ Sub422, Sub418, Sub731, Sub440, Sub444
        common /varXh/ Sub641, Sub349, Sub637, Sub335, Sub313
        common /varXh/ Sub299, Sub274, Sub285, Sub244, Sub247, Sub90
        common /varXh/ Sub106, Sub65, Sub104, Sub55, Sub119, Sub475
        common /varXh/ Sub116, Sub461, Sub161, Sub148, Sub674
        common /varXh/ Sub680, Sub669, Sub671, Sub696, Sub691
        common /varXh/ Sub693, Sub701, Sub746, Sub212, Sub268
        common /varXh/ Sub297, Sub283, Sub307, Sub355, Sub545
        common /varXh/ Sub553, Sub363, Sub206, Sub218, Sub365
        common /varXh/ Sub401, Sub603, Sub602, Sub424, Sub112
        common /varXh/ Sub171, Sub137, Sub464, Sub390, Sub110
        common /varXh/ Sub462, Sub404, Sub152, Sub410, Sub205
        common /varXh/ Sub556, Sub478, Sub514, Sub679, Sub371
        common /varXh/ Sub368, Sub540, Sub537, Sub583, Sub574
        common /varXh/ Sub510, Sub499, Sub732, Sub585, Sub402
        common /varXh/ Sub561, Sub414, Sub725, Sub710, Sub711
        common /varXh/ Sub512, Sub486, Sub726, Sub386, Sub70, Sub173
        common /varXh/ Sub51, Sub395, Sub426, Sub523, Sub467, Sub457
        common /varXh/ Sub411, Sub267, Sub143, Sub158, Sub221
        common /varXh/ Sub269, Sub284, Sub298, Sub308, Sub385
        common /varXh/ Sub471, Sub491, Sub350, Sub336, Sub28, Sub26
        common /varXh/ Sub330, Sub276, Sub356, Sub316, Sub237
        common /varXh/ Sub236, Sub233, Sub337, Sub287, Sub351
        common /varXh/ Sub301, Sub232, Sub650, Sub300, Sub317
        common /varXh/ Sub270, Sub290, Sub286, Sub277, Sub309
        common /varXh/ Sub303, Sub562, Sub271, Sub310, Sub195
        common /varXh/ Sub721, Sub720, Sub747, Sub686, Sub633
        common /varXh/ Sub635, Sub305, Sub292, Sub436, Sub438
        common /varXh/ Sub415, Sub655, Sub657, Sub738, Sub740
        common /varXh/ Sub177, Sub229, Sub431, Sub181, Sub40, Sub364
        common /varXh/ Sub111, Sub182, Sub41, Sub113, Sub366, Sub451
        common /varXh/ Sub454, Sub533, Sub535, Sub75, Sub527, Sub597
        common /varXh/ Sub327, Sub344, Sub352, Sub338, Sub416
        common /varXh/ Sub325, Sub347, Sub118, Sub123, Sub128
        common /varXh/ Sub156, Sub44, Sub459, Sub47, Sub466, Sub473
        common /varXh/ Sub477, Sub528, Sub549, Sub555, Sub599, Sub12
        common /varXh/ Sub17, Sub100, Sub622, Sub646, Sub647, Sub103
        common /varXh/ Sub108, Sub21, Sub36, Sub234, Sub235, Sub626
        common /varXh/ Sub630, Sub636, Sub644, Sub645, Sub448
        common /varXh/ Sub616, Sub240, Sub612, Sub81, Sub8, Sub601
        common /varXh/ Sub604, Sub238, Sub243, Sub250, Sub439
        common /varXh/ Sub447, Sub615, Sub239, Sub87, Sub228, Sub433
        common /varXh/ Sub187, Sub193, Sub199, Sub204, Sub370
        common /varXh/ Sub375, Sub378, Sub383, Sub539, Sub544, Sub60
        common /varXh/ Sub64, Sub617, Sub709, Sub80, Sub4, Sub668
        common /varXh/ Sub712, Sub620, Sub708, Sub658, Sub666
        common /varXh/ Sub667, Sub673, Sub722, Sub723, Sub84, Sub98
        common /varXh/ Sub16, Sub623, Sub724, Sub18, Sub690, Sub727
        common /varXh/ Sub24, Sub629, Sub736, Sub688, Sub689, Sub695
        common /varXh/ Sub741, Sub750, Sub751, Sub768, Sub774
        common /varXh/ Sub179, Sub224, Sub321, Sub790, Sub361
        common /varXh/ Sub794, Sub151, Sub176, Sub216, Sub227
        common /varXh/ Sub258, Sub265, Sub294, Sub320, Sub328
        common /varXh/ Sub341, Sub348, Sub360, Sub407, Sub427
        common /varXh/ Sub430, Sub357, Sub332, Sub522, Sub139
        common /varXh/ Sub594, Sub393, Sub502, Sub526, Sub530
        common /varXh/ Sub795, Sub57, Sub577, Sub596, Sub77, Sub791
        common /varXh/ Sub74, Sub78, Sub792, Sub793, Sub93, Sub96
        common /varXh/ Sub30, Sub34, Sub776, Sub780, Sub35, Sub756
        common /varXh/ Sub621, Sub758, Sub631, Sub760, Sub782
        common /varXh/ Sub652, Sub762, Sub684, Sub770, Sub610
        common /varXh/ Sub706, Sub718, Sub786, Sub734, Sub783
        common /varXh/ Sub761, Sub765, Sub769, Sub775, Sub777
        common /varXh/ Sub781, Sub784, Sub787, Sub97, Sub788, Sub509
        common /varXh/ Sub452, Sub560, Sub483, Sub592, Sub518
        common /varXh/ Sub498, Sub450, Sub505, Sub503, Sub480
        common /varXh/ Sub479, Sub273, Sub272, Sub266, Sub129
        common /varXh/ Sub397, Sub495, Sub493, Sub567, Sub281
        common /varXh/ Sub282, Sub142, Sub516, Sub515, Sub311
        common /varXh/ Sub295, Sub296, Sub157, Sub312, Sub165
        common /varXh/ Sub578, Sub315, Sub408, Sub373, Sub399
        common /varXh/ Sub413, Sub121, Sub169, Sub126, Sub140
        common /varXh/ Sub114, Sub135, Sub329, Sub551, Sub547
        common /varXh/ Sub532, Sub213, Sub534, Sub573, Sub453
        common /varXh/ Sub520, Sub485, Sub449, Sub125, Sub133
        common /varXh/ Sub130, Sub167, Sub223, Sub69, Sub588, Sub713
        common /varXh/ Sub716, Sub728, Sub521, Sub144, Sub159
        common /varXh/ Sub469, Sub131, Sub455, Sub62, Sub48, Sub489
        common /varXh/ Sub145, Sub134, Sub153, Sub166, Sub168
        common /varXh/ Sub398, Sub409, Sub419, Sub497, Sub507
        common /varXh/ Sub463, Sub481, Sub559, Sub494, Sub500
        common /varXh/ Sub504, Sub511, Sub587, Sub524, Sub591
        common /varXh/ Sub568, Sub579, Sub248, Sub259, Sub245
        common /varXh/ Sub255, Sub86, Sub85, Sub20, Sub262, Sub45
        common /varXh/ Sub252, Sub43, Sub19, Sub163, Sub136, Sub66
        common /varXh/ Sub648, Sub675, Sub618, Sub619, Sub627
        common /varXh/ Sub628, Sub698, Sub704, Sub682, Sub676
        common /varXh/ Sub697, Sub703, Sub575, Sub185, Sub200
        common /varXh/ Sub663, Sub659, Sub742, Sub275, Sub314
        common /varXh/ Sub170, Sub421, Sub147, Sub400, Sub508
        common /varXh/ Sub331, Sub572, Sub302, Sub288, Sub92, Sub95
        common /varXh/ Sub59, Sub61, Sub662, Sub665, Sub184, Sub189
        common /varXh/ Sub203, Sub748, Sub745, Sub326, Sub343
        common /varXh/ Sub353, Sub339, Sub324, Sub346, Sub178, Sub76
        common /varXh/ Sub109, Sub251, Sub230, Sub432, Sub598
        common /varXh/ Sub220, Sub254, Sub257, Sub261, Sub264
        common /varXh/ Sub279, Sub322, Sub333, Sub358, Sub362
        common /varXh/ Sub209, Sub425, Sub529, Sub531, Sub79, Sub796
        common /varXh/ Sub766, Sub785, Sub37, Sub611, Sub653, Sub685
        common /varXh/ Sub707, Sub719, Sub735, Sub767, Sub771, Sub99
        common /varXh/ Sub31, Sub25, Sub542, Sub550, Sub702, Sub470
        common /varXh/ Sub487, Sub160, Sub88, Sub91, Sub132, Sub412
        common /varXh/ Sub571, Sub582, Sub484, Sub519, Sub681
        common /varXh/ Sub120, Sub117, Sub162, Sub149, Sub46, Sub42
        common /varXh/ Sub115, Sub122, Sub172, Sub605, Sub608
        common /varXh/ Sub584, Sub563, Sub194, Sub624, Sub625
        common /varXh/ Sub191, Sub687, Sub613, Sub614, Sub183
        common /varXh/ Sub202, Sub342, Sub642, Sub639, Sub640
        common /varXh/ Sub643, Sub89, Sub94, Sub323, Sub345, Sub32
        common /varXh/ Sub27, Sub33, Sub29, Sub445, Sub442, Sub443
        common /varXh/ Sub446, Sub186, Sub192, Sub196, Sub201
        common /varXh/ Sub661, Sub664, Sub58, Sub63, Sub376, Sub198
        common /varXh/ Sub382, Sub744, Sub749, Sub340, Sub354
        common /varXh/ Sub403, Sub291, Sub304, Sub180, Sub215
        common /varXh/ Sub226, Sub231, Sub253, Sub256, Sub260
        common /varXh/ Sub263, Sub318, Sub334, Sub434, Sub490
        common /varXh/ Sub600, Sub569, Sub580, Sub138, Sub369
        common /varXh/ Sub372, Sub593, Sub367, Sub83, Sub82, Sub23
        common /varXh/ Sub188, Sub197, Sub381, Sub22, Sub632, Sub634
        common /varXh/ Sub107, Sub105, Sub435, Sub437, Sub246
        common /varXh/ Sub249, Sub656, Sub654, Sub737, Sub739
        common /varXh/ Sub214, Sub211, Sub222, Sub225, Sub280
        common /varXh/ Sub293, Sub306, Sub319, Sub359, Sub428
        common /varXh/ Sub174, Sub54, Sub72, Sub73, Sub772, Sub557
        common /varXh/ Sub589, Sub482, Sub506, Sub496, Sub517
        common /varXh/ Sub388, Sub374, Sub541, Sub538, Sub405
        common /varXh/ Sub101, Sub102, Sub242, Sub241, Sub380, Sub56
        common /varXh/ Sub68, Sub127, Sub155, Sub210, Sub53, Sub789
        common /varXh/ Sub581, Sub570, Sub590, Sub558, Sub536
        common /varXh/ Sub543, Sub423, Sub377, Sub672, Sub670
        common /varXh/ Sub692, Sub694, Sub124, Sub154, Sub476
        common /varXh/ Sub607, Sub609, Sub649, Sub715, Sub717
        common /varXh/ Sub730, Sub733, Sub458, Sub468, Sub472
        common /varXh/ Sub456, Sub465, Sub651, Sub700, Sub705
        common /varXh/ Sub460, Sub548, Sub552, Sub546, Sub554
        common /varXh/ Sub406, Sub429, Sub678, Sub683, Sub175
        common /varXh/ Sub150, Sub474, Sub141, Sub417, Sub164
        common /varXh/ Sub492, Sub513, Sub396, Sub576, Sub501
        common /varXh/ Sub586, Sub525, Sub595, Sub566

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7
        common /indices/ Sfe7

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /gqdbar_nInJqdbarg_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
