#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Oct-2016 12:47
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub45(4), Sub3(4), Sub38(4), Sub27(4)
        ComplexType Sub10(4), Sub20(4), Sub214(3,2)
        ComplexType Sub200(3,2), Sub215(3,2), Sub189(3,2)
        ComplexType Sub193(3,2), Sub191(3,2), Sub194(3,2)
        ComplexType Sub89(4,4), Sub90(4,4)
        ComplexType Sub56(3,4,2), Sub57(3,4,2)
        ComplexType Sub37(3,4,2), Sub39(3,4,2)
        ComplexType Sub66(3,4,2), Sub67(3,4,2)
        ComplexType Sub19(3,4,2), Sub21(3,4,2)
        ComplexType Sub63(3,4,2), Sub64(3,4,2)
        ComplexType Sub46(3,4,2), Sub47(3,4,2)
        ComplexType Sub59(3,4,2), Sub60(3,4,2)
        ComplexType Sub28(3,4,2), Sub29(3,4,2)
        ComplexType Sub4(3,4,2), Sub5(3,4,2)
        ComplexType Sub11(3,4,2), Sub17(3,4,2)
        ComplexType Sub13(3,4,2), Sub15(3,4,2)
        ComplexType Sub14(3,4,2), Sub1(3,4,2)
        ComplexType Sub8(3,4,2), Sub7(3,4,2)
        common /varXs/ Sub45, Sub3, Sub38, Sub27, Sub10, Sub20
        common /varXs/ Sub214, Sub200, Sub215, Sub189, Sub193
        common /varXs/ Sub191, Sub194, Sub89, Sub90, Sub56, Sub57
        common /varXs/ Sub37, Sub39, Sub66, Sub67, Sub19, Sub21
        common /varXs/ Sub63, Sub64, Sub46, Sub47, Sub59, Sub60
        common /varXs/ Sub28, Sub29, Sub4, Sub5, Sub11, Sub17, Sub13
        common /varXs/ Sub15, Sub14, Sub1, Sub8, Sub7

        ComplexType Opt6(3,3,3,3), Opt7(3)
        ComplexType Sub212(3,3,3), Sub203(3,3,4)
        ComplexType Sub199(3,3,4), Sub209(3,4,4)
        ComplexType Sub190(3,3,3,3,4,4)
        ComplexType Sub196(3,3,3,3,4,4)
        ComplexType Sub207(3,3,3,3,4,4)
        ComplexType Sub206(3,3,3,3,4,4)
        ComplexType Sub208(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt6, Opt7, Sub212, Sub203, Sub199, Sub209
        common /varXa/ Sub190, Sub196, Sub207, Sub206, Sub208, S, T
        common /varXa/ T14, T15, U, T24, T25, S34, S35, S45

        HelType F63, F57, F72, F64, F59, F80, F4, F50, F25, F60, F20
        HelType F3, F49, F26, F58, F18, F75, F105, F74, F79, F106
        HelType F66, F45, F90, F121, F11, F46, F91, F122, F14, F115
        HelType F116, F17, F67, F98, F69, F1, F19, F76, F99, F78, F6
        HelType F39, F102, F33, F2, F12, F82, F40, F97, F34, F5, F13
        HelType F77, F88, F87, F28, F27, F62, F21, F7, F100, F47
        HelType F15, F118, F101, F22, F9, F61, F23, F8, F110, F48
        HelType F16, F112, F111, F24, F10, F93, F94, F131, F132
        HelType F133, F134, F95, F96, F135, F136, F119, F120, F92
        HelType F84, F85, F65, F123, F124, F107, F125, F126, F86
        HelType F71, F89, F73, F127, F128, F117, F129, F130, F35
        HelType F81, F41, F83, F55, F108, F53, F114, F42, F109, F36
        HelType F37, F68, F43, F70, F56, F103, F54, F113, F44, F104
        HelType F38, F31, F52, F32, F29, F51, F30, Sub138, Sub128
        HelType Sub140, Sub100, Sub141, Sub152, Sub129, Sub132
        HelType Sub99, Sub154, Sub103, Sub102, Sub131
        HelType Sub12(HelDim(3),3), Sub2(HelDim(3),3)
        HelType Sub114(HelDim(3),3), Sub106(HelDim(3),3)
        HelType Sub108(HelDim(3),3), Sub55(HelDim(3),3)
        HelType Sub62(HelDim(3),3), Sub117(HelDim(4),4)
        HelType Sub144(HelDim(4),4), Sub165(HelDim(4),4)
        HelType Sub91(HelDim(4),4), Sub92(HelDim(4),4)
        HelType Sub101(HelDim(4),4), Sub104(HelDim(4),4)
        HelType Sub130(HelDim(4),4), Sub133(HelDim(4),4)
        HelType Sub153(HelDim(4),4), Sub156(HelDim(4),4)
        HelType Sub97(HelDim(4),4)
        HelType Sub176(HelDim(3),4,2)
        HelType Sub58(HelDim(3),4,2)
        HelType Sub172(HelDim(3),4,2)
        HelType Sub175(HelDim(3),4,2)
        HelType Sub40(HelDim(3),4,2)
        HelType Sub181(HelDim(3),4,2)
        HelType Sub68(HelDim(3),4,2)
        HelType Sub177(HelDim(3),4,2)
        HelType Sub180(HelDim(3),4,2)
        HelType Sub22(HelDim(3),4,2)
        HelType Sub137(HelDim(3),4,4)
        HelType Sub143(HelDim(3),4,4)
        HelType Sub65(HelDim(3),4,2)
        HelType Sub182(HelDim(3),4,2)
        HelType Sub48(HelDim(3),4,2)
        HelType Sub171(HelDim(3),4,2)
        HelType Sub61(HelDim(3),4,2)
        HelType Sub167(HelDim(3),4,2)
        HelType Sub170(HelDim(3),4,2)
        HelType Sub30(HelDim(3),4,2)
        HelType Sub6(HelDim(3),4,2)
        HelType Sub78(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub69(HelDim(3),4,2)
        HelType Sub16(HelDim(3),4,2)
        HelType Sub146(HelDim(3),4,2)
        HelType Sub9(HelDim(3),4,2)
        HelType Sub119(HelDim(3),4,2)
        HelType Sub35(HelDim(3),3,2,2)
        HelType Sub53(HelDim(3),3,2,2)
        HelType Sub31(HelDim(3),3,2,2)
        HelType Sub49(HelDim(3),3,2,2)
        HelType Sub33(HelDim(3),3,2,2)
        HelType Sub51(HelDim(3),3,2,2)
        HelType Sub25(HelDim(3),3,2,2)
        HelType Sub43(HelDim(3),3,2,2)
        HelType Sub94(HelDim(3),3,3,4,4)
        HelType Sub96(HelDim(3),3,3,4,4)
        HelType Sub83(HelDim(3),3,3,4,2)
        HelType Sub86(HelDim(3),3,3,4,2)
        HelType Sub110(HelDim(3),3,3,4,4)
        HelType Sub116(HelDim(3),3,3,4,4)
        HelType Sub150(HelDim(3),3,3,4,2)
        HelType Sub149(HelDim(3),3,3,4,2)
        HelType Sub160(HelDim(3),3,3,4,4)
        HelType Sub164(HelDim(3),3,3,4,4)
        HelType Sub188(HelDim(3),3,3,4,2)
        HelType Sub187(HelDim(3),3,3,4,2)
        HelType Sub80(HelDim(3),3,4,4,2)
        HelType Sub210(HelDim(3),3,3,3,4,4)
        HelType Sub211(HelDim(3),3,3,3,4,4)
        HelType Sub213(HelDim(3),3,3,3,4,4)
        HelType Sub122(HelDim(3),3,3,3,4,2)
        HelType Sub125(HelDim(3),3,3,3,4,2)
        HelType Sub72(HelDim(3),3,3,3,4,2)
        HelType Sub75(HelDim(3),3,3,3,4,2)
        HelType Sub205(HelDim(3),3,3,4,2,2)
        HelType Sub202(HelDim(3),3,3,4,2,2)
        HelType Sub204(HelDim(3),3,3,4,2,2)
        HelType Sub201(HelDim(3),3,3,4,2,2), Sub113
        HelType Sub105, Sub151, Sub155, Sub23(HelDim(3))
        HelType Sub41(HelDim(3)), Sub24(HelDim(3))
        HelType Sub42(HelDim(3)), Sub185(HelDim(3))
        HelType Sub158(HelDim(3)), Sub173(HelDim(4))
        HelType Sub174(HelDim(4)), Sub178(HelDim(4))
        HelType Sub179(HelDim(4)), Sub162(HelDim(3),3)
        HelType Sub134(HelDim(4),4)
        HelType Sub145(HelDim(3),3,4,4)
        HelType Sub36(HelDim(3),3,2,2)
        HelType Sub54(HelDim(3),3,2,2)
        HelType Sub32(HelDim(3),3,2,2)
        HelType Sub50(HelDim(3),3,2,2)
        HelType Sub34(HelDim(3),3,2,2)
        HelType Sub52(HelDim(3),3,2,2)
        HelType Sub26(HelDim(3),3,2,2)
        HelType Sub44(HelDim(3),3,2,2)
        HelType Sub98(HelDim(3),3,3,4,4)
        HelType Sub166(HelDim(3),3,3,4,4)
        HelType Sub118(HelDim(3),3,3,3,4,4)
        HelType Sub112(HelDim(3),3,3)
        HelType Sub139(HelDim(3),4,4)
        HelType Sub184(HelDim(3),3,4)
        HelType Sub111(HelDim(3),3), Sub183(HelDim(3),3)
        HelType Sub135(HelDim(3),4,4), Sub169(HelDim(4))
        HelType Sub168(HelDim(4)), Sub74(HelDim(3),3,3)
        HelType Sub70(HelDim(3),3,3)
        HelType Sub81(HelDim(3),3,3)
        HelType Sub85(HelDim(3),3,3)
        HelType Sub93(HelDim(3),3,3)
        HelType Sub95(HelDim(3),3,3)
        HelType Sub124(HelDim(3),3,3)
        HelType Sub120(HelDim(3),3,3)
        HelType Sub147(HelDim(3),3,3)
        HelType Sub148(HelDim(3),3,3)
        HelType Sub109(HelDim(3),3,3)
        HelType Sub142(HelDim(3),4,4)
        HelType Sub186(HelDim(3),3,4)
        HelType Sub73(HelDim(3),3,3)
        HelType Sub71(HelDim(3),3,3)
        HelType Sub84(HelDim(3),3,3)
        HelType Sub82(HelDim(3),3,3)
        HelType Sub123(HelDim(3),3,3)
        HelType Sub121(HelDim(3),3,3)
        HelType Sub115(HelDim(3),3,3)
        HelType Sub136(HelDim(3),4,4)
        HelType Sub107(HelDim(3),3,3)
        HelType Sub163(HelDim(3),3,3,4)
        HelType Sub159(HelDim(3),3,3,4)
        HelType Sub161(HelDim(3),3,3,4)
        HelType Sub157(HelDim(3),3,3,4)
        common /varXh/ F63, F57, F72, F64, F59, F80, F4, F50, F25
        common /varXh/ F60, F20, F3, F49, F26, F58, F18, F75, F105
        common /varXh/ F74, F79, F106, F66, F45, F90, F121, F11, F46
        common /varXh/ F91, F122, F14, F115, F116, F17, F67, F98
        common /varXh/ F69, F1, F19, F76, F99, F78, F6, F39, F102
        common /varXh/ F33, F2, F12, F82, F40, F97, F34, F5, F13
        common /varXh/ F77, F88, F87, F28, F27, F62, F21, F7, F100
        common /varXh/ F47, F15, F118, F101, F22, F9, F61, F23, F8
        common /varXh/ F110, F48, F16, F112, F111, F24, F10, F93
        common /varXh/ F94, F131, F132, F133, F134, F95, F96, F135
        common /varXh/ F136, F119, F120, F92, F84, F85, F65, F123
        common /varXh/ F124, F107, F125, F126, F86, F71, F89, F73
        common /varXh/ F127, F128, F117, F129, F130, F35, F81, F41
        common /varXh/ F83, F55, F108, F53, F114, F42, F109, F36
        common /varXh/ F37, F68, F43, F70, F56, F103, F54, F113, F44
        common /varXh/ F104, F38, F31, F52, F32, F29, F51, F30
        common /varXh/ Sub138, Sub128, Sub140, Sub100, Sub141
        common /varXh/ Sub152, Sub129, Sub132, Sub99, Sub154, Sub103
        common /varXh/ Sub102, Sub131, Sub12, Sub2, Sub114, Sub106
        common /varXh/ Sub108, Sub55, Sub62, Sub117, Sub144, Sub165
        common /varXh/ Sub91, Sub92, Sub101, Sub104, Sub130, Sub133
        common /varXh/ Sub153, Sub156, Sub97, Sub176, Sub58, Sub172
        common /varXh/ Sub175, Sub40, Sub181, Sub68, Sub177, Sub180
        common /varXh/ Sub22, Sub137, Sub143, Sub65, Sub182, Sub48
        common /varXh/ Sub171, Sub61, Sub167, Sub170, Sub30, Sub6
        common /varXh/ Sub78, Sub18, Sub69, Sub16, Sub146, Sub9
        common /varXh/ Sub119, Sub35, Sub53, Sub31, Sub49, Sub33
        common /varXh/ Sub51, Sub25, Sub43, Sub94, Sub96, Sub83
        common /varXh/ Sub86, Sub110, Sub116, Sub150, Sub149, Sub160
        common /varXh/ Sub164, Sub188, Sub187, Sub80, Sub210, Sub211
        common /varXh/ Sub213, Sub122, Sub125, Sub72, Sub75, Sub205
        common /varXh/ Sub202, Sub204, Sub201, Sub113, Sub105
        common /varXh/ Sub151, Sub155, Sub23, Sub41, Sub24, Sub42
        common /varXh/ Sub185, Sub158, Sub173, Sub174, Sub178
        common /varXh/ Sub179, Sub162, Sub134, Sub145, Sub36, Sub54
        common /varXh/ Sub32, Sub50, Sub34, Sub52, Sub26, Sub44
        common /varXh/ Sub98, Sub166, Sub118, Sub112, Sub139, Sub184
        common /varXh/ Sub111, Sub183, Sub135, Sub169, Sub168, Sub74
        common /varXh/ Sub70, Sub81, Sub85, Sub93, Sub95, Sub124
        common /varXh/ Sub120, Sub147, Sub148, Sub109, Sub142
        common /varXh/ Sub186, Sub73, Sub71, Sub84, Sub82, Sub123
        common /varXh/ Sub121, Sub115, Sub136, Sub107, Sub163
        common /varXh/ Sub159, Sub161, Sub157

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7, Sfe8
        common /indices/ Sfe7, Sfe8

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqdbar_nInJququbar_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
