#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Oct-2016 12:41
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub1(4), Sub5(4), Sub337(3,2)
        ComplexType Sub341(3,2), Sub345(3,2)
        ComplexType Sub348(3,2), Sub344(3,2)
        ComplexType Sub347(3,2), Sub339(3,2)
        ComplexType Sub342(3,2), Sub16(3,4,2)
        ComplexType Sub17(3,4,2), Sub13(3,4,2)
        ComplexType Sub14(3,4,2)
        common /varXs/ Sub1, Sub5, Sub337, Sub341, Sub345, Sub348
        common /varXs/ Sub344, Sub347, Sub339, Sub342, Sub16, Sub17
        common /varXs/ Sub13, Sub14

        ComplexType Opt2(3,3,3,3)
        ComplexType Opt3(3,3,3,3)
        ComplexType Sub353(3,3,4)
        ComplexType Sub354(3,3,3,3,4,4)
        ComplexType Sub359(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt2, Opt3, Sub353, Sub354, Sub359, S, T, T14
        common /varXa/ T15, U, T24, T25, S34, S35, S45

        HelType F4, F6, F11, F13, F14, F12, F16, F8, F15, F10
        HelType Sub18(HelDim(3),4,2)
        HelType Sub15(HelDim(3),4,2)
        HelType Sub19(HelDim(3),3,2,2)
        HelType Sub21(HelDim(3),3,2,2)
        HelType Sub20(HelDim(3),3,2,2)
        HelType Sub22(HelDim(3),3,2,2)
        common /varXh/ F4, F6, F11, F13, F14, F12, F16, F8, F15, F10
        common /varXh/ Sub18, Sub15, Sub19, Sub21, Sub20, Sub22

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqd_nInJqdqd_3645_Sq1Sq2_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
