#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Oct-2016 12:46
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub45(4), Sub38(4), Sub10(4)
        ComplexType Sub200(3,2), Sub189(3,2)
        ComplexType Sub37(3,4,2), Sub39(3,4,2)
        ComplexType Sub46(3,4,2), Sub47(3,4,2)
        ComplexType Sub11(3,4,2), Sub17(3,4,2)
        common /varXs/ Sub45, Sub38, Sub10, Sub200, Sub189, Sub37
        common /varXs/ Sub39, Sub46, Sub47, Sub11, Sub17

        ComplexType Sub203(3,3,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Sub203, S, T, T14, T15, U, T24, T25, S34, S35
        common /varXa/ S45

        HelType F50, F20, F49, F18, F45, F46, F12, F13, F28, F27, F21
        HelType F47, F23, F48, F31, F52, F29, F51
        HelType Sub40(HelDim(3),4,2)
        HelType Sub48(HelDim(3),4,2)
        HelType Sub18(HelDim(3),4,2)
        HelType Sub49(HelDim(3),3,2,2)
        HelType Sub43(HelDim(3),3,2,2)
        HelType Sub204(HelDim(3),3,3,4,2,2)
        HelType Sub41(HelDim(3)), Sub42(HelDim(3))
        HelType Sub50(HelDim(3),3,2,2)
        HelType Sub44(HelDim(3),3,2,2)
        common /varXh/ F50, F20, F49, F18, F45, F46, F12, F13, F28
        common /varXh/ F27, F21, F47, F23, F48, F31, F52, F29, F51
        common /varXh/ Sub40, Sub48, Sub18, Sub49, Sub43, Sub204
        common /varXh/ Sub41, Sub42, Sub50, Sub44

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        integer Sfe7
        common /indices/ Sfe7

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /qdqdbar_nInJququbar_456_Sq1_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
