#if 0
* vars.h
* variable declarations
* generated by FormCalc 8.4 on 27-Oct-2016 13:04
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 6

#include "decl.h"

#else

#include "decl.h"

        ComplexType Sub3(4), Sub1(4), Sub426(3,2)
        ComplexType Sub430(3,2), Sub434(3,2)
        ComplexType Sub437(3,2), Sub433(3,2)
        ComplexType Sub436(3,2), Sub428(3,2)
        ComplexType Sub431(3,2), Sub16(3,4,2)
        ComplexType Sub21(3,4,2), Sub17(3,4,2)
        ComplexType Sub18(3,4,2)
        common /varXs/ Sub3, Sub1, Sub426, Sub430, Sub434, Sub437
        common /varXs/ Sub433, Sub436, Sub428, Sub431, Sub16, Sub21
        common /varXs/ Sub17, Sub18

        ComplexType Opt2(3,3,3,3)
        ComplexType Opt3(3,3,3,3)
        ComplexType Sub442(3,3,4)
        ComplexType Sub443(3,3,3,3,4,4)
        ComplexType Sub448(3,3,3,3,4,4)
        RealType S, T, T14, T15, U, T24, T25, S34, S35, S45
        common /varXa/ Opt2, Opt3, Sub442, Sub443, Sub448, S, T, T14
        common /varXa/ T15, U, T24, T25, S34, S35, S45

        HelType F3, F6, F11, F14, F13, F12, F16, F8, F15, F9
        HelType Sub24(HelDim(3),4,2)
        HelType Sub19(HelDim(3),4,2)
        HelType Sub23(HelDim(3),3,2,2)
        HelType Sub25(HelDim(3),3,2,2)
        HelType Sub27(HelDim(3),3,2,2)
        HelType Sub12(HelDim(3),3,2,2)
        HelType Sub22(HelDim(3),3,4,4,2,2)
        HelType Sub28(HelDim(3),3,2,2)
        common /varXh/ F3, F6, F11, F14, F13, F12, F16, F8, F15, F9
        common /varXh/ Sub24, Sub19, Sub23, Sub25, Sub27, Sub12
        common /varXh/ Sub22, Sub28

        integer seq(2), Hel(6)
        common /helind/ seq, Hel

        HelType Ctree(HelDim(2))
        ComplexType MatSUN(2,2)
        common /ququ_nInJququ_3645_Sq1Sq2_formfactors/ Ctree, MatSUN

#if PARALLEL
        marker ends, enda, endhel
        common /varXs/ ends
        common /varXa/ enda
        common /helind/ endhel
#endif

#endif
